### ISSUE TITLE
Building android-aar failed & h264 encoding?

### ISSUE THREAD

**Issue by NiekAkerboom** [tanersener/mobile-ffmpeg#1]
~~When following the instructions after installing the required packages, I still get:
`Creating Android archive under prebuilt/android-aar: failed`
FFmpeg itself is successfully building for every arch, it's just the last bit where it fails. I'm running MacOS High Sierra.~~
EDIT: Never mind, I forgot that I uninstalled Gradle last week, working once reinstalled.

Are there plans for adding h264 encoding functionality? It would be awesome if we can enable either x264 or OpenH264 from the library list.

Thanks a lot!

**Comment by tanersener** [comment]
Could you please post contents of the build.log? Last lines should include the actual reason of this failure?

Well, I also want to include h264 functionality but both libraries are not compatible with LGPL v3.0 and I need to license this project under LGPL. Maybe adding an "--enable-gpl" option like ffmpeg can do it? Let me think about it.

**Comment by NiekAkerboom** [comment]
Reason for the .aar failure was my own, was cleaning my Mac and forgot to install some vital packages, including Gradle!

And yeah, I had a feeling that that would've been the primary reason. Yeah that sounds like an idea, dont enable h264 encoding libs unless the user enables it in the .sh files. Also, You don't have to add the said libraries' source files to the /src directory, just let the build files download them (if user enables it) so they are not in your repo. A GPL branch might also be an option.

I'll close this issue for now, thanks again!
