### ISSUE TITLE
Issue IOS

### ISSUE THREAD

**Issue by brainstormapps** [tanersener/mobile-ffmpeg#10]
[!] Unable to find a specification for `mobile-ffmpeg-full (~> 2.2)`

**Comment by tanersener** [comment]
It should be `2.0`, `2.2` is not released yet.

**Comment by brainstormapps** [comment]
[!] Unable to find a specification for `mobile-ffmpeg-full (~> 2.0)`

**Comment by tanersener** [comment]
Hmm, I'm testing with `pod 'mobile-ffmpeg-full', '~> 2.0'` and it is working right now.

Why do you use parentheses around the version, is there a special meaning?

**Comment by brainstormapps** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'FFmpeg' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for FFmpeg
  pod 'mobile-ffmpeg-full', '~> 2.0'
end
========================================
No i am not using  parentheses around the version actually this is a error when i run pod install command

**Comment by tanersener** [comment]
Hmm, OK. I tried on another machine, again no errors.

A similar error @ [stackoverflow](https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods) is solved by deleting and updating pod master repo. Can you try it, your machine may have a similar issue?

```
pod repo remove master
pod setup
pod install
```

**Comment by brainstormapps** [comment]
Many Many thanks 👍

**Comment by tanersener** [comment]
Great, glad it helped
