### ISSUE TITLE
iOS: 'config.h' file not found

### ISSUE THREAD

**Issue by snlo** [tanersener/mobile-ffmpeg#100]
Config.h is included in fftools_ffmpeg.h, but config.h does not exist at all.

iOS：9.3
Xcode：10.1
Pod： 'mobile-ffmpeg-full', '4.2'

**Comment by tanersener** [comment]
You're right, it is not included in IOS frameworks. But I didn't see it causing a failure. Can you share your compile output?

**Comment by snlo** [comment]
I think I probably imported "fftools_ffmpeg.h"
<img width="909" alt="屏幕快照 2019-03-22 上午10 05 24" src="https://user-images.githubusercontent.com/14214416/54796189-392da000-4c8a-11e9-9746-5644a8a2054f.png">
<img width="910" alt="屏幕快照 2019-03-22 上午10 05 05" src="https://user-images.githubusercontent.com/14214416/54796203-4185db00-4c8a-11e9-97d8-daf20b485c3c.png">

**Comment by tanersener** [comment]
Thanks. I can confirm that when `fftools_ffmpeg.h` is imported compilation fails with `'config.h' file not found`. 

Importing fftools_ffmpeg.h is not necessary most of the time. Do you have a specific reason to import it?

**Comment by snlo** [comment]
When I use some of the underlying APIs in ffmpeg, I might import the ‘fftools_ffmpeg.h’ file. You need to manually comment out the import of "config.h", which is not convenient for 'cocoapods' dependency management. Thank you for your attention.

**Comment by tanersener** [comment]
You're right. It will be removed in the next release.
