### ISSUE TITLE
[IOS] Crash in callbackDataRemove, in thread 23

### ISSUE THREAD

**Issue by EternalWill** [tanersener/mobile-ffmpeg#101]
Crash when compressing a video file, using the command @"-i file1.mov -crf 28 -b:v 600k -preset fast -y file2.mp4,
Environment: cocoapods import pod 'mobile-ffmpeg-video', '4.2', xcode10.1, emulator 12.1, iphone7 (12.0.1), swift and Objective-C, there are other C-mixes.
Try: New project demo test is normal, including the same simulator and real machine
![image](https://user-images.githubusercontent.com/16315595/54800425-bc57f180-4c9c-11e9-8676-75fa232cd6a9.png)

**Comment by tanersener** [comment]
I don't see the crash reason in your screenshot. Can you provide log output please?

**Comment by EternalWill** [comment]
I turned on the AV_LOG_TRACE log level and set the proxy and proxy callback log information, but did not return any logs.
The debug output has only the following 2 lines of information.
Swift and Objective-C crash collections are not collected

Loaded mobile-ffmpeg-video-x86_64-4.2
Async callback block started.

**Comment by EternalWill** [comment]
New findings:
I am in the simulator, close the exception breakpoint, will not crash, can be compressed normally. But even after the compression is complete, opening the exception breakpoint will crash.
Still not on the iphone7 phone

**Comment by tanersener** [comment]
Can you share your `file1.mov` input file?

**Comment by EternalWill** [comment]
[IMG_1305.MOV.zip](https://github.com/tanersener/mobile-ffmpeg/files/2995434/IMG_1305.MOV.zip)
The input video file was recorded by the iphone7 camera and the input file was replaced when the problem was corrected.
The problem should be related to my project environment, but I can't figure it out

**Comment by tanersener** [comment]
Thanks, I tested your command on `video` package with `IMG_1305.MOV` file but didn't receive any errors.

Do you have ARC enabled in your project?

**Comment by EternalWill** [comment]
Yes, ARC

**Comment by tanersener** [comment]
Which `Diagnostics` options are enabled for your scheme?

<img width="680" alt="Screen Shot 2019-03-22 at 12 27 42" src="https://user-images.githubusercontent.com/10158439/54813136-eb229780-4c9d-11e9-8432-e5e2cf195989.png">

**Comment by EternalWill** [comment]
Only open "Main Thread Checker"

**Comment by tanersener** [comment]
Having an `exception breakpoint` is causing this confusion. There is not a crash in your case. `callbackDataRemove` method receives exceptions on some conditions and catches them inside. But if you have an `exception breakpoint`, then application stops. This is not a crash. You need to catch only **uncaught** exceptions.

**Comment by EternalWill** [comment]
The picture below is a new screenshot.
After the exception breakpoint is closed, both the real machine and the emulator can compress the video normally.
But even after the compressed video is finished, enabling the exception breakpoint will stop.
![image](https://user-images.githubusercontent.com/16315595/54817713-8cc3dc00-4cd2-11e9-8d53-d081084f19c2.png)

**Comment by EternalWill** [comment]
At the beginning, I wrote this compression in the demo. I started the exception breakpoint during the test, and there was no problem.
Even if the exception breakpoint is closed in the project now, it is not a complete solution.

**Comment by tanersener** [comment]
> The picture below is a new screenshot.
After the exception breakpoint is closed, both the real machine and the emulator can compress the video normally.
But even after the compressed video is finished, enabling the exception breakpoint will stop.

<img width="804" alt="Screen Shot 2019-03-22 at 14 46 30" src="https://user-images.githubusercontent.com/10158439/54821159-6c842500-4cb2-11e9-9670-46f9aa8172e4.png">

Your second screenshot shows a crash with `SIGABRT`. It is different than the first one. The first one was in `callbackDataRemove` function and this one is in `executeWithArguments` function. Can you please explain how this crash occurred?

**Comment by EternalWill** [comment]
I use ffmpeg compression comparison with a unified video source, and the mobile_ffmpeg distortion and mosaic are severe.
Use the same command ffmpeg -i file1.mov -crf 28 -preset fast -y file2.mp4 The quality difference is too large.
One of the test videos is mac, one is compressed by mobile_ffmpeg
![image](https://user-images.githubusercontent.com/16315595/54824379-b63a3300-4ce5-11e9-9ea0-49f7300e1842.png)

**Comment by EternalWill** [comment]
Sorry, the second screenshot I can't reproduce.

**Comment by tanersener** [comment]
> Sorry, the second screenshot I can't reproduce.

Your last screenshot includes a NULL object, its address is 0x0. This must be the reason of your crash.

<img width="461" alt="Screen Shot 2019-03-22 at 16 57 29" src="https://user-images.githubusercontent.com/10158439/54828052-65fea900-4cc4-11e9-9e2e-b1e809a61555.png">

**Comment by tanersener** [comment]
> Use the same command ffmpeg -i file1.mov -crf 28 -preset fast -y file2.mp4 The quality difference is too large.
One of the test videos is mac, one is compressed by mobile_ffmpeg

Can you provide command outputs for both executions? I think outputs include the explanation of this difference.

**Comment by EternalWill** [comment]
mac：ffmpeg -i /Users/*/Downloads/originalVideo.mp4 -crf 28 -preset fast -y /Users/*/Downloads/crf28_fast.mp4 
simulator:-i /Users/essonmama/Library/Developer/CoreSimulator/Devices/6F7B6FEF-012B-4349-8DD5-5F56120476A9/data/Containers/Bundle/Application/D43E90BA-F242-4D59-8F91-C7BC2059B644/VideoEditDemo-Swift.app/originalVideo.mp4 -crf 28 -preset fast -y /Users/essonmama/Library/Developer/CoreSimulator/Devices/6F7B6FEF-012B-4349-8DD5-5F56120476A9/data/Containers/Data/Application/3E85861D-8CAE-4CB4-971F-9E86F63F2039/tmp/1553309611.795573_5.mp4

**Comment by tanersener** [comment]
Can you share outputs too?

**Comment by EternalWill** [comment]
[mac_crf_28.mp4.zip](https://github.com/tanersener/mobile-ffmpeg/files/3001719/mac_crf_28.mp4.zip)
[simulator_crf_28.mp4.zip](https://github.com/tanersener/mobile-ffmpeg/files/3001721/simulator_crf_28.mp4.zip)

**Comment by tanersener** [comment]
You can see the difference using `ffprobe`

> [mac_crf_28.mp4.zip](https://github.com/tanersener/mobile-ffmpeg/files/3001719/mac_crf_28.mp4.zip)

on macos, your video is encoded with `h264` (high quality) profile.

`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920, 3615 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)`

> [simulator_crf_28.mp4.zip](https://github.com/tanersener/mobile-ffmpeg/files/3001721/simulator_crf_28.mp4.zip)

on mobile-ffmpeg, your video is encoded with `mpeg4` (simple) profile.

`Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 3548 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)`

If you do not specify video codec for output, `ffmpeg` selects best video codec possible for that file extension. This is why the same command is encoded with different codecs on difference platforms, h264 on macos, mpeg4 on mobile-ffmpeg. 

If you add `-vcodec mpeg4` or `-vcodec h264` to your command then both output videos will be the same.

**Comment by EternalWill** [comment]
I recompress with command "ffmpeg -i %@ -vcodec h264 -crf 28 -preset fast -y %@", the following video and video information

[1553517310.390942_5.mp4.zip](https://github.com/tanersener/mobile-ffmpeg/files/3003250/1553517310.390942_5.mp4.zip)

Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1080x1920 [SAR 1:1 DAR 9:16], 1525 kb/s, 30 fps, 30 tbr, 15360 tbn, 30720 tbc (default)

**Comment by tanersener** [comment]
> I recompress with command "ffmpeg -i %@ -vcodec h264 -crf 28 -preset fast -y %@", the following video and video information

Do you have a question?

**Comment by EternalWill** [comment]
> > 我用命令“ffmpeg -i％@ -vcodec h264 -crf 28 -preset fast -y％@”重新压缩，以下视频和视频信息
> 
> 你有问题吗？

Video quality and the same commands used on the mac are still huge.
And the bit rate and tbc are only half of the mac environment, the output file is in the description

**Comment by tanersener** [comment]
> Video quality and the same commands used on the mac are still huge.
> And the bit rate and tbc are only half of the mac environment, the output file is in the description

This is not a `mobile-ffmpeg` issue. There may be many different reasons for this. 
- Different `ffmpeg` versions can cause this
- Different `x264` versions can cause this
- Different input videos can cause this
- Different hardware specs can cause this. When `ffmpeg` compresses a file, some encoding parameters are selected according to hardware capabilities (CPU/RAM) of that device. See answers to this [stackoverflow](https://stackoverflow.com/questions/46898384/ffmpeg-libx264-encoder-different-machines-different-output) question.

[ffmpeg h264 guide](https://trac.ffmpeg.org/wiki/Encode/H.264) includes additional information about `x264` encoding parameters. 

Also consider asking this question to `ffmpeg-user@ffmpeg.org` emailing list. They can help you about that.

**Comment by EternalWill** [comment]
Ok, thank you very much for your help.
