### ISSUE TITLE
error while building libuuid - WARNING: 'aclocal-1.13' is missing on your system.

### ISSUE THREAD

**Issue by moster67** [tanersener/mobile-ffmpeg#102]
I am building the development branch but I keep getting a failure with libuuid.
These are the last lines related to the error:

> config.status: executing depfiles commands
config.status: executing libtool commands
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/osboxes/mobile-ffmpeg/src/libuuid/missing aclocal-1.13
/home/osboxes/mobile-ffmpeg/src/libuuid/missing: line 81: aclocal-1.13: command not found
WARNING: 'aclocal-1.13' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:424: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

Any ideas what I can do to resolve this? I have googled but did not find a working solution.
Thanks.

**Comment by moster67** [comment]
Resolved it:
by using Reconf-option explained in the wiki here:
https://github.com/tanersener/mobile-ffmpeg/wiki/Reconf-Option
but `autoreconf` alone was not enough. I had to use this command:
`autoreconf --force --install`

OK, building is now continuing but I noted it takes quite some time on my VM so I will check tomorrow morning when I wake up and hopefully see everything built.

**Comment by moster67** [comment]
OK, after rebuilding twice (I forgot to set environment variables to ANDROID_HOME and JAVA_HOME), the build process succeeded. Well, at least that was what I thought:
When loading the AAR-file, I get the following error in Android Studio:

>  java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:115)
        at com.arthenica.mobileffmpeg.Config.enableLogCallback(Unknown Source:0)
        at com.tillekesoft.ffmpeg42test.MainActivity.enableLogCallback(MainActivity.java:79)
        at com.tillekesoft.ffmpeg42test.MainActivity.onCreate(MainActivity.java:50)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

I checked the JNI-folder and indeed `libcpufeatures.so` is missing. I compared the JNI-folder to the ones that we can download and in the downloaded AAR-package, the so-library is present.

So I guess something went wrong when building.

Any idea what I should I look for? By the way, I used the full option gpl enabled.
Thanks.

**Comment by tanersener** [comment]
Development branch includes some changes regarding `cpufeatures` library. It is no longer included in `.aar` archives, it is bundled in `libmobileffmpeg-abidetect.so`. So you shouldn't be needing it.

Can you share your `android.sh` line, also the output of `grep INFO build.log`?

**Comment by moster67** [comment]
I did this from root otherwise I got permission errors:
Unsure what you mean with `android.sh` but if you mean my command I used, then it was:
`./android.sh --full --enable-gpl`

Here is `grep INFO build.log`
https://pastebin.com/4yf3dZPC

As a I side note, I downloaded the development branch by cloning it in Git as follows:
`git clone -b development --single-branch https://github.com/tanersener/mobile-ffmpeg.git`

**Comment by tanersener** [comment]
Thanks, at which stage do you receive permission errors? What `build.log` prints at that point?

Also on which platform you received `java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found` error?

**Comment by moster67** [comment]
Permission errors are thrown in the beginning if I run Android.sh:

> osboxes@osboxes:~/mobile-ffmpeg$ export ANDROID_NDK_ROOT=/home/osboxes/Android/Sdk/ndk-bundle
osboxes@osboxes:~/mobile-ffmpeg$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
osboxes@osboxes:~/mobile-ffmpeg$ export ANDROID_HOME=/home/osboxes/Android/Sdk
osboxes@osboxes:~/mobile-ffmpeg$ ./android.sh --full --enable-gpl
./android.sh: line 493: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
./android.sh: line 496: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
./android.sh: line 497: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
./android.sh: line 568: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
./android.sh: line 575: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
Building mobile-ffmpeg library for Android

but running as root, then it works fine. 
Perhaps something with my VM installation (I am using a pre-configured Virtual Box image running Ubuntu 16.04.6 (64bit)? I am not a frequent user of Linux so this is what I do when I need to compile something in Linux.

I ran my simple Android-app (see code here: https://pastebin.com/WXRs7yvR) on Windows 10 using Android Studio 3.3.2. I tried to install the app on my Samsung Galaxy Note 9 so I guess the arm64-v8a architecture was used.

**Comment by tanersener** [comment]
> osboxes@osboxes:/mobile-ffmpeg$ ./android.sh --full --enable-gpl
> ./android.sh: line 493: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
> ./android.sh: line 496: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
> ./android.sh: line 497: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
> ./android.sh: line 568: /home/osboxes/mobile-ffmpeg/build.log: Permission denied
> ./android.sh: line 575: /home/osboxes/mobile-ffmpeg/build.log: Permission denied

It looks like your non-root user doesn't have write permissions on `build.log` file. If you delete `build.log` file it will be created with right permissions on your next run.

There was a bug in one of the external libraries enabled by `--full` flag. I just fixed it, if you pull the latest commits and try again your build will succeed.

**Comment by moster67** [comment]
Thank you. 
Now I don't need to use root.
I pulled the latest version and restarted with my build, using same command as before 
i.e. `./android.sh --full --enable-gpl`

However, I am still struggling to get this to work.
This time ffmpeg library fails to compile and I cannot fix it with `autoreconf`.
This is last lines in build.log
> /home/osboxes/mobile-ffmpeg/prebuilt/android-arm/libvpx/lib/libvpx.a(arm_cpudet$
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ffbuild/library.mak:102: recipe for target 'libavcodec/libavcodec.so.58' failed

Can I fix this somehow. In your Wiki article you don't mention any remedy...

**Comment by tanersener** [comment]
Development branch is not as stable as master; this is why you're having some difficulties building it. 

> /home/osboxes/mobile-ffmpeg/prebuilt/android-arm/libvpx/lib/libvpx.a(arm_cpudet$
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ffbuild/library.mak:102: recipe for target 'libavcodec/libavcodec.so.58' failed

This error is new for me, can you share your `build.log` please?

**Comment by moster67** [comment]
No worries. You are doing a great job, especially considering also the assistance you are giving. It is much appreciated.
The difference I noted from yesterday, is that ffmpeg fails to build.

Here is the log:
https://www.dropbox.com/s/iorn886kn7fz8w4/build.log.zip?dl=0

Please let me know when you have downloaded it so I can remove the link. Thanks.

**Comment by tanersener** [comment]
> Please let me know when you have downloaded it so I can remove the link. Thanks.

Downloaded it, thanks.

**Comment by tanersener** [comment]
I reverted back to original `cpufeatures` implementation. Can you pull the latest changes and try again with `./android.sh --full --rebuild-libvpx` command. `--enable-gpl` option alone does not enable GPL libraries, so I removed it.

**Comment by moster67** [comment]
Thanks.
I am in the office now but will do it as soon as I am home. I will report back later.

**Comment by moster67** [comment]
Seems everything is fine now. From logcat:

> 2019-03-25 20:59:23.579 1629-1629/com.tillekesoft.ffmpeg42test I/mobile-ffmpeg: Loaded mobile-ffmpeg-full-arm64-v8a-4.2-20190325.
> 2019-03-25 20:59:23.582 1629-1629/com.tillekesoft.ffmpeg42test I/System.out: 4.2
> 2019-03-25 20:59:23.594 1629-1787/com.tillekesoft.ffmpeg42test D/mobile-ffmpeg: ffmpeg version v4.2-dev-768

Many thanks for your help and patience.

Just two more questions if I may:
-Since enable GPL was removed, does this mean that this build does not include such libraries such as x264,x265?
-When I try FFmpeg.execute( "-protocols"), I never get the output. I even tried with your sample app. DO you get it?

**Comment by tanersener** [comment]
> -Since enable GPL was removed, does this mean that this build does not include such libraries like x264,x265? Edit: looking at the size of the aar generated, such libs are probably included.

No, they are not included with `--full` flag. You need to explicitly enable them with `--enable-gpl --enable-x264 --enable-x265 --enable-xvidcore --enable-libvidstab`. `.aar` becomes huge when all libraries are enabled so I recommend enabling only necessary libraries.

> -When I try FFmpeg.execute( "-protocols"), I never get the output. I even tried with your sample app. I tried it also with your uploaded libs but nothing. Do you get it?

I get it on `IOS` but not on `Android`. Not only on development branch, but also released versions doesn't print it. Other capabilities (encoders, formats, muxers, ...) are not printed as well. I think I shall create an issue about it.

**Comment by tanersener** [comment]
Thanks for your suggestions. Yes, you can close it.
