### ISSUE TITLE
[Android] minimum SDK problem

### ISSUE THREAD

**Issue by jigneshvashundhara** [tanersener/mobile-ffmpeg#103]
Manifest Merge Error & Required minimum sdk 24?

Why this library require minSdk 24? My app working on on minimum 16 sdk but some of functionality i require to use your library but in library minimum sdk define 24 so please help.. 

Thanking you

**Comment by tanersener** [comment]
`Main` releases require min API level 24, and `LTS` releases require min API level 21.

API capabilities required to build/run `mobile-ffmpeg` are not included in levels earlier than 21. This is why they are not supported.

**Comment by jigneshvashundhara** [comment]
sir please let me know how to use LTS release

**Comment by tanersener** [comment]
```
dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.2.LTS'
}
```

**Comment by foobra** [comment]
@tanersener Can I modify configure file to support api level 19? or which previous releases support api level 19? or some other build scripts recommend for api level 19? thanks

**Comment by tanersener** [comment]
None of the published binaries support API Level 19 and I don't plan to support it.

If you need it, you can download `mobile-ffmpeg` source, edit and try it yourself.

**Comment by ahar** [comment]
Hi @tanersener ! 

Try to use it in my app. My minSdkVersion is 21. 

I got errors: 
AndroidManifest.xml:26:9-45 Error:
	Attribute application@icon value=(@mipmap/icon_launcher) from AndroidManifest.xml:26:9-45
	is also present at [com.arthenica:mobile-ffmpeg-full:4.2.LTS] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:21:5-163:19 to override.
AndroidManifest.xml:27:9-37 Error:
	Attribute application@label value=(@string/kode) from AndroidManifest.xml:27:9-37
	is also present at [com.arthenica:mobile-ffmpeg-full:4.2.LTS] AndroidManifest.xml:14:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:21:5-163:19 to override.
AndroidManifest.xml:28:9-36 Error:
	Attribute application@supportsRtl value=(false) from AndroidManifest.xml:28:9-36
	is also present at [com.arthenica:mobile-ffmpeg-full:4.2.LTS] AndroidManifest.xml:16:9-35 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:21:5-163:19 to override.

I use lts, my build.gradle contains: 
    implementation 'com.arthenica:mobile-ffmpeg-full:4.2.LTS'

If I download zip archive from here: https://github.com/tanersener/mobile-ffmpeg/archive/v4.2.1.zip AndroidMenifest.xml clearly states that minsdkversion is 24. But in docs it is said that lts supports minSdkVersion 21. 

Thanks!

**Comment by tanersener** [comment]
> AndroidManifest.xml:26:9-45 Error:
> Attribute application@icon value=(@mipmap/icon_launcher) from AndroidManifest.xml:26:9-45
> is also present at [com.arthenica:mobile-ffmpeg-full:4.2.LTS] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
> Suggestion: add 'tools:replace="android:icon"' to element at AndroidManifest.xml:21:5-163:19 to override.

I think the message is pretty clear. `mobile-ffmpeg` library includes an `ic_launcher` icon inside. You need to add `tools:replace="android:icon"` to override it as suggested. The same error is printed for `label` and `supportsRtl`, you need to overwrite them too.

> If I download zip archive from here: https://github.com/tanersener/mobile-ffmpeg/archive/v4.2.1.zip AndroidMenifest.xml clearly states that minsdkversion is 24. But in docs it is said that lts supports minSdkVersion 21.

Version names of `LTS` releases end with `LTS`. https://github.com/tanersener/mobile-ffmpeg/archive/v4.2.1.zip is **not** an `LTS` release, it is `Main` release. So it supports API Level 24. Is it clear?

**Comment by ahar** [comment]
@tanersener oops. My bad. Sorry

**Comment by tanersener** [comment]
> None of the published binaries support API Level 19 and I don't plan to support it.
> 

API levels below 21 does not support `arm64-v8a` architecture. This is why my initial plan was to support API levels >= 21. 

Recently, I had some time to fix incompatibilities for API levels below 21 on the development branch. Right now, LTS release of development branch supports API level 16 and the next `mobile-ffmpeg` release is planned to support API Level 16 too.
