### ISSUE TITLE
link problem with android static library

### ISSUE THREAD

**Issue by foobra** [tanersener/mobile-ffmpeg#105]
**Description**
I change build/android-ffmepg.sh, enable static and disable shared. The build outputs are some .a files.

**Expected behavior**
Successfuly link .a with ndk files.

**Current behavior**
ld error. All  static library link with error like "....x86/libavcodec.a: member at 1709210 is not an ELF object"

**Environment**
 - Platform: Android
 - Architecture:x86
 - Version development branch
 - Source branch development branch
 - Android Studio version 3.3.2
 - Android NDK version 19.2.5345600

**Comment by tanersener** [comment]
`mobile-ffmpeg` builds shared libraries for Android. You can edit the scripts and build static libraries too but they are not officially supported. So your error is not an issue about the library.

**Comment by foobra** [comment]
@tanersener thanks for response. Under the same condition, will static library binary size smaller than dynamic library ? I use static library only for binary size reason.

**Comment by tanersener** [comment]
No, shared libraries have smaller size than static libraries.

**Comment by foobra** [comment]
@tanersener thanks, I will keep study on how to reduce library size. My goal is making android ffmpeg library size under 3m

**Comment by foobra** [comment]
btw, is there a convenient way to reduce the avcodec's size? For example, disable those codecs that barely use in android?

-rw-r--r-- 1 jtang jtang  25M 3  28 15:03 libavcodec.a
-rwxr-xr-x 1 jtang jtang  12M 3  28 13:56 libavcodec.so

**Comment by tanersener** [comment]
> btw, is there a convenient way to reduce the avcodec's size? For example, disable those codecs that barely use in android?
> 

You can use `--disable-all` to disable everything and use `--enable-XX` flags to enable only components you need.

**Comment by foobra** [comment]
Thanks, it works~
