### ISSUE TITLE
[IOS] build failure, libiconv!!

### ISSUE THREAD

**Issue by krislyy** [tanersener/mobile-ffmpeg#106]
**Description**
I use command "./ios.sh --enable-libass --disable-armv7 --disable-armv7s --disable-i386" to build libass.a.  
but failed in building libiconv.a. like the log shows below. I think it's problem of system environment.

**Logs**
'''
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sys/_types/_uid_t.h:31:3131make[2]: *** [allocator.o] Error 1
: make[2]: : *** Waiting for unfinished jobs....error: error
cannot combine with previous 'type-name' declaration specifier
: typedef __darwin_uid_t        uid_t;
                              ^cannot combine with previous 'type-name' declaration specifier

../config.h:1162typedef __darwin_uid_t        uid_t;
                              ^
:15:../config.h:1162 note: expanded from macro 'uid_t'
:15#define uid_t int
: note: expanded from macro 'uid_t'
              ^#define uid_t int
              ^

3 errors generated.
make[2]: *** [areadlink.o] Error 1
3 errors generated.
3 errors generated.
make[2]: *** [careadlinkat.o] Error 1
make[2]: *** [binary-io.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
'''
**Environment**
 - Platform: [IOS]
 - Architecture: [arm64,  x86_64]
 - Source branch (if applicable) [master]
 - Xcode version (if applicable) [12.2, 10.2]

**Other**

**Comment by tanersener** [comment]
This is compatibility issue about `Xcode 10.2`. Until I publish a fix, you can install `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` package as a workaround.

**Comment by krislyy** [comment]
I fixed the issue by reinstalling ../macOS_SDK_headers_for_macOS_10.14.pkg. Thanks a lot.

**Comment by tanersener** [comment]
Fixed in development branch

**Comment by tanersener** [comment]
This issue is fixed in `master` too. Can we close it?

**Comment by krislyy** [comment]
absolutely, yes!
