### ISSUE TITLE
dlopen failed: library "libcamera2ndk.so" not found

### ISSUE THREAD

**Issue by foobra** [tanersener/mobile-ffmpeg#108]
**Description**
My LG Nexus 4 phone, when executing 

> System.loadLibrary("avcodec")

app crashed with stacktrace: 
  java.lang.UnsatisfiedLinkError: dlopen failed: library "libcamera2ndk.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)

**Environment**
 - Platform: android
 - Architecture: arm-v7a-neon
 - Version (if applicable) 4.2
 - Source branch (if applicable) both v4.2 and development fail
 - Android Studio version (if applicable) 3.3.2
 - Android NDK version (if applicable) r19

x86 emulator work fine

**Comment by tanersener** [comment]
`libcamera2ndk.so` is included in Android devices with API Level 24+. What is the API level of your `My LG Nexus 4` device?

**Comment by foobra** [comment]
@tanersener Android 6.0（API level 23）
Did development branch drop support for api 23?

**Comment by tanersener** [comment]
No. You can build both Main (API 24) and LTS (API 21) variants of `mobile-ffmpeg` using `android.sh`. To support devices with API 21+ you need to build LTS variant with `--lts` flag.

`./android.sh --lts`

**Comment by foobra** [comment]
thanks, --lts works
