### ISSUE TITLE
Unable to use drawtext filter with spaces. 

### ISSUE THREAD

**Issue by tolew1** [tanersener/mobile-ffmpeg#109]
In Android, I've been trying for a while using quotes, and everything possible. drawtext in filter_complex will not work with spaces. 

Take this string for example this will not work using example text "Text Here"

` String drawtext = "drawbox=y=ih-h:color=black@0.3:width=iw:height=50:t=fill,drawtext=fontfile=/system/fonts/Roboto-Medium.ttf:text='Text Here':fontcolor=white@0.5:fontsize=28:x=w-tw-6:y=h-th-8";`

But this does

` String drawtext = "drawbox=y=ih-h:color=black@0.3:width=iw:height=50:t=fill,drawtext=fontfile=/system/fonts/Roboto-Medium.ttf:text='TextHere':fontcolor=white@0.5:fontsize=28:x=w-tw-6:y=h-th-8";`

I feel like I tried every combination of trying to escape space, etc.

**Comment by tanersener** [comment]
`FFmpeg.execute` method on Android is overloaded and has an optional delimiter parameter. Delimiter defines how a command string will be split into arguments. If you do not specify a delimiter then space character is used as default. 

In your case you have two options:
1. Split your command string into `String[]` yourself and call `execute(String[] arguments)` method.
2. Use a different delimiter character in your command call `execute` by specifying it `FFmpeg.execute("-i~file1.mp4~-c:v~mpeg4~file2.mp4", "~")`.
