### ISSUE TITLE
Video file not found in given test application (iOS)-SlideShow option

### ISSUE THREAD

**Issue by brainstormapps** [tanersener/mobile-ffmpeg#11]
I have successfully build test app on device. But when I press button to create video file using images as given in "Slide Show" option, get following result.

/var/containers/Bundle/Application/0DD4F2B0-FF37-471D-BA24-9F38FC27A2D6/MobileFFmpegTest.app/slideshow.mp4: Operation not permitted

I try to find slideshow.mp4 file from given solution (if I run it on simulator), there is no file exist in MobileFFmpegTest.app folder.

Similarly when I press play button to run video file in application, there is no result.

Do you have any suggestions to solve it.

Thanks in advance.

**Comment by tanersener** [comment]
`CREATE` button in test application creates a `slideshow.mp4` file under IOS `resource folder` and `PLAY` button plays it.

It looks like you can not create `slideshow.mp4` file, either you don't have permission or there is another error.

Let me try a few things and write it back.

**Comment by tanersener** [comment]
Just pushed a change on `dev-v2.x` branch, changing the folder `slideshow.mp4` is created. 

Can you pull and try with it? [this](https://github.com/tanersener/mobile-ffmpeg/commit/7c8743ba07145aca93556b389918f695f13ce3a8) is the actual commit, only two lines changed.

**Comment by brainstormapps** [comment]
Thanks for response,
I have found the reason. Basically this process take too much time to create required mp4 file through given images.
Can you help me to increase the speed of process(to reduce process time) which is acceptable for user.

**Comment by tanersener** [comment]
I'm closing this, if you need assistance please create a new issue.
