### ISSUE TITLE
Creating Android archive under prebuilt/android is failing

### ISSUE THREAD

**Issue by Blank-AS** [tanersener/mobile-ffmpeg#115]
After running android.sh and while its compiling & installing the required packages, I still get:
Creating Android archive under prebuilt/android-aar: failed
FFmpeg & Mobile-FFmpeg packages are successfully built for all the architectures, except when it reaches the end this problem happens.

Last contents from the building.log:

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/Userrname/Desktop/mobile-ffmpeg-4.2.1/android/app/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by tanersener** [comment]
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Have you considered setting `ANDROID_HOME` variable?

**Comment by Blank-AS** [comment]
It worked thanks.

**Comment by ekstrah** [comment]
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> Have you considered setting `ANDROID_HOME` variable?

Is it something like this? “/Users/[USER]/Library/Android/sdk”

**Comment by tanersener** [comment]
@ekstrah Please see [Android Environment Variables Documentation](https://developer.android.com/studio/command-line/variables#envar).
