### ISSUE TITLE
Integrating Mobile-FFMPEG with ANDROID

### ISSUE THREAD

**Issue by Blank-AS** [tanersener/mobile-ffmpeg#116]
Can you please put out a step for us on how to integrate the compiled objects under the "prebuilt" directory with our android project.

**Comment by tanersener** [comment]
`android.sh` build script creates `mobile-ffmpeg.aar` file under the `prebuilt/android-aar/mobile-ffmpeg` folder. You can import this file using `File -> New -> New Module -> Import .JAR/.AAR` in `Android Studio`.

**Comment by Blank-AS** [comment]
Thanks.

Then, after adding the dependency " implementation 'com.arthenica:mobile-ffmpeg-full:4.2.1' " in the Gradle file, I can use the FFMPEG commands normally or is there any extra things needed?

**Comment by Blank-AS** [comment]
And BTW the file is empty is it normal 
<img width="819" alt="-" src="https://user-images.githubusercontent.com/49361471/55728527-e63f4100-5a1c-11e9-98c0-fec29bce188c.png">

**Comment by tanersener** [comment]
Adding `implementation 'com.arthenica:mobile-ffmpeg-full:4.2.1'` in `build.gradle` will download prebuilt binaries from `jcenter()`.

In your case you don't need to do that. `File -> New -> New Module -> Import .JAR/.AAR` step will add a local dependency for your `.aar` file.
