### ISSUE TITLE
Is my ios device must be jailbroken to install it?

### ISSUE THREAD

**Issue by hasnogaems** [tanersener/mobile-ffmpeg#119]
Subj.

**Comment by tanersener** [comment]
No

**Comment by hasnogaems** [comment]
Can I install it with default permissions or I need some developer account or something?

**Comment by tanersener** [comment]
> Can I install it with default permissions or I need some developer account or something?

This project provides a `library` for mobile platforms and your questions are meaningful for a library. You can use this library in your mobile applications but the library itself is not an application, you can't install it alone.
