### ISSUE TITLE
Android - Overlay on top of a video

### ISSUE THREAD

**Issue by JohhhhhhDeep** [tanersener/mobile-ffmpeg#120]
Hello,
I'm looking to put an overlay on top of a video.
I'm trying this :

`String ffmpegCommand = String.format("-i %s -i %s -filter_complex overlay=10:main_h-overlay_h-10 %s", videoPath, "drawable://" + R.drawable.overlay, videoPath.replace(".mp4", "overlay.mp4"));
FFmpeg.execute(ffmpegCommand);`

It seems not working.
With the logs i just have an error about the drawable i'm trying to add, it seems it does not recognize the drawable path whereas it should works.
The error : `drawable://2131231064: Protocol not found`

Do you have any idea what is wrong ? Thanks.

**Comment by tanersener** [comment]
You are trying to use `drawable` protocol but it is not listen in [official protocols documentation](https://ffmpeg.org/ffmpeg-protocols.html). Can you show me an official reference about it?

**Comment by JohhhhhhDeep** [comment]
Hmmm i see...
So do you know how can i use an image from the ressources file of the app, with this library ?

**Comment by tanersener** [comment]
There is a test application under `android/test-app` folder. Video tab of that application uses images from resources folder. You can use the same approach in your application.
