### ISSUE TITLE
[Android] test-app

### ISSUE THREAD

**Issue by Blank-AS** [tanersener/mobile-ffmpeg#121]
When trying to open "test-app" application in android studio I'm getting this error: 

- unable to resolve class com.android.build.OutputFile

**Comment by tanersener** [comment]
> * unable to resolve class com.android.build.OutputFile

It is not possible to understand the cause of your error with so little information. You need to provide environment information: Android Studio version, gradle version, gradle version used by Android Studio.

**Comment by Blank-AS** [comment]
Android Studio Version: 3.4

Gradle Version: 5.2.1

**Comment by tanersener** [comment]
Test application is tested on both versions with no issues. Did you search for this issue at [stackoverflow](https://stackoverflow.com)?

**Comment by Blank-AS** [comment]
Yes, and no answers found.

**Comment by tanersener** [comment]
Can you share your `gradle` preferences under `Android Studio`?

<img width="256" alt="gradle" src="https://user-images.githubusercontent.com/10158439/56352565-2d28f580-61d8-11e9-9b82-71155efaca68.png">

**Comment by Blank-AS** [comment]
<img width="1008" alt="-" src="https://user-images.githubusercontent.com/49361471/56353560-48950000-61da-11e9-928f-af57357c0002.png">

**Comment by tanersener** [comment]
Did you try providing a local gradle distribution like `gradle 5.2.x` or `5.3.x`?

**Comment by Blank-AS** [comment]
I tried local cradle distribution with gradle version 5.4 and still facing the same problem.

**Comment by tanersener** [comment]
Do you have any local changes inside gradle files: `build.gradle`, `settings.gradle`, ... ?

**Comment by Blank-AS** [comment]
Nope.
Reinstalled again to be sure and still the same.

**Comment by tanersener** [comment]
Did you try running `./gradlew build` inside `android` folder, from the shell?

**Comment by Blank-AS** [comment]
<img width="567" alt="-" src="https://user-images.githubusercontent.com/49361471/56467222-af0d5e80-6424-11e9-8654-c028e93c6746.png">

**Comment by tanersener** [comment]
Android test-application is dependent to the parent directory's `build.gradle` file. If parent `build.gradle` file does not exist or its dependencies are modified then `test-app` build may fail.

Can you add the following block to your `build.gradle` and try again?

```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
    }
}
```
