### ISSUE TITLE
[Android] 4.2 LTS Min gpl need API 24 min

### ISSUE THREAD

**Issue by PromoZo** [tanersener/mobile-ffmpeg#124]
Hello,

I'm trying to add the aar file of the LTS 4.2 version (min gpl).
It seems the min API is 24 whereas it should be 21 for the LTS version.

Can you modify the package from the release on github please ?

Thanks.

**Comment by tanersener** [comment]
Thanks for reporting this. 

It looks like all packages of github `4.2.LTS` release were uploaded with wrong `minSdkVersion`. They are all corrected now.

**Comment by PromoZo** [comment]
Thanks, it works like a charm now.
