### ISSUE TITLE
[Android] Callback for a specific execution

### ISSUE THREAD

**Issue by PromoZo** [tanersener/mobile-ffmpeg#125]
Hello,
I'm trying to execute ffmpeg on a thread, and i would like to have a callback to notify when the execution is finished.

Is there a way to do that ?

FFmpeg.getLastReturnCode() is not efficient enough for my use.

Thanks

**Comment by tanersener** [comment]
Test application uses to the following class to perform executions. It can be used to notify execution results too.

https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/src/main/java/com/arthenica/mobileffmpeg/util/AsyncCommandTask.java#L26-L46
