### ISSUE TITLE
[Android] Dont working -t and -loop

### ISSUE THREAD

**Issue by mihail4216** [tanersener/mobile-ffmpeg#129]
Ignore the two commands -t and -loop

I overlay the video on the picture, and set the output video time. And the input video loops to infinity until the video ends.

It turns out just the output video time-limited input video.

This command:
                   
 -i 1556549646527.jpg
 -i jQLZPBXGnS6GWexQ7GaBislMo.mp4
 -filter_complex scale=550:900[bg];
[1:v]scale=442:414[video];
[video]loop=-1:1000:0[video+loop];
[bg][video+loop]overlay=53:242 
-t 12 
1556549646701.mp4

**Comment by tanersener** [comment]
Please ask ffmpeg questions to [ffmpeg-user@ffmpeg.org](ffmpeg-user@ffmpeg.org) emailing list.
