### ISSUE TITLE
build failed for iOS with libwebp

### ISSUE THREAD

**Issue by gfremex** [tanersener/mobile-ffmpeg#133]
./ios.sh --disable-armv7 --disable-armv7s --disable-arm64e --disable-i386 --enable-gpl --enable-x264 --enable-x265 --full
Building mobile-ffmpeg static library for IOS

Architectures: arm64, x86-64
Libraries: ios-zlib, ios-audiotoolbox, ios-coreimage, ios-bzip2, ios-videotoolbox, ios-avfoundation, fontconfig, freetype, fribidi, gmp, gnutls, lame, libass, libiconv, libtheora, libvorbis, libvpx, libwebp, libxml2, opencore-amr, shine, speex, wavpack, kvazaar, x264, x265, libilbc, opus, snappy, soxr, libaom, chromaprint, twolame, sdl, tesseract

Building arm64 platform

fribidi: ok
gmp: ok
libiconv: ok
libvpx: ok
libxml2: ok
opencore-amr: ok
shine: ok
speex: ok
wavpack: ok
kvazaar: ok
x264: ok
x265: ok
libilbc: ok
opus: ok
snappy: ok
soxr: ok
libaom: ok
chromaprint: ok
sdl: ok
giflib: ok
jpeg: ok
libogg: ok
libpng: ok
libuuid: ok
nettle: ok
tiff: ok
expat: ok
libsndfile: ok
freetype: ok
gnutls: ok
lame: ok
libvorbis: ok
libwebp: failed

Errors in build.log:

----------------------------------------------------------------

-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAVE_BUILTIN_BSWAP16
-- Performing Test HAVE_BUILTIN_BSWAP16 - Success
-- Performing Test HAVE_BUILTIN_BSWAP32
-- Performing Test HAVE_BUILTIN_BSWAP32 - Success
-- Performing Test HAVE_BUILTIN_BSWAP64
-- Performing Test HAVE_BUILTIN_BSWAP64 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Performing Test HAVE_PTHREAD_PRIO_INHERIT
-- Performing Test HAVE_PTHREAD_PRIO_INHERIT - Success
-- Performing Test PTHREAD_CREATE_UNDETACHED
-- Performing Test PTHREAD_CREATE_UNDETACHED - Success
-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR) 
-- Performing Test HAVE_MATH_LIBRARY
-- Performing Test HAVE_MATH_LIBRARY - Success
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib (found version "1.2.11") 
-- Found PNG: /Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/libpng/lib (found version "1.6.36") 
-- Found JPEG: /Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/jpeg/lib (found version "") 
-- Found TIFF: /Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/tiff/lib (found version "4.0.10") 
-- Found GIF: /usr/local/lib/libgif.dylib (found version "5.1.4") 
-- Performing Test GIF_COMPILES
-- Performing Test GIF_COMPILES - Success
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file GLUT/glut.h
-- Looking for include file GLUT/glut.h - not found
-- Looking for include file GL/glut.h
-- Looking for include file GL/glut.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file OpenGL/glut.h
-- Looking for include file OpenGL/glut.h - not found
-- Looking for include file shlwapi.h
-- Looking for include file shlwapi.h - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file wincodec.h
-- Looking for include file wincodec.h - not found
-- Looking for include file windows.h
-- Looking for include file windows.h - not found
-- Performing Test WEBP_HAVE_FLAG_SSE41
-- Performing Test WEBP_HAVE_FLAG_SSE41 - Failed
-- Performing Test WEBP_HAVE_FLAG_SSE41
-- Performing Test WEBP_HAVE_FLAG_SSE41 - Failed
-- Performing Test HAS_COMPILE_FLAG
-- Performing Test HAS_COMPILE_FLAG - Success
-- Performing Test FLAG_-mno-sse4.1
-- Performing Test FLAG_-mno-sse4.1 - Failed
-- Performing Test WEBP_HAVE_FLAG_SSE2
-- Performing Test WEBP_HAVE_FLAG_SSE2 - Failed
-- Performing Test WEBP_HAVE_FLAG_SSE2
-- Performing Test WEBP_HAVE_FLAG_SSE2 - Failed
-- Performing Test HAS_COMPILE_FLAG
-- Performing Test HAS_COMPILE_FLAG - Success
-- Performing Test FLAG_-mno-sse2
-- Performing Test FLAG_-mno-sse2 - Failed
-- Performing Test WEBP_HAVE_FLAG_MIPS32
-- Performing Test WEBP_HAVE_FLAG_MIPS32 - Failed
-- Performing Test WEBP_HAVE_FLAG_MIPS32
-- Performing Test WEBP_HAVE_FLAG_MIPS32 - Failed
-- Performing Test WEBP_HAVE_FLAG_MIPS_DSP_R2
-- Performing Test WEBP_HAVE_FLAG_MIPS_DSP_R2 - Failed
-- Performing Test WEBP_HAVE_FLAG_MIPS_DSP_R2
-- Performing Test WEBP_HAVE_FLAG_MIPS_DSP_R2 - Failed
-- Performing Test HAS_COMPILE_FLAG
-- Performing Test HAS_COMPILE_FLAG - Success
-- Performing Test FLAG_-mno-dspr2
-- Performing Test FLAG_-mno-dspr2 - Failed
-- Performing Test WEBP_HAVE_FLAG_NEON
-- Performing Test WEBP_HAVE_FLAG_NEON - Success
-- Performing Test WEBP_HAVE_FLAG_MSA
-- Performing Test WEBP_HAVE_FLAG_MSA - Failed
-- Performing Test WEBP_HAVE_FLAG_MSA
-- Performing Test WEBP_HAVE_FLAG_MSA - Failed
-- Performing Test HAS_COMPILE_FLAG
-- Performing Test HAS_COMPILE_FLAG - Success
-- Performing Test FLAG_-mno-msa
-- Performing Test FLAG_-mno-msa - Failed
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR) 
-- Configuring done
WARNING: Target "anim_dump" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/libpng/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_dump" requests linking to directory "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_dump" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/jpeg/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_dump" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/tiff/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_diff" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/libpng/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_diff" requests linking to directory "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_diff" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/jpeg/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "anim_diff" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/tiff/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "imagedec" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/libpng/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "imagedec" requests linking to directory "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "imagedec" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/jpeg/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "imagedec" requests linking to directory "/Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/prebuilt/ios-arm64-ios-darwin/tiff/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_AS
    CMAKE_CXX_FLAGS
    SDLMAIN_LIBRARY
    SDL_INCLUDE_DIR

-- Build files have been written to: /Volumes/Data/docs/downloads/builds-ios/mobile-ffmpeg/src/libwebp/build
Scanning dependencies of target webputils
Scanning dependencies of target webpdecode
Scanning dependencies of target webpdsp
[  1%] Building C object CMakeFiles/webputils.dir/src/utils/bit_reader_utils.c.o
Scanning dependencies of target webpencode
[  2%] Building C object CMakeFiles/webpdecode.dir/src/dec/alpha_dec.c.o
[  3%] Building C object CMakeFiles/webpdsp.dir/src/dsp/alpha_processing.c.o
[  4%] Building C object CMakeFiles/webpencode.dir/src/enc/alpha_enc.c.o
[  5%] Building C object CMakeFiles/webpdecode.dir/src/dec/buffer_dec.c.o
[  6%] Building C object CMakeFiles/webputils.dir/src/utils/color_cache_utils.c.o
[  7%] Building C object CMakeFiles/webpdsp.dir/src/dsp/cpu.c.o
[  8%] Building C object CMakeFiles/webpencode.dir/src/enc/analysis_enc.c.o
[  8%] Building C object CMakeFiles/webpdsp.dir/src/dsp/dec.c.o
[  9%] Building C object CMakeFiles/webputils.dir/src/utils/filters_utils.c.o
[ 10%] Building C object CMakeFiles/webpdecode.dir/src/dec/frame_dec.c.o
[ 10%] Building C object CMakeFiles/webputils.dir/src/utils/huffman_utils.c.o
[ 11%] Building C object CMakeFiles/webpdsp.dir/src/dsp/dec_clip_tables.c.o
[ 12%] Building C object CMakeFiles/webpencode.dir/src/enc/backward_references_cost_enc.c.o
[ 13%] Building C object CMakeFiles/webpdsp.dir/src/dsp/filters.c.o
[ 14%] Building C object CMakeFiles/webputils.dir/src/utils/quant_levels_dec_utils.c.o
[ 15%] Building C object CMakeFiles/webpdecode.dir/src/dec/idec_dec.c.o
[ 16%] Building C object CMakeFiles/webpdsp.dir/src/dsp/lossless.c.o
[ 17%] Building C object CMakeFiles/webputils.dir/src/utils/rescaler_utils.c.o
[ 17%] Building C object CMakeFiles/webpdecode.dir/src/dec/io_dec.c.o
[ 17%] Building C object CMakeFiles/webpencode.dir/src/enc/backward_references_enc.c.o
[ 18%] Building C object CMakeFiles/webputils.dir/src/utils/random_utils.c.o
[ 19%] Building C object CMakeFiles/webpdsp.dir/src/dsp/rescaler.c.o
[ 20%] Building C object CMakeFiles/webputils.dir/src/utils/thread_utils.c.o
[ 21%] Building C object CMakeFiles/webpdecode.dir/src/dec/quant_dec.c.o
[ 22%] Building C object CMakeFiles/webpdsp.dir/src/dsp/upsampling.c.o
[ 23%] Building C object CMakeFiles/webputils.dir/src/utils/utils.c.o
[ 24%] Building C object CMakeFiles/webpdecode.dir/src/dec/tree_dec.c.o
[ 24%] Building C object CMakeFiles/webputils.dir/src/utils/bit_writer_utils.c.o
[ 24%] Building C object CMakeFiles/webpdsp.dir/src/dsp/yuv.c.o
[ 25%] Building C object CMakeFiles/webpencode.dir/src/enc/config_enc.c.o
[ 26%] Building C object CMakeFiles/webpdecode.dir/src/dec/vp8_dec.c.o
[ 27%] Building C object CMakeFiles/webputils.dir/src/utils/huffman_encode_utils.c.o
[ 28%] Building C object CMakeFiles/webpencode.dir/src/enc/cost_enc.c.o
[ 29%] Building C object CMakeFiles/webpencode.dir/src/enc/filter_enc.c.o
[ 30%] Building C object CMakeFiles/webputils.dir/src/utils/quant_levels_utils.c.o
[ 31%] Building C object CMakeFiles/webpdsp.dir/src/dsp/alpha_processing_neon.c.o
[ 32%] Building C object CMakeFiles/webpdecode.dir/src/dec/vp8l_dec.c.o
[ 33%] Building C object CMakeFiles/webpencode.dir/src/enc/frame_enc.c.o
[ 33%] Built target webputils
[ 34%] Building C object CMakeFiles/webpdsp.dir/src/dsp/dec_neon.c.o
[ 35%] Building C object CMakeFiles/webpdecode.dir/src/dec/webp_dec.c.o
[ 36%] Building C object CMakeFiles/webpencode.dir/src/enc/histogram_enc.c.o
Scanning dependencies of target exampleutil
[ 37%] Building C object CMakeFiles/exampleutil.dir/examples/example_util.c.o
[ 37%] Built target webpdecode
[ 37%] Building C object CMakeFiles/webpencode.dir/src/enc/iterator_enc.c.o
[ 38%] Building C object CMakeFiles/webpdsp.dir/src/dsp/filters_neon.c.o
[ 39%] Linking C static library libexampleutil.a
[ 39%] Built target exampleutil
[ 40%] Building C object CMakeFiles/webpencode.dir/src/enc/near_lossless_enc.c.o
Scanning dependencies of target webpdspdecode
[ 41%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/alpha_processing.c.o
[ 42%] Building C object CMakeFiles/webpdsp.dir/src/dsp/lossless_neon.c.o
[ 43%] Building C object CMakeFiles/webpencode.dir/src/enc/picture_enc.c.o
[ 44%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/cpu.c.o
Scanning dependencies of target webputilsdecode
[ 45%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/bit_reader_utils.c.o
[ 45%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/dec.c.o
[ 46%] Building C object CMakeFiles/webpencode.dir/src/enc/picture_csp_enc.c.o
[ 47%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/color_cache_utils.c.o
[ 48%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/dec_clip_tables.c.o
[ 48%] Building C object CMakeFiles/webpdsp.dir/src/dsp/rescaler_neon.c.o
[ 50%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/filters_utils.c.o
[ 50%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/filters.c.o
[ 51%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/lossless.c.o
[ 51%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/huffman_utils.c.o
[ 52%] Building C object CMakeFiles/webpdsp.dir/src/dsp/upsampling_neon.c.o
[ 53%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/quant_levels_dec_utils.c.o
[ 54%] Building C object CMakeFiles/webpencode.dir/src/enc/picture_psnr_enc.c.o
[ 55%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/rescaler.c.o
[ 56%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/rescaler_utils.c.o
[ 57%] Building C object CMakeFiles/webpencode.dir/src/enc/picture_rescale_enc.c.o
[ 58%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/upsampling.c.o
[ 59%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/random_utils.c.o
[ 59%] Building C object CMakeFiles/webpencode.dir/src/enc/picture_tools_enc.c.o
[ 60%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/thread_utils.c.o
[ 60%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/yuv.c.o
[ 61%] Building C object CMakeFiles/webputilsdecode.dir/src/utils/utils.c.o
[ 62%] Building C object CMakeFiles/webpdsp.dir/src/dsp/yuv_neon.c.o
[ 62%] Built target webputilsdecode
[ 63%] Building C object CMakeFiles/webpencode.dir/src/enc/predictor_enc.c.o
[ 64%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/alpha_processing_neon.c.o
[ 65%] Building C object CMakeFiles/webpdsp.dir/src/dsp/cost.c.o
[ 66%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/dec_neon.c.o
[ 67%] Building C object CMakeFiles/webpdsp.dir/src/dsp/enc.c.o
[ 68%] Building C object CMakeFiles/webpencode.dir/src/enc/quant_enc.c.o
[ 69%] Building C object CMakeFiles/webpdsp.dir/src/dsp/lossless_enc.c.o
[ 70%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/filters_neon.c.o
[ 70%] Building C object CMakeFiles/webpdsp.dir/src/dsp/ssim.c.o
[ 71%] Building C object CMakeFiles/webpencode.dir/src/enc/syntax_enc.c.o
[ 72%] Building C object CMakeFiles/webpdsp.dir/src/dsp/cost_neon.c.o
[ 73%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/lossless_neon.c.o
[ 74%] Building C object CMakeFiles/webpencode.dir/src/enc/token_enc.c.o
[ 75%] Building C object CMakeFiles/webpdsp.dir/src/dsp/enc_neon.c.o
[ 75%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/rescaler_neon.c.o
[ 75%] Building C object CMakeFiles/webpencode.dir/src/enc/tree_enc.c.o
[ 76%] Building C object CMakeFiles/webpencode.dir/src/enc/vp8l_enc.c.o
[ 77%] Building C object CMakeFiles/webpdsp.dir/src/dsp/lossless_enc_neon.c.o
[ 78%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/upsampling_neon.c.o
[ 79%] Building C object CMakeFiles/webpencode.dir/src/enc/webp_enc.c.o
[ 80%] Building C object CMakeFiles/webpdspdecode.dir/src/dsp/yuv_neon.c.o
[ 80%] Built target webpdsp
[ 80%] Built target webpencode
Scanning dependencies of target webp
[ 80%] Linking C static library libwebp.a
[ 80%] Built target webp
Scanning dependencies of target imageioutil
Scanning dependencies of target webpdemux
Scanning dependencies of target imageenc
[ 81%] Building C object CMakeFiles/imageioutil.dir/imageio/imageio_util.c.o
[ 83%] Building C object CMakeFiles/webpdemux.dir/src/demux/anim_decode.c.o
[ 83%] Building C object CMakeFiles/imageenc.dir/imageio/image_enc.c.o
[ 83%] Built target webpdspdecode
[ 84%] Building C object CMakeFiles/webpdemux.dir/src/demux/demux.c.o
[ 85%] Linking C static library libimageioutil.a
Scanning dependencies of target webpdecoder
[ 85%] Built target imageioutil
[ 85%] Linking C static library libwebpdecoder.a
[ 86%] Linking C static library libimageenc.a
[ 86%] Built target webpdecoder
[ 86%] Built target imageenc
[ 87%] Linking C static library libwebpdemux.a
[ 87%] Built target webpdemux
Scanning dependencies of target imagedec
[ 87%] Building C object CMakeFiles/imagedec.dir/imageio/jpegdec.c.o
[ 88%] Building C object CMakeFiles/imagedec.dir/imageio/image_dec.c.o
[ 90%] Building C object CMakeFiles/imagedec.dir/imageio/pngdec.c.o
[ 90%] Building C object CMakeFiles/imagedec.dir/imageio/metadata.c.o
[ 92%] Building C object CMakeFiles/imagedec.dir/imageio/pnmdec.c.o
[ 92%] Building C object CMakeFiles/imagedec.dir/imageio/tiffdec.c.o
[ 93%] Building C object CMakeFiles/imagedec.dir/imageio/webpdec.c.o
[ 93%] Building C object CMakeFiles/imagedec.dir/imageio/wicdec.c.o
[ 94%] Linking C static library libimagedec.a
[ 94%] Built target imagedec
Scanning dependencies of target anim_diff
Scanning dependencies of target anim_dump
[ 94%] Building C object CMakeFiles/anim_diff.dir/examples/anim_diff.c.o
[ 94%] Building C object CMakeFiles/anim_dump.dir/examples/anim_util.c.o
[ 96%] Building C object CMakeFiles/anim_dump.dir/examples/anim_dump.c.o
[ 96%] Building C object CMakeFiles/anim_diff.dir/examples/anim_util.c.o
[ 97%] Building C object CMakeFiles/anim_diff.dir/examples/gifdec.c.o
[ 98%] Building C object CMakeFiles/anim_dump.dir/examples/gifdec.c.o
[ 99%] Linking C executable anim_diff
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
ld: library not found for -llibwebpmux
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [anim_diff] Error 1
make[1]: *** [CMakeFiles/anim_diff.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking C executable anim_dump
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
ld: library not found for -llibwebpmux
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [anim_dump] Error 1
make[1]: *** [CMakeFiles/anim_dump.dir/all] Error 2
make: *** [all] Error 2

**Comment by tanersener** [comment]
Can you provide the following issue template fields?

**Environment**
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]

**Comment by gfremex** [comment]
Source branch: master

Xcode: 10.2.1

iPhone SDK: iPhoneOS12.2.sdk
 
Homebrew can not install 'patch' and the error returned is:

Error: No available formula with the name "patch"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
gpatch                                                              patchelf                                                            patchutils
To install one of them, run (for example):
  brew install gpatch
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

I don't know if it matters.

By the way, how can I change iphoneos-version-min to 9.0 instead of the autodetected one ?

**Comment by tanersener** [comment]
You logs show that you have `libgif` installed under `/usr/local`, which breaks your build.

```
-- Found GIF: /usr/local/lib/libgif.dylib (found version "5.1.4")
```

Apply the following fix to disable auto-detection.

```
git cherry-pick 413a4cb5a687afb8fe812e8274dba6e31a0e3d5f -n
```

`iphoneos-version-min` is defined at `export IOS_MIN_VERSION=12.1` line in `ios.sh` script. You can update it but I do not guarantee that changing it won't break anything.

ps: `patch` is not required by the `master` branch, so it won't be a problem.

**Comment by gfremex** [comment]
413a4cb5a687afb8fe812e8274dba6e31a0e3d5f works !

I changed IOS_MIN_VERSION to 9.0 and everything seems OK so far.
