### ISSUE TITLE
How to set ffmpeg-specific CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by gfremex** [tanersener/mobile-ffmpeg#134]
I have to add a new custom protocol to ffmpeg using some depended libraries.

So I need to set ffmpeg-specific CFLAGS and LDFLAGS.

In build/ios-ffmpeg.sh, these two variables are defined:

FFMPEG_CFLAGS=""
FFMPEG_LDFLAGS=""

Is it OK to set values to these two variables like this:

FFMPEG_CFLAGS="-I/path/to/some/include_dir"
FFMPEG_LDFLAGS="-L/path/to/some/lib_dir -llib_name"

or export ffmpeg-specific env variables to ios.sh ?

**Comment by tanersener** [comment]
You can use both. For me, using `pkg-config` was a better approach. `ffmpeg` uses `pkg-config` to enable external libraries. So, loading library paths using `pkg-config` helped me fixing external library errors.

```
FFMPEG_CFLAGS+=" $(pkg-config --cflags <lib name>)"
FFMPEG_LDFLAGS+=" $(pkg-config --libs --static <lib name>)"
```

**Comment by gfremex** [comment]
It's very helpful, thanks !
