### ISSUE TITLE
build sdl: failed on mac os 10.14.3 (18D109)

### ISSUE THREAD

**Issue by ykbjson** [tanersener/mobile-ffmpeg#137]
**Description**

on mac os 10.14.3 (18D109).

when i changed android app module build.gradle file for support miniSdk at 19,i get an error :
build sdl: failed .

**Expected behavior**
sdl: ok

**Current behavior**
sdl: failed

**Logs**
➜  mobile-ffmpeg git:(master) ✗ export ANDROID_NDK_ROOT=/Users/yanan/Downloads/android-sdk-macosx/ndk-bundle
➜  mobile-ffmpeg git:(master) ✗ ./android.sh --full
Building mobile-ffmpeg library for Android

Architectures: arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86-64
Libraries: android-zlib, android-media-codec, fontconfig, freetype, fribidi, gmp, gnutls, lame, libass, libiconv, libtheora, libvorbis, libvpx, libwebp, libxml2, opencore-amr, shine, speex, wavpack, kvazaar, libilbc, opus, snappy, soxr, libaom, chromaprint, twolame, sdl, tesseract

Building arm-v7a platform on API level 24

fribidi: ok
gmp: ok
libiconv: ok
libvpx: ok
libxml2: ok
opencore-amr: ok
shine: ok
speex: ok
wavpack: ok
kvazaar: ok
libilbc: ok
opus: ok
snappy: ok
soxr: ok
libaom: ok
chromaprint: ok
sdl: failed

----------------------------------------------------------------------------------
build.log:

/bin/sh build-scripts/mkinstalldirs build
/bin/sh build-scripts/updaterev.sh
  CC     build/SDL_assert.lo
  CC     build/SDL_dataqueue.lo
error: unable to open output file 'build/SDL_assert.o': 'No such file or directory'
error: 1unable to open output file 'build/SDL_dataqueue.o': 'No such file or directory'
 error generated.
1 error generated.
mkdir -p -- build
make: *** [build/SDL_dataqueue.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/SDL_assert.lo] Error 1

**Environment**
 - Platform:  Android
 - Architecture: full
 - Version (if applicable) 4.2.1
 - Source branch (if applicable) master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Android Studio version 3.4
 - Android NDK version (if applicable) r19

**Comment by tanersener** [comment]
First of all, I have to remind you that `master` source branch supports API Level 21 or later. Level 19 is not supported by `master` and updating `minSdkVersion` inside `android/app/build.gradle` does not change the API Level of the library. 

`development` branch includes some changes to support API Level 16 or later. You can try to use them but these changes are not fully tested and I do not guarantee that they will work.

Regarding your error, your error is not linked to the changes inside `android/app/build.gradle` file. Do you have any other local changes? Also, it is not possible to understand the real cause without seeing the full build.log file. Can your share it on [Ghostbin](https://ghostbin.com)?

**Comment by ykbjson** [comment]
Thanks so much !
This problem occurs when I use full compilation. When I use the custom compile command to remove the sdl module, the master branch can also compile aar that supports sdk 19. The compile command is as follows:

./android.sh --enable-android-media-codec --enable-android-zlib --enable-chromaprint --enable-fontconfig --enable-freetype  --enable-fribidi --enable-gmp --enable-gnutls --enable-kvazaar --enable-lame --enable-libaom --enable-libass --enable-libiconv --enable-libilbc --enable-libtheora --enable-libvorbis  --enable-libvpx --enable-libwebp --enable-libxml2 --enable-opencore-amr  --enable-opus --enable-shine --enable-snappy --enable-soxr --enable-speex --enable-tesseract  --enable-twolame --enable-wavpack --disable-arm-v7a-neon  --disable-arm64-v8a  --disable-x86          --disable-x86-64  --enable-gpl 

The contents of the build file are as follows:
apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 240421
        versionName "4.2.1"
        project.archivesBaseName = "mobile-ffmpeg"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["../libs"]
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    lintOptions {
          abortOnError false
    }
}

task javadoc(type: Javadoc) {
    title = 'MobileFFmpeg'
    destinationDir = file("${projectDir}/../../docs/android/javadoc")
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    source = android.sourceSets.main.java.srcDirs
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
}

**Comment by tanersener** [comment]
>  Is this a problem caused by the order of dependencies between modules?

I think it is one of the issues listed in [Known Issues](https://github.com/tanersener/mobile-ffmpeg/wiki/Known-Issues) wiki page. Some libraries do not support parallel execution well and fail with strange I/O errors once in a while. Rebuilding them fixes the error most of the time.

**Comment by ykbjson** [comment]
Thank you for your answer, I will close this question.
