### ISSUE TITLE
Is it possible get preview video from camera on display during recording video by ffmpeg?

### ISSUE THREAD

**Issue by OrlovYuriy13** [tanersener/mobile-ffmpeg#146]
**Description**
On Android.
Is it possible get preview video from camera on display during recording video by ffmpeg?
Or maybe can ffmpeg get stream for recording  video from already opened camera?

If yes, can you provide exemple code. Thanks.

**Comment by tanersener** [comment]
> Is it possible get preview video from camera on display during recording video by ffmpeg?
> Or maybe can ffmpeg get stream for recording video from already opened camera?

I don't know the answers of your questions. I haven't tried them before.

**Comment by pushsoftdev** [comment]
@tanersener , i see that you have closed this one.. did you implemented any solution for this?

Pls let me know.

I'm using the below command in my iOS project and i want to display the camera preview in my UIView.

`-f avfoundation -r 30 -video_size 640x480 -pixel_format bgr0 -i \"default:default\" -preset ultrafast -c:v h264_videotoolbox -c:a mp2 -tune zerolatency -b 900k -f tee -map 0:v -map 0:a \"%@|[f=mpegts]udp://127.0.0.1:43000/`

How to do that?

**Comment by tanersener** [comment]
@pushsoftdev I don't know. How about asking this question on [stackoverflow](https://stackoverflow.com)?
