### ISSUE TITLE
get Information as JSON or key value

### ISSUE THREAD

**Issue by mohtasham1988** [tanersener/mobile-ffmpeg#147]
Hi
How can I get information about a video as JSON
for example Duration or bitrate  
now I get as string
### input
-------------------------------
`  execFFmpegBinary(new String[]{"-i",inputPath});`
 

### output 
---------------------------------
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/test1/20180113_112128.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-01-13 07:52:30
    com.android.version: 6.0
   **Duration**: 00:01:00.59, start: 0.000000, bitrate: 6107 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 640x480, 5909 kb/s, SAR 1:1 DAR 4:3, 29.60 fps, 29.58 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2018-01-13 07:52:30
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2018-01-13 07:52:30
      handler_name    : SoundHandle
At least one output file must be specified

**Comment by tanersener** [comment]
There is a `getMediaInformation` method defined in the API. Did you try that?

**Comment by mohtasham1988** [comment]
it's work but I can't use this library. my min SDK android is 16 and this lib is 24.

**Comment by tanersener** [comment]
As explained in the `README`, this project has two variants: `Main` release which supports API 24 and `LTS` release which support API level 21.

API level 16 is supported on the `development` branch and the next planned release will support it too.

**Comment by RowlandOti** [comment]
@tanersener  this library seems to behave differently for  .mp4 and m4v files.  For m4v files, when parsing the information, I keep on getting values like `unknown`. However, the same `getMediaInformation()` works well for .mp4 files. Is this a know issue?

**Comment by tanersener** [comment]
It is not a known issue. Can you share one of your `.mkv` files so I can test it?

Alternatively, you can run `FFprobe.execute()` insteaf of `FFprobe. getMediaInformation()` yourself and parse the output yourself.
