### ISSUE TITLE
[Android] remove allowBackup property from AndroidManifest.xml

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#154]
Remove allowBackup property from AndroidManifest.xml file to prevent the following error.

```
ERROR: Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:15:9-36
	is also present at [com.arthenica:mobile-ffmpeg-full:4.2.1] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:14:5-29:19 to override.
```

**Comment by tanersener** [comment]
fixed in development

**Comment by johnml1135** [comment]
Is there a workaround for 4.2?  I can add the following to my app, but then I show the ffmpeg logo rather than my logo:
  Add xmlns:tools="http://schemas.android.com/tools" to manifest tag in AndroidManifest.xml and 
  tools:replace="android:icon" in application tag.

**Comment by tanersener** [comment]
AndroidManifest.xml file in `v4.2` includes both [icon](https://github.com/tanersener/mobile-ffmpeg/blob/v4.2/android/app/src/main/AndroidManifest.xml#L6) and [round icon](https://github.com/tanersener/mobile-ffmpeg/blob/v4.2/android/app/src/main/AndroidManifest.xml#L8) attributes. Overriding both of them fixes the issue most of the time. If it doesn't then there should be another error message in your logs.
