### ISSUE TITLE
How iOS chooses the fewest libraries to implement the functions I want

### ISSUE THREAD

**Issue by woniurensheng** [tanersener/mobile-ffmpeg#155]
I want to write ass file into MP4 file and get a GIF graph with subtitles. Which libraries are needed to implement this function? Thanks
Xcode 10.1
platform iOS 
Deployment target  8.0

**Comment by tanersener** [comment]
You need to enable `libass` but I don't know if it'll be enough. Why don't you try and see it yourself?
