### ISSUE TITLE
where to download so bin of development branch?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#157]
hi Taner,
where to download .so bin files of development branch?

**Comment by tanersener** [comment]
Hi,
Unfortunately, I don't publish binaries from the development branch. I regularly create local builds but I never thought they will be requested.

I have one of the test builds uploaded here if you're interested: [mobile-ffmpeg-min-gpl-4.2.1.LTS-API16](https://www.dropbox.com/s/nm98yq4bfhjic3s/mobile-ffmpeg-min-gpl-4.2.1.LTS-API16.aar).

**Comment by suncj518** [comment]
thanks.  because the last 4.2 lts release was published in Jan , I would like to get a new LTS release. May I know when you plan to release a new LTS full gpl version?

**Comment by tanersener** [comment]
It will be published in the first week of July. Current plan in to publish LTS releases every six months.

Meanwhile, I created a [development-snapshot](https://www.dropbox.com/sh/frzg32yjzyucmob/AADX81RhiVfk9o7Vo2J8jlH2a) directory with binaries from development branch on `Dropbox`. You can use these binaries if you don't want to wait. Just remember that these binaries are not % 100 tested and may include minor issues.

**Comment by suncj518** [comment]
hi Taner
Tried to download, but can not access dropbox in China. would you please put the bin files to other places? thanks

**Comment by tanersener** [comment]
I'm sorry, I don't have another online storage account.

**Comment by suncj518** [comment]
Hi Taner
ok, got, thanks all the same.

**Comment by suncj518** [comment]
Hi Taner,


May I know when 4.2.X LTS new bin .so files can be released to download?


Thanks.


| |
suncj
|
|
suncj518@163.com
|
签名由网易邮箱大师定制
On 7/2/2019 02:56，Taner Sener<notifications@github.com> wrote：

I'm sorry, I don't have another online storage account.

**Comment by tanersener** [comment]
Hi @suncj518,

`v4.2.2.LTS` Android binaries are tested and uploaded to `jcenter()`. `iOS` and `tvOS` binaries are being tested right now.
