### ISSUE TITLE
Get logcat of ffmpeg library android

### ISSUE THREAD

**Issue by susu1009** [tanersener/mobile-ffmpeg#162]
I'm building the ffmpeg 4.1.3 library on android under this link: https://blog.csdn.net/bobcat_kay/article/details/80889398. I have successfully built it but the problem is not getting the ffmpeg log to calculate progress. Can you just help me to get the log? Thank you !!

**Comment by tanersener** [comment]
Your question is not about this library. [Please ask ffmpeg questions to ffmpeg-user@ffmpeg.org](https://github.com/tanersener/mobile-ffmpeg/issues/130).
