### ISSUE TITLE
geq Not support 

### ISSUE THREAD

**Issue by makani20** [tanersener/mobile-ffmpeg#163]
stream$(( ))starting]geq=lum='p(X,Y)

Above 'geq' is not working in mobile ffmpeg but same thing working in Shell Script.

**Comment by tanersener** [comment]
`geq` is licensed under GPL. If you want to use `geq` filter you need to use one of the GPL packages of `mobile-ffmpeg`.

**Comment by makani20** [comment]
i want to use transition for 'collapse_circular' and geq is using in this command but i can not use it , have you any solution for this issue?

**Comment by tanersener** [comment]
@makani20 Which `mobile-ffmpeg` package do you use?

**Comment by makani20** [comment]
https://github.com/tanersener/mobile-ffmpeg

i m using this one.

**Comment by tanersener** [comment]
There is a misunderstanding here. There are eight different `mobile-ffmpeg` packages. [Using](https://github.com/tanersener/mobile-ffmpeg#2-using) section explains the difference between them. I'm asking which one them is used in your project.

Which platform do you use Android or IOS? Can you show me how you defined `mobile-ffmpeg` dependency in `build.gradle` or `Podfile`?

**Comment by makani20** [comment]
Podfile , we are using

**Comment by tanersener** [comment]
Can post here your `mobile-ffmpeg` dependency?

It should be something similar to this block.

```
pod 'mobile-ffmpeg-full', '4.2.1'
```

**Comment by makani20** [comment]
pod 'mobile-ffmpeg-full', '4.2.LTS'

**Comment by tanersener** [comment]
> pod 'mobile-ffmpeg-full', '4.2.LTS'

postfix used after `mobile-ffmpeg-` defines your package. Currently you are using the `full` package. As I said in my previous posts, you need to use one of the GPL packages. GPL packages are those which end with `-gpl` postfix: `min-gpl`, `https-gpl` and `full-gpl`. Please update your `mobile-ffmpeg` dependency in `Podfile` and try again?

**Comment by makani20** [comment]
Thank you very much, i got solution

**Comment by tanersener** [comment]
OK, great 👍
