### ISSUE TITLE
[Android] 64 bit support

### ISSUE THREAD

**Issue by thucnd55** [tanersener/mobile-ffmpeg#164]
Hello and many thanks for your ffmpeg library for Android.
After reading about the new 64 bit requirement for Android of native libraries
Can you confirm that your library is OK with Google's 64 bit new requirements?
[https://developer.android.com/distribute/best-practices/develop/64-bit](https://developer.android.com/distribute/best-practices/develop/64-bit)
Thanks.

**Comment by tanersener** [comment]
This project has no issues with Android's 64-bit requirements. Both `Main Release` and `LTS Release` packages include necessary 64-bit libraries. You can safely use them.

**Comment by skogge** [comment]
I'm getting email from Google telling me my app is not complying with the new requirements. 
All other .so files are in both 64/32 bit folder. But I think Google sees the NEON specific 32 bit .so(libavcodec-neon.so, libavfilter-neon.so, libswscale-neon.so, libmobileffmpeg-armv7a-neon.so) implementation as its own 32 bit only libraries. Is there any known workaround for this?

**Comment by tanersener** [comment]
@skogge you are using the latest LTS release, `4.2.2.LTS` right?

**Comment by tanersener** [comment]
@skogge Can you give me more detail about your issue. Do you have per-ABI APKs? which APK receives an email warning? 

By the way, you can use the following snippet to exclude an invalid/unwanted .so file for Android. 

```
android { 
    packagingOptions {
        exclude 'lib/armeabi-v7a/ABC.so'
    }
}
```

**Comment by skogge** [comment]
@tanersener The build I have in production is 4.2.LTS.
I am using abi-splits, but the email just flagged the entire app, not any specific APK. 
I'll attempt the exclude option. Otherwise I guess building locally with `--disable-arm-v7a-neon` would also work?

**Comment by tanersener** [comment]
You don't need that. You can use one of the LTS releases and the `exclude` snippet above to exclude `arm-v7a-neon` files. It will be same thing practically.

Meanwhile, I'm trying to test my test applications on Play Console but my productions keys are gone and it will take some time.

**Comment by tanersener** [comment]
@skogge [Android 64-bit Requirements Guide](https://developer.android.com/distribute/best-practices/develop/64-bit) clearly states that `... depending on your app, there may or may not be exactly the same set of libraries in each folder. The goal is to ensure that your app runs correctly in a 64-bit-only environment.`. So I don't think that your issue is about having `.so` files with `-neon` postfix for `armeabi-v7a` ABI.

I finally uploaded my application bundles to `Play Console` and made them available for testing. But I didn't receive any errors or e-mails. Do you know what triggers Google's 64-bit compatibility check?

**Comment by skogge** [comment]
@tanersener I'll release a new version with the fixes today and see. There was no trigger I just received the email. I just can't find any other reasons why they'd flag the app.

**Comment by tanersener** [comment]
@skogge ok, I'd be glad if you let us know the progress of your issue

**Comment by bogdantmm92** [comment]
Hey, when I generate the apk with app bundle the app crashes when trying to execute`FFmpeg.execute(args);`

Any idea why that happens?
Thanks!

**Comment by tanersener** [comment]
> Hey, when I generate the apk with app bundle the app crashes when trying to execute`FFmpeg.execute(args);`
> 
> Any idea why that happens?
> Thanks!

@bogdantmm92 you issue doesn't look like a 64-bit issue. Why don't you create a new issue and add necessary issue template fields?

**Comment by skogge** [comment]
Google Play is now reporting that the current release is compliant with the 64 bit requirements. My current release does not include the neon instructions. I'll try to upload with them later.

**Comment by tanersener** [comment]
@skogge Great 👍
