### ISSUE TITLE
[Android] No such filter: 'boxblur'

### ISSUE THREAD

**Issue by khacchungory** [tanersener/mobile-ffmpeg#170]
Hi,
I tried blur photo with this code

`ffmpeg -i poster3.jpg -filter_complex "[0:v]scale=1080:720,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)/20:chroma_power=1[bg];[0:v]scale=1080:-2:force_original_aspect_ratio=decrease[fg];[bg][fg]overlay=(W-w)/2:(H-h)/2[outv]" -map [outv] -map 0:a? poster2.jpg`

i was successful on window, but i am using this code for android then code not working with error is no such filter boxblur.

Can you give me solution to fix bug? thank you.

**Screenshots**
![image_resize_blurred_background](https://user-images.githubusercontent.com/15797477/60637467-c4e7c880-9e44-11e9-9f20-22551bdf3e23.jpg)
![Capture](https://user-images.githubusercontent.com/15797477/60637715-ac2be280-9e45-11e9-9368-8663ac61857a.PNG)

**Comment by tanersener** [comment]
Which `mobile-ffmpeg` package do you use? `boxblur` filter is licensed with `GPL` and only `gpl` packages include it. Can you try using one of those packages?

**Comment by khacchungory** [comment]
Hi,
thank for answer.
I'm tried package full-gpl and old bug was fix. Now, i'm trying code blur photo like  [link](https://stackoverflow.com/questions/43577377/extend-scale-a-portrait-video-so-the-aspect-ratio-stays-and-the-black-borders) and this not working, my photo is black around.
![Capture](https://user-images.githubusercontent.com/15797477/60648016-3afe2680-9e69-11e9-97be-ba3917aaff32.PNG)

Thank for reading

**Comment by tanersener** [comment]
Did you test your command on desktop?

**Comment by khacchungory** [comment]
Yes, i test on desktop successfull but test in android error

**Comment by tanersener** [comment]
Can you share your command and input image that fails?

**Comment by khacchungory** [comment]
i will try, thanks you very much :D

**Comment by khacchungory** [comment]
Yeahh, i was fix success :D
