### ISSUE TITLE
Can you please tell me what are the files you are using for implementing "Execute"function in the mobileffmpeg framework

### ISSUE THREAD

**Issue by vinaysunny005** [tanersener/mobile-ffmpeg#171]
I have downloaded mobileffmpeg with pods and want to integrate iOS  videoKit with your mobileffmpeg , as there are many same files between VideoKit and mobileFFmpeg , so that I can relate and use only selected files in my project 
My Main task is to execute commands with mobileffmpeg .

**Comment by tanersener** [comment]
`ios/src` folder includes `iOS` library sources.
