### ISSUE TITLE
4.1.4 release 

### ISSUE THREAD

**Issue by azureplus** [tanersener/mobile-ffmpeg#180]
4.1.4 release 

need 4.1.4

**Comment by tanersener** [comment]
There will not be a new `mobile-ffmpeg` release from the `ffmpeg v4.1` branch. `mobile-ffmpeg` publishes releases from the `ffmpeg development` branch which is newer than the `ffmpeg v4.1.x` releases.

**Comment by azureplus** [comment]
Thank you

**Comment by azureplus** [comment]
> There will not be a new `mobile-ffmpeg` release from the `ffmpeg v4.1` branch. `mobile-ffmpeg` publishes releases from the `ffmpeg development` branch which is newer than the `ffmpeg v4.1.x` releases.


> There will not be a new `mobile-ffmpeg` release from the `ffmpeg v4.1` branch. `mobile-ffmpeg` publishes releases from the `ffmpeg development` branch which is newer than the `ffmpeg v4.1.x` releases.

Thanks you

**Comment by azureplus** [comment]
@tanersener  Thanks, Is the release version more stable?

**Comment by azureplus** [comment]
```
ffmpeg v4.1:
Michael Niedermayer Michael Niedermayer Changelog: fix typo  … Latest commit 9d06c1f  3 days ago
```

```
ffmpeg v4.2:
and  Michael Niedermayer
Michael Niedermayer Bump minor version for master after 4.1 branchpoint  …
Latest commit 517573a  on 2 Nov 2018
```

**Comment by azureplus** [comment]
Thank you, I use mobile-ffmpeg 3.0, mobile-ffmpeg-full-gpl-universal 3.0

**Comment by tanersener** [comment]
`ffmpeg` didn't publish a release from their `v4.2` branch.

Did you read [FFmpeg Releases Info](https://ffmpeg.org/download.html#releases) and [MobileFFmpeg Versions Info](https://github.com/tanersener/mobile-ffmpeg#3-versions)?

**Comment by azureplus** [comment]
OK,Thanks
