### ISSUE TITLE
How to contact Taner directly?

### ISSUE THREAD

**Issue by MaximusBaton** [tanersener/mobile-ffmpeg#181]
Hi, Taner! Hope you doing well)

I'm developing an application and would like to offer a short time taking job for you.
It's about rtsp streaming.

Looking forward your reply.

**Comment by tanersener** [comment]
Hi, thanks. 

You can use [gitter](https://gitter.im/mobile-ffmpeg) to contact me but I'm not sure if I can help, I don't have much experience in rtsp streaming.
