### ISSUE TITLE
Multi threaded parallel executions of ffmpeg command

### ISSUE THREAD

**Issue by leephela** [tanersener/mobile-ffmpeg#182]
Hello,
When you execute the command via the static method ffmpeg.execute(), you get the return code of only the last operation.

What if your application is mutli threaded , and sometimes you want to have two executions running in parallel, how do you differentiate the two return codes, like which one of the two generates which return code?

**Comment by tanersener** [comment]
Unfortunately, parallel executions are not supported right now. If you start a second execution your application may crash.

Please note that `FFmpeg.execute()` returns an integer which is the actual return code of that execution. So if I add parallel executions support in the future then you'll be able to use the return code of `execute` to differentiate.

**Comment by leephela** [comment]
Is this feature ( parallel operation) not coming in anytime soon? It will be the most complete library if it supports this feature.

**Comment by tanersener** [comment]
It's on the roadmap but I don't have a release date yet. I'm still working on it.

**Comment by tanersener** [comment]
Experimental support is added in `development` branch

**Comment by tanersener** [comment]
Fixed in `v4.3.1` release.
