### ISSUE TITLE
libvidstab: failed 

### ISSUE THREAD

**Issue by azureplus** [tanersener/mobile-ffmpeg#183]
mobile-ffmpeg-4.2.2.LTS dev$ ./ios.sh --disable-i386    --disable-arm64e  --disable-armv7s --enable-libvidstab  --enable-gpl 
Building mobile-ffmpeg static library for iOS
Architectures: armv7, arm64, x86-64
Libraries: libvidstab
Building armv7 platform
libvidstab: failed

I need all separate components of all Architectures(ios-arm64-apple-darwin,ios-armv7-apple-darwin,ios-x86_64-apple-darwin)

can you share it?

**Comment by azureplus** [comment]
how to enable detail compile log

**Comment by tanersener** [comment]
Please read the [Wiki](https://github.com/tanersener/mobile-ffmpeg/wiki), answer of your log question can be found inside [Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) page.

**Comment by azureplus** [comment]
@tanersener  I have solved the problem，

I had use vlc and your framework, so  I need some components, thanks your and this project

**Comment by abokhalel2** [comment]
Hi @azureplus,
I'm having the same issue. What kind of components did you use to solve the issue?
