### ISSUE TITLE
[Android] How we can write the file into SD Card (Removable Storage)

### ISSUE THREAD

**Issue by kingvhit** [tanersener/mobile-ffmpeg#185]
**Description**
Thanks to your contributions about FFMPEG Mobile tool.
We're getting a new issue with the way write a file into sd card (removable storage), as I know, from Android 5.0 and above, we must use SAF to get the `Uri` of sd card, and then take it a permission, because all the folder in Sd-card is read-only except Android/Data/package name/files.

I found the way can do it by default code, but in the FFmpeg, we must put the absolute path file as a String. However, the new way is not to use an absolute path to write a file into sd card, they use `DocumentFile` with `write` permission accepted.

You can also see the way write the file into SD-card at here
https://stackoverflow.com/questions/43066117/android-m-write-to-sd-card-permission-denied
**Expected behavior**
Find a way to export the result file into SD-card.

**Environment**
 - Platform: Android
 - Version : Android 5.0 and above

Could you please help me with this one.

**Comment by tanersener** [comment]
How about writing `ffmpeg` output to application's cache directory first and using SAF to copy the output from cache to sd card?

**Comment by kingvhit** [comment]
Yes, this is an idea that I already thinking about, just confirm your library is supported or not, because for this idea I will maintain many things todo of code in exist source code.

**Comment by tanersener** [comment]
Unfortunately, `ffmpeg` included in this library is built on top of NDK and NDK does not have a SAF API.
