### ISSUE TITLE
adding image as background of video 

### ISSUE THREAD

**Issue by siyaldaksh** [tanersener/mobile-ffmpeg#188]
Hi I m using your library for overlaying image in my application every thing working perfectly. Command is as follows String overlay = tempFolder + "/overlay.png";
		    String[] cmd  = new String[12];

		    cmd[0] = "-y";
			cmd[1] = "-i";
			cmd[2] = overlay;
			cmd[3] = "-i";
			cmd[4] = inputVideo;
			cmd[5] = "-filter_complex";
			cmd[6] = "overlay=main_w/2-overlay_w/2:main_h/2-overlay_h/2";
			cmd[7] = "-qscale 0";
			cmd[8] = "0";
			cmd[9] = "-c:a";
			cmd[10] = "copy";
			cmd[11] = output.mp4;
as it is working in every device except video captured from back camera of Nokia device android version PIE.  Out put is getting generated and its playing in Mx player but not in default video player and SimpleExoplayer.  It is saying "com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.HEVC, Format(1, null, video/hevc, -1, null, [1280, 1280, -1.0], [-1, -1])". Please let me know the problem.

**Comment by tanersener** [comment]
It looks like there is an incompatibility between your output video and the player.

You are not defining an output video codec in your command. On those cases `ffmpeg` selects the video codec according to the input video type and system capabilities. Why don't you compare the video codecs of your output videos and see which video codecs & profiles are supported by the player?

**Comment by siyaldaksh** [comment]
Hi... I found why this is happening... Actually bigger size video like
1920x1920 not supported by video view...
