### ISSUE TITLE
ANR issues for large files

### ISSUE THREAD

**Issue by leephela** [tanersener/mobile-ffmpeg#189]
Hello,
For files of large sizes say like 700mb+,  it  is always repoducing an ANR error when muxing video and audio files together.

A typical ffmpeg command:
-logstat error -i video.webp -i audio.m4a -c copy output.mkv

This freezing occurs not anywhere in the middle of the conversion process but only at the end of the conversion when it has been successfully finished.

Appending -logstat error/panic to the ffmpeg command seems to make the freezing a bit bearable.

For files of relative small and medium sizes, the app work as expected and normal , and no freezing is noticeable.

I suspect it has got to do with some IO stuff at the end of the conversion process.

**Comment by tanersener** [comment]
ANR error or similar type of errors are received when you invoke `execute` on a UI thread, which is no surprise considering ffmpeg's high cpu and ram usage. I always recommend using an `AsyncExecuteTask` or `AsyncTask` for Android. What type of thread did you run these tests on?

I agree with you, there might be an I/O flush step at the end of execution. `ffmpeg` includes options like `blocksize` and `max_interleave_delta` to control I/O writes. They can also help improve the situation.

**Comment by leephela** [comment]
The execution is done on a seperate background thread. The procession in the middle part goes well as expected, only just at the completion of the conversion. So any ideas as to what must be done to avert this ANR at the conversion completion? Thanks..

**Comment by tanersener** [comment]
There are many flags/options listed on [FFmpeg documentation](https://ffmpeg.org/ffmpeg-all.html) which can help you on this case. 

I recommend trying `flush_packets` and `max_muxing_queue_size`.

**Comment by leephela** [comment]
Hello,
I would like to reopen this issue . It so turns out that the ANR occurs only when doing a`-c copy`. For any other conversions, it happens to turn out just fine, but for big files, `-c copy` produces servere ANR. I'm beginning to think if it has got to do anything with how the `ffmpeg` handles the files write to the system, etc

**Comment by tanersener** [comment]
Well, I don't have anything to add about this case.
