### ISSUE TITLE
Support picture-based subtitles? Crash with command "-i 1.mp4 -vf subtitles=1.srt 2.mp4"

### ISSUE THREAD

**Issue by FengDeng** [tanersener/mobile-ffmpeg#19]

**Comment by tanersener** [comment]
I guess picture-based subtitles were not tested. Can you provide a sample .srt file so I can test it?

**Comment by FengDeng** [comment]
Here is url,[https://github.com/FengDeng/SOSubtitle/tree/master/SOSubtitle](srt file and mp4)

**Comment by tanersener** [comment]
Hi,
I made some tests with your project. Burning picture-based subtitles worked on IOS simulator but crashed on a real device with `arm64` architecture. Is this the issue you encountered?

**Comment by FengDeng** [comment]
Yes,It crashed on real devices.

**Comment by shoyu666** [comment]
add subtitle  by "-vf " 
mp4 file size 22M
android memory Increased to 100M+

**Comment by tanersener** [comment]
>By the way,memory leaks...

I see them too, unfortunately they come from `ffmpeg` libraries, no quick fix atm. Tried many things about them but modifying `ffmpeg` source is needed. Good thing is most of them are small in size, around a few KB. But some leaks in external libraries `x265` and `libvidstab` are huge and wastes MBs. Will monitor them in new releases.

Your issue with subtitles is a [bug](https://github.com/tanersener/mobile-ffmpeg/issues/22). I'm working on it but can not give a time frame about the fix.

**Comment by tanersener** [comment]
Hi, a patch is released about this issue; `v2.1.1` is published in cocoapods.

**Comment by tanersener** [comment]
OK mate; it's your decision to use `FFmpeg` or not. I just want to make sure everything is working properly.

There is an error on your project (https://github.com/FengDeng/SOSubtitle/tree/master/SOSubtitle). By applying the following two steps it is possible to successfully burn picture-based subtitles.

**1.** Add `方正大黑_GBK.ttf` font to your project. 

<img width="268" alt="1" src="https://user-images.githubusercontent.com/10158439/45307506-d95e7b80-b527-11e8-9065-ca83a22be6d4.png">

**2.** Update these two statements inside `AppDelegate.swift`

```
if let resourcePath = Bundle.main.resourcePath {
    MobileFFmpegConfig.setFontDirectory("\(resourcePath)", with: nil)
}

let r = MobileFFmpeg.execute("-i \(input) -vf subtitles=\(ass):force_style='FontName=方正大黑_GBK' \(output)")
```

Generated video will include subtitles.

<img width="214" alt="2" src="https://user-images.githubusercontent.com/10158439/45307795-97820500-b528-11e8-83d9-1b462b5bb7d4.png">

**Comment by FengDeng** [comment]
@tanersener 
cool.Thanks very much.Sorry to trouble you.

**Comment by tanersener** [comment]
no trouble mate, anytime
