### ISSUE TITLE
Support single quotes and double quotes in command strings

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#190]
It looks like we need this. Users expect to be able to run the same command on both the desktop and mobile device.

**Comment by tanersener** [comment]
fixed in development

**Comment by hedongfu** [comment]
Now the tag 4.2.2 doesn't include this fix. How to bypass if the file name has blank?

**Comment by tanersener** [comment]
Please see [Tips](https://github.com/tanersener/mobile-ffmpeg/wiki/Tips).
