### ISSUE TITLE
video compression

### ISSUE THREAD

**Issue by siyaldaksh** [tanersener/mobile-ffmpeg#191]
Hii I am trying video compression and using your library. The thing I observed that if we just pass input and getting output.mp4 video compressed to a default size. But I took one video in that video size is increased from 7 mb to 8 mb. When I checked the total bitrate is 961 kbps and by default with ffmpeg total bitrate is around 1100 kbps so because of that size is increased. I tried in command changing bitrate but no effect.
this command I tried.

String[] cmd  = new String[6];
		cmd[0] = "-y";
		cmd[1] = "-i";
		cmd[2] = ipVideo;
		cmd[3] = "-b:v";
		cmd[4] = "1000k";
		cmd[5] = output.mp4;
		testExecute(cmd);

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132) and [ask ffmpeg questions to ffmpeg-user@ffmpeg.org](https://github.com/tanersener/mobile-ffmpeg/issues/130).
