### ISSUE TITLE
Motion Vector Extraction

### ISSUE THREAD

**Issue by CosmicVarion** [tanersener/mobile-ffmpeg#193]
**Description**
Is there an easy way to extract motion vectors? Normally, one could use [extract_mvs.c](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/extract_mvs.c).

After compilation:
```
./extract_mvs <path to video> 
```
optionally piping to a text file, if desired.

Motion vectors may also be visualized with ffplay - [see here](https://trac.ffmpeg.org/wiki/Debug/MacroblocksAndMotionVectors).

**Expected behavior**
Ability to generate -
* a text file for parsing, for example, including motion vector information
* a string for parsing or data structure in Swift containing motion vector information information
* or, expanding on the afore-bulleted for absolute best case scenario, a multi-dimensional array arranged by frame index, then motion vector coordinates, with attached motion vector information

**Current behavior**
Unknown or N/A

**Screenshots**
N/A

**Logs**
N/A

**Environment**
 - Platform: iOS
 - Architecture: 
 - Version N/A
 - Source branch N/A
 - Xcode version N/A but using XCode
 - Cocoapods version N/A but using Cocoapods
 - Android Studio version N/A
 - Android NDK version N/A

**Other**
Thanks in advance!!

**Comment by tanersener** [comment]
`extract_mvs.c` is part of `ffmpeg` examples. Unfortunately, examples are not build by `mobile-ffmpeg` scripts and not included in `mobile-ffmpeg` binaries.

You need to add `extract_mvs.c` into your application and call its main method from your application.

**Comment by CosmicVarion** [comment]
Awesome! Thanks!! One quick question then - how would I call its main method?

**Comment by tanersener** [comment]
Please take a look at [MobileFFmpeg. executeWithArguments](https://github.com/tanersener/mobile-ffmpeg/blob/master/ios/src/MobileFFmpeg.m#L82) function, in which I'm invoking a method called `execute` which has the same signature. You can create a similar method, put all `extract_mvs` arguments into an `NSArray` and call that method.

**Comment by CosmicVarion** [comment]
Ok, seems fairly straightforward :) thanks again!

**Comment by gadia-aayush** [comment]
I am getting this error-
`bash: ./extract_mvs: Permission denied`

I have already successfully installed & compiled FFMPEG using this [link](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu). Please guide.
