### ISSUE TITLE
No such filter: 'drawtext'

### ISSUE THREAD

**Issue by krisai** [tanersener/mobile-ffmpeg#194]
**Description**
In my android, when i add your library and run my Android application i get below error
`
-filter_complex drawtext=x=0:y=300:text="HelloWorld"[text];movie=/storage/emulated/0/asd/asd.jpg[wm];[wm]scale=60:60[sc];[text][sc]overlay=30:30 `
**Screenshots**

![image](https://user-images.githubusercontent.com/4646060/61571137-f35fd780-aac3-11e9-9ddb-b1a8264e7a04.png)

**Logs**
I/mobile-ffmpeg:   Duration: 
I/mobile-ffmpeg: 00:00:29.23
I/mobile-ffmpeg: , start: 
I/mobile-ffmpeg: 0.000000
I/mobile-ffmpeg: , bitrate: 
I/mobile-ffmpeg: 3289 kb/s
I/mobile-ffmpeg:     Stream #0:0
I/mobile-ffmpeg: (und)
I/mobile-ffmpeg: : Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 323
I/mobile-ffmpeg: , 
I/mobile-ffmpeg: 25 fps, 
I/mobile-ffmpeg: 25 tbr, 
I/mobile-ffmpeg: 12800 tbn, 
I/mobile-ffmpeg: 50 tbc
I/mobile-ffmpeg:  (default)
I/mobile-ffmpeg:     Metadata:
I/mobile-ffmpeg:       handler_name    : 
I/mobile-ffmpeg: VideoHandler
I/mobile-ffmpeg:     Stream #0:1
I/mobile-ffmpeg: (und)
I/mobile-ffmpeg: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s
I/mobile-ffmpeg:  (default)
I/mobile-ffmpeg:     Metadata:
I/mobile-ffmpeg:       handler_name    : 
I/mobile-ffmpeg: SoundHandler
E/mobile-ffmpeg: [AVFilterGraph @ 0x74dcbff940] 
E/mobile-ffmpeg: No such filter: 'drawtext'
E/mobile-ffmpeg: Error initializing complex filters.
E/mobile-ffmpeg: Invalid argument

**Environment**
 - Platform: Android
 - version: 'com.arthenica:mobile-ffmpeg-min:4.2.2.LTS'

**Comment by tanersener** [comment]
`drawtext` depends on `libfreetype` and is only enabled in packages that include `libfreetype` external library.

Can you update your dependencies and depend on `full` package?

```
dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.2.2'
}
```
