### ISSUE TITLE
Processing time is too long...

### ISSUE THREAD

**Issue by siyaldaksh** [tanersener/mobile-ffmpeg#195]
**Description**
I am adding overlay image behind the video.

**Expected behaviour**
working as expected but taking too much time.

**Current behaviour**
one .mkv video of 44 MB of length 1 min 30 sec taking 6 min in low end devices and 3 min in high end device.

I am using this command 
String overlay = tempFolder + "overlay.png";
		    String[] cmd  = new String[10];
cmd[0] = "-y";
			cmd[1] = "-i";
			cmd[2] = overlay;
			cmd[3] = "-i";
			cmd[4] = input;
			cmd[5] = "-filter_complex";
			cmd[6] = "overlay=main_w/2-overlay_w/2:main_h/2-overlay_h/2";
			cmd[7] = "-c:a";
			cmd[8] = "copy";
			cmd[9] = output.mp4;

and I am using this dependecy
com.arthenica:mobile-ffmpeg-min:4.2.2.LTS

**Comment by hieuseesaa** [comment]
@tanersener hello admin. Please tell me how to increase command processing speed. 
I use 

`implementation 'com.arthenica:mobile-ffmpeg-full:4.2.2'`

This is command.

`-i input.mp4 -vf drawtext=text='Hello':enable='between(t,'60','70')':x=w-tw-105:y=h-th-105:fontsize=30:fontcolor=#FFFFFF -c:a copy output.mp4`

I have a video long 3 min. the above command takes about 5 minutes to succeed. Too long...

**Comment by tanersener** [comment]
@hieuseesaa please take a look at #197, especially [this post](https://github.com/tanersener/mobile-ffmpeg/issues/197#issuecomment-515010678).

Also, do not forget to include issue template fields when you create a new issue. See [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132).
