### ISSUE TITLE
Converting Input.MP3 to m4a 

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#196]
Hi i want to convert MP3 to m4a. I am using cmd  = {"-i",audioPath.MP3,outPath.mp4};. This is working for every format.
For "mp3" it's working , but not only for "MP3".  
Its giving the below error only for "MP3" 

"Incorrect BOM value
Error reading comment frame, skipped
Incorrect BOM value
Error reading lyrics, skipped
Input #0, mp3, from '/data/user/0/com.audioconvertertoanyformat.audioconvertertomp3/files/01 - Bang Bang - Tu Meri [DJMaza.Info].MP3':
  Metadata:
    album_artist    : Vishal-Shekhar | DJMaza.Info
    track           : 1/5
    copyright       : www.DJMaza.Info
    TBPM            : 0 BPM
    title           : Tu Meri - DJMaza.Info
    album           : Bang Bang (2014)
    iTunMOVI        : <?xml version="1.0" encoding="UTF-8"?>
                    : <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                    : <plist version="1.0">
                    : <dict>
                    : 	<key>asset-info</key>
                    : 	<dict>
                    : 		<key>file-size</key>
                    : 		<integer>9145612</integer>
                    : 		<key>flavor</key>
                    : 		<string>2:256</string>
                    : 	</dict>
                    : </dict>
                    : </plist>
                    : 
    genre           : Bollywood Music
    composer        : Music: Vishal-Shekhar | DJMaza.Info
    artist          : Vishal Dadlani
    TOPE            : www.DJMaza.Info
    performer       : www.DJMaza.Info
    TEXT            : www.DJMaza.Info
    TOLY            : www.DJMaza.Info
    TRSN            : www.DJMaza.Info
    publisher       : www.DJMaza.Info
    TPE4            : www.DJMaza.Info
    iTunSMPB        :  00000000 00000840 00000025 0000000000ACFF9B 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    iTunNORM        :  0000154F 000013E9 000080D8 00006FCC 0003C96F 0003C96F 00008000 00008000 00006B64 00006596
    Purchase Date   : 2014-08-23 19:36:38
    date            : 2014
  Duration: 00:04:17.15, start: 0.025056, bitrate: 174 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 166 kb/s
    Metadata:
      encoder         : LAME3.98r
    Stream #0:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 600x600 [SAR 96:96 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:1 -> #0:0 (mjpeg (native) -> h264 (h264_v4l2m2m))
  Stream #0:0 -> #0:1 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
[ipod @ 0x7c61bab400] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
[h264_v4l2m2m @ 0x7c61bd9500] can't configure encoder
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!"

**Comment by tanersener** [comment]
Your logs show multiple errors and it is hard to tell if they're connected to each other. I think comparing the outputs of successful and unsuccessful conversions can help you identifying the issue.

Additionally, can you explain what you are trying to do here? `mp3` is an audio file and `mp4` is an audio/video file. Are you trying to create a video file without any video streams?

**Comment by gururajKp** [comment]
> Your logs show multiple errors and it is hard to tell if they're connected to each other. I think comparing the outputs of successful and unsuccessful conversions can help you identifying the issue.
> 
> Additionally, can you explain what you are trying to do here? `mp3` is an audio file and `mp4` is an audio/video file. Are you trying to create a video file without any video streams?

Hi thanks for your reply :) . I changed command to "-c:v", "copy" and it is now working :).
Complete command.
String[] cmd = new String[]{"-i", audioPath, "-c:v", "copy", outPath};
