### ISSUE TITLE
[Android] Using existing ffmpeg shared library

### ISSUE THREAD

**Issue by arosendorff** [tanersener/mobile-ffmpeg#198]
**Description**
I have an app that has the [DJI Mobile SDK](https://developer.dji.com/mobile-sdk/documentation/introduction/index.html) added to it. Part of the SDK is a video streaming component, which uses ffmpeg to decode the frames from the drone.

When I unzip my .apk file, in the libs folder there is `libffmpeg.so`, which I assume is from the DJI SDK. Is there a way that I can use that existing ffmpeg instance with this library, without having to build any additional ffmpeg files?

Apologies for the very basic question, Android isn't my first language haha!

**Comment by tanersener** [comment]
On Android, published `mobile-ffmpeg` .aar archives include shared libraries of both `ffmpeg` and `mobile-ffmpeg`. In this scheme, `mobile-ffmpeg` libraries depend on `ffmpeg` libraries. 

If `libffmpeg.so` coming from `DJI Modile SDK` is compatible with `ffmpeg` coming from `mobile-ffmpeg`, then you can use `mobile-ffmpeg` with `libffmpeg.so` from `DJI Modile SDK`.

`Compatible` doesn't mean exactly the same version but means a lot of things and there is not an easy way of telling this without actually trying. So I recommend trying it.

**Comment by arosendorff** [comment]
Thank you, I will investigate and see if I can get the libraries talking to each-other!
