### ISSUE TITLE
 No such file or directory? how to resolve?

### ISSUE THREAD

**Issue by azureplus** [tanersener/mobile-ffmpeg#199]
-i /Documents/My Fileqqqq.mp4 -ab 128k Caches/01DGAHH8H85Y13NYVFBX0N6BPH.mp3

logCallback(_:_:) >
/Documents/My: No such file or directory

**Comment by azureplus** [comment]
"/Documents/My Fileqqqq.mp4" ?

**Comment by tanersener** [comment]
Please take a look at [Tips](https://github.com/tanersener/mobile-ffmpeg/wiki/Tips).

**Comment by azureplus** [comment]
@tanersener  thanks
