### ISSUE TITLE
ios.sh error

### ISSUE THREAD

**Issue by woniurensheng** [tanersener/mobile-ffmpeg#200]
Building mobile-ffmpeg static library for iOS

Architectures: arm64, arm64e
Libraries: ios-zlib, ios-audiotoolbox, ios-coreimage, ios-videotoolbox, ios-avfoundation, fontconfig, freetype, fribidi, libass, libiconv

Building arm64 platform

fribidi: already built
libiconv: already built
libpng: already built
libuuid: already built
expat: already built
freetype: already built
fontconfig: failed

**Comment by tanersener** [comment]
Detailed documentation is available at [wiki](https://github.com/tanersener/mobile-ffmpeg/wiki). Please take a look at `Logs`, `Reconf Option` and `Rebuild Option` pages.
