### ISSUE TITLE
App store rejects app because of usage of Camera though app is not using Camera

### ISSUE THREAD

**Issue by anuranBarman** [tanersener/mobile-ffmpeg#201]
**Description**
I have submitted my app using this library to App Store. I am **not using Camera** in my app. I am **just allowing user to pick video from their photo library**. As ffmpeg inside is using the camera app store says NSCameraUsageDescription is required. If I put this and submit again, they say app is not taking user consent for camera usage which I suppose they are saying because app is asking for camera permission but there is no camera functionality in the app. My app got rejected **4 Times** for this. Please help. How can I disable camera usage from this library?

**Environment**
 - Platform: IOS
 - Architecture: arm64
 - Version (if applicable) latest from Cocoapods
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version 4.2.2

**Comment by tanersener** [comment]
Which package do you use?

**Comment by anuranBarman** [comment]
I am using ffmpeg gpl package

**Comment by tanersener** [comment]
Which `GPL`? There are 3 different `GPL` packages as explained in the [Using](https://github.com/tanersener/mobile-ffmpeg#2-using) section?

**Comment by anuranBarman** [comment]
i am using `pod 'mobile-ffmpeg-full-gpl'`

**Comment by tanersener** [comment]
Thanks, let me  make some tests and understand your issue.

**Comment by anuranBarman** [comment]
Okay. meanwhile I will be adding camera support as backup.

**Comment by tanersener** [comment]
I tried different settings to disable `Camera Usage` by editing `xcconfig` files but none of them worked. I think it'd be right to say that it is not possible to disable `Camera Usage` on Cocoapods releases. You need to clone `mobile-ffmpeg` and build it yourself without `avfoundation`.

Also, I'm using test-applications under the `ios/test-app` folder to test App Store submissions and they have `NSCameraUsageDescription` in `Info.plist` files but actually they don't do anything about the camera. But they do not receive any warnings like your application. 

> they say app is not taking user consent for camera usage which I suppose they are saying because app is asking for camera permission but there is no camera functionality in the app...

Can you compare one of them with your application?

**Comment by anuranBarman** [comment]
I have added camera functionality of in my app. I will submit for review
again tonight. Lets see where it goes.

**Comment by anuranBarman** [comment]
closing the issue as app got accepted after adding camera functionality. Ffmpeg developers should not make the camera permission mandatory. Not every app will implement that. Anyway thanks for the port of ios. Cheers man.

**Comment by tanersener** [comment]
> Ffmpeg developers should not make the camera permission mandatory. 

There is a misunderstanding here. Neither `FFmpeg` nor `FFmpeg developers` know what a `camera permission` is. They can't force you to do something they don't know. Please remember that Apple is the owner of that rule. As I explained in my previous post, you can compare one of the test applications with your application to understand why Apple is complaining about `not taking user consent for camera usage`. According to your posts you didn't do that.

Additionally, I need to remind that binaries published by `mobile-ffmpeg` are built with most used options and camera access is one of those options. If you don't need it please `clone mobile-ffmpeg and build it yourself without avfoundation` as I suggested before. According to your posts you didn't do that too.

Please try these two suggestions if you are not happy with your solution.
