### ISSUE TITLE
Memory is to large

### ISSUE THREAD

**Issue by azureplus** [tanersener/mobile-ffmpeg#203]
![WX20190801-002955](https://user-images.githubusercontent.com/9008164/62230093-abaa4b80-b3f3-11e9-989c-b8ea932a2375.png)

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132)

**Comment by azureplus** [comment]
MobileFFmpeg.execute(cmd, delimiter: factory.delimiter)

:-i  MG_6705.MOV -r 10 -vf scale=500:-1 -ss 235.147 -t 12.0  IMG_6705.gif

the memory can not free,how to resolve this problem
