### ISSUE TITLE
Memory is not freed and too large

### ISSUE THREAD

**Issue by azureplus** [tanersener/mobile-ffmpeg#204]
**Description**
run ffmpeg cmd -ss [start] -t [duration] -accurate_seek -i [in].mp4 -codec copy [out].mp4

 
file size: 600MB

**Current behavior**
Memory is too large 500+MB
 

**Screenshots** 

**Logs** 

**Environment**
 - Platform: IOS
 - Architecture: arm64
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) 4.2.2 lts full
 - Xcode version (if applicable) 10.3 

--iphone7+

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132) issue and do not forget to provide logs.

I can't test/validate/confirm your issue without seeing `ffmpeg` logs. `ffmpeg` logs include your input/output file information and options used during encoding.
