### ISSUE TITLE
How to execute multiple ffmpeg commands in AsyncExecuteTask

### ISSUE THREAD

**Issue by rahulpawar1989** [tanersener/mobile-ffmpeg#205]
**Description**
Presently i am able to execute only one FFMPEG command in your AsyncExecuteTask.

public class AsyncExecuteTask extends AsyncTask<String, Integer, Integer> {

    private final ExecuteCallback executeCallback;

    public AsyncExecuteTask(final ExecuteCallback executeCallback) {
        this.executeCallback = executeCallback;
    }

    @Override
    protected Integer doInBackground(final String... arguments) {
        return FFmpeg.execute(arguments);
    }

    @Override
    protected void onPostExecute(final Integer rc) {
        if (executeCallback != null) {
            executeCallback.apply(rc, FFmpeg.getLastCommandOutput());
        }
    }

But what should i do if i want to execute multiple FFMPEG commands in loop. Can you give me idea how should i use your Library to execute multiple commands.

**Environment**
 - Platform: Android
 - Version: com.arthenica:mobile-ffmpeg-min:4.2.2.LTS
 - Android Studio version 3.4
 - Android NDK version 20.0.5

**Comment by tanersener** [comment]
How about executing the next command when `ExecuteCallback` is invoked?

**Comment by huongvu1397** [comment]
```
FFmpegUtils.executeAsync({ result, executeOutput ->
                if (result != 0) {
                    if (outputLocation.exists()) {
                        outputLocation.delete()
                    }
                    callback!!.onFailure(IOException())
                }
            }, ffmpegCommand)
```
How can i check executecallback when command success for running next command
