### ISSUE TITLE
Don't specify an Android app theme as that upsets the manifest merger

### ISSUE THREAD

**Issue by koush** [tanersener/mobile-ffmpeg#206]
**Description**
```
	Attribute application@theme value=(@style/ScryptedTheme) from AndroidManifest.xml:37:9-45
	is also present at [com.arthenica:mobile-ffmpeg-https:4.2.LTS] AndroidManifest.xml:17:9-40 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:31:5-95:19 to override.
```

**Expected behavior**
The library works out of the box.

**Current behavior**
The above build error.

**Environment**
 - Platform: Android
 - Architecture: All
 - Version  4.2 and 4.2.2
 - Android Studio version (if applicable) 3.4.2

Fix:

Just remove this line:
https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/AndroidManifest.xml#L6

Ideally the FFmpeg Library manifest should be empty.

**Comment by koush** [comment]
Obviously, the suggested workaround (tools:replace="android:theme") is available, but should not be necessary.

**Comment by tanersener** [comment]
Fixed in the development branch, will be included in the next main release.

**Comment by vlad-roid** [comment]
Thanks, this huge piece of **** cost me several hours. I didn't actually encounter the build error described here. Instead, I was using the new MaterialComponents theme under a custom theme, which happened to be also named AppTheme. When it has the same name, Android may randomly switch to use the AppTheme defined by the FFmpeg library, which results in
`java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant).`
Temporary solution: Rename your custom app theme until this change is live.

**Comment by tanersener** [comment]
@vlad-roid Thanks for the detailed explanation.
