### ISSUE TITLE
native static int execute allways return 0(success)

### ISSUE THREAD

**Issue by shoyu666** [tanersener/mobile-ffmpeg#21]
mobile-ffmpeg: sd/demo.mp4: No such file or directory
mobile-ffmpeg: Conversion failed!

`/**
     * <p>Synchronously executes FFmpeg with arguments provided.
     *
     * @param arguments FFmpeg command options/arguments
     * @return zero on successful execution, non-zero on error
     */`

native static int execute return 0 expect  non-zero

**Comment by tanersener** [comment]
There is a [bug](https://github.com/tanersener/mobile-ffmpeg/issues/13) about return code on `v2.0` and older versions. Could you please try with `v2.1`?
