### ISSUE TITLE
FFmpeg library exposition

### ISSUE THREAD

**Issue by lo-fo** [tanersener/mobile-ffmpeg#218]
**Description**

the **README.md** states

> Exposes both FFmpeg library and MobileFFmpeg wrapper library capabilities

But i have yet to understand how to access theses.

**Environment**
 - Platform: IOS

**Comment by tanersener** [comment]
You can find `MobileFFmpeg` API documentation under the `docs/ios/html` folder and `FFmpeg` documentation in this [link](https://ffmpeg.org/doxygen/trunk/index.html).

**Comment by lo-fo** [comment]
i exposed ffmpeg's libav by adding
```
#import "libavcodec/avcodec.h"
#import "libavdevice/avdevice.h"
#import "libavfilter/avfilter.h"
#import "libavformat/avformat.h"
#import "libavutil/avutil.h"
#import "libswresample/swresample.h"
#import "libswscale/swscale.h"
```
to my bridging header
