### ISSUE TITLE
Gradle sync issues

### ISSUE THREAD

**Issue by vikas-markk** [tanersener/mobile-ffmpeg#221]
**Description**
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.2.2] /home/XYZ/.gradle/caches/transforms-2/files-2.1/483b37fe0cdc5aaf55cb280c0bc2b866/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)

**Expected behavior**
Gradle sync success 

**Current behavior**
Failed to build

**Logs**
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.2.2] /home/XYZ/.gradle/caches/transforms-2/files-2.1/483b37fe0cdc5aaf55cb280c0bc2b866/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)

**Environment**
 - Platform:- Android
 - Version :-com.arthenica:mobile-ffmpeg-full:4.2.2
 - Android Studio version :- 3.5

**Comment by tanersener** [comment]
Please search for older issues before creating a new one. See #168.
