### ISSUE TITLE
is there fdk_aac support or any other alternative already in repo?

### ISSUE THREAD

**Issue by flyinghawker** [tanersener/mobile-ffmpeg#223]
Look through the doc but unable to find **fdk_aac**, any plan to support that or alternative idea? Thanks for the great job by the way!

**Comment by tanersener** [comment]
`fdk_aac` is listed under the [Incompatible libraries](https://github.com/FFmpeg/FFmpeg/blob/master/LICENSE.md#incompatible-libraries) section of FFmpeg license. So I don't know what license will `mobile-ffmpeg` have if I support it.

This is why it is not supported right now and I don't plan to support it in the future.

**Comment by flyinghawker** [comment]
Got it. Thanks for your quick response!
