### ISSUE TITLE
Unknown encoder 'h264_mediacodec'

### ISSUE THREAD

**Issue by dnhyde** [tanersener/mobile-ffmpeg#225]
**Description**
Cannot speedup Android encoding with mediacodec?
When I use` -hwaccel mediacodec -i <video_input> -c:v h264_mediacodec <video_output` i get the error `E/mobile-ffmpeg: Unknown encoder 'h264_mediacodec'`

Is this because there is no support for hwaccel encoders in Android according to the [wiki](https://trac.ffmpeg.org/wiki/HWAccelIntro).
Is there a way to speed up my encoding process? I already read through #197 

**Expected behavior**
Speed up decoding (which seems to work) and encoding time in Android

**Current behavior**
Error: `E/mobile-ffmpeg: Unknown encoder 'h264_mediacodec'`

**Screenshots**
n/a

**Logs**
-hwaccel mediacodec -i input.mp4  -c:v h264_mediacodec -an output.mp4
E/mobile-ffmpeg: Unknown encoder 'h264_mediacodec'

**Environment**
 - Platform: Android
 - Architecture: ARMv8 NEON
 - Version: mobile-ffmpeg-full-gpl-arm64-v8a-4.2.2-lts-20190703
 - Android Studio version: 3.4.2

**Other**
I have a very low speed even if I use libx264 as encoder and even if I set the flag -preset ultrafast.
Thanks for your work!

**Comment by tanersener** [comment]
> Is this because there is no support for hwaccel encoders in Android according to the wiki.

Yes, `MediaCodec` encoder is not implemented by `ffmpeg`, only decoder is available.

> Is there a way to speed up my encoding process? I already read through #197

There does not exist a magic option/flag to improve the speed. Using CPU optimizations makes the biggest difference for encoding/decoding.

You can ask this question in `ffmpeg` mailing list too. `FFmpeg` developers may have different ideas on improving the encoding speed.

**Comment by dnhyde** [comment]
Still the `libx264 -preset ultrafast` should work even on Android right?
Thank you very much for your quick answer

**Comment by tanersener** [comment]
Yes, it works on Android.

**Comment by galex** [comment]
Hello @tanersener , 

I see in the Android documentation at [Supported Media Formats](https://developer.android.com/guide/topics/media/media-formats) that h264 is available as an encoder for Android 6+. 

How can I use this with **mobile-ffmpeg**? I tried using version **4.3.1** and **4.4** with `-vcodec h264_mediacodec` but I still get `Unknown encoder h264_mediacodec` as a response from ffmpeg. 

Thank you in advance!

**Comment by tanersener** [comment]
@galex Unfortunately h264_mediacodec encoder is not implemented by `ffmpeg`. See https://trac.ffmpeg.org/wiki/HWAccelIntro. It is only available as `decoder`.
