### ISSUE TITLE
Unable to perform ffmpeg command.

### ISSUE THREAD

**Issue by vikas-markk** [tanersener/mobile-ffmpeg#227]
Unable to perform below commanf
 -i test.mp4  -i overlay-large.png  -filter_complex "[1] scale=w=1080:h=1920 [tmp]; [0][tmp] overlay=0:0" -strict -2 -y -movflags +faststart -c:v libx264 -coder 1 -pix_fmt yuv420p -preset:v ultrafast -tune film -bf 3 -b_strategy 2 -g 100 -refs 10 -b:v 3M -minrate 2.85M -maxrate 7M -bufsize 7M -movflags faststart -b:a 128k -pass 1 output_001.mp4
Same command working fine on desktop, but facing problem on mobile device.

**Expected behavior**
Suppose to get success .

**Current behavior**
Getting ffmpeg error.

**Environment**
 - Platform: Android
 - Version :    implementation 'com.arthenica:mobile-ffmpeg-full:4.2.LTS'

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132).
