### ISSUE TITLE
Same video file multiple times processing  

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#232]
**Description**
Same video multiple commands.

**Expected behavior**

Want to use same processed video for multiple commands. Like if I crop the video the same videos file i want for water mark, water marks output for trimming and so on. But I am getting error as shown below. 

**Current behavior**
Corrupted video .

**Screenshots**

**Logs**
ffmpeg version v4.2-dev-1824 Copyright (c) 2000-2019 the FFmpeg developers
  built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
  configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libx264 --enable-gpl --enable-libxvid --enable-gpl --enable-libx265 --enable-gpl --enable-libvidstab --enable-gpl --disable-sdl2 --enable-zlib --enable-mediacodec
  libavutil      56. 30.100 / 56. 30.100
  libavcodec     58. 53.101 / 58. 53.101
  libavformat    58. 28.101 / 58. 28.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/VideoEditor/Temp/1567936351.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.28.101
  Duration: 00:00:09.97, start: 0.000000, bitrate: 612 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p, 720x1280, 812 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 (h264) -> setpts
  Stream #0:1 (aac) -> atempo
  setpts -> Stream #0:0 (libx264)
  atempo -> Stream #0:1 (aac)
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[out_0_1 @ 0x7a0790f880] 100 buffers queued in out_0_1, something may be wrong.
[libx264 @ 0x7a06a37300] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x7a06a37300] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit
[libx264 @ 0x7a06a37300] 264 - core 157 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0

**Environment**
 - Platform: [e.g. Android/IOS]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Comment by tanersener** [comment]
Can you confirm that your command is working fine on desktop ffmpeg?

**Comment by gururajKp** [comment]
> Can you confirm that your command is working fine on desktop ffmpeg?

Hi i can u please tell me how to run the and use ffmpeg on desktop ?

**Comment by tanersener** [comment]
[FFmpeg download](https://ffmpeg.org/download.html) page includes binaries for different platforms. On macOS you can install it using `brew install ffmpeg`.

**Comment by tanersener** [comment]
@gururajKp any updates about this issue?

**Comment by gururajKp** [comment]
> @gururajKp any updates about this issue?

 Hi @tanersener  sorry for late reply. No i dint see that as I am processing video for only one command.

**Comment by tanersener** [comment]
@gururajKp Can I close this issue then?

**Comment by gururajKp** [comment]
> @gururajKp Can I close this issue then?

yes u can close @tanersener  :).
