### ISSUE TITLE
Adding adio to video 

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#235]
**Description**
I want to add an audio to a video.

**Expected behavior**
Same audio should loop till video ends. Example if audio's length is 5 seconds and video's length is 30 seconds then video should play up to 30 seconds with repeated audio of 5 seconds. 

**Current behavior**
Trimming the video depending on the audio duration.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.com) and insert the link here.

**Environment**
 
 - Android Studio version (if applicable) [e.g. 3.1]

**Other**

**Comment by tanersener** [comment]
[Please ask ffmpeg questions to ffmpeg-user@ffmpeg.org](https://github.com/tanersener/mobile-ffmpeg/issues/130).
