### ISSUE TITLE
How to execute multiple command ffmpeg

### ISSUE THREAD

**Issue by huongvu1397** [tanersener/mobile-ffmpeg#237]
**Description**
I have a for-loop and need to execute many commands in it
```
 for (item in list!!) {
            setMute(File(item.path))
        }
```

```
fun setMute(path:String){
...
FFmpegUtils.executeAsync({ result, executeOutput ->
                if (result != 0) {
                    callback!!.onFailure(IOException())
                } else if (result == RETURN_CODE_SUCCESS) {
                    callback!!.onSuccess()
                }
            }, ffmpegCommand)
...
}
```

but something wrong when i run it! how can i run with multiple command ffmpeg

**Comment by tanersener** [comment]
`mobile-ffmpeg` does not support parallel executions, only one execution is possible at any particular time.

If you want to run multiple commands you need to execute them one by one.

**Comment by danisein** [comment]
Why not support parallel executions? Are there technical issues？

**Comment by tanersener** [comment]
@danisein Parallel execution support is added in `v4.3.1`. Please see [Concurrent Execution Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Concurrent-Execution-Support).

**Comment by danisein** [comment]
@tanersener Thanks!
