### ISSUE TITLE
Statistics always returning 0 for all properties

### ISSUE THREAD

**Issue by fayte0618** [tanersener/mobile-ffmpeg#24]
I'm currently using 2.1 version of your lib and mimicked your implementation in your test app using  Config.enableStatisticsCallback.  However, I noticed my StatisticsCallback isn't executed, and if I force get the statistics using Config.getLastReceivedStatistics I only receive all 0s. There's no error also. The command executes fine and exports the video. And I'm also using  Config.enableLogCallback and it works fine. Why is this? Do I have to set this up or follow a series of steps before I use this?

Thanks for the help :)

**Comment by fayte0618** [comment]
![capture](https://user-images.githubusercontent.com/8073714/45361242-552df600-b604-11e8-8a8d-2d2496f3079a.PNG)

**Comment by tanersener** [comment]
> my StatisticsCallback isn't executed, and if I force get the statistics using Config.getLastReceivedStatistics I only receive all 0s. There's no error also. 

You don't have to do anything else; it sounds like be bug, but I need to check it first.

Could you please provide the command you used if it is OK for you? I want to test it locally.

**Comment by fayte0618** [comment]
-y -hide_banner -i [inputpath] -vf hue=s=0 -preset ultrafast -profile:v baseline -level 3.1 -crf 28 -c:a [outputpath]

if it helps im using the min-gpl version of your lib. But, when I switched to the others it still has the same bug.

**Comment by tanersener** [comment]
Tried your command and it worked for me, I received statistics callbacks.

To analyze it further, could you please post your command output? `MobileFFmpeg` basically extracts statistics from `FFmpeg` reports. Looking at command output, we can see whether `FFmpeg` generated reports or not?

**Comment by fayte0618** [comment]
Here's the logs from the LogCallback
![1](https://user-images.githubusercontent.com/8073714/45401687-70d8e100-b684-11e8-88d1-60e9e4fb89c5.PNG)
![2](https://user-images.githubusercontent.com/8073714/45401690-720a0e00-b684-11e8-9c6f-c2e24275f485.PNG)
![3](https://user-images.githubusercontent.com/8073714/45401710-8fd77300-b684-11e8-98c4-9c9273eb42a0.PNG)

**Comment by tanersener** [comment]
I tested statistics with negative values; they are not causing any trouble.

Is it possible to test your application with the following debug aar? This package includes extra debug logs for statistics printed to LogCat. They may help to identify this issue.

[mobile-ffmpeg-min-gpl-snapshot-2.2.aar](https://www.dropbox.com/s/olgvcn9b6oaocpw/mobile-ffmpeg-min-gpl-2.2.aar?dl=0)

**Comment by fayte0618** [comment]
Sorry for the late reply. I tried using your .aar but it gives me this error 
![capture](https://user-images.githubusercontent.com/8073714/45541324-6283f400-b841-11e8-9e3c-5e9a2a173f86.PNG)

**Comment by tanersener** [comment]
No problem mate. 

I managed to reproduce this issue on `arm-v7a-neon`. It looks like `x86` variants are not affected from this, only `arm` ABIs I guess. 

I'm working on it, I'll post an update after making some tests.

**Comment by tanersener** [comment]
Further tests show that `armeabi-v7a` and `arm64-v8a` are not affected from this issue, only `armeabi-v7a-neon` so far.

**Comment by tanersener** [comment]
Can you test this issue with `v2.1.1`?

**Comment by fayte0618** [comment]
It works! thank you very much :))

**Comment by tanersener** [comment]
You're welcome. Thank you for helping me improve.
