### ISSUE TITLE
does not contain any stream

### ISSUE THREAD

**Issue by runner525** [tanersener/mobile-ffmpeg#241]
when I use the demo ,I get Error:
my code is :
String[] cmd =  {"-y -i /sdcard/p_26794701.flv /sdcard/p_26794701.mp4"};
        //String[] cmd =  {" -i " + filepath + " -r 1 -t 1 " + imagefilepath};
        try {
            // to execute "ffmpeg -version" command you just need to pass "-version"
            ffmpeg.execute(cmd, new ExecuteBinaryResponseHandler() {

the error message is:

06-25 11:10:21.239 11364 11364 I ffmpeg  : Output #0, mp4, to ' -y -i /sdcard/p_26794701.flv /sdcard/p_26794701.mp4':
06-25 11:10:21.239 11364 11364 I ffmpeg  : Output file #0 does not contain any stream
06-25 11:10:21.239 11364 11364 I ffmpeg  : execute onFinish
06-25 11:10:21.291  1817 11407 I FFMPEG  : [device/hisilicon/bigfish/hidolphin/component/hiplayer/component/ffmpeg_adp/libavformatadp_v100r002/hi_svr_format.c:14151] set cache time = -532719348

**Comment by tanersener** [comment]
Can you test your command on desktop `ffmpeg`?

**Comment by runner525** [comment]
it work well on PC :
D:\log\locaimage>ffmpeg  -y -i p_26794701.flv p_26794701.mp4

**Comment by runner525** [comment]
> Could you please test your command on desktop `ffmpeg`?

it works well on PC like this:
D:\log\locaimage>ffmpeg  -y -i p_26794701.flv p_26794701.mp4

**Comment by tanersener** [comment]
Can you share your input file `p_26794701.flv` with me? So I can investigate it further.

**Comment by runner525** [comment]
> Can you share your input file `p_26794701.flv` with me? So I can investigate it further.
It is due to the wrong inoput file, after changing the input file ,it works ,thanks a lot
