### ISSUE TITLE
Custom build for minimum size

### ISSUE THREAD

**Issue by yangshulin2019** [tanersener/mobile-ffmpeg#244]
**Description**
Thanks for you work on this open source project. These days I am working on building mobile-ffmpeg for minimum size. I just need ffmpeg to deal with wav/pcm and m4a audio format. 
1.convert m4a file to wav
2.split a wav file 
3.merge wav files to one m4a.
Most of code is not necessary for my project, so I begin to reduce the library size. I have choose some encoders, decoders, muxers, demuxers just need. But I encounter runtime error when reduce filters, I disable all filters and enable what I use. I do not know what filter is necessary for wav and m4a, and if filter has dependence. My filters is volume, amix, adelay. Can you give me some advice about this?
Another thing, I find your project can not custom build for --disable-avdevice and --disable-swscale which is not needed for my project.

**Comment by tanersener** [comment]
> I do not know what filter is necessary for wav and m4a, and if filter has dependence. My filters is volume, amix, adelay. Can you give me some advice about this?

Unfortunately, I don't know. How about asking this question to to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list. `ffmpeg` developers may have an idea about it.

> Another thing, I find your project can not custom build for --disable-avdevice and --disable-swscale which is not needed for my project.

Well, technically it is not possible to support all custom build options. If you share your error I can comment on that but I'm not sure if I can make something to fix it.
