### ISSUE TITLE
Get the percentage of FFMpeg execution

### ISSUE THREAD

**Issue by jsfan3** [tanersener/mobile-ffmpeg#246]
Thank you for this project.

On Android, assuming to use an example as reported in the README.md, that is `FFmpeg.execute("-i file1.mp4 -c:v mpeg4 file2.mp4");`, how can I get the percentage of that execution?

**Comment by tanersener** [comment]
You must calculate the percentage yourself using fields in the Statistics Callback.

```
Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        int percentage = (newStatistics.getTime()/totalTime)*100;
    }
});
```

**Comment by jsfan3** [comment]
Thank you very much!
I hope you will keep to make this project updated.

Tomorrow I'll publish an open source CN1Lib (Codename One Library) that includes your MobileFFmpeg library.
I sent you a small donation using PayPal.

**Comment by tanersener** [comment]
> Tomorrow I'll publish an open source CN1Lib (Codename One Library) that includes your MobileFFmpeg library.

Great!

> I sent you a small donation using PayPal.

Thanks so much :+1:

**Comment by jsfan3** [comment]
Out of curiosity, I have just published my library that include yours:
https://github.com/jsfan3/CN1Libs-VideoOptimizer

**Comment by tanersener** [comment]
> Out of curiosity, I have just published my library that include yours:
> https://github.com/jsfan3/CN1Libs-VideoOptimizer

Congrats :tada:

**Comment by vjsingh96** [comment]
This function is not updating UI.
```
Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        int percentage = (newStatistics.getTime()/totalTime)*100;
    }
});
```

**Comment by BilalAsif25** [comment]
@tanersener sorry for silly question, what is totalTime?

Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        int percentage = (newStatistics.getTime()/totalTime)*100;
    }
});

**Comment by tanersener** [comment]
@BilalAsif25 It should be set by the app developer. `ffmpeg` can tell the total duration only after completing the execution. As the developer you should know what you're trying to do and what will be the `totalDuration`. You can use `FFprobe` to get the initial duration of a file.

**Comment by quangpham69** [comment]
> Vì tò mò, tôi vừa xuất bản thư viện của mình bao gồm thư viện của bạn:
> https://github.com/jsfan3/CN1Libs-VideoOptimizer

can you publish a specialized Audio library?

**Comment by quangpham69** [comment]
> Out of curiosity, I have just published my library that include yours:
> https://github.com/jsfan3/CN1Libs-VideoOptimizer

can you publish a specialized Audio library?
