### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by paul159357** [tanersener/mobile-ffmpeg#247]
**Description**
Hi, I'm using your plugin to merge videos on Unity Android. Thanks to your plugin that I can make and edit game highlight vid so easily, but there is a problem. When I call

        int response=jc.CallStatic<int>("execute", 
            string.Format("-f concat -i {0} -c copy {1}",
                (Application.persistentDataPath + "/" + "mylist.txt") ,//textfile, list of file names to merge
                (Application.persistentDataPath + "/" + "highlight.mp4")) //output file directory name
        );

, it gets response of 1. I could only find 0 means success and 255 means cancel on docs. Can you please tell me what does code 1 mean?

**Expected behavior**
should return 0, Want to know why so that I can get hint to fix it.

**Current behavior**
function execute returns 1

**Environment**
 - Platform: [e.g. Android(Unity)]
 - Architecture: [arm64-v8a]
 - Version (if applicable) [e.g. v4.2.2 LTS]
 - Source branch (if applicable) [e.g. master]

**Comment by paul159357** [comment]
+Here's log from adb
10-03 14:58:58.090 10100 10164 I mobile-ffmpeg:   configuration: --cross-prefix=arm-linux-androideabi- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=armv7-a --cpu=armv7-a --cc=armv7a-linux-androideabi16-clang --cxx=armv7a-linux-androideabi16-clang++ --target-os=android --disable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-sdl2 --enable-zlib --enable-mediacodec
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:   libavutil      56. 30.100 / 56. 30.100
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:   libavcodec     58. 53.101 / 58. 53.101
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:   libavformat    58. 28.101 / 58. 28.101
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:   libavdevice    58.  7.100 / 58.  7.100
10-03 14:58:58.091 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:   libavfilter     7. 55.100 /  7. 55.100
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:   libswscale      5.  4.101 /  5.  4.101
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:
10-03 14:58:58.092 10100 10164 I mobile-ffmpeg:   libswresample   3.  4.100 /  3.  4.100
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg:
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg: [concat @ 0xc699b400]
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg:
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg: Line 1: unknown keyword '/storage/emulated/0/Android/data/com.DefaultCompany.AdventureOfPoleon/files/recording_2019_10_03_14_50_43_303.mp4'
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg:
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg:
10-03 14:58:58.093 10100 10164 E mobile-ffmpeg: /storage/emulated/0/Android/data/com.DefaultCompany.AdventureOfPoleon/files/mylist.txt: Invalid data found when processing input

**Comment by tanersener** [comment]
> Can you please tell me what does code 1 mean?

1 means error/failure.

> Line 1: unknown keyword '/storage/emulated/0/Android/data/com.DefaultCompany.AdventureOfPoleon/files/recording_2019_10_03_14_50_43_303.mp4'

This is the reason of the failure. Do you have `file` keyword before the file path as described in the [FFmpeg Concatenate Documentation](https://trac.ffmpeg.org/wiki/Concatenate).

**Comment by paul159357** [comment]
Oh, I thought the return number might contain some information about the error. I think file keyword was missing in the command as you said. Thank you for reply!

**Comment by charlieaboumoussa** [comment]
@tanersener Hello. I tried adding the file keyword manually. Yet it didn't work. How to retrieve the path with the file keyword from a URI? Thank you

**Comment by charlieaboumoussa** [comment]
@paul159357 Hello Paul. How did you solve this?

**Comment by charlieaboumoussa** [comment]
```
I/mobile-ffmpeg:   configuration: --cross-prefix=arm-linux-androideabi- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=armv7-a --cpu=armv7-a --cc=armv7a-linux-androideabi16-clang --cxx=armv7a-linux-androideabi16-clang++ --target-os=android --disable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libkvazaar --enable-libsnappy --enable-libaom --disable-sdl2 --enable-zlib --enable-mediacodec
I/mobile-ffmpeg:   libavutil      56. 30.100 / 56. 30.100
I/mobile-ffmpeg:   libavcodec     58. 53.101 / 58. 53.101
      libavformat    58. 28.101 / 58. 28.101
I/mobile-ffmpeg:   libavdevice    58.  7.100 / 58.  7.100
I/mobile-ffmpeg:   libavfilter     7. 55.100 /  7. 55.100
      libswscale      5.  4.101 /  5.  4.101
I/mobile-ffmpeg:   libswresample   3.  4.100 /  3.  4.100
E/mobile-ffmpeg: true: No such file or directory
I/MediaRecorderJNI: finalize
    release
```

Content provider paths:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-files-path
      name="external_files"
      path="Pictures/" />
  <external-files-path
      name="external_video_files"
      path="Movies/" />
</paths>
```

It doesn't seem to find the file. How to solve this? It is also returning Result Code 1.
