### ISSUE TITLE
Android X error

### ISSUE THREAD

**Issue by Andrebets** [tanersener/mobile-ffmpeg#248]
I am developing an Android application with dependency on "implementation 'com.arthenica: mobile-ffmpeg-full-gpl: 4.2.2'". With the SDK in version 28, "compileSdkVersion = 28", a video generation works normally. I'm transitioning to SDK 29, "compileSdkVersion = 29" and passing all dependencies to Android X and generating the video is returning the error in the attached image.
![ffmpeg_error](https://user-images.githubusercontent.com/56031801/65964574-a12c2280-e433-11e9-8784-79b3bf4425ae.jpg)

**Comment by tanersener** [comment]
`mobile-ffmpeg-4.2.2` does not have any issues with `compileSdkVersion 29`. It is already tested and verified. There should be another reason causing this error.

Can you share your project's gradle files (build.gradle, settings.grade, gradle.properties) please?
