### ISSUE TITLE
iOS pod installation

### ISSUE THREAD

**Issue by jlorencelim** [tanersener/mobile-ffmpeg#25]
I am using this version: 
`'mobile-ffmpeg-min-gpl', '~> 2.1.1'`

I tried to install the library using pods for iOS but it the download URL is not correct. This is the path that it is using when using pods: 
`https://github.com/tanersener/mobile-ffmpeg/releases/download/v2.1.1/mobile-ffmpeg-min-gpl-2.1.1-ios-framework.zip` 
But when I checked the your releases, it should be: 
https://github.com/tanersener/mobile-ffmpeg/releases/download/v2.1.1.ios/mobile-ffmpeg-min-gpl-2.1.1-ios-framework.zip

Thanks for the help

**Comment by tanersener** [comment]
Sorry, you are right. It's fixed now. Can you try again?

**Comment by jlorencelim** [comment]
It works fine now. Thanks!

**Comment by tanersener** [comment]
I thank you
