### ISSUE TITLE
LGPL license for Android app

### ISSUE THREAD

**Issue by yangshulin2019** [tanersener/mobile-ffmpeg#260]
**Description**
I want to use mobile-ffmpeg in my Android app, because mobile-ffmpeg is LGPL, I find it hard to comply with the license. The app is close source, as LGPL said, user can build their own library and relink to app. I think ffmpeg so libraries is ok, user can rebuild ffmpeg so libraries and replace them in the apk file. I think it will works, but I have not try it. How about the ffmpeg execute binary? The java code is biggest obstacle. As java class will compile into apk dex file, it is impossible to replace the class file. So can you give me some suggestion to solve this problem? And may you change the java code to a no LGPL license, for example [this project](https://github.com/MKergall/osmbonuspack#licence).

**Comment by tanersener** [comment]
> How about the ffmpeg execute binary? 

This project uses `so` libraries for Android and does not generate `ffmpeg` executable binary. 

There is a [Building ffmpeg executable on Android](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) page in wiki which lists modifications necessary to generate `ffmpeg` executable but generated `ffmpeg` executable binary is not compatible with `mobile-ffmpeg`. You can not use it with `mobile-ffmpeg`. It is only created to help people who don't need `mobile-ffmpeg` but still want to use `ffmpeg`.

> The java code is biggest obstacle. As java class will compile into apk dex file, it is impossible to replace the class file. So can you give me some suggestion to solve this problem? 

Are you asking about including `ffmpeg` executable binary in an application or `mobile-ffmpeg`. I have a [Using MobileFFmpeg in Commercial Applications](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Commercial-Applications) about this project.

> And may you change the java code to a no LGPL license, for example [this project](https://github.com/MKergall/osmbonuspack#licence).

Java code can be linked to `LGPL` or `GPL` licensed libraries depending on how you build it. Changing its license is only possible for `LGPL` and needs a lot of effort. Additionally, it will be very difficult to explain it to users. I don't want to do that.

**Comment by yangshulin2019** [comment]
Ok, thanks a lot for you reply. I had a misunderstand about he ffmpeg binary. That is not a problem now. Jave code can be linked to LGPL licensed libraries, but in Android, it seems very hard to. I want to change the mobile-ffmpeg link method. I will build mobible-ffmpeg in so libraries and not aar, because aar contains java code. I write the java code by myself in the app project and use so libraries. When users want to relink the libraries, they can build so libraries and replace them in the APK. And it will works well and also comply with LGPL. Am I right?

**Comment by tanersener** [comment]
> When users want to relink the libraries, they can build so libraries and replace them in the APK. And it will works well and also comply with LGPL. Am I right?

Yeah, you are right.
