### ISSUE TITLE
Android log verbosity problem

### ISSUE THREAD

**Issue by JAK0723** [tanersener/mobile-ffmpeg#264]
**Description**
The `Config` file seems to indicate that the verbosity set by `setLogLevel` will be used to determine what type of log message is printed. This does not appear to be the case, which is making it more difficult to organise my log messages.
https://github.com/tanersener/mobile-ffmpeg/blob/a10996cf7ebf1e7ff6e62e5a4cbb1e4cb4a4ea94/android/app/src/main/java/com/arthenica/mobileffmpeg/Config.java#L250

**Expected behavior**
When `Level.AV_LOG_DEBUG` is passed to `Config.setLogLevel`, ffmpeg messages should be logged with `Log.d`.
When `Level.AV_LOG_ERROR` is passed to `Config.setLogLevel`, ffmpeg messages should be logged with `Log.e`.

**Current behavior**
When any verbosity level below info (`AV_LOG_QUIET`, `AV_LOG_PANIC`, `AV_LOG_FATAL`, `AV_LOG_ERROR`, `AV_LOG_WARNING`) is passed to `Config.setLogLevel`, then it will be treated as if quiet verbosity was set, all ffmpeg messages are ignored.
When any verbosity level above info (`AV_LOG_VERBOSE`, `AV_LOG_DEBUG`, `AV_LOG_TRACE`) is passed to `Config.setLogLevel`, then it will be treated as if info verbosity was set, all ffmpeg messages are logged with `Log.i`.

**Environment**
 - Platform: Android
 - Architecture: arm64-v8a
 - Version: full-gpl:4.2.2
 - Android Studio version: 3.5.1

**Comment by tanersener** [comment]
> **Expected behavior**
> When `Level.AV_LOG_DEBUG` is passed to `Config.setLogLevel`, ffmpeg messages should be logged with `Log.d`.
> When `Level.AV_LOG_ERROR` is passed to `Config.setLogLevel`, ffmpeg messages should be logged with `Log.e`.

No. This is not the expected behaviour. `setLogLevel` defines which log messages are allowed and will be printed. But it doesn't set the severity/level of the logs. All log messages has their own log severity/level set by `ffmpeg` itself. Please see the following signature. `levelValue` is set by `ffmpeg` and `mobile-ffmpeg` does not modify it.

```
    private static void log(final int levelValue, final byte[] logMessage) {
```
 
> When any verbosity level below info (`AV_LOG_QUIET`, `AV_LOG_PANIC`, `AV_LOG_FATAL`, `AV_LOG_ERROR`, `AV_LOG_WARNING`) is passed to `Config.setLogLevel`, then it will be treated as if quiet verbosity was set, all ffmpeg messages are ignored.

That's the meaning of `AV_LOG_QUIET`. Nothing should be printed. Why do you expect something to be printed?

> When any verbosity level above info (`AV_LOG_VERBOSE`, `AV_LOG_DEBUG`, `AV_LOG_TRACE`) is passed to `Config.setLogLevel`, then it will be treated as if info verbosity was set, all ffmpeg messages are logged with `Log.i`.

No, log severity/level set by `ffmpeg` defines on which `Log.x` level that message will be printed. See the following code.

```
                case AV_LOG_TRACE:
                case AV_LOG_DEBUG: {
                    android.util.Log.d(TAG, text);
                }
                break;
                case AV_LOG_VERBOSE: {
                    android.util.Log.v(TAG, text);
                }
                break;
                case AV_LOG_INFO: {
                    android.util.Log.i(TAG, text);
                }
                break;
                case AV_LOG_WARNING: {
                    android.util.Log.w(TAG, text);
                }
                break;
                case AV_LOG_ERROR:
                case AV_LOG_FATAL:
                case AV_LOG_PANIC: {
                    android.util.Log.e(TAG, text);
                }
                break;
                default: {
                    android.util.Log.v(TAG, text);
                }
```

**Comment by JAK0723** [comment]
Oh, so `Config.setLogLevel` sets the verbosity threshold for ffmpeg messages and the verbosity of these messages are then used to determine the type of log message. I thought that `Config.setLogLevel` was for directly setting the log type. Sorry for my mistake.

**Comment by tanersener** [comment]
No problem 👍
