### ISSUE TITLE
Warning: ARM function not 4-byte aligned

### ISSUE THREAD

**Issue by macrohard** [tanersener/mobile-ffmpeg#265]
I tried to add the compiled static library to the XCode project, but I encountered a lot of warning messages at compile time:
ld: warning: ARM function not 4-byte aligned: .Lpic2 from libavcodec.a(ac3dsp_armv6.o)
ld: warning: ARM function not 4-byte aligned: .Lpic6 from libavcodec.a(ac3dsp_armv6.o)
ld: warning: ARM function not 4-byte aligned: .Lpic5 from libavcodec.a(fft_fixed_neon.o)
ld: warning: ARM function not 4-byte aligned: .Lpic17 from libavcodec.a(fft_fixed_neon.o)
ld: warning: ARM function not 4-byte aligned: .Lpic34 from libavcodec.a(fft_fixed_neon.o)
......

**Comment by tanersener** [comment]
Could you please [fill the issue template fields](https://github.com/tanersener/mobile-ffmpeg/issues/132)?

**Comment by macrohard** [comment]
I found the cause and solved it myself. The reason is that XCode11 and iOS SDK13 do not support the optimization instructions of armv7. I added the --disable-arm when compiling armv7. The problem does not exist.

**Comment by tanersener** [comment]
Okay then
