### ISSUE TITLE
how can i get all frames of video

### ISSUE THREAD

**Issue by huongvu1397** [tanersener/mobile-ffmpeg#267]
Can FFmpeg.getMediaInformation() support for me to get all frames of video ?

**Comment by tanersener** [comment]
Are you asking how to get the frame count, or how to extract images from a video?

**Comment by huongvu1397** [comment]
yeah , i want to know how to get the frame count, i'm using FFmpeg.getMediaInformation() to get the real frame and using [real frame] * [duration] = [frame count] but i think im wrong 😄

**Comment by tanersener** [comment]
> i'm using FFmpeg.getMediaInformation() to get the real frame and using [real frame] * [duration] = [frame count] but i think im wrong 😄

No, it is not wrong. But it may not give you the exact number. 

See this [stackoverflow](https://stackoverflow.com/questions/2017843/fetch-frame-count-with-ffmpeg) thread, there  are different solutions posted there. You can try one of the solutions that use `ffmpeg`.

**Comment by huongvu1397** [comment]
yeah, thank you , i will try it <3

**Comment by huongvu1397** [comment]
i have try this cmd : `ffmpeg -i ouput.mp4 -map 0:v:0 -c copy -f null -` to get count of frames but in this case i don't know how to get it.
```
  val ffmpegCmd = String.format(
            "-hide_banner${FFmpegUtils.REGEX}%s",
            cmd.joinToString(FFmpegUtils.REGEX)
        )
        Config.enableStatisticsCallback { newStatistics ->
            Log.d(
               Config.TAG,
                String.format(
                    "frame: %d, time: %d",
                    newStatistics.videoFrameNumber,
                    newStatistics.time
                )
            )
            framesCount = newStatistics.videoFrameNumber
        }

        FFmpegUtils.executeAsync({ returnCode, _ ->
            if (returnCode == RETURN_CODE_SUCCESS) {
                Log.d( Config.TAG, "Encode completed successfully; playing video. $framesCount")
            } else {
                Log.d( Config.TAG, "Encode failed.")
            }
        }, ffmpegCmd)
```

and Logcat: 

2019-11-11 16:37:55.002 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: Stream mapping:
2019-11-11 16:37:55.003 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg:   Stream #0:0 -> #0:0
2019-11-11 16:37:55.003 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg:  (copy)
2019-11-11 16:37:55.003 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: Press [q] to stop, [?] for help
2019-11-11 16:37:55.007 5834-5907/com.example.demoimagemagick3 D/mobile-ffmpeg: **frame: 1, time: 11104**
2019-11-11 16:37:55.008 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: frame=    1 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=3.67x    
**2019-11-11 16:37:55.036 5834-5834/com.example.demoimagemagick3 D/mobile-ffmpeg: Encode completed successfully; playing video. 1**
2019-11-11 16:37:55.039 5834-5907/com.example.demoimagemagick3 D/mobile-ffmpeg: **frame: 281, time: 11104**
2019-11-11 16:37:55.039 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: frame=  281 fps=0.0 q=-1.0 Lsize=N/A time=00:00:11.10 bitrate=N/A speed= 156x    
2019-11-11 16:37:55.039 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: video:23259kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
2019-11-11 16:37:55.039 5834-5907/com.example.demoimagemagick3 I/mobile-ffmpeg: unknown

i have 2 result frames and returnCode success with first frame count : 1

**Comment by tanersener** [comment]
When you execute an `ffmpeg` command, `ffmpeg` prints processed frame count in a statistics line and that frame count starts with 1 naturally. 

In your case the last one is the final one and includes the total frame number counted. 

`frame= 281 fps=0.0 q=-1.0 Lsize=N/A time=00:00:11.10 bitrate=N/A speed= 156x`

**Comment by huongvu1397** [comment]
However, i want to get 281 frames when "returnCode == RETURN_CODE_SUCCESS", but in this case this log "Encode completed successfully; playing video. 1" come first so i will get 1 frames not 281 frames. i don't know how to get it when returnCode == RETURN_CODE_SUCCESS.

**Comment by tanersener** [comment]
`Encode completed successfully; playing video` is a user log. It is not printed by the library, your application prints it. Can you disable it?

**Comment by huongvu1397** [comment]
yes , i can . but i want to know when the encode complete with the library , can the library have callback when the endcode complete ?

**Comment by tanersener** [comment]
> However, i want to get 281 frames when "returnCode == RETURN_CODE_SUCCESS", but in this case this log "Encode completed successfully; playing video. 1" come first

You said that `Encode completed successfully; playing video. 1` comes first. So, I explained why it is printed. 

> yes , i can . but i want to know when the encode complete with the library , can the library have callback when the endcode complete ?

Of course it can. Did you try using `FFmpeg.getLastCommandOutput();` ?
