### ISSUE TITLE
[ios] build error

### ISSUE THREAD

**Issue by andyrenkehe** [tanersener/mobile-ffmpeg#270]
./ios.sh --enable-x264 --enable-libass  --enable-freetype   --enable-fribidi  --enable-fontconfig  --enable-gpl -l

error happened:
(*) LTS packages should be built using SDK 9.3 but current configuration uses SDK 13.0

How to solve this problem?

**Comment by tanersener** [comment]
You need to have `SDK 9.3` to build the `LTS` variant of the library.

**Comment by xoai** [comment]
@tanersener Any idea how to download and install iOS SDK 9.3?

I have Xcode 11.2.1 and no iOS 9.3 simulator appears in Xcode -> Preferences -> Components. I tried to download Xcode 10.2.1 and install iOS 9.3 simulator but no luck. The SDK 9.3 doesn't show up when I run:
`xcodebuild -showsdks`

**Comment by tanersener** [comment]
You need to download `Xcode 7.3.1` (which includes iOS SDK 9.3) from `https://developer.apple.com/download/more/`and install it with a different name without overriding your existing `Xcode 10.2.1`.

**Comment by andyrenkehe** [comment]
Thank you!

**Comment by MarsVard** [comment]
is anybody building the latest versions with --lts? I can't seem to install xcode 7.3.1 under catalina :'(

**Comment by xoai** [comment]
> is anybody building the latest versions with --lts? I can't seem to install xcode 7.3.1 under catalina :'(

I did have to borrow an old macbook installed old version of MacOS to install Xcode 7.3.1. It seems there's no other way.

**Comment by MarsVard** [comment]
damn, it's hopeless for me.

**Comment by tanersener** [comment]
@MarsVard You don't need Xcode 7.3.1. You just need iOS SDK coming with it. I use `Catalina` too and I don't have any problems about it. You can:

- Download Xcode 7.3.1 ad Command Line Tools for 7.3.1 from Apple
- Mount it and copy Xcode under Applications with a different name
- Set `DEVELOPER_DIR` to your Xcode 7.3.1
    ```
    export DEVELOPER_DIR=/Applications/Xcode-v7.3.1.app/Contents/Developer
    ```
- And run `./ios.sh --lts`
