### ISSUE TITLE
Progress callback required for video operation command Android 

### ISSUE THREAD

**Issue by chiragpindianic** [tanersener/mobile-ffmpeg#273]
**Description**
The library doesn't provide the percentage of the amount being processed. Elucidating the current behavior for a command `FFmpeg.execute("-i file1.mp4 -c:v mpeg4 file2.mp4"); ` there is no way to find how much of the file percentage is already processed. This is exasperating for a user to assume, How much file is processed? Is it really processing or stopped somewhere? Do we need to really wait for a long period (User might escape when the file is almost processed under the assumption that it is just loading and nothing is working)

**Expected behavior**
There should be a way by which we can identify the process in the terms of percentage/ time for the better user experience over making them feel clueless about the progress.

Requesting for callbacks for the Progress with Success and Failure.

**Current behavior**
Using this we can get only callbacks of Success, Failure.  

**Environment**
 - Platform: [e.g. Android/IOS]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

Your quick response to this matter will be really appreciated!

Do let me know if any information is required on the same.

Thanks!

**Comment by andriistefanyshyn** [comment]
You can implement processing progress like described in this [comment](https://github.com/tanersener/mobile-ffmpeg/issues/246#issuecomment-536681484)

**Comment by tanersener** [comment]
Did you try using a `StatisticsCallback`?
