### ISSUE TITLE
video effects sepia, black and white.

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#274]
Hi @tanersener as I am using your library it is working fine for cropping video and rotating video and overlaying. But I wanted to know is your library also supports effects like sepia black and white hue ?

**Comment by tanersener** [comment]
Did you check [FFmpeg filters](https://ffmpeg.org/ffmpeg-filters.html) page? 

You can create sepia with [colorchannelmixer](https://ffmpeg.org/ffmpeg-filters.html#colorchannelmixer) and hue with [hue](https://ffmpeg.org/ffmpeg-filters.html#hue) filter.
