### ISSUE TITLE
POD for TVOS doesnt Exist

### ISSUE THREAD

**Issue by JChappel** [tanersener/mobile-ffmpeg#276]
**Description**
I'm trying to install with the tvOS Pod 'mobile-ffmpeg-tv-full' but I receive the error:

[!] Unable to find a specification for `mobile-ffmpeg-tv-full (~> 4.3)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Expected behavior**
Pod to install for TVOS project

**Current behavior**
Pod does not install.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: tvOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) 4.3
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by JChappel** [comment]
It looks like there is a typo in the Installation instructions. It shows:
pod 'mobile-ffmpeg-tv-full', '~> 4.3'

but it should be:
pod 'mobile-ffmpeg-tvos-full', '~> 4.3'

after fixing this the pod install worked.

**Comment by tanersener** [comment]
Thanks for reporting this issue. It is fixed now.
