### ISSUE TITLE
Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by max296** [tanersener/mobile-ffmpeg#277]
I need to encode video by h264, i know that it contain in external library and i have to enable that. But i can't figure out how to do that. Can you please provide steps to enable that?

**Comment by tanersener** [comment]
How do you use `mobile-ffmpeg`, do you use a prebuilt binary from `jcenter()`/`cocoapods`?

**Comment by max296** [comment]
Currently i am using it by from dependency for android

implementation 'com.arthenica:mobile-ffmpeg-full:4.2.2.LTS'

**Comment by tanersener** [comment]
`libx264` is only included in `GPL` licensed packages. Can you use the following dependency?

```
implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.2.2.LTS'
```

**Comment by yangfeng1994** [comment]
user  https://github.com/yangfeng1994/FFmpeg-Android

**Comment by GrilloLuca** [comment]
i have the same problem but if i use the 
full-gpl instead of the full, i have this error: "libcpufeatures.so not found"

**Comment by tanersener** [comment]
@GrilloLuca Can you please search for other issues about `libcpufeatures.so`?

**Comment by cahyofendhi** [comment]
i have same issue on android, using latest version `4.3.2`

**Comment by z5xframeworks** [comment]
Hi @tanersener  I have tested with both 4.2.2.LTS & 4.3.1.LTS, but still the Unknown encoder 'libx264' and Unknown encoder 'libx265' comes whenever i try the below command.
 "-i",  inputVideo,
            "-b:v", "1M",
            "-vcodec", "libx264",
            "-b:a", "128k",
            "-ss",
            "00:00:00",
            "-t",
            "00:00:15",
            "-crf", "32",
             "-y", outputUri


//inputVideo is the filepath of input video mp4
//outputUri is the filepath of output video.mp4

//Mobile - Android Emulator Api 29

**Comment by tanersener** [comment]
@z5xframeworks Did you see my previous posts where I clearly state that `x264` and `x265` are only included in `GPL` licensed packages?
