### ISSUE TITLE
excute cmd return 1 in some IOS sdk 

### ISSUE THREAD

**Issue by chenyangxx** [tanersener/mobile-ffmpeg#279]
Hi,  command is : 
-hide_banner -i /var/mobile/Containers/Data/Application/DB1ED5E3-1813-4E98-851A-26A3C076DFF9/Documents/BPOriginalVideos/292042509d73d1c269a21a709a404734_292042509d73d1c269a21a709a404734_IMG_5197.MP4 -i /var/mobile/Containers/Data/Application/DB1ED5E3-1813-4E98-851A-26A3C076DFF9/Library/Caches/bitmaps/29001/%d.png -itsoffset 0 -i /private/var/containers/Bundle/Application/5397A052-58BA-4E5F-8A31-B18399150BAD/bluepulse-caption-ios.app/gif_logo_12.gif -vcodec libx264 -filter_complex [0:v]scale=1080:-1,fps=30[bg];[2:v]scale=179:96[bg1];[bg][bg1]overlay=16:588:enable='between(t,0,12)'[bg2];[1:v]zoompan=s=1080x62:fps=30:d=0+'6*eq(in,0)'+'30*eq(in,1)'+'2*eq(in,2)'+'56*eq(in,3)'+'30*eq(in,4)'+'6*eq(in,5)'+'28*eq(in,6)'+'3*eq(in,7)'+'39*eq(in,8)'+'52*eq(in,9)'+'8*eq(in,10)'+'28*eq(in,11)'+'3*eq(in,12)'+'42*eq(in,13)'+'58*eq(in,14)'+'25*eq(in,15)'+'35*eq(in,16)'+'35*eq(in,17)'+'6*eq(in,18)'+'28*eq(in,19)'+'7*eq(in,20)'+'69*eq(in,21)'+'36*eq(in,22)'+'184*eq(in,23)'+'6*eq(in,24)'+'80*eq(in,25)'+'66*eq(in,26)'+'36*eq(in,27)'+'43*eq(in,28)'+'57*eq(in,29)'+'92*eq(in,30)'+'38*eq(in,31)'+'57*eq(in,32)'+'44*eq(in,33)'+'8*eq(in,34)'+'40*eq(in,35)'+'5*eq(in,36)'+'26*eq(in,37)'+'2*eq(in,38)'+'59*eq(in,39)'+'3*eq(in,40)'+'56*eq(in,41)'+'59*eq(in,42)'+'2*eq(in,43)'+'36*eq(in,44)'+'55*eq(in,45)'+'8*eq(in,46)'+'43*eq(in,47)'+'5*eq(in,48)'[bg3];[bg2][bg3]overlay=0:589.5027027027027 -pix_fmt yuv420p -crf 23 -preset superfast -vprofile baseline -c:a aac /var/mobile/Containers/Data/Application/DB1ED5E3-1813-4E98-851A-26A3C076DFF9/Documents/BPVideosIncludeSubtitles/19727/77521cd56035410d895e46de5c617455_1575189587.422726_292042509d73d1c269a21a709a404734_IMG_5197.MP4

error output: 

 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/mobile/Containers/Data/Application/DB1ED5E3-1813-4E98-851A-26A3C076DFF9/Documents/BPOriginalVideos/292042509d73d1c269a21a709a404734_292042509d73d1c269a21a709a404734_IMG_5197.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:58.07, start: 0.000000, bitrate: 8590 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p, 1110x720, 8520 kb/s, 30.29 fps, 60 tbr, 1000k tbn, 2000k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Input #1, image2, from '/var/mobile/Containers/Data/Application/DB1ED5E3-1813-4E98-851A-26A3C076DFF9/Library/Caches/bitmaps/29001/%d.png':
  Duration: 00:00:01.96, start: 0.000000, bitrate: N/A
    Stream #1:0: Video: png, rgba(pc), 3240x186 [SAR 8504:8504 DAR 540:31], 25 fps, 25 tbr, 25 tbn, 25 tbc
Input #2, gif, from '/private/var/containers/Bundle/Application/5397A052-58BA-4E5F-8A31-B18399150BAD/bluepulse-caption-ios.app/gif_logo_12.gif':
  Duration: 00:00:12.00, start: 0.000000, bitrate: 100 kb/s
    Stream #2:0: Video: gif, bgra, 580x310, 25 fps, 25 tbr, 100 tbn, 100 tbc
Stream mapping:
  Stream #0:0 (h264) -> scale (graph 0)
  Stream #1:0 (png) -> zoompan (graph 0)
  Stream #2:0 (gif) -> scale (graph 0)
  overlay (graph 0) -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
height not divisible by 2 (1080x701)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Qavg: 64508.441
2 frames left in the queue on closing

mobile-ffmpeg version:  4.2.2
iOS version: iOS11.1.3  iPhoneXs Max

**Comment by tanersener** [comment]
Execution fails with the following error. You need to fix that?
```
height not divisible by 2 (1080x701)
```

**Comment by chenyangxx** [comment]
> Execution fails with the following error. You need to fix that.
> 
> ```
> height not divisible by 2 (1080x701)
> ```

you are right, thans
