### ISSUE TITLE
How to improve the speed of video generation from pictures?

### ISSUE THREAD

**Issue by andyrenkehe** [tanersener/mobile-ffmpeg#282]
Mac Xcode IOS

In test-app MobileFFmpegTest, test video is generated from three pictures, such as VideoViewController.m. If three  pictures are replaced with larger picture(1~2M), it becomes very slow(about 30 ~ 40 seconds). How to improve the speed of video generation from pictures?

**Comment by tanersener** [comment]
There is not an easy answer for your question. I need to see your command to recommend something. Can you share your command please?

**Comment by andyrenkehe** [comment]
> There is not an easy answer for your question. I need to see your command to recommend something. Can you share your command please?

ffmpeg -loop 1 -t 3 -i picpng6.png -loop 1 -t 3 -i kfoaga514uyp.jpg -loop 1 -t 3 -i melfga50qm0v.jpg -loop 1 -t 3 -i io6zga50tr8b.jpg -loop 1 -t 3 -i gteiiz6o46uf.jpg -filter_complex "[0:v]scale=w='if(gte(iw/ih,410/723),min(iw,410),-1)':h='if(gte(iw/ih,410/723),-1,min(ih,723))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,pad=width=410:height=723:x=(410-iw)/2:y=(723-ih)/2:color=#00000000,fade=t=out:st=2:d=1[v0]; [1:v]scale=w='if(gte(iw/ih,410/723),min(iw,410),-1)':h='if(gte(iw/ih,410/723),-1,min(ih,723))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,pad=width=410:height=723:x=(410-iw)/2:y=(723-ih)/2:color=#00000000,fade=t=in:st=0:d=1,fade=t=out:st=2:d=1[v1]; [2:v]scale=w='if(gte(iw/ih,410/723),min(iw,410),-1)':h='if(gte(iw/ih,410/723),-1,min(ih,723))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,pad=width=410:height=723:x=(410-iw)/2:y=(723-ih)/2:color=#00000000,fade=t=in:st=0:d=1,fade=t=out:st=2:d=1[v2]; [3:v]scale=w='if(gte(iw/ih,410/723),min(iw,410),-1)':h='if(gte(iw/ih,410/723),-1,min(ih,723))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,pad=width=410:height=723:x=(410-iw)/2:y=(723-ih)/2:color=#00000000,fade=t=in:st=0:d=1,fade=t=out:st=2:d=1[v3]; [4:v]scale=w='if(gte(iw/ih,410/723),min(iw,410),-1)':h='if(gte(iw/ih,410/723),-1,min(ih,723))',scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=sar=1/1,pad=width=410:height=723:x=(410-iw)/2:y=(723-ih)/2:color=#00000000,fade=t=in:st=0:d=1,fade=t=out:st=2:d=1[v4];[v0][v1][v2][v3][v4]concat=n=5:v=1:a=0,format=yuv420p[v]" -map [v] -c:v libx264 -r 30 -y out1.mp4

**Comment by tanersener** [comment]
Did you try using another video codec? On some cases `mpeg4` is faster than `x264`. For `x264` you can try setting `-preset ultrafast` as well.

**Comment by andyrenkehe** [comment]
> Did you try using another video codec? On some cases `mpeg4` is faster than `x264`. For `x264` you can try setting `-preset ultrafast` as well.

I tried it and it didn't speed up significantly.Is this due to iPhone performance limitations?Running the same code on mac is fast

**Comment by tanersener** [comment]
> I tried it and it didn't speed up significantly.Is this due to iPhone performance limitations?Running the same code on mac is fast

Yes. Unfortunately, mobile CPUs are slower than desktop/laptop CPUs.

**Comment by andyrenkehe** [comment]
> > I tried it and it didn't speed up significantly.Is this due to iPhone performance limitations?Running the same code on mac is fast
> 
> Yes. Unfortunately, mobile CPUs are slower than desktop/laptop CPUs.

OK.Thank you!
