### ISSUE TITLE
preview of command 

### ISSUE THREAD

**Issue by makani20** [tanersener/mobile-ffmpeg#285]
**Description**
i want to know preview of command at same time of button click
e.g. ffmpeg -i 1.mp4 -vf "transpose=1" output.mp4

i am using this command for rotate video but its taking time for processing , i dont want to output at this moment, just want to show preview of command.

please help me with this trim command to show preview, i will generate output later as per user want.

**Comment by tanersener** [comment]
You can extract an image from your video file and apply the video filter to only that image. It will be faster.

**Comment by makani20** [comment]
i want to show preview (desire output) of command before ffmpeg execute command output, if ffmpeg start to generate output it will start processing and that i don't want, i want without out i want to show preview of command looks like this.

**Comment by tanersener** [comment]
So, you want to generate a preview without using `ffmpeg`, right? 

I don't know how to do that. I can only help about using this library.

**Comment by makani20** [comment]
ffplay is for preview but what i can do in mobile ffmpeg, there is no way to build ffplay  ?please suggest me how i can use in mobile ffmpeg iOS?

**Comment by tanersener** [comment]
> ffplay is for preview but what i can do in mobile ffmpeg, there is no way to build ffplay ?

`mobile-ffmpeg` does not include `ffplay` and it is not possible to build it easily. I'm working on it but I don't have a release date for that right now.

> please suggest me how i can use in mobile ffmpeg iOS?

I posted my recommendation about generating a preview using `mobile-ffmpeg` in my previous post. Other than that I don't have any recommendations. If you're not happy with the solution feel free to ask this question at [stackoverflow](https://stackoverflow.com).
