### ISSUE TITLE
problem building ffmpeg for android with openh264

### ISSUE THREAD

**Issue by qbasso** [tanersener/mobile-ffmpeg#288]
**Description**
building ffmpeg for android with `./android.sh --enable-openh264` fails

**Expected behavior**
successfully building .aar

**Current behavior**
build fails with message `ERROR: openh264 not found using pkg-config` after sucessfully prebuilding openh264

**Logs**
build.log - https://ghostbin.co/paste/upcpz
config.log - https://ghostbin.co/paste/bn3ng

**Environment**
 - Platform: Android
 - Architecture: arm-v7a-neon
 - Source branch: master
 - Android NDK version: 21.0.6011959
- system: MacOS Catalina

**Comment by tanersener** [comment]
Can you try rebuilding `openh264` with `--rebuild-openh264` option?

**Comment by qbasso** [comment]
Doesn't seem to change output result. Called `./android.sh --enable-openh264 --rebuild-openh264` in `mobile-ffmpeg` cloned dir. 
Here is build output. Would appreciate any hint.
https://ghostbin.co/paste/yje26

**Comment by tanersener** [comment]
`master` is tested with the latest stable `NDK` release which is `r20b`. But you are using `v21.0.6011959-beta2`. This version generates the following errors on your build.

`Android NDK: APP_STL stlport_shared is no longer supported. Please switch to either c++_static or c++_shared`

Are there any specific reasons for not using the `r20b`?

**Comment by qbasso** [comment]
@tanersener i downgraded NDK and uninstalled ffmpeg i had installed locally + all its dependencies. Afterwards i was able to build it. Sorry for the fuss and thanks for your help
