### ISSUE TITLE
Expose libavutil Error.h values to Swift

### ISSUE THREAD

**Issue by mjarvis** [tanersener/mobile-ffmpeg#289]
**Description**
`libavutil` `Error.h` has a number of `#define` macros which convert error codes for comparison, such as `AVERROR(e)`, and a number of actual error codes such as `AVERROR_EOF`

**Expected behavior**
I would like for those error macros to be translated in some way such that they are available to Swift users.

**Current behavior**
The error conversion / comparison defines are not available in Swift. (Since function-style c macros are not accessible)

**Screenshots**
n/a

**Logs**
n/a

**Environment**
 - Platform: iOS
 - Architecture: any
 - Version: 4.3
 - Source branch: n/a
 - Xcode version: 11.1
 - Cocoapods version: 1.8.3
 - Android Studio version: n/a
 - Android NDK version: n/a

**Other**
I will be integrating a c/objc file into my project that exposes the macros to swift, but this feels like something that might be useful to have in `mobile-ffmpeg` itself.
If so, and if there is a preferred way of exposing these values please provide an example and I can fill in the rest and attempt to submit a PR.

**Comment by mjarvis** [comment]
Here is an example `.h` file which starts to implement the above:
```c
#import <Foundation/Foundation.h>
#import <libavutil/error.h>

#if EDOM > 0

NS_INLINE __attribute__((swift_name("AVERROR(_:)"))) int _AVERROR(int errnum) {
    return AVERROR(errnum);
}

NS_INLINE __attribute__((swift_name("AVUNERROR(_:)"))) int _AVUNERROR(int errnum) {
    return AVUNERROR(errnum);
}

#else

NS_INLINE __attribute__((swift_name("AVERROR(_:)"))) int _AVERROR(int errnum) {
    return errnum;
}

NS_INLINE __attribute__((swift_name("AVUNERROR(_:)"))) int _AVUNERROR(int errnum) {
    return errnum;
}

#endif

// These two below I'm not sure about... It means in swift one has to do `AVERROR_BSF_NOT_FOUND()` instead of `AVERROR_BSF_NOT_FOUND`
NS_INLINE __attribute__((swift_name("AVERROR_BSF_NOT_FOUND()"))) int _AVERROR_BSF_NOT_FOUND(void) {
    return AVERROR_BSF_NOT_FOUND;
}

NS_INLINE __attribute__((swift_name("AVERROR_EOF()"))) int _AVERROR_EOF(void) {
    return AVERROR_EOF;
}
```

I'd be happy to get some feedback on if this seems like a good way to expose these values, or if there are some changes I should make.

**Comment by tanersener** [comment]
Thanks for posting this issue and also for your pull request. 

I do understand what you want to have, but this library is still an `Objective C` library and my knowledge about `Swift` is limited. I can't recommend any solutions about your issue. Also I can't accept your pull request because I can't test it wight now.

Do you have any suggestions for me?

**Comment by mjarvis** [comment]
At the moment my suggestion is to somewhat ignore this issue & PR.
I suspect the need for this is quite low. It may be best such that once I have a confirmed working example for this that I push the code, and we simply close the issue & PR, leaving it for people who need it to search for & import into their codebases as necessary, rather than actually include it in the core library.

**Comment by tanersener** [comment]
okay then, thanks

**Comment by mjarvis** [comment]
Closing as per above description. Code at https://github.com/tanersener/mobile-ffmpeg/pull/290 works as intended if someone needs to include it in their own project.
