### ISSUE TITLE
Spaces in input files

### ISSUE THREAD

**Issue by fayte0618** [tanersener/mobile-ffmpeg#29]
Hi! I just want to ask since i noticed the string command dont accept double quotes or single quotes on input files? how do I add them since some of my filenames have spaces. Or is there an alternative way to escape spaces in filenames on input files? Thanks

**Comment by tanersener** [comment]
You are right, `execute` method accepts a single string and splits it using spaces. 

There is an overloaded `execute` method with array input in Android and an `executeWithArray` method for IOS which accepts NSArray. You can build your command yourself, deciding where to split your command use one of these methods depending on your platform.

**Comment by tanersener** [comment]
@fayte0618 do you still need help, can we close this issue?

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you need help.
