### ISSUE TITLE
IOS Unrecognized option \'f\'.\n

### ISSUE THREAD

**Issue by corifilemanagermobileapp** [tanersener/mobile-ffmpeg#292]
**Description**
Try to download m3u8 video from server.
make command: `MobileFFmpeg.execute("-i link_to.m3u8 -c copy output.mp4")`

**Expected behavior**
should save video to output.mp4

**Current behavior**
errors:
"Unrecognized option \'c\'.\n"
"Error splitting the argument list: "
"Option not found\n"

**Logs**
"ffmpeg version v4.3-dev-1181"
" Copyright (c) 2000-2019 the FFmpeg developers"
"\n"
"  built with Apple clang version 11.0.0 (clang-1100.0.33.8)\n"
"  configuration: --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-arm64-apple-darwin/ffmpeg --enable-version3 --arch=aarch64 --cpu=armv8 --target-os=darwin --ar=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=clang --cxx=clang++ --as=\'/Users/taner/Projects/mobile-ffmpeg/.tmp/gas-preprocessor.pl -arch aarch64 -- clang -arch arm64 -target aarch64-ios-darwin -march=armv8-a+crc+crypto -mcpu=generic -DMOBILE_FFMPEG_ARM64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -fembed-bitcode -DIOS -DMOBILE_FFMPEG_BUILD_DATE=20191026 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk -Oz -miphoneos-version-min=12.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/include\' --ranlib=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib --strip=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --enable-neon --enable-cross-compile --enable-pic --enable-asm --enable-inline-asm --enable-optimizations --enable-swscale --enable-static --disable-shared --enable-small --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --disable-openssl --disable-xmm-clobber-test --disable-debug --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libkvazaar --enable-libsnappy --enable-libaom --disable-sdl2 --enable-zlib --enable-audiotoolbox --enable-coreimage --enable-bzlib --enable-videotoolbox --enable-avfoundation\n"
"  libavutil      56. 35.101 / 56. 35.101\n"
"  libavcodec     58. 59.102 / 58. 59.102\n"
"  libavformat    58. 33.100 / 58. 33.100\n"
"  libavdevice    58.  9.100 / 58.  9.100\n"
"  libavfilter     7. 65.100 /  7. 65.100\n"
"  libswscale      5.  6.100 /  5.  6.100\n"
"  libswresample   3.  6.100 /  3.  6.100\n"
"Unrecognized option \'c\'.\n"
"Error splitting the argument list: "
"Option not found\n"
""

**Environment**
 - Platform: IOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version 4.3
 - Xcode version 11.3
 - Cocoapods version 4.3

**Comment by tanersener** [comment]
Can you share the name `mobile-ffmpeg` package  and `m3u8` file you are using ?

**Comment by corifilemanagermobileapp** [comment]
i found a problem, it was because i didn't use enabled gpl libraries
