### ISSUE TITLE
Crashes App When processing a large number of video files

### ISSUE THREAD

**Issue by RowlandOti** [tanersener/mobile-ffmpeg#293]
**Description**
App crashes when processing a large batch of files

**Expected behavior**
Parse the content from media, without crashing

**Current behavior**
App crashes after some time of work

**Screenshots**
No screenshots, as service runs in the background, as a foreground service

**Logs**
> `Thread[3,tid=9260,WaitingInMainSignalCatcherLoop,Thread*=0xdf098200,peer=0x32c0c310,"Signal Catcher"]: reacting to signal 3`

More information pulled using ` adb pull /data/anr/traces.txt
` can be found at https://drive.google.com/file/d/1vTdZrU7-I77tUMDdI1WH22l6vAlxcQz9/view?usp=sharing

**Environment**
-  Version of library -    'com.arthenica:mobile-ffmpeg-full:4.3'
 - Platform is Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, armv7, armv7s, arm64]

**Comment by tanersener** [comment]
Can you please share more details about this issue? I can't understand/test/reproduce this issue using information provided in your post?

**Comment by RowlandOti** [comment]
I updated the missing information, also the code: in a while loop based on a Cursor with about 200 rows, I am running the code :

```java
try {
                        val info = FFmpeg.getMediaInformation(FileUtil.convertMediaUriToPath(currentUri))

                        val metaDataInfo = MetaDataStore()
                        metaDataInfo.fromMetaDataMap(info.metadataEntries)


                        currentSynopsis = metaDataInfo.comment!!
                        currentAlbum = metaDataInfo.album!!
                        currentAlbumArtist = metaDataInfo.artist!!
                        currentGenre = metaDataInfo.genre!!
                        currentComposer = metaDataInfo.composer!!
                        currentTrack = metaDataInfo.track!!

                        Timber.d("%s%s", currentDisplayName, currentTitle)
                    } catch (e: Exception) {
                        Timber.e(e)
                        Timber.e("%s%s", currentDisplayName, currentTitle)
                    }

```

200 times, as I extract the metadata from each and every one of the files retrieved from the MediaProvider.

**Comment by tanersener** [comment]
Thanks. Is it possible to share your `logcat` output too? I want to see what you have before `Thread[3,tid=9260,WaitingInMainSignalCatcherLoop,Thread*=0xdf098200,peer=0x32c0c310,"Signal Catcher"]: reacting to signal 3` error message.

**Comment by RowlandOti** [comment]
I can no longer reproduce the stacktrace, after reducing the size of the Cursor by processing it in batches.  It seems to occur when I have a large no. of items to process.  I suspect it could be due to a memory limit or OOM, but I can't know just yet. Will update, if I can gather more information, hence can close issue for now.
