### ISSUE TITLE
May I know how to convert to amr_wb of amr format ?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#296]
Hi Taner,
I found I can only convert to amr_nb of amr format, may I know what's the command to convert to amr_wb of amr?
Thanks.

**Comment by tanersener** [comment]
Can you check `Audio` tab under the test-application?

**Comment by suncj518** [comment]
Hi Taner,
Yes, checked.
The test-application used 
-ar 8000 -ab 12.2k -c:a libopencore_amrnb
When I use 
-ar 16000 -ab 20.2k -c:a libopencore_amrwb
Error happened.
May I know to make libopencore_amrwb worked ?

Thanks.

**Comment by tanersener** [comment]
`opencore-amr` library is included in `audio`, `full` and `full-gpl` packages. Are using one of them?

**Comment by suncj518** [comment]
I use full-gpl,  ar 8000 -ab 12.2k -c:a libopencore_amrnb   can work.  
but -ar 16000 -ab 20.2k -c:a libopencore_amrwb  can not work.
not sure why.

**Comment by tanersener** [comment]
console output ?
