### ISSUE TITLE
how to use custom command

### ISSUE THREAD

**Issue by mansiJspaceo** [tanersener/mobile-ffmpeg#300]
how to add custom command of ffmpeg.
run it using this library

**Comment by tanersener** [comment]
I don't understand your question. What is a non-custom command? All commands are already custom.

**Comment by mansiJspaceo** [comment]
can you please describe what is pipe- Image. how can i use images path instead of pipe.

**Comment by tanersener** [comment]
I'm sorry but I don't understand your question. I don't know what is a "pipe- Image"? Examples in README already uses file paths.
