### ISSUE TITLE
Is there any possible to use ffmpeg library to make custom objective-c library?

### ISSUE THREAD

**Issue by golditmobile** [tanersener/mobile-ffmpeg#303]
**Description**
I am building custom library which record video using ffmpeg library.

**Expected behavior**
I am planning to use this library in Swift project.

**Current behavior**
When I generate framework, there are no ffmpeg headers in Headers directory.

**Project Source code**
https://www.dropbox.com/s/6w4frjl9nq1bcac/videoframerefios.zip?dl=0

**Comment by tanersener** [comment]
`ffmpeg` headers are included inside `ffmpeg` frameworks. Did you take a look at `libavcodec.framework`, `libavdevice.framework`, `libavfilter.framework`, `libavformat.framework` and `libavutil.framework`?

**Comment by golditmobile** [comment]
Hello @tanersener 
Thanks for your reply.
Where can I find `libavcodec.framework`, `libavdevice.framework`, `libavfilter.framework`, `libavformat.framework` and `libavutil.framework`?

**Comment by tanersener** [comment]
If you are using `mobile-ffmpeg` using `Cocoapods`, you can find ffmpeg frameworks under the `Pods/mobile-ffmpeg-<package name>` folder.

If you are building `mobile-ffmpeg` yourself, ffmpeg frameworks are created under the `prebuild/ios-framework` folder.
