### ISSUE TITLE
hope include opencv and openssl as an library

### ISSUE THREAD

**Issue by xiedeacc** [tanersener/mobile-ffmpeg#304]
hope include opencv and openssl as an library
hope include opencv and openssl as an library
hope include opencv and openssl as an library

**Comment by tanersener** [comment]
Current `openssl` license is not compatible with LGPL/GPL. So `openssl` won't be included until `v3.0` is released. `openssl v3.0` will have Apache License 2.0 and be compatible with LGPL/GPL.

**Comment by tanersener** [comment]
I don't have an idea about `opencv`. I need to take a look at it first.

**Comment by xiedeacc** [comment]
thanks a lot
