### ISSUE TITLE
./android.sh --full failed build fribidi

### ISSUE THREAD

**Issue by xiedeacc** [tanersener/mobile-ffmpeg#305]
./android.sh --full

Building mobile-ffmpeg library for Android

Architectures: arm-v7a-neon, arm64-v8a, x86, x86-64
Libraries: android-zlib, android-media-codec, fontconfig, freetype, fribidi, gmp, gnutls, lame, libass, libiconv, libtheora, libvorbis, libvpx, libwebp, libxml2, opencore-amr, shine, speex, wavpack, kvazaar, libilbc, opus, snappy, soxr, libaom, chromaprint, twolame, sdl, tesseract, openh264

Building arm-v7a-neon platform on API level 24

fribidi: failed

**Comment by xiedeacc** [comment]
tag 4.3

**Comment by tanersener** [comment]
Please see [Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) wiki page to understand the reason of the failure.

**Comment by xiedeacc** [comment]
/root/mobile-ffmpeg/src/fribidi/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:441: recipe for target 'aclocal.m4' failed

**Comment by xiedeacc** [comment]
> Please see [Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) wiki page to understand the reason of the failure.

it seems cannot found aclocal，but I have an aclocal in /usr/bin/

**Comment by xiedeacc** [comment]
aclocal version was aclocal (GNU automake) 1.15.1

**Comment by xiedeacc** [comment]
after install Automake 1.16.1 this problem fix，maybe you can update prequisition

**Comment by tanersener** [comment]
[Reconf option](https://github.com/tanersener/mobile-ffmpeg/wiki/Reconf-Option) is implemented to overcome `automake` version conflicts.
