### ISSUE TITLE
./android.sh --full --enable-gpl  v4.2.2.LTS expat:faild

### ISSUE THREAD

**Issue by xiedeacc** [tanersener/mobile-ffmpeg#306]
as title

**Comment by xiedeacc** [comment]
ndk r20

**Comment by tanersener** [comment]
Please see [Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) wiki page to understand the reason of the failure.

**Comment by xiedeacc** [comment]
after upgrade automake to 1.16.1，this problem fixed
