### ISSUE TITLE
libvorbis never succed

### ISSUE THREAD

**Issue by xiedeacc** [tanersener/mobile-ffmpeg#307]
Building mobile-ffmpeg library for Android

Architectures: arm-v7a-neon, arm64-v8a, x86, x86-64
Libraries: android-zlib, android-media-codec, fontconfig, freetype, fribidi, gmp, gnutls, lame, libass, libiconv, libtheora, libvorbis, libvpx, libwebp, libxml2, opencore-amr, shine, speex, wavpack, kvazaar, libilbc, opus, snappy, soxr, libaom, chromaprint, twolame, sdl, tesseract, openh264

Building arm-v7a-neon platform on API level 21

fribidi: ok
gmp: ok
libiconv: ok
libvpx: ok
libxml2: ok
opencore-amr: ok
shine: ok
speex: ok
wavpack: ok
kvazaar: ok
libilbc: ok
opus: ok
snappy: ok
soxr: ok
libaom: ok
chromaprint: ok
sdl: ok
openh264: ok
giflib: ok
jpeg: ok
libogg: ok
libpng: ok
libuuid: ok
nettle: ok
tiff: ok
expat: ok
libsndfile: ok
freetype: ok
gnutls: ok
lame: ok
libvorbis: failed

log
make[3]: Entering directory '/root/mobile-ffmpeg/src/libvorbis/lib'
  CC       test_sharedbook-sharedbook.o
  CC       smallft.lo
  CC       mdct.lo
  CC       block.lo
sharedbook.c:21:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
Makefile:655: recipe for target 'test_sharedbook-sharedbook.o' failed
make[3]: *** [test_sharedbook-sharedbook.o] Error 1
make[3]: *** Waiting for unfinished jobs....
block.c:23:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
In file included from smallft.c:33:
In file included from ./smallft.h:20:
../include/vorbis/codec.h:25:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
Makefile:648: recipe for target 'block.lo' failed
make[3]: *** [block.lo] Error 1
1 error generated.
In file included from mdct.c:43:
../include/vorbis/codec.h:25:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
Makefile:648: recipe for target 'smallft.lo' failed
make[3]: *** [smallft.lo] Error 1
1 error generated.
Makefile:648: recipe for target 'mdct.lo' failed
make[3]: *** [mdct.lo] Error 1
make[3]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis/lib'
Makefile:681: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis/lib'
Makefile:535: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132)

**Comment by xiedeacc** [comment]
sharedbook.c:21:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
Makefile:655: recipe for target 'test_sharedbook-sharedbook.o' failed
make[3]: *** [test_sharedbook-sharedbook.o] Error 1
make[3]: *** Waiting for unfinished jobs....
block.c:23:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
In file included from smallft.c:33:
In file included from ./smallft.h:20:
../include/vorbis/codec.h:25:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
Makefile:648: recipe for target 'block.lo' failed
make[3]: *** [block.lo] Error 1
1 error generated.
In file included from mdct.c:43:
../include/vorbis/codec.h:25:10: fatal error: 'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
Makefile:648: recipe for target 'smallft.lo' failed
make[3]: *** [smallft.lo] Error 1
1 error generated.
Makefile:648: recipe for target 'mdct.lo' failed
make[3]: *** [mdct.lo] Error 1
make[3]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis/lib'
Makefile:681: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis/lib'
Makefile:535: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mobile-ffmpeg/src/libvorbis'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xiedeacc** [comment]
> Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132)

filled the issue template

**Comment by xiedeacc** [comment]
> Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132)

shouled I compile ogg in ubuntu ? or mobile-ffmpeg should compile ogg as an lib for libvorbis?

**Comment by xiedeacc** [comment]
I found libogg compile in mobile-ffmpeg/prebuilt/android-arm/libogg/

**Comment by tanersener** [comment]
Can you apply instructions given in this [comment](https://github.com/tanersener/mobile-ffmpeg/issues/41#issuecomment-437318031) ?

**Comment by xiedeacc** [comment]
I inspect  android-libvorbis.sh found,
--with-ogg-includes=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/include \
 --with-ogg-libraries=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/lib \
there exists ogg include and lib files in that spefic folder.

**Comment by xiedeacc** [comment]
#!/bin/bash
export ANDROID_HOME=/usr/local/Sdk
export ANDROID_NDK_ROOT=/usr/local/android-ndk-r20
export http_proxy=http://proxy.tencent.com:8080
export https_proxy=http://proxy.tencent.com:8080
export ftp_proxy=http://proxy.tencent.com:8080
bash ./android.sh \
    --enable-gpl   \
    --enable-android-media-codec \
    --enable-android-zlib \
    --enable-chromaprint \
    --enable-fontconfig \
    --enable-freetype \
    --enable-fribidi \
    --enable-gmp \
    --enable-gnutls \
    --enable-kvazaar \
    --enable-lame \
    --enable-libaom \
    --enable-libass \
    --enable-libiconv \
    --enable-libilbc \
    --enable-libtheora \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libxml2 \
    --enable-opencore-amr \
    --enable-openh264 \
    --enable-opus \
    --enable-sdl \
    --enable-shine \
    --enable-snappy \
    --enable-soxr \
    --enable-speex \
    --enable-tesseract \
    --enable-twolame \
    --enable-wavpack \
    --enable-libvidstab \
    --enable-x264 \
    --enable-x265 \
    --enable-xvidcore \
    --enable-libvorbis \

**Comment by xiedeacc** [comment]
env

INFO: Building libvorbis with the following environment variables

LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.244.1 62574 192.168.244.128 22
ARCH=arm-v7a-neon
ANDROID_HOME=/usr/local/Sdk
LANG=en_US.UTF-8
TOOLCHAIN=linux-x86_64
LESS=-R
DISPLAY=localhost:10.0
BASEDIR=/root/mobile-ffmpeg
OLDPWD=/root/mobile-ffmpeg/prebuilt
ORIGINAL_API=24
JAVA_HOME=/usr/local/jdk1.8.0_211
CFLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=softfp -DMOBILE_FFMPEG_ARM_V7A_NEON -std=c99 -Wno-unused-function -fno-integrated-as -fstrict-aliasing -fPIC -DANDROID -D__ANDROID__ -D__ANDROID_API__=24 -Os -ffunction-sections -fdata-sections  -I/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include
ZSH=/root/.oh-my-zsh
CLASSPATH=.:/usr/local/jdk1.8.0_211/lib:/usr/local/jdk1.8.0_211/jre/lib
CC=armv7a-linux-androideabi24-clang
XDG_SESSION_ID=1
USER=root
CXXFLAGS=-std=c++11 -fno-exceptions -fno-rtti -Os -ffunction-sections -fdata-sections
PAGER=less
LSCOLORS=Gxfxcxdxbxegedabagacad
STRIP=arm-linux-androideabi-strip
GOPATH=/root/src/go
PWD=/root/mobile-ffmpeg
HOME=/root
GOROOT=/usr/local/go
LC_CTYPE=en_US.UTF-8
SSH_CLIENT=192.168.244.1 62574 22
ANDROID_NDK_ROOT=/usr/local/android-ndk-r20
SED_INLINE=sed -i
https_proxy=http://proxy.tencent.com:8080
RANLIB=arm-linux-androideabi-ranlib
AS=arm-linux-androideabi-as
AR=arm-linux-androideabi-ar
http_proxy=http://proxy.tencent.com:8080
SSH_TTY=/dev/pts/0
NO_PROXY=git.code.oa.com
MAIL=/var/mail/root
CXX=armv7a-linux-androideabi24-clang++
SHELL=/usr/bin/zsh
TERM=xterm
ZLIB_PACKAGE_CONFIG_PATH=/root/mobile-ffmpeg/prebuilt/android-arm/pkgconfig/zlib.pc
API=24
SHLVL=3
TOOLCHAIN_ARCH=arm
LOGNAME=root
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
XDG_RUNTIME_DIR=/run/user/0
LDFLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=softfp -Wl,--fix-cortex-a8 -Wl,--gc-sections,--icf=safe -Os -ffunction-sections -fdata-sections -lc -lm -ldl -llog -L/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/arm-linux-androideabi/lib -L/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/24 -L/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib -Wl,--hash-style=both -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libunwind.a
MOBILE_FFMPEG_TMPDIR=/root/mobile-ffmpeg/.tmp
JRE_HOME=/usr/local/jdk1.8.0_211/jre
INSTALL_PKG_CONFIG_DIR=/root/mobile-ffmpeg/prebuilt/android-arm/pkgconfig
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/root/src/go/bin:/usr/local/jdk1.8.0_211/bin:/root/.ft:/usr/local/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin
ftp_proxy=http://proxy.tencent.com:8080
LD=arm-linux-androideabi-ld
_=/usr/bin/env
----------------------------------------------------------------

INFO: System information

INFO: Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tanersener** [comment]
> I inspect android-libvorbis.sh found,
> --with-ogg-includes=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/include
> --with-ogg-libraries=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/lib
> there exists ogg include and lib files in that spefic folder.

Is this a question?

Did you try instructions given in the comment I've posted?

**Comment by xiedeacc** [comment]
after apt remove libogg-dev, succed, but configue has already spefic that --with-ogg-includes --with-ogg-libraries???

**Comment by tanersener** [comment]
> Building mobile-ffmpeg library for Android
> 
> Architectures: arm-v7a-neon, arm64-v8a, x86, x86-64
> Libraries: android-zlib, android-media-codec, fontconfig, freetype, fribidi, gmp, gnutls, lame, libass, libiconv, libtheora, libvorbis, libvpx, libwebp, libxml2, opencore-amr, shine, speex, wavpack, kvazaar, libilbc, opus, snappy, soxr, libaom, chromaprint, twolame, sdl, tesseract, openh264
> 
> Building arm-v7a-neon platform on API level 21
> 
> ...
> libogg: ok
> ...
> libvorbis: failed

As you can see from your console output, `mobile-ffmpeg` already includes inside `libogg` inside and builds it before `libvorbis`. `--with-ogg-includes` and `--with-ogg-libraries` flags inside `libvorbis` build scripts are used to specify the paths of `libogg` version that comes with `mobile-ffmpeg`. But if `libogg-dev` package installed on your machine, then `make` uses the version that is installed by `libogg-dev` rather than the version that comes with `mobile-ffmpeg`. That is the reason of this issue. I re-pushed the fix about it on the development branch. It will be included in the next release.
