### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by ankitsiliconithub** [tanersener/mobile-ffmpeg#31]
I'm following steps given in 

https://github.com/tanersener/mobile-ffmpeg/wiki/Using-IOS-Universal-Binaries

but with 'mobile-ffmpeg-min-gpl-2.1.1-ios-shared-universal'

and app crashing at launch saying : 

dyld: Library not loaded: @rpath/libavcodec.dylib
  Referenced from: /Users/SANAL/Library/Developer/CoreSimulator/Devices/7653659F-C64F-465C-81EA-FB7845EA8F86/data/Containers/Bundle/Application/58341C2F-9F8E-4807-9B66-D148FE01AD6C/FFMpegDemo.app/FFMpegDemo
  Reason: no suitable image found.  Did find:
	/Users/SANAL/Library/Developer/CoreSimulator/Devices/7653659F-C64F-465C-81EA-FB7845EA8F86/data/Containers/Bundle/Application/58341C2F-9F8E-4807-9B66-D148FE01AD6C/FFMpegDemo.app/Frameworks/libavcodec.dylib: mach-o, but not built for iOS simulator

while it is working perfectly with 'mobile-ffmpeg-universal' !!

Hoping for quick solution , 

Best regards

**Comment by tanersener** [comment]
Hi, 

Unfortunately my IOS test environment has some problems and I am unable to test binaries right now. But we can find a solution if I you help me. Could you please run `otool -L libavcodec.dylib` with full path of `libavcodec.dylib` and share output with me? 

> while it is working perfectly with 'mobile-ffmpeg-universal' !!

Additionally, which version do you mean by `mobile-ffmpeg-universal`, do you mean static binaries?

**Comment by ankitsiliconithub** [comment]
/Users/SANAL/Downloads/mobile-ffmpeg-min-gpl-2.1.1-shared-universal/lib/libavcodec.dylib:
	@rpath/libavcodec.dylib (compatibility version 58.0.0, current version 58.18.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	@rpath/libswresample.dylib (compatibility version 3.0.0, current version 3.1.100)
	@rpath/libavutil.dylib (compatibility version 56.0.0, current version 56.14.100)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1556.0.0)
	/System/Library/Frameworks/CoreVideo.framework/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/CoreMedia.framework/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++abi.dylib (compatibility version 1.0.0, current version 400.17.0)

**Comment by tanersener** [comment]
Thanks, according to this output, library paths are valid. It looks like something is wrong with the project settings. Also, which is version do you mean by `mobile-ffmpeg-universal`?

**Comment by ankitsiliconithub** [comment]
I followed steps from 

https://github.com/tanersener/mobile-ffmpeg/wiki/Using-IOS-Universal-Binaries

and mobile-ffmpeg-universal is at : 

https://we.tl/t-47fijobpDS

which was provided by you

**Comment by tanersener** [comment]
Hi @ankitsiliconithub, my test environment is back and I am able to perform tests with universal binaries. 

What I see is; `mobile-ffmpeg-min-gpl-2.1.1-ios-shared-universal` binaries work on `Xcode 10` but produce the following errors on `Xcode 9.x`. Do you have these errors during linking?

```
ld: warning: URGENT: building for iOS simulator, but linking against dylib (/Users/taner/Projects/mobile-ffmpeg/ios/test-app/mobile-ffmpeg-min-gpl-2.1.1-shared-universal/lib/libavdevice.dylib) built for (unknown). Note: This will be an error in the future.
```

**Comment by tanersener** [comment]
Hi @ankitsiliconithub. Shared universal binaries of [v2.1.1 release](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v2.1.1.universal) are updated. Could you please try using new binaries?

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you still need help about it.
