### ISSUE TITLE
Support for Xamarin Forms IOS?

### ISSUE THREAD

**Issue by periman2** [tanersener/mobile-ffmpeg#310]
**Description**

Firstly I'd like to thank you for this amazing all in one repo!

I'm trying to import the iOS version for the ffmpeg into a xamarin forms project. To do this I need to create bindings for the library, at least for the parts of the library that I need which are encoding and video stabilization.

To give a better example I'd like to do the same that this repository did for nativescript ios but for xamarin ios instead: https://github.com/triniwiz/nativescript-ffmpeg

I haven't found a way to do that yet. Are there any plans to support this in the future or at least give me a hint as to what to do ? 

**Expected behavior**

**Current behavior**
Not supported yet.

**Screenshots**

**Logs**

**Environment**
 -  Xamarin IOS

**Comment by tanersener** [comment]
I don't plan to support Xamarin Forms. I don't have any knowledge about it. 

Well, I'd like to help about creating bindings but because of the same reason I can't do it. I'm not familiar with Xamarin Forms. Though I can help if someone tries.

**Comment by periman2** [comment]
@tanersener  Thank you for the quick answer. I understand. I will try my best to do it and let you know if I manage to make it happen.

**Comment by dczaretsky** [comment]
Any updates on this? Would be great to have support for Xamarin.Forms

**Comment by Hackmodford** [comment]
@periman2 Wouldn't you want to bind C# to ffmpeg instead of to the iOS version of this?

**Comment by TingtingAn** [comment]
good point
