### ISSUE TITLE
FFmpeg command is executed and there is no response

### ISSUE THREAD

**Issue by leafyesy** [tanersener/mobile-ffmpeg#311]
phone:LG-H848
Android:6.0.1
excute cmd:
"-y -i " + sourcePath + " -vcodec copy -acodec copy -vbsf h264_mp4toannexb "+ dstPath

When performing the "Loading mobile-ffmpeg".no more log.

**Comment by tanersener** [comment]
Please see [Always fill the issue template](https://github.com/tanersener/mobile-ffmpeg/issues/132)
