### ISSUE TITLE
Read the Embedded Artwork Given the Uri of a Video File

### ISSUE THREAD

**Issue by RowlandOti** [tanersener/mobile-ffmpeg#312]
**Description**
How can I be able to read the embedded artwork for a video file?

**Expected behavior**
Have a command I can use to extract the Bitmap, and display it in android, via image.

**Current behavior**
Can't seem to see how in the wiki or sample codes

**Logs**
N/A

**Environment**
 - Platform: is Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]

**Comment by tanersener** [comment]
Well, I don't have any idea about it. How about asking this question to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list.

**Comment by RowlandOti** [comment]
This library here : https://github.com/andyfuturex/FFmpegMediaMetadataRetriever/blob/master/gradle/fmmr-library/library/src/main/jni/metadata/mediametadataretriever.cpp#L79 does something similar and it also uses ffmpeg behind the scenes. Can something similar be implemented here?

**Comment by tanersener** [comment]
Technically it is possible. But I don't provide that kind of methods in this project. Feel free to clone the library and implement it yourself.

Besides, there are some threads at stackoverflow like [this one](https://stackoverflow.com/questions/13592709/retrieve-album-art-using-ffmpeg) in which several commands are given in answers to retrieve album data. You may try running these commands with this library. I'm not sure if they are exactly what you want but testing these commands would be faster for you.

**Comment by RowlandOti** [comment]
Surely, it will be really fair if we have it as a Byte or list of Bytes in the `MediaInformation` class. Besides, the command that works is something along the lines of :

```java
ffmpeg -i video.mp4 -map 0:v -map -0:V -c copy cover.jpg
```

I am not sure of how to proceed in order to implement it within this library such that, it is a field in `MediaInformation`, which I can read on demand.  Please guide.

**Comment by tanersener** [comment]
I understand what you want but this is beyond the scope of this library. I'm just trying replicate `ffmpeg` functionality on mobile platforms. You want me to build a helper function to extract streams inside a file. Please remember that there is no limit in helper functions that can be built on top of `ffmpeg`.  I don't want to do that in this project.

In you case, why don't you read the `cover.jpg` file using `java.io` package classes?

**Comment by RowlandOti** [comment]
Okay, I will have to extend the project myself on a separate branch.  I see helper functions for extracting the other streams in your project i. video. audio, data. What would be the cover art stream? Would you be kind enough to advise on how I can read them and convert to an input stream, rather than to a jpeg/png file?  Do I have to convert the binary data to a file first?

**Comment by tanersener** [comment]
> I see helper functions for extracting the other streams in your project i. video. audio, data. 

There is only one helper function in the library. It is [getMediaInformation](https://github.com/tanersener/mobile-ffmpeg/blob/v4.3.1/android/app/src/main/java/com/arthenica/mobileffmpeg/FFprobe.java#L85=L94) and implemented to imitate `FFprobe`, because `FFprobe` was not included in the project at that time. If you take a look at the code, you can see that it uses `MediaInformationParser` class to parse the output. So it is a helper class which only parses text, nothing more. You can't use/extend that method to extract binary data.

> Would you be kind enough to advise on how I can read them and convert to an input stream, rather than to a jpeg/png file? Do I have to convert the binary data to a file first?

I didn't write the `ffmpeg` code. So I don't know the answer of your question. Why don't you ask this question to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list?
