### ISSUE TITLE
When rendering the ass file is based on libass? Can the ass support the introduction of images? Or a font image?

### ISSUE THREAD

**Issue by chenyangxx** [tanersener/mobile-ffmpeg#314]
When rendering the ass file is based on libass? Can the ass support the introduction of images? Or a font image?

**Comment by tanersener** [comment]
> Can the ass support the introduction of images?

What does that mean? 

I'm not a `libass` expert. Can you ask your question to [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list.
