### ISSUE TITLE
FFMPEG.cancel not working in 4.3.1 LTS

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#315]
Hi Taner

Seems that FFMPEG.cancel not working in 4.3.1 LTS. The convert process is still running until done.

**Comment by suncj518** [comment]
It is working in working in 4.2.2 LTS.

**Comment by tanersener** [comment]
I tested released packages myself and it was working. Can you please provide more info about it, like package name, API level of your device?

**Comment by suncj518** [comment]
package is mobile-ffmpeg-full-gpl-4.3.1.LTS,  API level is 28 ( Android 9) .
Seems that the process is not terminated immediately, it does not return failed callback,  thanks.

**Comment by suncj518** [comment]
Seems that FFMPEG.cancel is executed, the return code  rc =FFMPEG.execute() is still equals to 0, not 255.

**Comment by tanersener** [comment]
Can you please delete your `gradle cache` and try again?
There was a bug about `cancel` operation. I had to re-publish the binaries with the fix.

**Comment by suncj518** [comment]
Thanks, worked now.

**Comment by tanersener** [comment]
Great 👍 

Thanks for reporting this issue. 
It looks like I missed that bug during my tests.
