### ISSUE TITLE
ERROR: Failed to resolve: com.arthenica:mobile-ffmpeg-min:4.3.1.LTS

### ISSUE THREAD

**Issue by vlad-roid** [tanersener/mobile-ffmpeg#316]
Gradle sync fails with `ERROR: Failed to resolve: com.arthenica:mobile-ffmpeg-min:4.3.1.LTS`, works fine with 4.2.2.LTS

**Comment by tanersener** [comment]
`4.3.1.LTS` release was re-published yesterday. Can you please try again?

**Comment by vlad-roid** [comment]
yep worked, thanks
