### ISSUE TITLE
build ffmpeg.so file for android studio 

### ISSUE THREAD

**Issue by mansiJspaceo** [tanersener/mobile-ffmpeg#319]
i build ffmpeg with ndk file now i not able to build with android studio. any idea how can we build with it. any reference for it please provide us.

Thank you in advance

**Comment by tanersener** [comment]
Sorry, I don't understand your question. Could you please fill **Issue Template** fields and explain what you want to achieve?

**Comment by mansiJspaceo** [comment]
i want to build ffmpeg in android . also download source code of ffmpeg. also build .so file for all like 
libavutil,libswresample,libswscale,libavcodec etc.

now how can i run ffmpeg command in android studio using all this files

**Comment by tanersener** [comment]
If you want to use this project, `mobile-ffmpeg`, see `Building` section [README](https://github.com/tanersener/mobile-ffmpeg#5-building). If you want to use `ffmpeg`, please refer to [Official FFmpeg Documentation about Android](https://trac.ffmpeg.org/wiki/CompilationGuide/Android).
