### ISSUE TITLE
does the lib support converting png to jpg?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#32]
does the lib support converting png to jpg? if yes, may Iknow the command?

**Comment by tanersener** [comment]
> does the lib support converting png to jpg? if yes, may Iknow the command?

Yes it does,

`FFmpeg.execute('-i <my png path> <my jpg path>');`

**Comment by suncj518** [comment]
Thank you.
When I converted png to to jpg,  the error below happened, program crashed.
However when I converted mp4 to mp3, all is fine without the error blow.

May I know how to avoid this error ?  Thanks. 



10-03 06:45:35.074: I/mobile-ffmpeg(10603): Loading mobile-ffmpeg.
10-03 06:45:35.081: I/mobile-ffmpeg(10603): NEON supported armeabi-v7a library not found. Loading default armeabi-v7a library.
10-03 06:45:35.081: I/mobile-ffmpeg(10603): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_log_default_callback" referenced by "/data/app/net.windcloud.explorer-1/lib/arm/libmobileffmpeg-armv7a-neon.so"...
10-03 06:45:35.081: I/mobile-ffmpeg(10603): 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
10-03 06:45:35.081: I/mobile-ffmpeg(10603): 	at java.lang.System.loadLibrary(System.java:1530)
10-03 06:45:35.081: I/mobile-ffmpeg(10603): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:89)
10-03 06:45:35.081: I/mobile-ffmpeg(10603): 	at com.arthenica.mobileffmpeg.Config.enableLogCallback(Config.java:166)

**Comment by suncj518** [comment]
After more investigation, I found it is due to conflict with another 3rd thirty of .so lib FmpegMediaMetadataRetriever, they have same functions in different version of ffmpeg so files I guess.

**Comment by tanersener** [comment]
> May I know how to avoid this error ? Thanks.

Which version and package do you use?

**Comment by suncj518** [comment]
Version 2.2.1, after I removed so files of FFmpegMediaMetadataRetriever,  it is working.
Thanks.

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you need help.
