### ISSUE TITLE
how concurrent support works ?

### ISSUE THREAD

**Issue by btxdevs** [tanersener/mobile-ffmpeg#321]
How to use it?

**Comment by tanersener** [comment]
You can start running multiple commands at the same time. Just create another thread and call `execute()` method without waiting other executions to finish.

**Comment by btxdevs** [comment]
but how can you keep track of each execution?

**Comment by tanersener** [comment]
Each one has its own return code. You can check them to see if they are successful.

**Comment by btxdevs** [comment]
is it not possible to see the output while executing like logCallback of each execution?

**Comment by tanersener** [comment]
No, it is not. You need to analyse it yourself.
