### ISSUE TITLE
FFmpeg executable

### ISSUE THREAD

**Issue by TooLazyy** [tanersener/mobile-ffmpeg#322]
**Description**
Hi. Is it possible to create executable ffmpeg file?
To use it like: storage/emulated/0/ffmpeg -...arg
I tried to build ffmpeg from Build section in readme, but its not executable.

**Comment by tanersener** [comment]
Please see [Building ffmpeg executable on Android](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) wiki page.

**Comment by TooLazyy** [comment]
Yeah. Almost works. Nom I'm getting an error:
Android NDK: ERROR:jni/ffmpeg/Android.mk:avcodec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/ffmpeg/../../../prebuilt/android-arm/ffmpeg/lib/libavcodec.so exists  or that its path is correct   
/Users/ivanovartem/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
After a regular build libavcodec.so appears, but when I run a build with changed android-ffmpeg.sh file, the error appears.

**Comment by tanersener** [comment]
Ignore those errors, they are about `mobile-ffmpeg`, you can find `ffmpeg` and `ffprobe` executabes under `prebuilt`.

**Comment by TooLazyy** [comment]
true, thank you.
closing the issue.
