### ISSUE TITLE
How build binaries?

### ISSUE THREAD

**Issue by AppWerft** [tanersener/mobile-ffmpeg#323]
Great work, for my app I need only audio. I tried to install binary at start time, but this is rejected by Google. In my app I need only audio stuff. The file `mobile-ffmpeg-audio-4.3.1.aar` only contains stuff in jni folder. Maybe a beginners question, but I'm a beginner in this area: how can I build?

**Comment by tanersener** [comment]
[Building](https://github.com/tanersener/mobile-ffmpeg#5-building) section of README explains how to build binaries. Did you follow instructions given there?

**Comment by btxdevs** [comment]
but how can you keep track of each execution?
