### ISSUE TITLE
4.3.1.LTS getMediaInformation: Unknown output format with name 'default'

### ISSUE THREAD

**Issue by vlad-roid** [tanersener/mobile-ffmpeg#324]
**Description**
The first time I call FFprobe.getMediaInformation on a local path on Android, it works fine. When I call it again a few seconds later for the same or any other path, the returned MediaInformation object is corrupt, having no streams and only rawInformation="Unknown output format with name 'default'".

**Expected behavior**
The result of FFprobe.getMediaInformation should be valid.

**Current behavior**
"Unknown output format with name 'default'" **only using 4.3.1.LTS**.

**Logs**
Could not find any logs, just the message inside rawInformation.

**Environment**
 - Platform: Android 9
 - Architecture: arm-v7a
 - Android Studio version: 3.5.3
 - Mobile-FFmpeg 4.3.1.LTS

**Other**
As soon as I switch back to 4.2.2.LTS the error disappears.

**Comment by tanersener** [comment]
`v4.3.1.LTS` is republished including a fix for this issue. If you clean your `gradle` cache and test the this case again, it will be resolved.
