### ISSUE TITLE
tvOS: No failback to HEVC software

### ISSUE THREAD

**Issue by skrew** [tanersener/mobile-ffmpeg#325]
**Description**
The ffmpeg compiled on tvOS don't failback to software H265 if the hardware decoder don't handle the format.
I only got a "blue screen" instead. In the logs, ffmpeg return "null" as format.

Compiled with ```--enable-libass --enable-tvos-audiotoolbox --enable-tvos-videotoolbox --enable-gpl --enable-gnutls```

FFmpeg build with another script works fine, failback to software decoder as expected.
Note, the other script build FFmpeg 4.1.3 (not tested with more recent version, i will do if you need), but your script don't contain `tvos.sh` script on 4.1.x version, so i can't test with the same version.

**Expected behavior**
Failback to software decoder

**Current behavior**
Blue screen and / or not sound (seem to be the same problem with ac3)

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - tvOS 13
 - Apple TV
 - Master (head)
 - Xcode 13

**Comment by tanersener** [comment]
> The ffmpeg compiled on tvOS don't failback to software H265 if the hardware decoder don't handle the format.
I only got a "blue screen" instead. In the logs, ffmpeg return "null" as format.

Can you give me an example about that. Which command you're trying to execute?

> Note, the other script build FFmpeg 4.1.3 (not tested with more recent version, i will do if you need), but your script don't contain tvos.sh script on 4.1.x version, so i can't test with the same version.

Which version is that one? I don't have a `v4.1.3`. `tvOS` support was added in `v4.2.2`.

**Comment by skrew** [comment]
Yes, by "other script build", i mean `FFmpeg-iOS-build-script`, not your.

I'm using MPV, and using your script to build ffmpeg + libass

I have 2 versions:
- One for iOS
- One for tvOS

for iOS, i'm still using FFmpeg libs from `FFmpeg-iOS-build-script`, and i had see that all HEVC 4K videos is playing fine (with hevc hardware and software decoding)
for tvOS, i'm using your script. 
Users reported some HEVC 4K videos won't play.
After checking, it seem ffmpeg don't switch to software decoding when videotoolbox can't handle the format (because the hardware decoding don't handle it)

With `FFmpeg-iOS-build-script`:
```
21.871][i][cplayer]  (+) Video --vid=1 (*) 'Video 2160p 4K HDR' (hevc 3840x1600 23.976fps)
[  21.871][i][cplayer]      Video --vid=2 [P] 'cover.png' (png)
[  21.871][i][cplayer]  (+) Audio --aid=1 --alang=fre (*) 'VFi' (ac3 6ch 48000Hz)
[  21.871][i][cplayer]  (+) Subs  --sid=1 --slang=fre (*) (f) 'Fr Forces' (hdmv_pgs_subtitle)
[  21.871][i][cplayer]      Subs  --sid=2 --slang=fre 'Fr Complet' (hdmv_pgs_subtitle)
[  21.871][i][display-tags] File tags:
[  21.871][i][display-tags]  Title: <redacted>
[  21.872][v][vd] Container reported FPS: 23.976025
[  21.873][v][vd] Codec list:
[  21.873][v][vd]     hevc - HEVC (High Efficiency Video Coding)
[  21.873][v][vd] Opening decoder hevc
[  21.875][v][vd] Looking at hwdec hevc-videotoolbox...
[  21.875][v][vd] Trying hardware decoding via hevc-videotoolbox.
[  21.885][t][ffmpeg/video] hevc: nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
[  21.885][t][ffmpeg/video] hevc: Decoding VPS
[  21.885][t][ffmpeg/video] hevc: Main 10 profile bitstream
[  21.885][t][ffmpeg/video] hevc: nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
[  21.885][t][ffmpeg/video] hevc: Decoding SPS
[  21.885][t][ffmpeg/video] hevc: Main 10 profile bitstream
[  21.885][t][ffmpeg/video] hevc: Decoding VUI
[  21.885][t][ffmpeg/video] hevc: nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
[  21.885][t][ffmpeg/video] hevc: Decoding PPS
[  21.886][v][vd] Selected codec: hevc (HEVC (High Efficiency Video Coding))
[  21.886][v][vf] User filter list:
[  21.886][v][vf]   (empty)
[  21.886][v][ad] Codec list:
[  21.886][v][ad]     ac3 - ATSC A/52A (AC-3)
[  21.886][v][ad]     ac3_fixed (ac3) - ATSC A/52A (AC-3)
[  21.887][v][ad]     ac3_at (ac3) - ac3 (AudioToolbox)
[  21.887][v][ad] Opening decoder ac3
[  21.887][v][ad] Requesting 1 threads for decoding.
[  21.890][v][ad] Selected codec: ac3 (ATSC A/52A (AC-3))
[  21.890][v][af] User filter list:
[  21.890][v][af]   (empty)
[  21.890][v][cplayer] Starting playback...
```

With your script:
```
[  28.167][i][cplayer]  (+) Video --vid=1 (*) 'Video 2160p 4K HDR' (hevc 3840x1600 23.976fps)
[  28.167][i][cplayer]      Video --vid=2 [P] 'cover.png' (png)
[  28.167][i][cplayer]  (+) Audio --aid=1 --alang=fre (*) 'VFi' (ac3 6ch 48000Hz)
[  28.167][i][cplayer]  (+) Subs  --sid=1 --slang=fre (*) (f) 'Fr Forces' (hdmv_pgs_subtitle)
[  28.167][i][cplayer]      Subs  --sid=2 --slang=fre 'Fr Complet' (hdmv_pgs_subtitle)
[  28.167][i][display-tags] File tags:
[  28.167][i][display-tags]  Title: <redacted>
[  28.168][v][vd] Container reported FPS: 23.976025
[  28.168][v][vd] Codec list:
[  28.168][v][vd]     hevc - (null)
[  28.169][v][vd] Opening decoder hevc
[  28.170][v][vd] Looking at hwdec hevc-videotoolbox...
[  28.170][v][vd] Trying hardware decoding via hevc-videotoolbox.
[  28.176][t][ffmpeg/video] hevc: nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
[  28.176][t][ffmpeg/video] hevc: Decoding VPS
[  28.176][t][ffmpeg/video] hevc: Main 10 profile bitstream
[  28.176][t][ffmpeg/video] hevc: nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
[  28.176][t][ffmpeg/video] hevc: Decoding SPS
[  28.176][t][ffmpeg/video] hevc: Main 10 profile bitstream
[  28.176][t][ffmpeg/video] hevc: Decoding VUI
[  28.176][t][ffmpeg/video] hevc: nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
[  28.176][t][ffmpeg/video] hevc: Decoding PPS
[  28.176][v][vd] Selected codec: hevc ((null))
[  28.176][v][vf] User filter list:
[  28.176][v][vf]   (empty)
[  28.177][v][ad] Codec list:
[  28.177][v][ad]     ac3 - (null)
[  28.177][v][ad]     ac3_fixed (ac3) - (null)
[  28.177][v][ad]     ac3_at (ac3) - (null)
[  28.177][v][ad] Opening decoder ac3
[  28.177][v][ad] Requesting 1 threads for decoding.
[  28.178][v][ad] Selected codec: ac3 ((null))
[  28.178][v][af] User filter list:
[  28.178][v][af]   (empty)
[  28.179][v][cplayer] Starting playback...
``` 

As you can see, codec list (for video AND audio) is "null", which is strange (and explain why it don't works)
In `build.log`, i can see HEVC in `Enabled decoders`, `Enabled parsers` and `Enabled demuxers`

(i will test right now the same FFmpeg version as your, to be sure it's not a regression bug from FFmpeg since 4.1.3)

**Comment by tanersener** [comment]
Why don't you create a ticket on `ffmpeg`? 
I'm sure guys over there can identify the issue and fix it.

**Comment by skrew** [comment]
i will, i think @tmm1 is the right guy for this bug
