### ISSUE TITLE
FFmpeg full buid

### ISSUE THREAD

**Issue by TooLazyy** [tanersener/mobile-ffmpeg#326]
command I use to build ffmpeg
`./android.sh -l --enable-gpl --disable-arm-v7a-neon --disable-arm64-v8a --disable-x86 --disable-x86-64 --full --enable-x264`
and getting an error:
```
3 warnings generated.
AR	libavformat/libavformat.a
AR	libavcodec/libavcodec.a
7 warnings generated.
AR	libswresample/libswresample.a
AR	libswscale/libswscale.a
AR	libavutil/libavutil.a
1 warning generated.
8 warnings generated.
6 warnings generated.
LD	ffmpeg_g
LD	ffplay_g
LD	ffprobe_g
/Users/user/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/16/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffplay_g] Error 1
make: *** Waiting for unfinished jobs....

```

Ndk path ix exported like /Users/username/Library/Android/sdk/ndk-bundle.
Also tried /Users/username/Library/Android/sdk/ndk/20.0.5594570 - still getting the error, but the different one.

I can guess the reason is in cmake version, but not sure.

**Comment by tanersener** [comment]
`android.sh` does not generate `ffmpeg`, `ffplay` and `ffprobe` by default. Did you modified the scripts?

**Comment by TooLazyy** [comment]
Yes, according to Build executable section.

**Comment by tanersener** [comment]
Your build fails because your scripts try to build `ffplay` and `ffplay` can not be built. Can you please add `--disable-ffplay` option to your configure line at `build/android-ffmpeg.sh`?

**Comment by TooLazyy** [comment]
> Your build fails because your scripts try to build `ffplay` and `ffplay` can not be built. Can you please add `--disable-ffplay` option to your configure line at `build/android-ffmpeg.sh`?

yeah, that help, ty.
but I've got another error building x265)

Stacktrace is quite big.
```
/Users/username/Downloads/ffmpeg4.2.2/src/x265/source/common/cudata.h:51:5: note: previous declaration is here
    NUM_SIZES
    ^
make[2]: *** [encoder/CMakeFiles/encoder.dir/bitcost.cpp.obj] Error 1
In file included from /Users/username/Downloads/ffmpeg4.2.2/src/x265/source/encoder/slicetype.cpp:26:
In file included from /Users/username/Downloads/ffmpeg4.2.2/src/x265/source/common/common.h:30:
/Users/username/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/cmath:622:68: error: too many arguments provided to function-like macro invocation
  static_assert(is_same<_FloatT, float>::value || is_same<_FloatT, double>::value
                                                                   ^
/Users/username/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__config:861:13: note: macro 'static_assert' defined here
#    define static_assert(__b, __m) _Static_assert(__b, __m)
            ^
In file included from /Users/username/Downloads/ffmpeg4.2.2/src/x265/source/encoder/slicetype.cpp:26:
In file included from /Users/username/Downloads/ffmpeg4.2.2/src/x265/source/common/common.h:30:
/Users/username/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/cmath:622:3: error: use of undeclared identifier 'static_assert'
  static_assert(is_same<_FloatT, float>::value || is_same<_FloatT, double>::value
  ^
2 errors generated.
make[2]: *** [encoder/CMakeFiles/encoder.dir/motion.cpp.obj] Error 1
1 warning and 2 errors generated.
make[2]: *** [encoder/CMakeFiles/encoder.dir/search.cpp.obj] Error 1
2 errors generated.
make[2]: *** [encoder/CMakeFiles/encoder.dir/slicetype.cpp.obj] Error 1
make[1]: *** [encoder/CMakeFiles/encoder.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tanersener** [comment]
Which version of `mobile-ffmpeg` are you trying to compile? 
Do you have any changes in the source code?

**Comment by TooLazyy** [comment]
4.2.LTS | 4.2-dev-480 | Jan 3, 2019
16 api.
I had to update gradle version + change some lines in CameraSupport.java so that it build.

**Comment by tanersener** [comment]
Sometimes changes in the NDK cause this kind of errors after a release has been published. Can you try using `build/android-x265.sh` file from `master` branch in your build?

**Comment by TooLazyy** [comment]
@tanersener ty, it work for arn-v7a.
Building for x86 fails with:
```
fatal: not a git repository (or any of the parent directories): .git
Generated codec/common/inc/version_gen.h
make: nasm: No such file or directory
nasm -DX86_32 -DHAVE_AVX2 -f elf -I./codec/common/x86/   -o codec/encoder/core/x86/dct.o codec/encoder/core/x86/dct.asm
make: *** [codec/encoder/core/x86/coeff.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
```

**Comment by tanersener** [comment]
> make: nasm: No such file or directory

Do you have all [Android Prerequisites](https://github.com/tanersener/mobile-ffmpeg/wiki/Android-Prerequisites) installed?

**Comment by TooLazyy** [comment]
@tanersener by bad, I missed nasm.
The last question.
As mention [here](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) I need to use libc++_shared.so. Where should I find this file and where to put it in my project?

**Comment by tanersener** [comment]
`libc++_shared.so` can be found under the `${ANDROID_NDK_ROOT}/sources/cxx-stl/llvm-libc++/libs/<arch>` folder. 

Put `libc++_shared.so` on the same path as `ffmpeg` and/or `ffprobe`.

**Comment by TooLazyy** [comment]
So, let's say, if I copy ffmpeg executable into `sdcard/some_folder`, `libc++_shared.so `should be placed there too?

**Comment by tanersener** [comment]
It doesn't have to be, but it would be easier for application to find `libc++_shared.so`. So you won't need to do something extra, like setting some environment variables.

**Comment by TooLazyy** [comment]
Well, guess I've missed smth. Coz when I try to get ffmpeg version an error occurs:
`CANNOT LINK EXECUTABLE "/data/user/0/package/files/ffmpeg/ffmpeg": library "libcpufeatures.so" not found`

**Comment by TooLazyy** [comment]
even after copying `libc++_shared.so + ffmpeg + libcpufeatures.so` (which was found in test-app/build/intermediates/merged_native_libs..) together into one folder "-version" still not working

**Comment by tanersener** [comment]
How do you execute a command?

**Comment by TooLazyy** [comment]
```
String[] commands = new String[] {
 "/data/user/0/package/files/ffmpeg/ffmpeg"
"-version"
}
Runtime.getRuntime().exec(commands).waitFor();
```
This way before I used another ffmpeg executable.

**Comment by tanersener** [comment]
The problem here is, Android needs to know where it can find `libc++_shared.so` library. This is the problem in this case.

As far as I know, Android documentation doesn't provide a mechanism to do that. So, you need a workaround for it. 

There are things you can try, 
- Like trying to call `System.loadLibrary("/data/user/0/package/files/ffmpeg/libc++_shared.so")` before executing ffmpeg
- Setting LD_LIBRARY_PATH environment variable to "/data/user/0/package/files/ffmpeg"
- Exception stack trace you receive right now shows which paths are searched. You can try putting `libc++_shared.so` in one of those directories

Also, instead of asking me you can google about it. I'm not recommending using executables. I recommend using  `MobileFFmpeg` library.

**Comment by alexcohn** [comment]
> So, let's say, if I copy ffmpeg executable into `sdcard/some_folder`, `libc++_shared.so `should be placed there too?

On *normal* devices, `sdcard` is marked as non-executable file system. You should copy `ffmpeg` executable to `/data/local/tmp` if you run it standalone, or in your app `files` directory if it's extracted from an APK.

As for the `libc++_shared.so`, you should put it next to `ffmpeg` binary, and use 
````
Runtime.getRuntime().exec(
    new String[]{"/data/user/0/package/files/ffmpeg/ffmpeg", "-version"}, 
    new String[]{"LD_LIBRARY_PATH=/data/user/0/package/files/ffmpeg"});
````
