### ISSUE TITLE
[iOS] arm64 devices crash on ff_hscale_8_to_15_neon function with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#328]
`FFmpeg` operations fail with EXC_BAD_ACCESS on `ff_hscale_8_to_15_neon` function.

<img width="253" alt="Screenshot 2020-01-25 at 09 31 22" src="https://user-images.githubusercontent.com/10158439/73119147-94d55380-3f55-11ea-8763-2739925f79f5.png">

All iOS devices with arm64 architecture (probably arm64e as well), running `v4.3.1` and `v4.3.1.LTS` releases, are affected from this.

The crash is caused by [ffmpeg commit bd831912712e32b8e78d409bfa7ea7e668ce4b42](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/bd831912712e32b8e78d409bfa7ea7e668ce4b42).

**Comment by tanersener** [comment]
This issue is fixed using the previous version of `libswscale/aarch64/hscale.S` file.

**Comment by alexcohn** [comment]
does this problem apply to Android at all?

**Comment by tanersener** [comment]
I'm not sure. Unfortunately, I couldn't test it. I don't have a working `arm64` Android device right now. So I'm using the same workaround for Android as well.

**Comment by alexcohn** [comment]
Have you got a test case to prove it? I have some arm64 here to run such test. Also, the device is rather old, so if it works there, it will also work on more advanced devices.

**Comment by tanersener** [comment]
Yes, I do. It is pretty easy actually.

On iOS, it is possible to reproduce it using the test-application. If I test "mp4" encoding under the "Video" tab, library crashes with EXC_BAD_ACCESS. 

I think the same scenario can be tested using the Android test app. Both Android/iOS applications use the same commands for encoding. So if the same bug is there, it will crash there too. 

It'd be great if you can test this.

**Comment by alexcohn** [comment]
> If I test "mp4" encoding under the "Video" tab, library crashes with EXC_BAD_ACCESS.

I tested it on my Android arm64 device (BV-6000) and it **a)** works correctly, and **b)** I proved that this `ff_hscale_8_to_15_neon` function is actually called (an artificial div by 0 caused the expected crash).

So, I propose to mark this patch *iOS only*. After all, the claim on https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/bd831912712e32b8e78d409bfa7ea7e668ce4b42 is that this gives 25% improvement, which is not something one can dismiss lightheartedly.

**Comment by tanersener** [comment]
Thanks for testing this case. Yes, we can mark this patch iOS only. I will update `android-ffmpeg.sh` and remove the workaround. This change will be included in the next Main release.
