### ISSUE TITLE
'Unable to find a suitable output format for'

### ISSUE THREAD

**Issue by anubhavmalik** [tanersener/mobile-ffmpeg#330]
**Description**
The error occurs in the ffmpeg command(given below) where 1.7 is defined. This command runs successfully on same version linux build ffmpeg but not on mobile ffmpeg.

**Expected behaviour**
For the command to complete running and actually create an output file

**Current behaviour**
the command fails to run

**Logs**

E/mobile-ffmpeg: [NULL @ 0x55bed1c310] 
E/mobile-ffmpeg: Unable to find a suitable output format for '1.7'
E/mobile-ffmpeg: 1.7: Invalid argument

**Environment**
 - Platform: Android
 - Architecture: arm64-v8a
 - Version v4.2.2.LTS
 - Source branch master
 - Android Studio version : 3.5
 - Android NDK version : 21

**Other**
-ffmpeg Command : 

-f lavfi -i color=c=#FFFFFF:s=700x550:d=0.5 -ss 0 -i https://memeops.s3.ap-south-1.amazonaws.com/templates/video_158.mp4 -loop 1 -i /storage/emulated/0/Android/data/tech.trolls.memerAdmin/files/meme/text_1memer2.png -loop 1 -i https://s3.ap-south-1.amazonaws.com/memeops/remixAssets/userGeneratedStickersDev/0JzmEokUbbTj7Ig2yTdUrQ1I2Pw2/1576137222875/downloadURL -f lavfi -i anullsrc=channel_layout=mono:sample_rate=48000 -y -filter_complex [1:v]scale=w='668':h='432'[1v_scaled];[1v_scaled]rotate=angle=0:fillcolor=black@0:out_w=rotw(0):out_h=roth(0)[1v_rotated];[0][1v_rotated]overlay=enable='between(t,0,10000)':x=16:y=102[x];[2:v]format=rgba,trim=duration=10[2v_processed];[2v_processed]scale=w='668':h='54'[2v_scaled];[2v_scaled]rotate=angle=0:fillcolor=black@0:out_w=rotw(0):out_h=roth(0)[2v_rotated];[x][2v_rotated]overlay=enable='between(t,0,10000)':x=16:y=16[xx];[3:v]format=rgba,trim=duration=10[3v_processed];[3v_processed]scale=w='188.6196':h='271.71777'[3v_scaled];[3v_scaled]rotate=angle=-0.020943537380899234:fillcolor=black@0:out_w=rotw(-0.020943537380899234):out_h=roth(-0.020943537380899234)[3v_rotated];[xx][3v_rotated]overlay=enable='between(t,0,10000)':x='if(lte(t, 1.7 ) , 378.93903 , 378.93903 )':y='if(lte(t, 1.7 ) , 105.36995 , 105.36995 )'[xxx];[4:a]atrim=0:0[1a_start];[1:a]atrim=0:100000[1a_trim];[1a_start][1a_trim]concat=n=2:v=0:a=1[1a_toBeMixed];[1a_toBeMixed]amix=inputs=1:duration=longest[out_a] -map [xxx] -map [out_a]? -vcodec libx264 -pix_fmt yuv420p -crf 20 -strict -2 -movflags +faststart /storage/emulated/0/1580199557210Memes.mp4

**Comment by anubhavmalik** [comment]
So, I found the issue. 

while parsing, the parseArgumentsMethod removes some ' (single quotes) I have in my original command which causes the command to change and this error is caused

**Comment by tanersener** [comment]
Can you try using one of the `4.3.x` versions which has better quotes support?

**Comment by anubhavmalik** [comment]
yes, I tried it with 4.3.1.LTS. Same issue.

Although I solved it for my case. It is just a workaround for my case though, here's the code : 

public String[] parseArguments(final String command) {
        final List<String> argumentList = new ArrayList<>();
        StringBuilder currentArgument = new StringBuilder();

        boolean singleQuoteStarted = false;
        boolean doubleQuoteStarted = false;

        for (int i = 0; i < command.length(); i++) {
            final Character previousChar;
            if (i > 0) {
                previousChar = command.charAt(i - 1);
            } else {
                previousChar = null;
            }
            final char currentChar = command.charAt(i);

            if (currentChar == ' ') {
                if (singleQuoteStarted || doubleQuoteStarted) {
                    currentArgument.append(currentChar);
                } else if (currentArgument.length() > 0) {
                    argumentList.add(currentArgument.toString());
                    currentArgument = new StringBuilder();
                }
            } else if (currentChar == '\'' /*&& (previousChar == null || previousChar != '\\')*/) {
                if (singleQuoteStarted) {
                    singleQuoteStarted = false;
//                } else if (doubleQuoteStarted) {
//                    currentArgument.append(currentChar);
                } else {
                    singleQuoteStarted = true;
                }
                currentArgument.append(currentChar);

            } else if (currentChar == '\"' && (previousChar == null || previousChar != '\\')) {
                if (doubleQuoteStarted) {
                    doubleQuoteStarted = false;
//                } else if (singleQuoteStarted) {
//                    currentArgument.append(currentChar);
                } else {
                    doubleQuoteStarted = true;
                }
                currentArgument.append(currentChar);

            } else {
                currentArgument.append(currentChar);
            }
        }

        if (currentArgument.length() > 0) {
            argumentList.add(currentArgument.toString());
        }

        return argumentList.toArray(new String[0]);
    }

**Comment by anubhavmalik** [comment]
Thankfully, the method to directly provide a String[] as parameter is available so I could change the parsing function according to my need.

**Comment by tanersener** [comment]
I think, in `4.3.x` releases, using double quotes at the beginning and end of filter_complex may also fix your issue.
