### ISSUE TITLE
MobileFFmpegConfig.h not found

### ISSUE THREAD

**Issue by xiedeacc** [tanersener/mobile-ffmpeg#335]
ios test_app, use xcode 11, opened xcworkspace, build prompts MobileFFmpegConfig.h not found.
I have found all issues, no one report this problem

**Comment by tanersener** [comment]
Which test-app? There are 3 different test apps?

**Comment by xiedeacc** [comment]
both all of three

**Comment by xiedeacc** [comment]
> Which test-app? There are 3 different test apps?

my macos filesystem was case sensitive?

**Comment by xiedeacc** [comment]
> > Which test-app? There are 3 different test apps?
> 
> my macos filesystem was case sensitive?

was I open this project problem?

**Comment by tanersener** [comment]
`ios/test-app/pods-with-tooltips` test-application requires you to run `pod install` under the directory. Did you try doing that?

**Comment by xiedeacc** [comment]
yes pod-with-tooltips with pod install run success
