### ISSUE TITLE
Capture Video, Video Rendering and Playing on iOS

### ISSUE THREAD

**Issue by asifhabib** [tanersener/mobile-ffmpeg#336]
**Description**
Mobile fffmpeg is in very raw form and it is impossible to run it on iOS. Current example is very simple which joins the images into video. There is no sample of capturing the video through ffmpeg. 
There is instruction#7 given in iOS section how to record video but it does not open the camera and there is no guide about the video formate and captured video do not play in AVPlayer. 

**Expected behavior**
There should be and example of capturing the video and applying filter on live camera or at-least capturing the video. It is available in javacv which is for android and you can apply filters on camera preview. 

**Current behavior**
There is no example in the test-app for iOS

**Environment**
 - Platform: iOS

**Other**
Is there any wrapper available for iOS like javaCV(which uses ffmpeg under the hud) for ffmpeg.

**Comment by tanersener** [comment]
Your expected behaviour is not correct. Please read [FFmpeg](https://en.wikipedia.org/wiki/FFmpeg) to better understand what `FFmpeg` is what to expect from it.
