### ISSUE TITLE
I want to make a horizontal video a vertical video with letterbox on Android.

### ISSUE THREAD

**Issue by audxo112** [tanersener/mobile-ffmpeg#337]
**Description**
It works fine on Windows but not on Android.

**Expected behavior**
I want to make a horizontal image a vertical image with letterbox on Android.

**Current behavior**
FFmpeg.execute("-i " + uri.getPath() + " -vf \"scale=1440:2960:force_original_aspect_ratio=decrease,pad=1440:2960:(ow-iw)/2:(oh-ih)/2\" " + dst.getAbsolutePath());

I made a video on android using the above command.
However, the video does not play in ExoPlayer and Gallery.
It looks like you shouldn't add the vf command.
By the way, it works well in Windows pod player.
Also, using the same command on Windows will run fine on Android.

**Screenshots**
![Screenshot_20200207-203347 1](https://user-images.githubusercontent.com/9216335/74026278-309ca000-49e9-11ea-9e31-874ba8563b43.png)

**Logs**
https://ghostbin.co/paste/ac42f

**Environment**
 - Platform: Android 7
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable)
 - Source branch (if applicable) 4.3.1.LTS
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) 3.5.3
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Comment by tanersener** [comment]
Can you please share the output of your `FFmpeg` command? 
Also can you please share the name of `mobile-ffmpeg` package you use?
Additionally, did you try playing the output video on a desktop player?

**Comment by audxo112** [comment]
@tanersener 
I/mobile-ffmpeg: Loading mobile-ffmpeg.
I/mobile-ffmpeg: Loaded mobile-ffmpeg-full-arm64-v8a-4.3.1-lts-20200125.
D/mobile-ffmpeg: Callback thread started.
I/mobile-ffmpeg: ffmpeg version git-2020-01-25-fd11dd500
     Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
I/mobile-ffmpeg:   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disa
      libavutil      56. 38.100 / 56. 38.100
      libavcodec     58. 65.102 / 58. 65.102
      libavformat    58. 35.101 / 58. 35.101
      libavdevice    58.  9.103 / 58.  9.103
      libavfilter     7. 70.101 /  7. 70.101
      libswscale      5.  6.100 /  5.  6.100
      libswresample   3.  6.100 /  3.  6.100
I/mobile-ffmpeg: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/youcut/YouCut_20191203_133657_1139129846.org.mp4':
      Metadata:
        major_brand     : 
    mp42
        minor_version   : 
    0
        compatible_brands: 
    isommp42
        creation_time   : 
    2019-12-03T04:36:54.000000Z
        location        : 
    +35.1814+126.8941/
        location-eng    : 
    +35.1814+126.8941/
        com.android.version: 
    7.0
      Duration: 
    00:00:02.54
    , start: 
    0.000000
    , bitrate: 
    17267 kb/s
        Stream #0:0
    (eng)
    : Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 17009 kb/s
    , SAR 1:1 DAR 16:9
I/mobile-ffmpeg: , 
    29.65 fps, 
    29.97 tbr, 
    90k tbn, 
    180k tbc
     (default)
        Metadata:
          rotate          : 
    90
          creation_time   : 
    2019-12-03T04:36:54.000000Z
          handler_name    : 
    VideoHandle
        Side data:
          
    displaymatrix: rotation of -90.00 degrees
        Stream #0:1
    (eng)
    : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s
     (default)
        Metadata:
          creation_time   : 
    2019-12-03T04:36:54.000000Z
          handler_name    : 
    SoundHandle
I/mobile-ffmpeg: Stream mapping:
      Stream #0:0 -> #0:0
     (h264 (native) -> mpeg4 (native))
      Stream #0:1 -> #0:1
     (aac (native) -> aac (native))
    Press [q] to stop, [?] for help
W/mobile-ffmpeg: [graph 0 input from stream 0:0 @ 0x75ba6957c0] sws_param option is deprecated and ignored
I/mobile-ffmpeg: Output #0, mp4, to '/storage/emulated/0/Movies/knock/2.mp4':
      Metadata:
        major_brand     : 
    mp42
        minor_version   : 
    0
        compatible_brands: 
    isommp42
        com.android.version: 
    7.0
        location        : 
    +35.1814+126.8941/
        location-eng    : 
    +35.1814+126.8941/
        encoder         : 
    Lavf58.35.101
        Stream #0:0
    (eng)
    : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1440x2960 [SAR 1:1 DAR 18:37], q=2-31, 200 kb/s
I/mobile-ffmpeg: , 
    29.97 fps, 
    30k tbn, 
    29.97 tbc
     (default)
        Metadata:
          encoder         : 
    Lavc58.65.102 mpeg4
I/mobile-ffmpeg:       creation_time   : 
    2019-12-03T04:36:54.000000Z
          handler_name    : 
    VideoHandle
        Side data:
          
    cpb: 
    bitrate max/min/avg: 0/0/200000 buffer size: 0 
    vbv_delay: N/A
          
    displaymatrix: rotation of -0.00 degrees
        Stream #0:1
I/mobile-ffmpeg: (eng)
    : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
     (default)
        Metadata:
          creation_time   : 
    2019-12-03T04:36:54.000000Z
          handler_name    : 
    SoundHandle
          encoder         : 
    Lavc58.65.102 aac
I/mobile-ffmpeg: frame=    4 fps=0.0 q=2.2 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=1.57x    
I/mobile-ffmpeg: frame=    9 fps=7.8 q=15.4 size=     256kB time=00:00:01.00 bitrate=2091.9kbits/s dup=1 drop=0 speed=0.868x    
I/mobile-ffmpeg: frame=   15 fps=9.0 q=30.3 size=     512kB time=00:00:01.00 bitrate=4183.5kbits/s dup=1 drop=0 speed=0.603x    
I/mobile-ffmpeg: frame=   21 fps=9.6 q=31.0 size=     512kB time=00:00:01.00 bitrate=4183.5kbits/s dup=1 drop=0 speed=0.456x    
I/mobile-ffmpeg: frame=   25 fps=9.3 q=24.8 size=     512kB time=00:00:01.81 bitrate=2313.2kbits/s dup=1 drop=0 speed=0.672x    
I/mobile-ffmpeg: frame=   32 fps=9.9 q=31.0 size=     768kB time=00:00:02.00 bitrate=3137.5kbits/s dup=1 drop=0 speed=0.621x    
I/mobile-ffmpeg: frame=   38 fps= 10 q=31.0 size=     768kB time=00:00:02.00 bitrate=3137.5kbits/s dup=1 drop=0 speed=0.534x    
I/mobile-ffmpeg: frame=   44 fps= 10 q=31.0 size=     768kB time=00:00:02.00 bitrate=3137.5kbits/s dup=1 drop=0 speed=0.47x    
I/mobile-ffmpeg: frame=   50 fps= 10 q=31.0 size=     768kB time=00:00:02.00 bitrate=3137.5kbits/s dup=1 drop=0 speed=0.419x    
I/mobile-ffmpeg: frame=   55 fps= 10 q=31.0 size=    1024kB time=00:00:02.02 bitrate=4139.3kbits/s dup=1 drop=0 speed=0.381x    
I/mobile-ffmpeg: frame=   62 fps= 11 q=31.0 size=    1024kB time=00:00:02.45 bitrate=3419.4kbits/s dup=1 drop=0 speed=0.418x    
I/mobile-ffmpeg: frame=   68 fps= 11 q=31.0 size=    1024kB time=00:00:02.45 bitrate=3419.4kbits/s dup=1 drop=0 speed=0.383x    
I/mobile-ffmpeg: frame=   74 fps= 11 q=31.0 size=    1280kB time=00:00:02.45 bitrate=4274.2kbits/s dup=1 drop=0 speed=0.353x    
I/mobile-ffmpeg: frame=   77 fps= 11 q=31.0 Lsize=    1365kB time=00:00:02.53 bitrate=4411.0kbits/s dup=1 drop=0 speed=0.349x    
    video:1319kB audio:43kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
    0.260651%
I/mobile-ffmpeg: [aac @ 0x75aca66600] Qavg: 1377.468
D/ViewRootImpl@91569bc[MainActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x7 surface={isValid=true 505927804416} surfaceGenerationChanged=true
    mHardwareRenderer.initialize() mSurface={isValid=true 505927804416} hwInitialized=true

The above is the log

dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS'
}
I don't know if the package is correct

Videos play well on desktop.

Even videos created on the desktop with the same command will run normally on Android.

**Comment by tanersener** [comment]
Tested your command with the same `mobile-ffmpeg` package but it works for me. Can you share one of your input videos?

**Comment by audxo112** [comment]
@tanersener 
Input video
https://drive.google.com/file/d/11aSG748TNX_9deuSaWjbdU6Ye44kIjP1/view?usp=sharing

output video in android
https://drive.google.com/file/d/1ooaFscg8m103QPD5J0zRtynwMECgAwwg/view?usp=sharing

output video in window
https://drive.google.com/file/d/1uPS9reff6iT_MUgUbPYR2XtkmtWMU-0f/view?usp=sharing
environment
- window 10
- ffmpeg 4.2.2

The two outputs used the same FFmpeg code.

**Comment by audxo112** [comment]
Android Code
https://ghostbin.co/paste/yu6ca

**Comment by tanersener** [comment]
**Android video output:**
`Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 1440x2960 [SAR 1:1 DAR 18:37]`

**Windows video output:**
`Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1440x2960`

You can see that `mobile-ffmpeg` is creating an mpeg4 file with `Simple Profile` and your Windows ffmpeg is creating and h264 file. I think mpeg4's `Simple Profile` is not supported by your Android device. This is why it is not playable on Android. 

Can you try:
- Creating an mpeg4 file with an advanced profile by adding `-profile:v 15` to your command

or 

- Creating an h264 file by using `mobile-ffmpeg-full-gpl` package

**Comment by audxo112** [comment]
@tanersener 

Thank you very much
After cleaning the project, using the mobile-ffmpeg-full-gpl package solved the problem!
