### ISSUE TITLE
App crashes when using "com.arthenica:mobile-ffmpeg-full-gpl:4.3.1.LTS" dependency!

### ISSUE THREAD

**Issue by chhatrasal09** [tanersener/mobile-ffmpeg#343]
**Description**
When I use **"com.arthenica:mobile-ffmpeg-full-gpl:4.3.1"** then app is performing correctly. I want to use libx264 codec and it is available in full-gpl dependecy and my **minSdkVersion** is **21** so I have to use **LTS** version of the library. When I try to run the demo app given in this library with **"com.arthenica:mobile-ffmpeg-full-gpl:4.3.1.LTS"** the app is crashing. 
I have attached the images for the dependecy and the crash i am getting. I am using Redmi 7 for testing. I am have no idea about NDK so I don't know what this .so file is. Please help me solve to this.

**Expected behavior**
The app should not crash.

**Current behavior**
App is crashing

**Screenshots**
Dpendency
![img1](https://user-images.githubusercontent.com/21989289/74438109-6fba6d80-4e8f-11ea-91c5-2fe5cff84352.JPG)

Crash reason.
![img2](https://user-images.githubusercontent.com/21989289/74438126-7648e500-4e8f-11ea-88e3-43e433801f24.JPG)

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64] - **arm64**
 - Version (if applicable) [e.g. v1.2] - **4.3.1.LTS**
 - Source branch (if applicable) [e.g. master, dev-v2.x] - **master**
 - Android Studio version (if applicable) - **3.5.6**
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Comment by tanersener** [comment]
What is the output of the following command?

`cd ~/.gradle; find . -name mobile-ffmpeg-full-gpl-4.3.1.LTS.aar -exec jar -tf {} +`

**Comment by chhatrasal09** [comment]
> 
> 
> What is the output of the following command?
> 
> `cd ~/.gradle; find . -name mobile-ffmpeg-full-gpl-4.3.1.LTS.aar -exec jar -tf {} +`

Sorry, But I am using Windows for development. So can you give commands that can run on Windows Command Prompt?

**Comment by chhatrasal09** [comment]
> 
> 
> What is the output of the following command?
> 
> `cd ~/.gradle; find . -name mobile-ffmpeg-full-gpl-4.3.1.LTS.aar -exec jar -tf {} +`

I got access to macOS and tried there also I got app crash but with some different filename. I also ran the commands that you gave and I got the following results. It seems the generated jar has the required files that are being thrown as exception.
The device sdk version is **28**.
The crash exception:
![Screenshot 2020-02-14 at 11 07 50 AM](https://user-images.githubusercontent.com/21989289/74504916-c1103e80-4f1b-11ea-80be-1ddebefcc654.png)
The output of the file :
![Screenshot 2020-02-14 at 11 05 14 AM](https://user-images.githubusercontent.com/21989289/74504944-d84f2c00-4f1b-11ea-86d3-e53811ae0efb.png)

**Comment by tanersener** [comment]
Your screenshots show that both `libc++_shared.so` and `libcpufeatures.so` are there. Did you try cleaning your project and building it again? There were similar issues created before and all of them were resolved by cleaning the project cache and building it again.

**Comment by chhatrasal09** [comment]
> 
> 
> Your screenshots show that both `libc++_shared.so` and `libcpufeatures.so` are there. Did you try cleaning your project and building it again? There were similar issues created by other users and all of them were resolved by cleaning the project cache and building it again.

Cleaning of project doesn't fixed the crash. I had already tried that. But cleaning the project and invalidating cache fixed the crash. Now I am able to run the app with LTS version. Thanks for the help. I should have tried this before reporting here.
I have one more question if you can reply on this thread. I used the following command, rather than reducing the file size or keeping it same it increased the file size. Is anything wrong with the command. 
`-i input.mp4 -vcodec libx264 -preset ultrafast -c:a aac output.mp4`
I know i am using ultrafast which does not reduce file size to much extent but it should reduce ithe size or keep as it is, as I am not up-scaling the anything. I think the above command is just copying file from source to destination, nothing else.

**Comment by tanersener** [comment]
You're not specifying an output format for your `output.mp4` file. `ffmpeg` chooses the output format and other output parameters for you. Sometimes it will decrease the size and sometimes it will increase the size. It's better to explicitly set an output format with `-c:v` or `-f` options. https://ffmpeg.org/ffmpeg-formats.html page includes examples you can look at.

Also logs can help you to understand why file size is increasing. Maybe your input file is using a more compressed format/preset then the one selected by `ffmpeg`.
