### ISSUE TITLE
about neon version

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#35]
@tanersener , may I know how to use neon version .so files only ?
I tried to use 4 *neon files only, and  deleted related 4 non-neon .so files,  other common .so files are kept, the program crashed.
BTW, neon version of .so files can support all Android 5.0 and above OS ?
Thanks.

**Comment by tanersener** [comment]
Well, NEON support for Android is a little complicated.

In short, you can not use .so files *-neon alone. An ABI needs the following .so files for `MobileFFmpeg`.

```

libavcodec.so
libavdevice.so
libavfilter.so
libavformat.so
libavutil.so
libc++_shared.so
libcpufeatures.so
libmobileffmpeg-abidetect.so
libmobileffmpeg.so
libswresample.so
libswscale.so
```

For NEON supported `armeabi-v7a`ABI, the list is;

```
libavcodec-neon.so
libavdevice.so
libavfilter-neon.so
libavformat.so
libavutil.so
libc++_shared.so
libcpufeatures.so
libmobileffmpeg-abidetect.so
libmobileffmpeg-armv7a-neon
libswresample.so
libswscale-neon.so
```
