### ISSUE TITLE
amr lib libopencore_amrwb is not supported in 4.3.1 GPL LTS?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#352]
Hi taner,

I tested and found libopencore_amrnb is supported and working, but libopencore_amrwb is not supported, it said :
Unknown encoder 'libopencore_amrwb'
anything I missed?

log is here:

02-21 12:11:57.298 31728-31728 ffmpeg command: [-y, -i, /storage/emulated/0/VID_20191125_200348_new.ts, -acodec, libopencore_amrwb, -ab, 23.85k, -ac, 1, -ar, 16000, -preset, superfast, /storage/emulated/0/VID_20191125_200348_new_new_2.amr]

02-21 12:11:57.439 31728-2402/ D/mobile-ffmpeg: Callback thread started.
02-21 12:11:57.439 31728-2402/ D/mobile-ffmpeg: 39.96 tbc
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg:     Stream #0:1
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg: [0x101]
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg: : Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 126 kb/s
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg: Unknown encoder 'libopencore_amrwb'
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg: [AVIOContext @ 0xcee64100] Statistics: 774288 bytes read, 2 seeks
02-21 12:11:57.440 31728-2402/ D/mobile-ffmpeg: Conversion failed!

**Comment by tanersener** [comment]
Can you run `-codecs` and look for `amr` in the output. That output will explain the situation to you.
