### ISSUE TITLE
FFmpeg.execute hangs on Android when passed images as input

### ISSUE THREAD

**Issue by flovouin** [tanersener/mobile-ffmpeg#354]
**Description**

I'm using mobile-ffmpeg in my Android app. I've used it for various short video processing, and it has always worked.
I now want to convert an image to a video. I'm calling `FFmpeg.execute` with those arguments (they are very similar to what I usually do for videos, except the input is an image and I'm using the `zoompan` filter):

```
0 = "-i"
1 = "myimage.jpg"
2 = "-loglevel"
3 = "trace"
4 = "-pix_fmt"
5 = "yuv420p"
6 = "-vf"
7 = "transpose=cclock,transpose=cclock,transpose=cclock,scale=1280:1706,crop=1280:720:0:493,zoompan=z=1.25:y=y+0.96:x=128:d=150:s=1280x720:fps=30"
8 = "-c:v"
9 = "libx264"
10 = "-preset"
11 = "ultrafast"
12 = "-b:v"
13 = "8388608"
14 = "-an"
15 = "myvideo.mp4"
```

The output video _is_ produced. Unfortunately, `FFmpeg.execute` never returns and leaves me hanging.
I've tried many arguments combination, and keeping only the bare minimum in the command, but I can't get FFmpeg to return.

A similar command works fine on macOS with FFmpeg 4.2.2.

**Expected behavior**

I would expect `FFmpeg.execute` to return once the processing is done.

**Current behavior**

The video is produced and readable, but `FFmpeg.execute` never returns.

**Logs**

[Here's the output](https://gist.github.com/flovouin/7fc00d290b8825d9939baeadff568fd8) I get from `mobile-ffmpeg`.

**Environment**

 - Platform: Android
 - Architecture: arm64? (Google Pixel 3)
 - Version: 4.2.LTS, but I also tried 4.3.1.LTS
 - Android Studio version: 3.6

**Comment by tanersener** [comment]
Do you have the same issue on other architectures as well?

**Comment by flovouin** [comment]
Your question led me to test on other devices, and I actually realised the issue was coming from elsewhere.
Sorry for the useless notification, and thank you for replying so quickly and for your work on this project.
