### ISSUE TITLE
Fade  effects not working

### ISSUE THREAD

**Issue by binhdk** [tanersener/mobile-ffmpeg#359]
Hi Tanersener,
 I encountered  a problem with filter effect, fade filter not working when apply with overlay image.
This is my command:

ffmpeg -ss 0.000 -t 10.732 -i /storage/emulated/0/Converted/ab.mp4 -noautorotate -loop 1 -framerate 18 -ss 6.780 -t 3.943 -i /storage/emulated/0/Overlay/sticker_hi.png -filter_complex 
[0:v]setpts=1.000*PTS-STARTPTS,scale='iw*min(1280/iw,720/ih):ih*min(1280/iw,720/ih)',setsar=1,pad='1280:720:(1280-iw*min(1280/iw,720/ih))/2:(720-ih*min(1280/iw,720/ih))/2'[v0];
[0:a]asetpts=1.000*PTS-STARTPTS[a0];
[v0][a0]concat=n=1:v=1:a=1[v][a];
[v]format=yuv420p[concatOut];
[1:v] scale=296:264[scaleOut1];
[scaleOut1] rotate=-2.6529005:ow='rotw(-2.6529005)':oh='roth(-2.6529005)':c=none[rotate1];
[rotate1]format=rgba,fade=in:7:2:alpha=1[effect1];
[concatOut[effect1]overlay=537.1377:117.404045:enable='between(t,6.780,10.723)'[overlayIconOut]
 -map [overlayIconOut0] -map [a] -vsync 2 -async 1 -aspect 16:9 -c:v libx264 -preset ultrafast -crf 18 /storage/emulated/0/Pictures/export_1583467141636.mp4 -y

I fade image in 7s - 9s, but effect not showing. Am I confused somewhere?

**Comment by tanersener** [comment]
You are assigning duration values to parameters that expect frame numbers. Please check other `fade` filter parameters if you want to use duration at [fade filter documentation](https://ffmpeg.org/ffmpeg-filters.html#fade).

**Comment by binhdk** [comment]
Thank you so much!
