### ISSUE TITLE
How to convert to amr file using opencore_amr ?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#36]
@tanersener Hi Taner, I tried to convert file to amr  file using opencore_amr , but failed ? 
May I know how to use this lib via -c:v ?

Thanks.

**Comment by tanersener** [comment]
Hi, you can use the following command format;

`-i input.wav -ar 8000 -ab 12.2k -c:a libopencore_amrnb output.amr`
