### ISSUE TITLE
How to stop the ffmpeg command

### ISSUE THREAD

**Issue by gowthami77** [tanersener/mobile-ffmpeg#361]
Hi my command is for get the images from the live video. images are coming from the video but i am unable to stop the command. How can i stop the video. Please answer as soon as possible.
Thanks in advance

**Comment by tanersener** [comment]
Did you try calling `cancel` function?

**Comment by gowthami77** [comment]
yes, i called that one but that is not working. Means getting the frames continuously with out stopping.

**Comment by gowthami77** [comment]
here is my command.
 final String cmd[] = {
                "-y", "-rtsp_transport", "tcp",
                "-i",
                "url of the video",
                "-vf",
                "fps=.5",
                finalFile
        };
        int rc = FFmpeg.execute(cmd);



        if (rc == RETURN_CODE_SUCCESS) {

            Log.i(Config.TAG, "Command execution completed successfully.");
        } else if (rc == RETURN_CODE_CANCEL) {
            Log.i(Config.TAG, "Command execution cancelled by user.");
        } else {
            Log.i(Config.TAG, String.format("Command execution failed with rc=%d and the output below.", rc));
//            Config.printLastCommandOutput(Log.INFO);
        }

**Comment by tanersener** [comment]
How do you call the `cancel` method? Are you sure it is executed?

**Comment by gowthami77** [comment]
after starting this command i am calling in another button click. like this
               FFmpeg.cancel();

**Comment by gowthami77** [comment]
once the command start process nothing is working. Recently i identified that. nothing is working only continuesly getting the frames from the video.

**Comment by gowthami77** [comment]
i run that ffmpeg command in separate thread. Now i am able ho cancel the ffmpeg onGoing process. Thanks for your response.
