### ISSUE TITLE
Working with another FFMPEG Library

### ISSUE THREAD

**Issue by JChappel** [tanersener/mobile-ffmpeg#363]
**Description**
We are currently using another Framework that uses FFMPEG as well. I'm able to get mobile-FFmpeg loaded and running but when we try to play a video using our other framework our app crashes with "EXC_BAD_ACCESS".  I know it is not your framework crashing but I wanted to see if you had an idea for where the conflict may be occurring.

The function we are crashing at is loading AVFormatContext
if ((errConn = [self startConnectionWithContext:&_avFmtCtx fileName:input avInput:NULL options:&option userOptions:NULL])) {

Also, would you be available for us to speak with you about some custom development of the FFMPEG library?

**Expected behavior**
App to not crash ;)

**Current behavior**
App Crashes

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: tvOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by tanersener** [comment]
Your app crashes because `FFmpeg` implementations are not compatible with each other. See #198 for Android and [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application).

**Comment by JChappel** [comment]
Thanks, I'm working on getting it down to one FFMPEG Library. The other Library was using an older version of FFMPEG it looks like so I'm working through some of that.

On another note are you available for Custom Development, if so what would be a good way to contact you?

**Comment by tanersener** [comment]
Sorry, I don't have much time available these days. You can still reach me via `LinkedIn` or `gitter` but I'm not sure if I can help.

**Comment by JChappel** [comment]
I left you a message on Gitter, but don't know if you received it or not.

**Comment by tanersener** [comment]
I didn't receive any messages. Where is it posted?

**Comment by JChappel** [comment]
Posted on Gitter, not sure If I did it in the right spot: https://gitter.im/Taner-Sener/Lobby

**Comment by tanersener** [comment]
Sorry, I didn't join my public Lobby before.
