### ISSUE TITLE
sdl-player branch for android

### ISSUE THREAD

**Issue by ins1der1211** [tanersener/mobile-ffmpeg#364]
Can't build lib on sdl-player branch fro android.

I tried:
```
export ANDROID_HOME=/mnd/hdd/Android/Sdk && \
export ANDROID_NDK_ROOT=/mnt/hdd/Downloads/android-ndks/ndk-20 && \
./android.sh \
--disable-arm-v7a \
--disable-arm-v7a-neon \
--disable-x86-64 \
--enable-android-media-codec \
--enable-android-zlib \
--enable-sdl
```

and get this error:

CMake Error at /usr/share/cmake-3.10/Modules/Platform/Android-Determine.cmake:28 (message):
  Android: The specified CMAKE_SYSROOT:

    /mnt/hdd/Downloads/android-ndks/ndk-20/toolchains/llvm/prebuilt/linux-x86_64/sysroot

  is not an existing directory.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:130 (include)
  CMakeLists.txt:6 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by tanersener** [comment]
`sdl-player` branch is not stable. I don't recommend building it. I'm working on it from time to time, it implements `ffplay` but doesn't have a working player implementation inside right now.

By the way, the reason of your build errors can ben be cmake version. I'm running my tests using a newer cmake version, 3.16.x.

**Comment by ins1der1211** [comment]
Thank you, I'll try with newer cmake version.
