### ISSUE TITLE
libsndfile: failed

### ISSUE THREAD

**Issue by longxinlx** [tanersener/mobile-ffmpeg#365]
**Description**
./ios.sh --full --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-coreimage --enable-ios-bzip2 --enable-ios-videotoolbox --enable-ios-zlib --enable-ios-libiconv --enable-chromaprint --enable-fontconfig --enable-freetype --enable-fribidi --enable-gmp --enable-gnutls --enable-kvazaar --enable-lame --enable-libaom --enable-libass --enable-libilbc --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-opencore-amr --enable-openh264 --enable-opus --enable-sdl --enable-shine --enable-snappy --enable-soxr --enable-speex --enable-tesseract --enable-twolame --enable-wavpack --enable-gpl --enable-libvidstab --enable-x264 --enable-x265 --enable-xvidcore

**Expected behavior**
success build

**Current behavior**
libsndfile: failed

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.
https://ghostbin.co/paste/nqm6e

**Environment**
 - Platform: [e.g. Android/IOS]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by tanersener** [comment]
`make[1]: autogen: No such file or directory`

Your build fails because `autogen` is not found. Did you install all [iOS Prerequisites](https://github.com/tanersener/mobile-ffmpeg/wiki/iOS-Prerequisites)?

**Comment by longxinlx** [comment]
> `make[1]: autogen: No such file or directory`
> 
> Your build fails because `autogen` is not found. Did you install all [iOS Prerequisites](https://github.com/tanersener/mobile-ffmpeg/wiki/iOS-Prerequisites)?

thanks,  problem resolved.


by the way , do u have plan replace Android MediaPlayer And iOS AVPlayer with ffplay ?
the test-app can't play some encoded files,  for example video.mkv

**Comment by tanersener** [comment]
Unfortunately, I don't have a working `ffplay` implementation right now. If I manage to make it work I can think of replacing the players. But it is a long shot.
