### ISSUE TITLE
libwebp_anim encoder missing

### ISSUE THREAD

**Issue by MarsVard** [tanersener/mobile-ffmpeg#366]
**Description**
On desktop when I execute ffmpeg -encoders, it has 2 encoders for webp. libwebp and libwebp_anim

When I manually set libwebp_anim encoder does some magic to make animated webp look better also fixes the trailing issue that some people have been reporting on stackoverflow and other places.

On Android when I execute ffmpeg -encoders, it only has the webp encoder not the webp_anim encoder. Is this preinstalled on android or is there a way to add this encoder?

**Expected behavior**
both encoders would be present since it's the same libwebp library

**Current behavior**
webp_anim encoder not present on Android

**Environment**
 - Platform: Android
 - Architecture: arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64
 - Version: 4.3.1.LTS (also tested on other versions)

**Comment by tanersener** [comment]
Some components of `libwebp` library are disabled due to compilation errors. I suspect `libwebp_anim` is disabled due to one of those. I need to test and see if this is the case.

**Comment by MarsVard** [comment]
How can I help? Can you give me direction on where to start? I'll make a pull-request if possible.

**Comment by tanersener** [comment]
Fixed in `development`. Scripts in `development` branch builds `ffmpeg` with `libwebp_anim` encoder enabled. 

This change will be included in the next release.

**Comment by MarsVard** [comment]
Legendary, I'm here breaking my head, didn't see your message :D Cheers!

**Comment by tanersener** [comment]
Released with `v4.3.2`.
