### ISSUE TITLE
openh264 for Android arm32 does not use COMMON_ASM_ARM_SRCS

### ISSUE THREAD

**Issue by alexcohn** [tanersener/mobile-ffmpeg#367]
**Description**
Building openh264 as part of `android --full`, neon assembly files are excluded. Is this intentional?

**Expected behavior**
I thought assembly files should be included:

 	$(COMMON_SRCDIR)/arm/copy_mb_neon.S\
	$(COMMON_SRCDIR)/arm/deblocking_neon.S\
	$(COMMON_SRCDIR)/arm/expand_picture_neon.S\
	$(COMMON_SRCDIR)/arm/intra_pred_common_neon.S\
	$(COMMON_SRCDIR)/arm/mc_neon.S\

**Current behavior**
These files are excluded, by virtue of **android-openh264.sh** massaging some of original **.mk** files.

**Environment**
 - Platform: Android
 - Architecture: arm-v7a-neon
 - Version: 4.3.1
 - Source branch: master
 - Android NDK version: 21.1.6273396

**Comment by tanersener** [comment]
You're right. Those files are not built for `arm-v7a-neon`. Let me check if it possible to enable them.

**Comment by alexcohn** [comment]
> You're right. Those files are not built for `arm-v7a-neon`. Let me check if it possible to enable them.

I have a fix for that. Will prepare a pull request by tomorrow.

**Comment by tanersener** [comment]
Thanks. Can you open your pull request against `development`?

**Comment by tanersener** [comment]
Fixed in the development branch.

**Comment by tanersener** [comment]
Released with `v4.3.2`
