### ISSUE TITLE
getSupportedCameraIds() returns empty list

### ISSUE THREAD

**Issue by juha-h** [tanersener/mobile-ffmpeg#368]
In build.gradle of my app I have 
```
minSdkVersion 24
```
and dependency
```
implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.3.1'
```
In AndroidManifest.xml I have 
```
<uses-permission android:name="android.permission.CAMERA" />
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
```
and I have granted CAMERA permission to my app.

In MainActivity I have
```
import com.arthenica.mobileffmpeg.Config
...
Log.d("Baresip", "Cameras ${Config.getSupportedCameraIds(applicationContext)}")
```
which produces to log:
```
03-31 10:25:39.631 29978 29978 D Baresip : Cameras []
```
Any idea why no cameras (front or rear) are found?

**Comment by tanersener** [comment]
Did you read [Camera Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Camera-Support) wiki page? Unfortunately, some camera implementations are not supported by Android's NDK API. As a result they are not supported by `MobileFFmpeg` too. 

When `getSupportedCameraIds()` is called unsupported camera ids are listed in `logcat`. Did you check `logcat` output?

**Comment by juha-h** [comment]
Yes, I read the page and from there I learned about getSupportedCameraIds() function.  The line
```
03-31 10:25:39.631 29978 29978 D Baresip : Cameras []
``` 
in above, is the logcat output from getSupportedCameraIds() call embedded in Log.d() call.

The device that I'm using in this test is a pretty new Nokia Android One phone running Android 9.0.

**Comment by juha-h** [comment]
I AndroidManifest, I changed
```
<uses-feature
        android:name="android.hardware.camera"
        android:required="true" />
```
and the app started OK, which I think means that a camera exists.  Still getSupportedCameraIds()  returns empty list.  Unfortunately I don't have another device to test.

You can close this if the conclusion is that the camera of my device is not supported and there is nothing that can be done about it.

**Comment by tanersener** [comment]
Can you try to debug [this code block](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/java/com/arthenica/mobileffmpeg/CameraSupport.java#L48-L66) in your app and see whether your camera is supported or not?

**Comment by juha-h** [comment]
OK, will try, but need first to convert your Java code to Kotlin.

**Comment by juha-h** [comment]
This is what I got:
```
03-31 14:53:35.713  3333  3333 D Baresip : Detected camera with id 0 has LEGACY hardware level which is not supported by Android Camera2 NDK API.
03-31 14:53:35.739  3333  3333 D Baresip : Detected camera with id 1 has LEGACY hardware level which is not supported by Android Camera2 NDK API.
```
So no luck with this device.

Thanks for your help.
