### ISSUE TITLE
Audio absent on android

### ISSUE THREAD

**Issue by vuzya** [tanersener/mobile-ffmpeg#371]
**Description**
Hello! I am trying to use mobile-ffmpeg to stream from android camera. With video it works ok, but audio is absent. I was checking with commands like
`-f android_camera  -video_size hd720 -framerate 30 -i discarded -tune zerolatency -c:v libx264 -profile:v main -s 640x360 -preset fast -c:a aac -b:a 96k -b:v 650k -f flv rtmp://myserver/mystream`
and 
`-f android_camera  -video_size hd720 -framerate 30 -i 0:0 -tune zerolatency -c:v libx264 -profile:v main -s 640x360 -preset fast -c:a aac -b:a 96k -b:v 650k -f flv rtmp://myserver/mystream`
But FFmpeg output logs says that there's only one input stream "Stream #0:0: Video: rawvideo".
Am I doing something wrong? Should I use some different input for audio?

**Expected behavior**
Audio is captured

**Current behavior**
Audio is not in a stream

**Logs**
ffmpeg version git-2020-01-25-fd11dd500 Copyright (c) 2000-2020 the FFmpeg developers
  built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
  configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disa  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 65.102 / 58. 65.102
  libavformat    58. 35.101 / 58. 35.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 70.101 /  7. 70.101
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
[android_camera @ 0x7374331200] Android camera capture session is active.
Input #0, android_camera, from 'discarded':
  Duration: N/A, start: 76726.672175, bitrate: N/A
    Stream #0:0: Video: rawvideo (NV21 / 0x3132564E), nv21, 1280x720, 30 fps, 30 tbr, 1000000000.00 tbn, 1000000000.00 tbc
    Side data:
      displaymatrix: rotation of -90.00 degrees
[android_camera @ 0x7374331200] Input queue was full, dropping frame, consider raising the input_queue_size option (current value: 5)
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[graph 0 input from stream 0:0 @ 0x730cacfe00] sws_param option is deprecated and ignored
[libx264 @ 0x730cc31300] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x730cc31300] profile Main, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x730cc31300] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=5 lookahead_threads=5 sliced_threads=1 slices=5 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc=abr mbtree=0 bitrate=650 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://dealers-01.playelt.video/live/dealerSlot10196':
  Metadata:
    encoder         : Lavf58.35.101
    Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), nv21, 640x360, q=-1--1, 650 kb/s, 30 fps, 1k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.65.102 libx264
    Side data:
cpb: bitrate max/min/avg: 0/0/650000 buffer size: 0 vbv_delay: N/A
      displaymatrix: rotation of -0.00 degrees
frame=   18 fps=0.0 q=26.0 size=      45kB time=00:00:00.90 bitrate= 412.8kbits/s speed= 1.8x     frame=   33 fps= 32 q=26.0 size=      84kB time=00:00:01.40 bitrate= 493.3kbits/s speed=1.36x     [flv @ 0x7374331800] Failed to update header with correct duration.
[flv @ 0x7374331800] Failed to update header with correct filesize.
frame=   46 fps= 31 q=26.0 Lsize=     120kB time=00:00:01.83 bitrate= 534.0kbits/s speed=1.22x    
video:118kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.153547%
[libx264 @ 0x730cc31300] frame I:46    Avg QP:21.22  size:  2617
[libx264 @ 0x730cc31300] mb I  I16..4: 94.4%  0.0%  5.6%
[libx264 @ 0x730cc31300] final ratefactor: 22.44
[libx264 @ 0x730cc31300] coded y,uvDC,uvAC intra: 39.3% 12.9% 0.0%
[libx264 @ 0x730cc31300] i16 v,h,dc,p: 20% 45% 19% 16%
[libx264 @ 0x730cc31300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12%  5% 72%  2%  3%  2%  2%  1%  1%
[libx264 @ 0x730cc31300] i8c dc,h,v,p: 82% 14%  4%  1%
[libx264 @ 0x730cc31300] kb/s:628.15
[android_camera @ 0x7374331200] Android camera capture session was closed.
Exiting normally, received signal 2.

**Environment**
 - Platform: Android
 - Architecture: armv8
 - Version: release mobile-ffmpeg-full-gpl:4.3.1
 - Android Studio version 3.6.1

**Comment by tanersener** [comment]
Unfortunately, `android_camera` does not support audio and we don't have any other device that supports recording for Android. I remember I tried building `alsa` to record audio but it wasn't possible at that time.
