### ISSUE TITLE
Get wavepic from audio doesn't seem to work

### ISSUE THREAD

**Issue by SabiRoth** [tanersener/mobile-ffmpeg#372]
**Description**
I try to get the wavepic of an audio for my android app and use the command from the FFmpeg doc ("-i $audiofile  showwavespic=split_channels=1:s=1024x800 waveform.png).

**Expected behavior**
A picture with the waves should be created.

**Current behavior**
I do not get an error but the RETURN_CODE_SUCCESS condition doesn't get called so it doesn't create an image either.

**Environment**
 - Platform: Android
 - Android Studio version: 3.5.2

Did I do something wrong?

**Comment by tanersener** [comment]
Did you see anything in the `logcat`? 

You're not providing the full path in your command. Most probably you're trying to create that file in a read-only location.

**Comment by SabiRoth** [comment]
My bad of course I need audiofile.path. I'm sorry. Such a great library by the way!!
