### ISSUE TITLE
What does "-Wno-ignored-optimization-argument" mean?

### ISSUE THREAD

**Issue by AsteriskZuo** [tanersener/mobile-ffmpeg#377]
**Description**
I can not find "-Wno-ignored-optimization-argument" in Google、Bing、llvm.com, Can you explain it further? Or the official source of this usage, thank you.

**Environment**
 - Version (if applicable) [MobileFFmpeg v4.3.1 Full-GPL Mac Catalyst Beta 2, tag: 99a6f18]

**Comment by AsteriskZuo** [comment]
There are also many cflags parameters. Such as:
-Wno-unused-result
-Wno-unused-variable
-Wno-deprecated-declarations
-Wno-pointer-sign
-Wno-unused-function

**Comment by tanersener** [comment]
During the build process, I received the following warning and disabled that warning with `-Wno-ignored-optimization-argument`.

`
clang: warning: optimization flag '-finline-limit=64' is not supported [-Wignored-optimization-argument]
`

Please see documentation about [-Wignored-optimization-argument](https://clang.llvm.org/docs/DiagnosticsReference.html#wignored-optimization-argument) and [Options to Control Error and Warning Messages](https://clang.llvm.org/docs/UsersManual.html#options-to-control-error-and-warning-messages) which explains what does prefixing a warning with `no-` means.

**Comment by AsteriskZuo** [comment]
Thank you very much.
