### ISSUE TITLE
how to build 264

### ISSUE THREAD

**Issue by onexuan** [tanersener/mobile-ffmpeg#379]
I change android.sh
ENABLED_LIBRARIES=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)

build error 

-n Libraries: 
-n x264
-n , 
-n xvidcore
-n , 
-n x265
-n , 
-n libvidstab

-e 
(*) Invalid configuration detected. GPL library x264 enabled without --enable-gpl flag.

**Comment by onexuan** [comment]
Fix 
GPL_ENABLED="yes"

**Comment by tanersener** [comment]
Manually editing build scripts is not something I recommend. Do at your own risk.
