### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by AsteriskZuo** [tanersener/mobile-ffmpeg#380]
**Description**
`sh ios.sh --enable-gpl --full --enable-libvidstab --enable-rubberband --enable-x264 --enable-x265 --enable-xvidcore --disable-armv7s --disable-arm64e --disable-i386 --disable-x86-64-mac-catalyst`

The script failed to run.
`
4 warnings generated.
4 warnings generated.
  CCLD     ALAC/libalac.la
  CCLD     libsndfile.la
Making all in examples
make[1]: Nothing to be done for `all'.
Making all in tests
autogen --writable utils.def
make[1]: autogen: No such file or directory
make[1]: *** [utils.h] Error 1
make: *** [all-recursive] Error 1
`

**Logs**
[build.log](https://github.com/tanersener/mobile-ffmpeg/files/4467682/build.log)
[build.log.zip](https://github.com/tanersener/mobile-ffmpeg/files/4467684/build.log.zip)

**Environment**
 - Platform: [IOS]
 - Architecture: [arm64, x86_64]
 - Version (if applicable) [MobileFFmpeg v4.3.1 Full-GPL Mac Catalyst Beta 2, tag: 99a6f18 ]
 - Xcode version (if applicable) [Version 11.3.1 (11C504)]
 - Cocoapods version (if applicable) [1.8.4]

**Comment by AsteriskZuo** [comment]
The failure appears to have been caused by libsndfile.

**Comment by AsteriskZuo** [comment]
Building mobile-ffmpeg static library for iOS

-n Architectures: 
-n arm64
-n , 
-n x86-64

-n Libraries: 
-n ios-zlib
-n , 
-n ios-audiotoolbox
-n , 
-n ios-coreimage
-n , 
-n ios-bzip2
-n , 
-n ios-videotoolbox
-n , 
-n ios-avfoundation
-n , 
-n ios-libiconv
-n , 
-n ios-libuuid
-n , 
-n fontconfig
-n , 
-n freetype
-n , 
-n fribidi
-n , 
-n gmp
-n , 
-n gnutls
-n , 
-n lame
-n , 
-n libass
-n , 
-n libtheora
-n , 
-n libvorbis
-n , 
-n libvpx
-n , 
-n libwebp
-n , 
-n libxml2
-n , 
-n opencore-amr
-n , 
-n shine
-n , 
-n speex
-n , 
-n wavpack
-n , 
-n kvazaar
-n , 
-n x264
-n , 
-n xvidcore
-n , 
-n x265
-n , 
-n libvidstab
-n , 
-n rubberband
-n , 
-n libilbc
-n , 
-n opus
-n , 
-n snappy
-n , 
-n soxr
-n , 
-n libaom
-n , 
-n chromaprint
-n , 
-n twolame
-n , 
-n sdl
-n , 
-n tesseract
-n , 
-n openh264

-e 
Building arm64 platform

-n fribidi: 
ok
-n gmp: 
ok
-n lame: 
ok
-n libvpx: 
ok
-n libxml2: 
ok
-n opencore-amr: 
ok
-n shine: 
ok
-n speex: 
ok
-n wavpack: 
ok
-n kvazaar: 
ok
-n x264: 
ok
-n xvidcore: 
ok
-n x265: 
ok
-n libvidstab: 
ok
-n libilbc: 
ok
-n opus: 
ok
-n snappy: 
ok
-n soxr: 
ok
-n libaom: 
ok
-n chromaprint: 
ok
-n sdl: 
ok
-n openh264: 
ok
-n giflib: 
ok
-n jpeg: 
ok
-n libogg: 
ok
-n libpng: 
ok
-n nettle: 
ok
-n tiff: 
ok
-n expat: 
ok
-n libsndfile: 
failed

**Comment by AsteriskZuo** [comment]
I found out why I didn't install autogen.
I'd like to suggest that you check out the tools you need to build for each platform.
For example, under the MAC.
`
    if [ ! $(which yasm) ]; then
        log_warning_print 'Yasm not found. Trying to install...'
        brew install yasm || log_error_print "Yasm install fail."
    fi
`

**Comment by tanersener** [comment]
Prerequisites required for each platform are clearly stated in `README`. For the details, refer to [iOS Prerequisites](https://github.com/tanersener/mobile-ffmpeg/wiki/iOS-Prerequisites) wiki page.

**Comment by AsteriskZuo** [comment]
I see what you mean, but you may not quite see what I mean.
You can do better by adding the above checks to your shell script.

**Comment by tanersener** [comment]
I don't agree. Scripts are already too complex. Putting additional checks for the information which is already there doesn't make any sense. 

`make` is already checking whether `autogen` is installed or not. The following message from the log file is pretty clear. 

`make[1]: autogen: No such file or directory`

**Comment by AsteriskZuo** [comment]
OK
