### ISSUE TITLE
Can enable vo-amrwbenc library?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#381]
**Description**
can not support amr_wb encode.

**Expected behavior**
can enable vo-amrwbenc library. 
https://sourceforge.net/projects/opencore-amr/files/vo-amrwbenc/vo-amrwbenc-0.1.3.tar.gz/download

**Current behavior**
can not encode audio with amr-wb

**Screenshots**

**Logs**

**Environment**
 - Platform: [Android]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version[4.3.1]
 - Source branch  [development]
 - Android Studio version (if applicable) [3.5.2]
 - Android NDK version (if applicable) [20]

**Other**

**Comment by tanersener** [comment]
In terms of license, it looks ok. But someone has to work on build scripts.

**Comment by tanersener** [comment]
Fixed in `development`.

**Comment by zhangruiyu** [comment]
So when is the next release, we really need to support AMR_WB right now

**Comment by tanersener** [comment]
The next month. 

Btw, you can always build the `development` branch yourselves.

**Comment by zhangruiyu** [comment]
Hi, when will the update be released this month.0-0

**Comment by tanersener** [comment]
Before the end of the month.

**Comment by tanersener** [comment]
Released in `v4.4`.

**Comment by zhangruiyu** [comment]
Mobile-ffmpeg-audio is 4.4, but Libamr_WB still doesn't work
![image](https://user-images.githubusercontent.com/10591822/88997161-9bd48880-d321-11ea-84b4-f9297c5dd762.png)
![image](https://user-images.githubusercontent.com/10591822/88997213-ba3a8400-d321-11ea-8ac0-606e78d803f6.png)

**Comment by tanersener** [comment]
@zhangruiyu see #507
