### ISSUE TITLE
[Android] How to compile static ffmpeg library

### ISSUE THREAD

**Issue by codechinafly** [tanersener/mobile-ffmpeg#386]
Hi,
I modified the android-ffmpeg.sh script to compile the static ffmpeg library(use --enable-statuic and --disable-shared).
It compiles successfully, but when linking the ffmpeg static library in my project, the error ‘member at xxx is not an ELF object’ is reported.
What did I do wrong? Or how can I compile the ffmpeg library of static library

**Comment by mgood7123** [comment]
i have the ffmpeg library as shared and in a /usr/bin /usr/libs structure

**Comment by wjhtinger** [comment]
@codechinafly 
Do you have solved this? I have the same problem now

**Comment by codechinafly** [comment]
> @codechinafly
> Do you have solved this? I have the same problem now

I finally gave up

**Comment by codechinafly** [comment]
> @codechinafly
> Do you have solved this? I have the same problem now

I used the following script to compile successfully

`#!/bin/bash

#darwin linux
PLATFORM=darwin
TOOLCHAIN=${NDK_HOME}/toolchains/llvm/prebuilt/${PLATFORM}-x86_64
ANDROID_API=23

echo PLATFORM=${PLATFORM}
echo NDK_HOME=${NDK_HOME}
echo TOOLCHAIN=${TOOLCHAIN}
echo ANDROID_API=${ANDROID_API}

get_cpu_count() {
    if [ "$(uname)" == "Darwin" ]; then
        echo $(sysctl -n hw.physicalcpu)
    else
        echo $(nproc)
    fi
}

function build_ffmpeg {
	echo "Compiling FFmpeg for $CPU"
	./configure \
		--prefix=${PREFIX} \
		--pkg-config=pkg-config \
		${ASM_FLAGS} \
		--disable-decoders \
		--disable-encoders \
		--disable-shared \
		--enable-static \
		--enable-pic \
		--enable-libfreetype \
		--enable-optimizations \
		--disable-doc \
		--disable-ffmpeg \
		--disable-ffplay \
		--disable-ffprobe \
		--disable-avdevice \
		--disable-symver \
		--disable-devices \
		--disable-indevs \
		--disable-outdevs \
		--disable-parsers \
		--disable-protocols \
		--disable-demuxers \
		--disable-muxers \
		--disable-bsfs \
		--disable-network \
		--disable-filters \
		--enable-filter=drawtext \
		--disable-neon-clobber-test \
		--disable-programs \
		--disable-postproc \
		--disable-htmlpages \
		--disable-manpages \
		--disable-podpages \
		--disable-txtpages \
		--cross-prefix=${CROSS_PREFIX} \
		--target-os=android \
		--arch=${ARCH} \
		--cpu=${CPU} \
		--cc=${CC} \
		--cxx=${CXX} \
		--enable-cross-compile \
		--sysroot=${SYSROOT} \
		--extra-cflags="-Os -fpic ${OPTIMIZE_CFLAGS}" \
		--extra-ldflags="${ADDI_LDFLAGS}" \
		${ADDITIONAL_CONFIGURE_FLAG}
    make clean
    make -j$(get_cpu_count)
    make install
    echo "The Compilation of FFmpeg for $CPU is completed"
}

#armv8-a
ARCH=arm64
CPU=armv8-a
CC=${TOOLCHAIN}/bin/aarch64-linux-android${ANDROID_API}-clang
CXX=${TOOLCHAIN}/bin/aarch64-linux-android${ANDROID_API}-clang++
SYSROOT=${NDK_HOME}/toolchains/llvm/prebuilt/${PLATFORM}-x86_64/sysroot
CROSS_PREFIX=${TOOLCHAIN}/bin/aarch64-linux-android-
PREFIX=$(pwd)/android/arm64-v8a
OPTIMIZE_CFLAGS="-march=${CPU}"
ASM_FLAGS=" --enable-neon --enable-asm --enable-inline-asm"
export PKG_CONFIG_LIBDIR=/Users/xx/Desktop/workspace/mobile-ffmpeg/prebuilt/android-arm64/pkgconfig
pkg-config --libs freetype2
build_ffmpeg

#armv7-a
ARCH=arm
CPU=armv7-a
CC=${TOOLCHAIN}/bin/armv7a-linux-androideabi${ANDROID_API}-clang
CXX=${TOOLCHAIN}/bin/armv7a-linux-androideabi${ANDROID_API}-clang++
SYSROOT=${NDK_HOME}/toolchains/llvm/prebuilt/${PLATFORM}-x86_64/sysroot
CROSS_PREFIX=${TOOLCHAIN}/bin/arm-linux-androideabi-
PREFIX=$(pwd)/android/armeabi-v7a
OPTIMIZE_CFLAGS="-mfloat-abi=softfp -mfpu=vfp -marm -march=$CPU "
ASM_FLAGS=" --enable-neon --enable-asm --enable-inline-asm"
export PKG_CONFIG_LIBDIR=/Users/xx/Desktop/workspace/mobile-ffmpeg/prebuilt/android-arm/pkgconfig
pkg-config --libs freetype2
build_ffmpeg

#x86
ARCH=x86
CPU=x86
CC=${TOOLCHAIN}/bin/i686-linux-android${ANDROID_API}-clang
CXX=${TOOLCHAIN}/bin/i686-linux-android${ANDROID_API}-clang++
SYSROOT=${NDK_HOME}/toolchains/llvm/prebuilt/${PLATFORM}-x86_64/sysroot
CROSS_PREFIX=${TOOLCHAIN}/bin/i686-linux-android-
PREFIX=$(pwd)/android/x86
OPTIMIZE_CFLAGS="-march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32"
ASM_FLAGS=" --disable-neon --disable-asm --disable-inline-asm"
export PKG_CONFIG_LIBDIR=/Users/xx/Desktop/workspace/mobile-ffmpeg/prebuilt/android-x86/pkgconfig
pkg-config --libs freetype2
build_ffmpeg

#x86_64
ARCH=x86_64
CPU=x86-64
CC=${TOOLCHAIN}/bin/x86_64-linux-android${ANDROID_API}-clang
CXX=${TOOLCHAIN}/bin/x86_64-linux-android${ANDROID_API}-clang++
SYSROOT=${NDK_HOME}/toolchains/llvm/prebuilt/${PLATFORM}-x86_64/sysroot
CROSS_PREFIX=${TOOLCHAIN}/bin/x86_64-linux-android-
PREFIX=$(pwd)/android/x86_64
OPTIMIZE_CFLAGS="-march=$CPU -msse4.2 -mpopcnt -m64 -mtune=intel"
ASM_FLAGS=" --disable-neon --disable-asm --disable-inline-asm"
export PKG_CONFIG_LIBDIR=/Users/xx/Desktop/workspace/mobile-ffmpeg/prebuilt/android-x86_64/pkgconfig
pkg-config --libs freetype2
build_ffmpeg
`
