### ISSUE TITLE
How to increase speed of command in android

### ISSUE THREAD

**Issue by phukhanhlee** [tanersener/mobile-ffmpeg#387]
Example :
String command = String.format("-y -i %s -c:v libx264 %s", "input.mp4", "output.mp4");

"input.mp4" : video record from android device

                int rc = FFmpeg.execute(command);

                if (rc == Config.RETURN_CODE_SUCCESS) {
                } else if (rc == Config.RETURN_CODE_SUCCESS) {
                    Log.d(Config.TAG, "Command execution cancelled by user.");
                } else {
                    Log.d(Config.TAG, String.format("Command execution failed with rc=%d and the output below.", rc));
                    //Config.printLastCommandOutput(Log.INFO);
                }

This code run on AsyncTask

It's taking too long time to convert a video ( 2:22 minutes long - 361mb) - take more than 4minute :|
Can't wait for user.
Can we speed up the performance ?
in iOS, the compression of system very speed, we can have a compress video usually about 10 - 30s.

**Comment by tanersener** [comment]
The first thing you can try is to decrease the quality of your video by using one of the encoding/tuning options listed in [FFmpeg H.264 Video Encoding Guide](https://trac.ffmpeg.org/wiki/Encode/H.264).

If you don't want to do that I recommend reading [my previous comment](https://github.com/tanersener/mobile-ffmpeg/issues/197#issuecomment-515010678) about this.

**Comment by phukhanhlee** [comment]
Thanks for your reply. But I'm not sure some params affect to result. I checked but still 4 minutes after using "-preset ultrafast -crf"

String command = String.format("-i %s -c:v libx264 -preset ultrafast -crf 0 %s","input.mp4", "output.mp4");


Some logs : 
frame= 7562 fps= 82 q=0.0 size= 1223680kB time=00:01:03.16 bitrate=158694.1kbits/s dup=5739 drop=0 speed=0.689x

**Comment by tanersener** [comment]
`-crf 0` creates a lossless video. You can't increase the speed by using low values in `-crf`. You need to use higher values. It is all explained in the documentation page I shared. Please give a read.

**Comment by phukhanhlee** [comment]
Sorry ! 
I saw after change some values it decrease time. 4 minutes -> about 3 minutes (Also try with "-tune zerolatency")

Command:
String command = String.format("-i %s -c:v libx264 -preset ultrafast -crf 51 %s", fileSourcePath, fileDesPath);

Do you think we can optimize more ? I saw with video < 1 minutes, time to wait is acceptable. But to wait about 3 minutes still so long.

**Comment by tanersener** [comment]
For this particular video which is 360 MB, I don't think it is possible to process it under 1 min.

> in iOS, the compression of system very speed, we can have a compress video usually about 10 - 30s.

Are you using the same command on `iOS`? There's too much difference.

**Comment by phukhanhlee** [comment]
Nope, I get export video from camera roll by using normal iOS system library. You can see when you send an email from iOS and included a video for example, it's very fast even the video recorded in iPhone with same duration (2 minutes) - about 20-30s. (video export is mov)

**Comment by tanersener** [comment]
Import/export scenarios are not that simple. First of all, iOS export is decreasing the quality, dimensions, fps and format of the video before the upload. As you've said, format is not .x264 it is .mov. In order to compare the duration to do that with Android, you need to have a similar device and use the same input/output parameters for export. Without doing that comparing Android with iOS is waste of time. 

On iOS, there are some hardware assisted encoders like `h264_videotoolbox` which can be used on `ffmpeg` too. They can increase the speed for you but there does not exist a similar hardware assisted encoder on Android.

If you are targeting to implement an export video functionality for Android and compare its performance with a similar functionality on iOS, I recommend you to analyse the functionality that exist on iOS in detail first. It can help you to define more realistic performance targets on your application.

**Comment by phukhanhlee** [comment]
Thanks for you response. I know but suppose that we accepted for the lowest quality, fps or dimension change, I just want try to make the compression as fast as possible. As you can see I try with "-preset ultrafast -crf 51" but time to convert still so long. I also try with "-vf scale=480x320" but time to convert still long (>2.5 minutes)

Can you try with video about 300mb (2 minutes duration) and use ffmpeq to covert .mp4 to .mp4 with h264 encoder  in android ? I just want to know the best time we can have.

The functionality is simple. We can took a video from gallery and covert it to mp4 file as fast as possible.

**Comment by tanersener** [comment]
I don't think we are on the same page.

The test you want me to do doesn't make any sense.
- Encoding an 300 MB h264 encoded file using x264 can take X time
- Encoding a 300 MB mpeg4 file using x264 can take X/2 time
- Encoding a 300 MB mpeg4 file using h264_videotoolbox encoder can take X/3 time
- Encoding a 300 MB mpeg4 file using quicktime (mov) can take X/2 time
- Encoding a 300 MB raw video file using quicktime (mov) with different encoding profile (params) can take X/4 time

As you can see, duration totally depends on what is the input codec, output codec and other params. 300mb size and 2 minutes duration doesn't tell anything about the file itself. So making that test won't prove anything. I don't have time to make a test which has no value.

**Comment by phukhanhlee** [comment]
Ok Thanks. I understand the problem !
