### ISSUE TITLE
NDK API's

### ISSUE THREAD

**Issue by mgood7123** [tanersener/mobile-ffmpeg#388]
could you add NDK api's that i can use when using your library for `    implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2'` or do i need to manually build the library by `android.sh`

**Comment by tanersener** [comment]
I don't understand your question. You don't need to have NDK to use packages from `jcenter()`.

**Comment by mgood7123** [comment]
i meant like, if i obtain the library via
`implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2'`
how would i access the API's and stuff (such as headers and libraries) from C++ instead of from java/kotlin

**Comment by mgood7123** [comment]
for example, if my audio engine is C++ based instead of Java/Kotlin based

**Comment by tanersener** [comment]
`implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2'` includes `MobileFFmpeg` Java library for Android. This library includes native libraries inside but native headers are not included. It's not a choice, it is how `.aar` are packaged on Android.

If you want to access native headers and libraries then you don't need to have `implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2'` in your app. Compile `ffmpeg` and include it in your application.

**Comment by mgood7123** [comment]
aww ok

**Comment by alexcohn** [comment]
Actually, this topic is addressed by https://github.com/alexcohn/mobile-ffmpeg/tree/feature/prefab (WIP: the prefab tool is still pending official release by Google).

**Comment by mgood7123** [comment]
note that with Android 4.0 AAR packages now allow the packaging of JNI libraries

```
Additionally, an AAR file may include one or more of the following optional entries:

    /assets/
    /libs/name.jar
    /jni/abi_name/name.so (where abi_name is one of the Android supported ABIs)
    /proguard.txt
    /lint.jar
    /api.jar
```

https://youtu.be/f1fHPqAYj5I?t=573

**Comment by alexcohn** [comment]
@mgood7123 Unfortunately, https://developer.android.com/studio/projects/android-library#aar-contents is misleading. A typical prefab AAR contains **prefab** folder that is not listed in the doc, but does not include **classes.jar** or other entries that are listed as _mandatory_ there.

The only entry in the AAR that Gradle Android Plugin requires to use it as a dependency, is **`/AndroidManifest.xml`**.

**Comment by mgood7123** [comment]
oh ok

**Comment by GilbertusAlbans** [comment]
Please, please, please do this enhancement. I need those .h's and .so's. Who would write in java or swift when we have Qt, right? And I have no intention of spoiling my beautiful cross-platform c++ code with another layer of jni wrapper class unless absolutely necessary.

> If you want to access native headers and libraries then you don't need to have implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2' in your app. Compile ffmpeg and include it in your application.

Could you elaborate on this? I want to do exactly that (the native/cpp way not the jni/aar way), and I would if I could. I don't believe just removing the mobile-ffmpeg dependency would pull the ffmpeg code and put it in cpp folder with the right flags and all. Am I wrong?
Thank you for this well maintained repo by the way.

**Comment by alexcohn** [comment]
> I want to do exactly that (the native/cpp way not the jni/aar way), and I would if I could. I don't believe just removing the mobile-ffmpeg dependency would pull the ffmpeg code and put it in cpp folder with the right flags and all. Am I wrong?

Actually, this is exactly what you will receive. Run the `./android.sh` script (with additional parameters of your choice), and you will find directory `./prebuilt/android-arm64/ffmpeg/include` with all public ffmpeg headers (tuned for arm64), and `./prebuilt/android-arm64/ffmpeg/lib` with `libavcodec.so  libavdevice.so  libavfilter.so  libavformat.so  libavutil.so  libswresample.so  libswscale.so` built with the right flags and all. You can even find the **Android.mk** file in `./android/jni/ffmpeg`. Then, it's enough to `$(call import-module, ffmpeg)` in your **Android.mk** to have it all working. You can use `./android/jni/Android.mk` as an example.

**Comment by mgood7123** [comment]
Oh
