### ISSUE TITLE
Package %DEPENDENCIES% was not found in the pkg-config search path

### ISSUE THREAD

**Issue by mgood7123** [tanersener/mobile-ffmpeg#391]
**Description**
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found

**Expected behavior**
ffmpeg to succeed

**Current behavior**
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found

**Screenshots**

**Logs**
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found
Package %DEPENDENCIES% was not found in the pkg-config search path.
Perhaps you should add the directory containing `%DEPENDENCIES%.pc'
to the PKG_CONFIG_PATH environment variable
Package '%DEPENDENCIES%', required by 'rubberband', not found

**Environment**
 - Platform: Android
 - Architecture: arm-v7a-neon
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1] 10.3
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1] 4.0
 - Android NDK version (if applicable) [e.g. 16b, 17c] 21.0.6

**Other**

**Comment by tanersener** [comment]
Another error caused by `SED_INLINE`. See #389.
