### ISSUE TITLE
ERROR: rubberband >= 1.8.1 not found using pkg-config

### ISSUE THREAD

**Issue by mgood7123** [tanersener/mobile-ffmpeg#392]
**Description**
`ERROR: rubberband >= 1.8.1 not found using pkg-config` when using ffmpeg

**Expected behavior**
rubberband to be found

**Current behavior**
`ERROR: rubberband >= 1.8.1 not found using pkg-config`

**Screenshots**

**Logs**
https://ghostbin.co/paste/xktgp

**Environment**
 - Platform: Android
 - Architecture: arm-v7a-neon
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1] 10.3
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1] 4.0
 - Android NDK version (if applicable) [e.g. 16b, 17c] 21.0.6

**Other**

**Comment by tanersener** [comment]
See [Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) wiki page.
