### ISSUE TITLE
NDK 20 libvorbis: fail

### ISSUE THREAD

**Issue by mgood7123** [tanersener/mobile-ffmpeg#393]
**Description**
libvorbis fails to build on arm64-v8a and x86

**Expected behavior**
libvorbis suceeds

**Current behavior**
configure: error: Ogg >= 1.0 required !

**Screenshots**

**Logs**
https://ghostbin.co/paste/gbpyw

**Environment**
 - Platform: Android
 - Architecture: x86
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1] 10.3
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1] 4.0
 - Android NDK version (if applicable) [e.g. 16b, 17c] 21.0.6

**Other**
all the libraries (except ffmpeg) where saying already-built even tho i only built them for `arm-v7a-neon`

**Comment by tanersener** [comment]
1. Try to rebuild `libogg`.
2. Sometimes this error occurs if you have `libogg` installed on your computer. If the error persists remove `libogg` library from your computer.

**Comment by mgood7123** [comment]
ill try that
