### ISSUE TITLE
How to FFmpeg Exception Handling?

### ISSUE THREAD

**Issue by audxo112** [tanersener/mobile-ffmpeg#395]
**Description**
I felt very satisfied using the library here.
While using it, I wondered where to deal with FFmpeg if it fails.
FFmpeg only has a statement of execution
Config did not find any part that has Callback.
How can I Exception Handling?

**Expected behavior**
I want to define callback for errors

**Current behavior**
I don't know how to handle the error

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
com.arthenica:mobile-ffmpeg-min-gpl:4.3.1.LTS
 - Android Studio version **3.6.2**
 - Android NDK version (if applicable) [e.g. 16b, 17c]

I'm sorry I asked you a strange question.
FFmpeg return 0 takes advantage of the fact that it is a success.
I got to know by reading Wiki.

**Comment by mgood7123** [comment]
try reading the documentation for the FFmpeg API itself?

**Comment by tanersener** [comment]
`MobileFFmpeg` API  does not throw exceptions when it receives an error. You can receive errors coming from Android Runtime or JNI, if you do something wrong but they are very rare.

Defining an error callback makes sense only if you have an async API. However `MobileFFmpeg` Android API is mostly synchronous. You'll have the return code at the end of your call. So, I don't think you need an error callback. 

If you are calling `MobileFFmpeg` API asynchronously then you can use [AsyncSingleFFmpegExecuteTask](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/java/com/arthenica/mobileffmpeg/util/AsyncSingleFFmpegExecuteTask.java#L27) in which you can define a callback for both success and failure cases.
