### ISSUE TITLE
iOS Encoders like libxvid, libx265 etc seems to be missing

### ISSUE THREAD

**Issue by saqibdb** [tanersener/mobile-ffmpeg#400]
**Description**
I am trying to convert mov (h264) to avi(xvid) and mkv(h265). But whenever i try to use the respective encoders for these, i get "Unknown encoder" error, I see these encoders are supported but they are not working.

**Expected behavior**
Convert the video to respective formats using these encoders.

**Current behavior**
Error = Unknown encoder "libxvid" , "libx265".

**Screenshots**
[https://prnt.sc/s561ez](url)

**Logs**
`Command execution failed with rc=%d and output=%@.
 1 Optional("Input #0, mov,mp4,m4a,3gp,3g2,mj2, from \'file:///var/mobile/Media/DCIM/100APPLE/IMG_0962.MOV\':\n  Metadata:\n    major_brand     : qt  \n    minor_version   : 0\n    compatible_brands: qt  \n    creation_time   : 2020-04-22T19:09:47.000000Z\n  Duration: 00:00:05.60, start: 0.000000, bitrate: 4179 kb/s\n    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt709/bt709/unknown), 750x1334, 4232 kb/s, 29.91 fps, 30 tbr, 600 tbn, 1200 tbc (default)\n    Metadata:\n      creation_time   : 2020-04-22T19:09:47.000000Z\n      handler_name    : Core Media Video\n      encoder         : H.264\n    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 2 kb/s (default)\n    Metadata:\n      creation_time   : 2020-04-22T19:09:47.000000Z\n      handler_name    : Core Media Audio\nPlease use -q:a or -q:v, -qscale is ambiguous\nUnknown encoder \'libxvid\'\n")`

**Environment**
 - Platform: IOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version 4.3.2
 - Source branch master
 - Xcode version 11.4
 - Cocoapods version 1.9.1

**Other**
Here is the FFMPEG command 
`-hide_banner -y -i (input).MOV -qscale 0 -c:v libxvid  (output).avi`

**Comment by tanersener** [comment]
Which `mobile-ffmpeg` package do you use? You need to use one of the `GPL` licensed packages, the ones which end with `-gpl`.

**Comment by saqibdb** [comment]
> Which `mobile-ffmpeg` package do you use? You need to use one of the `GPL` licensed packages, the ones which end with `-gpl`.

Ok yeah that worked. I missed that part. I was wondering why these were used in the test-app if there is no support of them, maybe chaging the podfile [here](https://github.com/tanersener/mobile-ffmpeg/blob/master/ios/test-app/pods-with-tooltips/Podfile) would be less confusing.

Thanks for the quick fix
