### ISSUE TITLE
FFmpeg join mp4 videos

### ISSUE THREAD

**Issue by rennovale** [tanersener/mobile-ffmpeg#401]
**Description**
When i'm trying to join three videos with different FPS and TBN, the library returns an error:
```
16467-16704/com.my.myapplication E/mobile-ffmpeg: [mpeg4 @ 0x90445000] timebase 1/1000000 not supported by MPEG 4 standard, the maximum admitted value for the timebase denominator is 65535
2020-04-25 12:45:14.507 16467-16704/com.my.myapplication E/mobile-ffmpeg: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**The prob of first file** 

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video_base_1080p.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2020-04-24T14:49:05.000000Z
    encoder         : Lavf58.42.100
  Duration: 00:00:07.04, start: 0.000000, bitrate: 1594 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1463 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2020-04-24T14:49:05.000000Z
      handler_name    : VideoHandler
    Stream #0:1(por): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      creation_time   : 2020-04-24T14:49:05.000000Z
      handler_name    : SoundHandler

**The prob of second file** 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid_dire01_seq01.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : 2020/04/10 10:32:38
    encoder         : Lavf58.12.100
  Duration: 00:00:24.13, start: 0.000000, bitrate: 869 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 680 kb/s, 24 fps, 24 tbr, 90k tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 183 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**The command i'm using**
```

String[] s = new String[]{
                        "-i", "/storage/emulated/0/Pictures/vid_dire01_seq01.mp4",
                        "-i", "/storage/emulated/0/Pictures/video_base_1080p.mp4",
                        "-i", "/storage/emulated/0/Pictures/vid_dire01_seq01.mp4",
                        "-filter_complex",
                        "[0:v:0] [0:a:0][1:v:0][1:a:0][2:v:0][2:a:0]concat=n=3:v=1:a=1[outv][outa]",
                        "-map", "[outv]",
                        "-map", "[outa]",
                        "-vsync", "0",
                        "/storage/emulated/0/Pictures/output.mp4"};
                int rc = FFmpeg.execute(s);
```

**I was using [bravobit library](https://github.com/bravobit/FFmpeg-Android), and this command worked perfectly without any problems**. However i needed to change to this library and this error happened.

**Using this command in Windows 10 x64 [FFmpeg](https://www.ffmpeg.org/) works fine too**. Version ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019

**My Build Gradle**
```
compileSdkVersion 29
    buildToolsVersion "29.0.1"
    defaultConfig {
        applicationId "com.my.myapplication"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

**Dependencies**
I added just this line 
```
dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.3.2'
}
```

**Verified**
If i use the same file as input, the error won't happen. 
`-i vid_dire01_seq01 -i vid_dire01_seq01 -i vid_dire01_seq01.mp4`
Clearly the error only happens because files specs are different. I tried to change some of them to be equal, but the errors persists.

**Solution**
If the solution is related to change the files specs please tell me. I can change the file "vid_dire01_seq01.mp4" as i wish. However, i can't change second file video_base_1080p specs, because it's a file recorded by smartphone camera.

Please give me a feedback, 
Thanks a lot

**Comment by tanersener** [comment]
`[0:v]setpts=PTS-STARTPTS,scale=1920x1080,fps=24,format=yuv420p[video0]`

Instead of directly using `[0:v:0]` in `concat`, use the filter chain above to normalise video streams first and concatenate outputs of those in `concat`. You may need to do the same thing for audio too.

**Comment by rennovale** [comment]
Well thanks for your answer, i appreciate it very much. Just to check if i'm doing it correctly:

`ffmpeg -i vid_dire01_seq01.mp4 -i video_base_1080p.mp4 -i vid_dire01_seq01.mp4 -filter_complex "[0:v]setpts=PTS-STARTPTS,scale=1920x1080,fps=24,format=yuv420p[video0];[1:v]setpts=PTS-STARTPTS,scale=1920x1080,fps=24,format=yuv420p[video1];[2:v]setpts=PTS-STARTPTS,scale=1920x1080,fps=24,format=yuv420p[video2];[video0][0:a:0][video1][1:a:0][video2][2:a:0]concat=n=3:v=1:a=1[outv][outa]" -map [outv] -map [outa] -vsync 0 output.mp4`

The full command i'm using now is above, and it works perfectly. So thanks a lot again. I didn't notice any audio issues. But just to make sure, how should i approach to do the same with the audio?

**Comment by tanersener** [comment]
`[0:a]aformat=sample_fmts=fltp:sample_rates=48000:channel_layouts=stereo[audio0]`

I'm doing the same thing for audio, using the filter chain above to normalise audio.

**Comment by rennovale** [comment]
You are awesome, thank you very much. Fully resolved.
