### ISSUE TITLE
[SWIFT]StatisticsDelegate's statisticsCallback function is only being called thrice

### ISSUE THREAD

**Issue by saqibdb** [tanersener/mobile-ffmpeg#402]
**Description**
StatisticsDelegate's statisticsCallback function is only being called thrice, Once at the start of the execution and twice at the end of the execution, i need to display the progress bar but the delegate is not being called like each iteration etc

**Expected behavior**
statisticsCallback should be getting called time to time when some progress is made. I tried the test-app(objective C) from the repo and it works perfectly in that , i set the StatisticsDelegate in the viewdidload().

**Current behavior**
StatisticsDelegate's statisticsCallback function is only being called thrice, Once at the start of the execution and twice at the end of the execution. I have couple of execution that does take more than 10 seconds to do but still there is no regular callback in the delegations.

**Screenshots**
https://prnt.sc/s6a2lg

**Logs**
`2020-04-26 22:34:17.804805+0500 ScreenCapturer[2747:856661] Loaded mobile-ffmpeg-full-gpl-arm64-4.3.1-20200125
Selected item: .webm(VP8, slow) at index: 2
COMMAND = -hide_banner -y -i file:///var/mobile/Media/DCIM/101APPLE/IMG_1026.MOV -qscale 0 -crf 10 -c:v libvpx -q:v 1 -preset slow -vb 20M  file:///var/mobile/Containers/Data/Application/5DCC4C85-EE65-4E0C-813D-0B0778DD9274/Documents/Video_exported/IMG_1026.webm
statistics = 0
statistics = 3754
statistics = 3774
Command execution completed successfully.

2020-04-26 22:34:27.336773+0500 ScreenCapturer[2747:856661] creating player instance using shared library
2020-04-26 22:34:27.626081+0500 ScreenCapturer[2747:856661] Metal GPU Frame Capture Enabled
2020-04-26 22:34:27.626837+0500 ScreenCapturer[2747:856661] Metal API Validation Enabled
`

**Environment**
 - IOS[SWIFT]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version 'mobile-ffmpeg-full-gpl', '4.3.1'
 - Source branch master
 - Xcode version 11.4

**Other**
I dont know if it is related to actual command or the swift language (though i doubt that).
Here is also the code for better understanding.

`
import UIKit
import Photos
import AVKit
import DropDown
import SwiftSpinner
import Foundation
import mobileffmpeg

typealias Dispatch = DispatchQueue
class PlayerViewController: UIViewController {
    var selectedAsset : PHAsset!
    @IBOutlet weak var topView: UIView!
    @IBOutlet weak var playerView: UIView!
    let formatDropDown = DropDown()
    @IBOutlet weak var formatTxt: UITextField!
    @IBOutlet weak var formatBtn: UIButton!
    let avController = AVPlayerViewController()
    var selectedExt = ""
    var customOptions = ""

    override func viewDidLoad() {
        super.viewDidLoad()

        self.view.layoutIfNeeded()
        
        selectedAsset.getURL { (url) in
            DispatchQueue.main.async {
                let player = AVPlayer(url: url!)
                self.avController.player = player
                // your desired frame
                self.avController.view.frame = self.playerView.bounds
                self.playerView.addSubview(self.avController.view)
                self.addChild(self.avController)
                player.play()
            }
        }

        formatDropDown.anchorView = formatTxt
        formatDropDown.dataSource =  [".mp4(H.264)", ".mov(H.264)", ".webm(VP8, slow)", ".mpg(MPEG1)", ".avi(Xvid)", ".mkv(H.264)", ".mkv(H.265, slow)", ".m2ts(H.264)", ".wmv(WMV)", ".gif"]        
        
        formatDropDown.width = self.formatBtn.frame.size.width - 30.0
        formatDropDown.selectionAction = { [unowned self] (index: Int, item: String) in
            print("Selected item: \(item) at index: \(index)")
            self.formatDropDown.hide()
            self.formatTxt.text = item
            self.selectExtension(fromFormat: item)
            self.selectCustomOptions(fromFormat: item)
        }
        // Do any additional setup after loading the view.
        DispatchQueue.main.async {
            MobileFFmpegConfig.setLogDelegate(self)
            MobileFFmpegConfig.setStatisticsDelegate(self)
        }    
    }
  
    @IBAction func formatDropDownAction(_ sender: UIButton) {
        formatDropDown.show()
    }
    
    @IBAction func convertAction(_ sender: UIButton) {
        //MobileFFmpeg.execute("-codecs")
        //MobileFFmpeg.execute("-formats")
        MobileFFmpegConfig.setLogDelegate(self)
        MobileFFmpegConfig.resetStatistics()

        selectedAsset.getURL { (url) in
            DispatchQueue.main.async {
                SwiftSpinner.show("Converting...")

                let destinationUrl = self.getDocumentsDirectoryWithVideoFolder().appendingPathComponent((url?.absoluteString.simpleFileName())!)
                
                var scaleOption = "-qscale 0"
                let outputString = "\(destinationUrl.absoluteString).\(self.selectedExt)"
                let command = "-hide_banner -y -i \((url?.absoluteString)!) \(scaleOption) \(self.customOptions) \(outputString)"
                print("COMMAND = \(command)")
                
                Dispatch.background {
                    // do stuff
                    let rc = MobileFFmpeg.execute(command)

                    Dispatch.main {
                        if (rc == RETURN_CODE_SUCCESS) {
                            SwiftSpinner.hide()
                            AlertsPopUps.showPopupMessage(title: "Success", titleColor: .white, description: "Converted Successfully.", descriptionColor: .white, buttonTitleColor: .darkSubText, buttonBackgroundColor: .white, image: UIImage(named: "whiteExclamation")!, type: .success)

                            print("Command execution completed successfully.\n");
                            let newUrl = URL(string: outputString)
                            self.performSegue(withIdentifier: "ToConverted", sender: newUrl)
                            
                        } else if (rc == RETURN_CODE_CANCEL) {
                            SwiftSpinner.hide()
                            AlertsPopUps.showPopupMessage(title: "Cancelled", titleColor: .white, description: "Operation cancelled.", descriptionColor: .white, buttonTitleColor: .darkSubText, buttonBackgroundColor: .white, image: UIImage(named: "whiteExclamation")!, type: .warning)

                            print("Command execution cancelled by user.\n")
                        } else {
                            SwiftSpinner.hide()
                            AlertsPopUps.showPopupMessage(title: "Failed!!!", titleColor: .white, description: "Please try again!", descriptionColor: .white, buttonTitleColor: .darkSubText, buttonBackgroundColor: .white, image: UIImage(named: "failedIcon")!, type: .error)

                            print("Command execution failed with rc=%d and output=%@.\n", rc, MobileFFmpegConfig.getLastCommandOutput() as Any);
                        }
                    }
                }
            }
        }
        
    }
    
    
    func getDocumentsDirectoryWithVideoFolder() -> URL {
        
        let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        let dataPath = documentsDirectory.appendingPathComponent("Video_exported")
        
        do {
            try FileManager.default.createDirectory(atPath: dataPath.path, withIntermediateDirectories: true, attributes: nil)
        } catch let error as NSError {
            print("Error creating directory: \(error.localizedDescription)")
        }
        return dataPath
        
    }
    
    func selectExtension(fromFormat format : String){
        if format == ".mp4(H.264)" {
            selectedExt = "mp4"
        } else if format == ".mov(H.264)" {
            selectedExt = "mov"
        } else if format == ".webm(VP8, slow)" {
            selectedExt = "webm"
        } else if format == ".mpg(MPEG1)" {
            selectedExt = "mpg"
        } else if format == ".avi(Xvid)" {
            selectedExt = "avi"
        } else if format == ".rmv(RealVideo)" {
            selectedExt = "rm"
        } else if format == ".mkv(H.264)" {
            selectedExt = "mkv"
        } else if format == ".mkv(H.265, slow)" {
            selectedExt = "mkv"
        } else if format == ".m2ts(H.264)" {
            selectedExt = "m2ts"
        } else if format == ".wmv(WMV)" {
            selectedExt = "wmv"
        } else if format == ".gif" {
            selectedExt = "gif"
        } else {
            selectedExt = "mp4"
        }
    }
    
    
    func selectCustomOptions(fromFormat format : String){
       
        if format == "x265" {
            customOptions = "-crf 28 -preset fast "
        } else if format == ".webm(VP8, slow)" {
            customOptions = "-crf 10 -c:v libvpx -q:v 1 -preset slow -vb 20M "
        }  else if format == ".mov(H.264)" {
            customOptions = "-format hap_q -c:v h264 "
        } else if format == ".mp4(H.264)" {
            customOptions = "-c:v h264 -q:v 1 -preset slow -vb 20M "
        } else if format == ".mkv(H.264)" {
            customOptions = "-c:v h264_videotoolbox -q:v 1 -preset slow -vb 20M "
        } else if format == ".mkv(H.265, slow)" {
            customOptions = "-c:v libx265 -q:v 1 -preset slow -vb 20M "
        } else if format == ".m2ts(H.264)" {
            customOptions = "-c:v h264 -q:v 1 -preset slow -vb 20M "
        } else if format == ".avi(Xvid)" {
            customOptions = "-c:v libxvid -q:v 1 -preset slow -vb 20M "

        } else if format == ".rmv(RealVideo)" {
            customOptions = "-g 12 -r 30 -s qcif -vcodec rv20 "

        }else if format == ".wmv(WMV)" {
            customOptions = "-c:v wmv1 "
        }else if format == ".gif" {
            customOptions = ""
        } else {
            customOptions = ""
        }//libxvid
    }
    

    
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
        if segue.destination is ConvertedPlayerViewController {
            let vc = segue.destination as! ConvertedPlayerViewController
            vc.convertedURL = (sender as! URL)
            vc.selectedExt = self.selectedExt
        }
    }
    

}
extension PHAsset {

    func getURL(completionHandler : @escaping ((_ responseURL : URL?) -> Void)){
        if self.mediaType == .image {
            let options: PHContentEditingInputRequestOptions = PHContentEditingInputRequestOptions()
            options.canHandleAdjustmentData = {(adjustmeta: PHAdjustmentData) -> Bool in
                return true
            }
            self.requestContentEditingInput(with: options, completionHandler: {(contentEditingInput: PHContentEditingInput?, info: [AnyHashable : Any]) -> Void in
                completionHandler(contentEditingInput!.fullSizeImageURL as URL?)
            })
        } else if self.mediaType == .video {
            let options: PHVideoRequestOptions = PHVideoRequestOptions()
            options.version = .original
            PHImageManager.default().requestAVAsset(forVideo: self, options: options, resultHandler: {(asset: AVAsset?, audioMix: AVAudioMix?, info: [AnyHashable : Any]?) -> Void in
                if let urlAsset = asset as? AVURLAsset {
                    let localVideoUrl: URL = urlAsset.url as URL
                    completionHandler(localVideoUrl)
                } else {
                    completionHandler(nil)
                }
            })
        }
    }
}

extension PlayerViewController : LogDelegate ,StatisticsDelegate{
    func logCallback(_ level: Int32, _ message: String!) {
        Dispatch.main.async {
            //print("logCallback = \(MobileFFmpegConfig.getLastReceivedStatistics()?.getTime())")

        }
    }
    
    func statisticsCallback(_ statistics: Statistics!) {
        Dispatch.main.async {
            print("statistics = \(statistics.getTime())")
        }
    }  
}

extension String {

    func fileName() -> String {
        return URL(fileURLWithPath: self).deletingPathExtension().absoluteString
    }

    func fileExtension() -> String {
        return URL(fileURLWithPath: self).pathExtension
    }
    
    func simpleFileName() -> String {
        return URL(fileURLWithPath: self).deletingPathExtension().lastPathComponent
    }
}

extension Dispatch {

    static func background(_ task: @escaping () -> ()) {
        Dispatch.global(qos: .background).async {
            task()
        }
    }

    static func main(_ task: @escaping () -> ()) {
        Dispatch.main.async {
            task()
        }
    }
}
`

**Comment by tanersener** [comment]
I recommend two things.

1. Adding ` -v info` option to your command.
2. Running exactly the same command with the same input file on iOS `test-app` and comparing the outputs.

Output of these two tests can explain if there is something is wrong in your application.

**Comment by saqibdb** [comment]
Ok After a thorough testing, here are the results:

- When i execute the same command in the test-app, the delegate works perfectly so it is not due to command.
- I copied the whole code from test-app and placed it in my project and executed the same command but again even with test-app code in my project, the issue remains with delegate so it is not due to swift and objective c code
- I even tried different versions of the library but still the problem persists.

Now my conclusion or theory is it might be due to other dependencies in the project, i am using MobileVLCKit as well, maybe they are interferring with this or something. OR I am missing some crucial thing that is needed to be done like in some other class (appdelegate though i have double checked it)

**Comment by tanersener** [comment]
`MobileVLCKit` includes an `FFMpeg` implementation inside too. So that can be the reason of this behaviour. 

Also, log output printed by `MobileFFmpeg` includes hints if another `FFmpeg` implementation is found in the application. You can check your logs and see it if that is the case.
