### ISSUE TITLE
[Android] E/libEGL: call to OpenGL ES API with no current context (logged once per thread) when canceling FFmpeg

### ISSUE THREAD

**Issue by chaocharleswang** [tanersener/mobile-ffmpeg#403]
When I call `FFmpeg.cancel()`
Get the following error:

E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
E/libEGL: validate_display:91 error 3008 (EGL_BAD_DISPLAY)
E/chromium: [ERROR:mailbox_manager_sync.cc(57)] eglCreateSyncKHR failed
E/libEGL: validate_display:91 error 3008 (EGL_BAD_DISPLAY)
E/chromium: [ERROR:mailbox_manager_sync.cc(57)] eglCreateSyncKHR failed
    
    --------- beginning of crash
A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x74dc1bee28)
E/libEGL: validate_display:91 error 3008 (EGL_BAD_DISPLAY)
    validate_display:91 error 3008 (EGL_BAD_DISPLAY)
E/chromium: [ERROR:android_image_reader_utils.cc(19)] Failed to create android native fence sync object.

**Comment by 1van** [comment]
how to resolve this

**Comment by tanersener** [comment]
@1van see #132
