### ISSUE TITLE
Cannot encode video in MP4

### ISSUE THREAD

**Issue by seccpur** [tanersener/mobile-ffmpeg#406]
**Description**
Successfully  installed mobile-ffmpeg from git. Trying to convert an mp3 along with an image into mp4.

`-y -loop 1 -framerate 1 -i "/storage/emulated/0/Download/test.jpg" -i "/storage/emulated/0/Download/test.mp3" -c:v libx264 -c:a libmp3lame -shortest "/storage/emulated/0/Download/test.mov"`

**Expected behavior**
Convert the mp3 along with the image into mp4.

**Current behavior**
Message displays  "unknown encoder libx264"

**Environment**
 - Platform: Android
 - Source branch: master
 - Android Studio version:3.5.3

**Log**

> 
> I/mobile-ffmpeg: Loading mobile-ffmpeg.
> I/mobile-ffmpeg: Loaded mobile-ffmpeg-full-x86-4.3.2-20200415.
> D/mobile-ffmpeg: Deleted old temporary font configuration: true.
> D/mobile-ffmpeg: Callback thread started.
> D/mobile-ffmpeg: Saved new temporary font configuration with 1 font name mappings.
> D/mobile-ffmpeg: Font directory /data/user/0/com.arthenica.mobileffmpeg.test/cache registered successfully.
> D/AIR Imphal AV Convertor: Application fonts registered.
>  D/AIR Imphal AV Convertor: Listing supported camera ids.
>  I/CameraManagerGlobal: Connecting to camera service
> D/AIR Imphal AV Convertor: Supported camera detected: 0
> D/AIR Imphal AV Convertor: Supported camera detected: 1
> D/AIR Imphal AV Convertor: Last command output was: 
>  I/AIR Imphal AV Convertor: Command Tab Activated
> D/HostConnection: HostConnection::get() New Host Connection established 0xd14dfe10, tid 10597
> D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
> W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
> D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
> D/EGL_emulation: eglCreateContext: 0xdca60060: maj 3 min 0 rcv 3
> D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> W/Gralloc3: mapper 3.x is not supported
> D/HostConnection: createUnique: call
>  D/HostConnection: HostConnection::get() New Host Connection established 0xd14e1c60, tid 10597
> D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
> D/eglCodecCommon: allocate: Ask for block of size 0x1000
>  D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3ff805000 size 0x2000
> D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
> D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10564/com.arthenica.mobileffmpeg.test I/AssistStructure: Flattened final assist data: 2388 bytes, containing 1 windows, 15 views
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10564/com.arthenica.mobileffmpeg.test W/TextClassifierService: Package or service not found in package com.google.android.as for user 0
> 10564-10564/com.arthenica.mobileffmpeg.test W/TextClassifierService: Package or service not found in package com.google.android.as for user 0
> 10564-10603/com.arthenica.mobileffmpeg.test W/TextClassifierService: Package or service not found in package com.google.android.as for user 0
> 10564-10603/com.arthenica.mobileffmpeg.test D/androidtc: Loading ModelFile { path=/data/misc/textclassifier/lang_id.model name=lang_id.model version=0 locales=und }
> 2020-04-28 22:43:53.285 10564-10603/com.arthenica.mobileffmpeg.test D/androidtc: Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=707 locales=en }
> 10564-10603/com.arthenica.mobileffmpeg.test I/tflite: Initialized TensorFlow Lite runtime.
> 10564-10603/com.arthenica.mobileffmpeg.test W/LabeledIntent: resolveInfo or activityInfo is null
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10603/com.arthenica.mobileffmpeg.test W/TextClassifierService: Package or service not found in package com.google.android.as for user 0
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/OpenGLRenderer: endAllActiveAnimators on 0xbdbff880 (RippleDrawable) with handle 0xe7b89210
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10564/com.arthenica.mobileffmpeg.test D/AV Convertor: Testing FFmpeg COMMAND synchronously.
> 10564-10564/com.arthenica.mobileffmpeg.test D/ AV Convertor: FFmpeg process started with arguments
>     '-y -loop 1 "/storage/emulated/0/Download/test.jpg" -i "/storage/emulated/0/Download/test.mp3" -c:v libx264 -c:a libmp3lame -shortest "/storage/emulated/0/Download/test.mov"'
> 10564-10600/com.arthenica.mobileffmpeg.test E/mobile-ffmpeg: Exception thrown inside LogCallback block
>     android.util.AndroidRuntimeException: I am test exception thrown by test application
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$3.apply(CommandTabFragment.java:131)
>         at com.arthenica.mobileffmpeg.Config.log(Config.java:232)
> 0564-10600/com.arthenica.mobileffmpeg.test I/chatty: uid=10136(com.arthenica.mobileffmpeg.test) Thread-2 identical 13 lines
> 10564-10600/com.arthenica.mobileffmpeg.test E/mobile-ffmpeg: Exception thrown inside LogCallback block
>     android.util.AndroidRuntimeException: I am test exception thrown by test application
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$3.apply(CommandTabFragment.java:131)
>         at com.arthenica.mobileffmpeg.Config.log(Config.java:232)
> 10564-10564/com.arthenica.mobileffmpeg.test D/AIR Imphal AV Convertor: FFmpeg process exited with rc 1
> 10564-10600/com.arthenica.mobileffmpeg.test E/mobile-ffmpeg: Exception thrown inside LogCallback block
>     android.util.AndroidRuntimeException: I am test exception thrown by test application
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$3.apply(CommandTabFragment.java:131)
>         at com.arthenica.mobileffmpeg.Config.log(Config.java:232)
> 10564-10600/com.arthenica.mobileffmpeg.test I/chatty: uid=10136(com.arthenica.mobileffmpeg.test) Thread-2 identical 48 lines
> 10564-10600/com.arthenica.mobileffmpeg.test E/mobile-ffmpeg: Exception thrown inside LogCallback block
>     android.util.AndroidRuntimeException: I am test exception thrown by test application
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$3.apply(CommandTabFragment.java:131)
>         at com.arthenica.mobileffmpeg.Config.log(Config.java:232)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 10564-10597/com.arthenica.mobileffmpeg.test D/EGL_emulation: eglMakeCurrent: 0xdca60060: ver 3 0 (tinfo 0xdcaa73d0)
> 
> 
>

**Comment by tanersener** [comment]
`x264` is only included in `GPL` licensed packages. Please install one of them. You are using `full` package right now.

**Comment by seccpur** [comment]
@tanersener : Thanks for swift response. I am bit newbie in Java& Android, coming from c++. How to choose the gpl package?

**Comment by tanersener** [comment]
The following section is taken from the README. It shows how a `MobileFFmpeg` dependency is formed. `MobileFFmpeg` package installed in the following gradle dependency is `full`. `mobile-ffmpeg-<package name>` is the format. **2. Using** section lists all 8 `MobileFFmpeg` packages available. 3 of those packages end with `-gpl`: `min-gpl`, `https-gpl` and `full-gpl`. You need to install one of these. Gradle dependency will be something like `    implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.3.2'`.

**2.1 Android**
Add MobileFFmpeg dependency to your `build.gradle` in `mobile-ffmpeg-<package name>` format

```
dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.3.2'
}
```

**Comment by seccpur** [comment]
@tanersener : Thanks. Works like charm. Now there's no warning or error from ffmpeg, but the application, instead showing the progress, seems to freeze. The output video also seemed to be corrupted. Any clue?

**Comment by tanersener** [comment]
`FFmpeg.execute()` is a synchronous call. It does not run on another thread. If you want to run it asynchronously, run it inside an AsyncTask or use `AsyncSingleFFmpegExecuteTask ` class to run it.

I don't know what you expect about `progress indicator`. `MobileFFmpeg` is not connected to any ui/widget/layout, you need to implement it yourself in your application.

**Comment by seccpur** [comment]
Works like charm. The output video is also good. Thanks.

**Comment by seccpur** [comment]
Sorry to open this thread again for not fault of your library, but my failure in a basic implementation. As advised, I tried using `AsyncTask` ( tested ok with some delay routine without running FFmpeg.execute), but results into error. I don't why it fails with `FFmpeg.execute`. Thanks.

```
public class CommandTabFragment extends Fragment {   
    ProgressDialog progressDialog;
    final AtomicBoolean taskdone;
    View runFFmpegButton;
    /*…*/

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);      
        runFFmpegButton = view.findViewById(R.id.runFFmpegButton);
        runFFmpegButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                taskdone.set(false);
                FFmpegAsyncTask asyncTask=new FFmpegAsyncTask();
                asyncTask.execute();
            }
        });
    }

    private class FFmpegAsyncTask extends AsyncTask<Void, Void, Void> {
        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            progressDialog = new ProgressDialog(context);
            progressDialog.setMessage("Please wait while it is encoding ...");
            progressDialog.setIndeterminate(false);
            progressDialog.setCancelable(false);
            progressDialog.show();
        }
        @Override
        protected Void doInBackground(Void... strings) {
            runFFmpeg();
            taskdone.set(true);
            return null;
        }
        @Override
        protected void onPostExecute(Void v) {
            super.onPostExecute(v);
            if(taskdone.get()) {
                progressDialog.hide();
            }else {
                progressDialog.show();
            }
        }
}
public void runFFmpeg() {
        clearLog();
        FFmpeg.execute("-version"); 
}


}
```

**Log**

> 2020-05-07 21:07:41.420 30772-30772/com.arthenica.mobileffmpeg.test I/CatcherGestureDetector: DecorView onAttached
> 2020-05-07 21:07:41.441 30772-30808/com.arthenica.mobileffmpeg.test E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
>     Process: com.arthenica.mobileffmpeg.test, PID: 30772
>     java.lang.RuntimeException: An error occurred while executing doInBackground()
>         at android.os.AsyncTask$3.done(AsyncTask.java:354)
>         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
>         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #4,5,main] that has not called Looper.prepare()
>         at android.os.Handler.<init>(Handler.java:205)
>         at android.os.Handler.<init>(Handler.java:118)
>         at android.view.textservice.SpellCheckerSession$1.<init>(SpellCheckerSession.java:106)
>         at android.view.textservice.SpellCheckerSession.<init>(SpellCheckerSession.java:106)
>         at android.view.textservice.TextServicesManager.newSpellCheckerSession(TextServicesManager.java:181)
>         at android.widget.SpellChecker.resetSession(SpellChecker.java:127)
>         at android.widget.SpellChecker.setLocale(SpellChecker.java:148)
>         at android.widget.SpellChecker.spellCheck(SpellChecker.java:223)
>         at android.widget.Editor.updateSpellCheckSpans(Editor.java:834)
>         at android.widget.Editor.sendOnTextChanged(Editor.java:1443)
>         at android.widget.TextView.sendOnTextChanged(TextView.java:9807)
>         at android.widget.TextView.setText(TextView.java:5757)
>         at android.widget.TextView.setText(TextView.java:5588)
>         at android.widget.TextView.setText(TextView.java:5545)
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment.runFFmpeg(CommandTabFragment.java:258)
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$FFmpegAsyncTask.doInBackground(CommandTabFragment.java:133)
>         at com.arthenica.mobileffmpeg.test.CommandTabFragment$FFmpegAsyncTask.doInBackground(CommandTabFragment.java:121)
>         at android.os.AsyncTask$2.call(AsyncTask.java:333)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
> 2020-05-0

**Comment by tanersener** [comment]
`java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #4,5,main] that has not called Looper.prepare()`

This is the error you need to fix.

**Comment by seccpur** [comment]
@tanersener : By removing UI related codes from the asynctask solved the issue. Thanks again.
