### ISSUE TITLE
I can't build iOS binary

### ISSUE THREAD

**Issue by aduldach** [tanersener/mobile-ffmpeg#407]
**Description**
./ios.sh --disable-armv7 --disable-armv7s --disable-i386 --disable-x86-64 --disable-x86-64-mac-catalyst --disable-arm64e --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-videotoolbox --enable-ios-zlib --enable-ios-libiconv --enable-ios-bzip2 --enable-gnutls --xcframework

**Logs**
libavdevice/avfoundation.m:134:5: error: 'AVCaptureDeviceTransportControlsPlaybackMode' is unavailable: not available on iOS
    AVCaptureDeviceTransportControlsPlaybackMode observed_mode;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1638:28: note: 'AVCaptureDeviceTransportControlsPlaybackMode' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVCaptureDeviceTransportControlsPlaybackMode) {
                           ^
libavdevice/avfoundation.m:196:9: error: 'AVCaptureDeviceTransportControlsPlaybackMode' is unavailable: not available on iOS
        AVCaptureDeviceTransportControlsPlaybackMode mode =
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1638:28: note: 'AVCaptureDeviceTransportControlsPlaybackMode' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVCaptureDeviceTransportControlsPlaybackMode) {
                           ^
libavdevice/avfoundation.m:200:25: error: 'AVCaptureDeviceTransportControlsNotPlayingMode' is unavailable: not available on iOS
            if (mode == AVCaptureDeviceTransportControlsNotPlayingMode) {
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1638:28: note: 'AVCaptureDeviceTransportControlsPlaybackMode' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVCaptureDeviceTransportControlsPlaybackMode) {
                           ^
libavdevice/avfoundation.m:541:36: error: 'transportControlsSupported' is unavailable: not available on iOS
    int trans_ctrl = [video_device transportControlsSupported];
                                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1654:37: note: property 'transportControlsSupported' is declared unavailable here
@property(nonatomic, readonly) BOOL transportControlsSupported API_UNAVAILABLE(ios, watchos, tvos);
                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1654:37: note: 'transportControlsSupported' has been explicitly marked unavailable here
libavdevice/avfoundation.m:542:5: error: 'AVCaptureDeviceTransportControlsPlaybackMode' is unavailable: not available on iOS
    AVCaptureDeviceTransportControlsPlaybackMode trans_mode = [video_device transportControlsPlaybackMode];
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1638:28: note: 'AVCaptureDeviceTransportControlsPlaybackMode' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVCaptureDeviceTransportControlsPlaybackMode) {
                           ^
libavdevice/avfoundation.m:542:77: error: 'transportControlsPlaybackMode' is unavailable: not available on iOS
    AVCaptureDeviceTransportControlsPlaybackMode trans_mode = [video_device transportControlsPlaybackMode];
                                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1664:77: note: property 'transportControlsPlaybackMode' is declared unavailable here
@property(nonatomic, readonly) AVCaptureDeviceTransportControlsPlaybackMode transportControlsPlaybackMode API_UNAVAILABLE(ios, watchos, tvos);
                                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1664:77: note: 'transportControlsPlaybackMode' has been explicitly marked unavailable here
6 errors generated.
CC	libavfilter/af_aecho.o
make: *** [libavdevice/avfoundation.o] Error 1
make: *** Waiting for unfinished jobs....

**Environment**
 - Platform: IOS
 - Architecture: arm64
 - Version: 4.3.2
 - Source branch 4.3.2
 - Xcode version 11.4.1

**Other**
Thanks.

**Comment by tanersener** [comment]
Do you have all prerequisites listed in [5.1 Prerequisites](https://github.com/tanersener/mobile-ffmpeg#51-prerequisites) section? I suspect something is missing.

Can you also provide all logs from `build.log` file?

**Comment by aduldach** [comment]
> Do you have all prerequisites listed in 5.1 Prerequisites section? I suspect something is missing.

Already do it.

> Can you also provide all logs from build.log file?

[build.log.txt](https://github.com/tanersener/mobile-ffmpeg/files/4554759/build.log.txt)

**Comment by tanersener** [comment]
[This line](https://github.com/tanersener/mobile-ffmpeg/blob/master/build/ios-ffmpeg.sh#L419) fails on your build. It fails with this error message: `fatal: not a git repository (or any of the parent directories): .git`.

How did you download this repository?

**Comment by aduldach** [comment]
> How did you download this repository? If repository is cloned using git clone then there should be a .git directory in the parent directory.

Yes. I download from https://github.com/tanersener/mobile-ffmpeg/archive/v4.3.2.zip
I think that it not point of error in avfoundation.m file

**Comment by tanersener** [comment]
Default `avfoundation.m` file included in v4.3.2.zip file can not be compiled. It is a bug in `FFmpeg` source code. Error messages in your logs come from that `avfoundation.m` file.

`iOS` build scripts checks out previous version of `avfoundation.m` file during the build. But it does not work you because of the errors I explained in my previous posts.

So, I recommend using `git clone` to download the repository.

**Comment by aduldach** [comment]
Ok thank. I got it.
But I want to know number of previous version of file > avfoundation.m 
Can you explain me thank.

**Comment by tanersener** [comment]
You can see the commit id in [this line](https://github.com/tanersener/mobile-ffmpeg/blob/master/build/ios-ffmpeg.sh#L419). Use that commit id to get the correct version of that file.
