### ISSUE TITLE
add 64 bit .so files

### ISSUE THREAD

**Issue by robmr88** [tanersener/mobile-ffmpeg#409]
Hi, this is more a question than an issue.
I'm working on an Android project that already had ffmpeg integrated. Now I have to add the 64 bit libraries but I don't know exactly how. 
Could you give me some advice on how I could do it ?
I attached screenshot of jnilibs folder, as you can see only 32 bit folders are there for the .so files.

<img width="454" alt="Screenshot at Apr 29 17-04-04" src="https://user-images.githubusercontent.com/60899275/80691318-5dd08a00-8ad0-11ea-957a-59c82915959d.png">

**Comment by tanersener** [comment]
I don't recommend using multiple `ffmpeg` implementations in the same application. It is prone to errors and I don't support it.

If you need help about porting your application to 64-bit, please visit Android documentation about it, https://developer.android.com/distribute/best-practices/develop/64-bit.

**Comment by robmr88** [comment]
My main issue is that I don't actually know the procedure to generate the 64 bit .so files .
So my first help request would be if you could give some advice on how to do that.
Second , in your previous comment you said that this isn't the best implementation for ffmpeg, could you give some advice on the better alternative?
I know I'm basically asking for free help but I don't have much experience in jnilibs integration and ffmpeg but I have to find a solution for this.
Thank you.

**Comment by robmr88** [comment]
Would it be possible to replace all those libraries that I have in this project (judging by the screenshot) with the library mobile-ffmpeg ?

**Comment by tanersener** [comment]
Your questions don't make sense. You don't have to know how to build libraries. There is a long README, a lot of wiki pages which explain how you can build `MobileFFmpeg`. Why don't you read them?

I've said that using multiple `ffmpeg` implementations is not a good option. But it is not my idea. It is a technical limitation about native libraries. It is not specific to `ffmpeg` as well. You are trying to use two versions of the same library on Android. I recommend googling about it. It's a complex topic and not easy to solve.

You are asking help about replacing libraries. Replacing `.so` libraries is not a good practice, again prone to errors. Why do you concentrate on manually copying/replacing files/folders. There are a lot of prebuilt `ffmpeg` implementations out there. Use them. You don't have to use `mobile-ffmpeg` as well. If you have 32 bit versions of `ffmpeg` libraries, how about asking to the owner of those 32 bit  libraries to generate 64 bit versions of those files?

**Comment by robmr88** [comment]
Sorry for asking the wrong questions. I've had 0 experience  with .so files, this is my first project.  I didn't make this project and I can't get in touch with the developer that made it. I have to make some updates to this app and publish it on the store but I can't do that without the 64 bit version of those .so files. So what I was trying to do is find a way to generate the 64 bit version of those files so I can put it on the play store. Of course I will go and read documentation to make the process but I am aware that it's not an easy task so I was searching for some guidance for the main points of the problem, just to have the right approach. I thought that generating the 64 bit versions would have been the best and fastest way.

**Comment by mgood7123** [comment]
the generated libs are usially in `prebuilt/x86_64` and `prebuilt/arm64-v8a` assuming you do not invoke `android.sh` with `--disable-x86_64` and `disable-arm64-v8a`

**Comment by mgood7123** [comment]
i personally use my own scripts to aid in this process:

https://github.com/mgood7123/libmedia/blob/master/app/src/main/java/libmedia/FFMPEG-ANDROID/merge_includes.sh

and

https://github.com/mgood7123/libmedia/blob/master/app/src/main/java/libmedia/FFMPEG-ANDROID/copy_ffmpeg_shared_libraries.sh

**Comment by robmr88** [comment]
Hi everyone, thank you for your answers. I managed to resolve my issue . This project was a bit old and the developers that first created are out of reach. They've used various integrations of ffmpeg and it was confusing for me at the beginning to understand how they used it and how was i supposed to update the integration. Thank you for your time

**Comment by BilalAsif25** [comment]
@robmr88  Hi , can you help me out about how you solved it, i also want 64 bit so

**Comment by robmr88** [comment]
@BilalAsif25 , Hi, I solved by doing just a bit more research on the library that was used in the project. By exploring all the versions and resources I found that the developers made de 64 bit .so files available. It depends on the library that you are using to integrate ffmpeg
