### ISSUE TITLE
dlopen failed: library "libcpufeatures.so" not found in android

### ISSUE THREAD

**Issue by mrj976** [tanersener/mobile-ffmpeg#411]
I use com.arthenica:mobile-ffmpeg library in android and give me this error:
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libcpufeatures.so" not found`

Test All this types:
`'com.arthenica:mobile-ffmpeg-full:4.3.2'`
`'com.arthenica:mobile-ffmpeg-min:4.3.2'`
`'com.arthenica:mobile-ffmpeg-min-gpl:4.3.2'`
`'com.arthenica:mobile-ffmpeg-full-gpl:4.3.2'`
`'com.arthenica:mobile-ffmpeg-https:4.3.2'`
`'com.arthenica:mobile-ffmpeg-https-gpl:4.3.2'`
Please help me.
Thanks

**Comment by tanersener** [comment]
There are similar issues posted about this error. Please see [them](https://github.com/tanersener/mobile-ffmpeg/issues?q=is%3Aissue+libcpufeatures).

**Comment by mrj976** [comment]
> There are similar issues posted about this error. Please see [them](https://github.com/tanersener/mobile-ffmpeg/issues?q=is%3Aissue+libcpufeatures).

I visit them but not solved my problem
