### ISSUE TITLE
Can't execute RTSP commands 

### ISSUE THREAD

**Issue by sunnyyehuda** [tanersener/mobile-ffmpeg#412]
**Description**
I'm trying to execute the copy rtsp command:

`-rtsp_flag listen -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov -c:av copy bunny.mov`

I tried with various options, and it didn't seem to work

I've added the following code so the app can show if the command succeed:

```
int rc = FFmpeg.execute("-rtsp_flag listen -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov -c:v copy bunny.mov");

if (rc == RETURN_CODE_SUCCESS) 
{
       Toast.makeText(getApplicationContext(), "ffmpeg succeed:", Toast.LENGTH_LONG).show();
 } else {
        Toast.makeText(getApplicationContext(), "ffmpeg failed:", Toast.LENGTH_LONG).show();
 }
```

**Test**
The following command succeed:
`int rc = FFmpeg.execute("-version");`

the following command also failed:
`int rc = FFmpeg.execute("-i /storage/emulated/0/DCIM/Camera/my_vid.mp4 -c:av copy new_vid.mp4");`

**Permission**
added both in the manifest.xml and in realtime via the activity.

**Environment**
 - Platform: Android, Pixel 4 & Pixel 3 XL API 29
 - Architecture: [arm-v7a, arm64-v8a, x86, x86_64]
 - Android Studio version 3.6.3
 - Android NDK version 21b

Thanks :-)

**Comment by tanersener** [comment]
Can you share logs, console output or logcat output for this case?

**Comment by sunnyyehuda** [comment]
sorry for the late answer.
here is the logs:
      libavutil      56. 38.100 / 56. 31.100
      libavcodec     58. 65.102 / 58. 54.100
      libavformat    58. 35.101 / 58. 29.100
      libavdevice    58.  9.103 / 58.  8.100
      libavfilter     7. 70.101 /  7. 57.100
      libswscale      5.  6.100 /  5.  5.100
      libswresample   3.  6.100 /  3.  5.100
W/mobile-ffmpeg: [udp @ 0x727f9bdea0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
    [udp @ 0x727f9bdf40] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
W/mobile-ffmpeg: [udp @ 0x727f9c07e0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
    [udp @ 0x727fa6c320] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
I/mobile-ffmpeg: Input #0, rtsp, from 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov':
      Metadata:
        title           : 
    BigBuckBunny_115k.mov
      Duration: 
    00:09:56.48
    , start: 
    0.000000
    , bitrate: 
    N/A
        Stream #0:0
    : Audio: aac (LC), 12000 Hz, stereo, fltp
        Stream #0:1
    : Video: h264 (Constrained Baseline), yuv420p(progressive), 240x160
    , 
    24 fps, 
    24 tbr, 
    90k tbn, 
    48 tbc
E/mobile-ffmpeg: out.mov: Read-only file system

**Comment by sunnyyehuda** [comment]
it seems that now it's working, maybe the problem was in the WOWZA streaming test web

**Comment by tanersener** [comment]
Great :+1:
