### ISSUE TITLE
[Android] Remove internal log line limit

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#418]
Log callback implementation of Android uses an internal limit of 1024 characters per line (`#define LOG_LINE_SIZE 1024`). This limit was inherited from `LINE_SZ` definition in `libavutil/log.c` file. Unfortunately, putting a log line limit causes some characters to be dropped from log line, which causes further problems like #331.

**Comment by tanersener** [comment]
Fixed in `development`.

**Comment by jaredbracken** [comment]
Thank you!

**Comment by tanersener** [comment]
Released in `v4.4`.
