### ISSUE TITLE
Possibility of reducing size of audio build

### ISSUE THREAD

**Issue by NLLAPPS** [tanersener/mobile-ffmpeg#42]
I was trying to build a small audio only FFmpeg binary for Android before I've discovered your project.
I was able to reduce the size of FFmpeg executable to 4.5 MB with below audio only config. That's half of what it is  created by your project.

Would you be able to add an alternative audio build? With similar config below? Please note I did not worry about licensing details as I was merely trying to see how much I can reduce the binary size

---------

./configure --prefix=$PREFIX \
        $CROSS_COMPILE_FLAGS \
        --pkg-config=$(which pkg-config) \
        --pkg-config-flags="--static" \
	--disable-everything \
	--enable-pthreads \
        --enable-pic \
        --enable-small \
        --enable-gpl \
	--enable-version3 \
	--enable-nonfree \
        \
        --disable-shared \
        --enable-static \
        \
        --enable-ffmpeg \
        --disable-ffplay \
        --disable-ffprobe \
        \
        --disable-protocols \
        --enable-protocol='file,pipe,concat' \
        \
	--disable-filters \
	--enable-filter='acopy,amerge,aresample,asetrate,aformat,anull,atrim,format,null,setpts,trim' \
	\
        --disable-muxers \
	\
	--disable-demuxers \
        --enable-demuxer=ac3 \
	--enable-demuxer=aiff \
	--enable-demuxer=ape \
	--enable-demuxer=au \
	--enable-demuxer=concat \
	--enable-demuxer=asf \
	--enable-demuxer=aac \
	--enable-demuxer=flac \
	--enable-demuxer=mp3 \
	--enable-demuxer=ogg \
	--enable-demuxer=wav \
	--enable-demuxer=pcm_alaw \
	--enable-demuxer=pcm_mulaw \
	--enable-demuxer=dnxhd \
	--enable-demuxer=pcm_alaw \
	--enable-demuxer=pcm_mulaw \
	--enable-demuxer=pcm_f64be \
	--enable-demuxer=pcm_f64le \
	--enable-demuxer=pcm_f32be \
	--enable-demuxer=pcm_f32le \
	--enable-demuxer=pcm_s32be \
	--enable-demuxer=pcm_s32le \
	--enable-demuxer=pcm_s24be \
	--enable-demuxer=pcm_s24le \
	--enable-demuxer=pcm_s16be \
	--enable-demuxer=pcm_s16le \
	--enable-demuxer=pcm_s8 \
	--enable-demuxer=pcm_u32be \
	--enable-demuxer=pcm_u32le \
	--enable-demuxer=pcm_u24be \
	--enable-demuxer=pcm_u24le \
	--enable-demuxer=pcm_u16be \
	--enable-demuxer=pcm_u16le \
	--enable-demuxer=pcm_u8 \
	--enable-demuxer=wav \
	--enable-demuxer=xwma \
	\
	--enable-muxer='ac3,aiff,ape,au,alac,wma,concat,asf,3gp,flac,mp3,mp4,ogg,opus,wav,dnxhd' \
        \
        --disable-encoders \
	--enable-encoder=pcm_alaw \
	--enable-encoder=pcm_mulaw \
	--enable-encoder=libfdk_aac \
        --enable-encoder=aac \
	--enable-encoder=flac \
	--enable-encoder=libmp3lame \
	--enable-encoder=libopus \
	--enable-encoder=libvorbis \
	--enable-libopencore-amrnb \
	--enable-libopencore-amrwb \
	--enable-encoder=mpeg4 \
	--enable-encoder=dnxhd \
	--enable-encoder=pcm_s8 \
	--enable-encoder=pcm_s16be \
	--enable-encoder=pcm_s16le \
	--enable-encoder=pcm_s24be \
	--enable-encoder=pcm_s24le \
	--enable-encoder=pcm_s32be \
	--enable-encoder=pcm_s32le \
	--enable-encoder=pcm_u8 \
	--enable-encoder=pcm_u16be \
	--enable-encoder=pcm_u16le \
	--enable-encoder=pcm_u24be \
	--enable-encoder=pcm_u24le \
	--enable-encoder=pcm_u32be \
	--enable-encoder=pcm_u32le \
	\
        --disable-decoders \
	--enable-decoder=pcm_alaw \
	--enable-decoder=pcm_mulaw \
        --enable-decoder=aac \
	--enable-decoder=aac_latm \
	--enable-decoder=ac3 \
	--enable-decoder=alac \
	--enable-decoder=als \
	--enable-decoder=ape \
	--enable-decoder=eac3 \
	--enable-decoder=flac \
	--enable-decoder=gsm \
	--enable-decoder=gsm_ms \
	--enable-decoder=mp1 \
	--enable-decoder=mp1float \
	--enable-decoder=mp2 \
	--enable-decoder=mp2float \
	--enable-decoder=mp3 \
	--enable-decoder=mp3adu \
	--enable-decoder=mp3adufloat \
	--enable-decoder=mp3float \
	--enable-decoder=mp3on4 \
	--enable-decoder=mp3on4float \
	--enable-decoder=opus \
	--enable-decoder=ralf \
	--enable-decoder=vorbis \
	--enable-decoder=wavpack \
	--enable-decoder=wmalossless \
	--enable-decoder=wmapro \
	--enable-decoder=pcm_s24daud \
	--enable-decoder=pcm_s24le \
	--enable-decoder=pcm_s24le_planar \
	--enable-decoder=pcm_s32be \
	--enable-decoder=pcm_s32le \
	--enable-decoder=wmav1 \
	--enable-decoder=wmav2 \
	--enable-decoder=wmavoice \
	--enable-decoder=aac_at \
	--enable-decoder=aac_fixed \
	--enable-decoder=libopus \
	--enable-decoder=libvorbis \
	--enable-decoder=mpeg4 \
	--enable-decoder=pcm_s16le \
	--enable-decoder=pcm_s16be \
	--enable-decoder=dnxhd \
	--enable-decoder=pcm_alaw \
	--enable-decoder=pcm_bluray \
	--enable-decoder=pcm_dvd \
	--enable-decoder=pcm_f32be \
	--enable-decoder=pcm_f32le \
	--enable-decoder=pcm_f64be \
	--enable-decoder=pcm_f64le \
	--enable-decoder=pcm_lxf \
	--enable-decoder=pcm_mulaw \
	--enable-decoder=pcm_s8 \
	--enable-decoder=pcm_s8_planar \
	--enable-decoder=pcm_s16be \
	--enable-decoder=pcm_s16be_planar \
	--enable-decoder=pcm_s16le \
	--enable-decoder=pcm_s16le_planar \
	--enable-decoder=pcm_s24be \
	--enable-decoder=pcm_s32le_planar \
	--enable-decoder=pcm_u8 \
	--enable-decoder=pcm_u16be \
	--enable-decoder=pcm_u16le \
	--enable-decoder=pcm_u24be \
	--enable-decoder=pcm_u24le \
	--enable-decoder=pcm_u32be \
	--enable-decoder=pcm_u32le \
	--enable-decoder=pcm_zork \
	--enable-decoder=dsd_lsbf \
	--enable-decoder=dsd_msbf \
	--enable-decoder=dsd_lsbf_planar \
	--enable-decoder=dsd_msbf_planar \
	\
	--enable-parser='aac,aac_latm,ac3,cook,dca,flac,gsm,mpegaudio,vorbis' \
	\
        --enable-libmp3lame \
        --enable-libopus \
        --enable-libvorbis \
        --enable-bsf=aac_adtstoasc \
	\
        --disable-doc

**Comment by tanersener** [comment]
> Would you be able to add an alternative audio build? With similar config below? Please note I did not worry about licensing details as I was merely trying to see how much I can reduce the binary size

Options above disables almost everything and enables only selective features in `FFmpeg`. It is a good way to decrease the size of `FFmpeg`. I guess disabled parts are video specific features and can be ignored for `audio`. 

Well, these configs need detailed analysis of each supported/disabled/enabled feature and testing too. I can try to do that but it will take time and I can't promise on anything before making these tests.

Until then, you can try to build your custom version by using your options in `build/android-ffmpeg.sh` file.

**Comment by NLLAPPS** [comment]
Thanks
