### ISSUE TITLE
Read-only file system error for FFmpeg execute

### ISSUE THREAD

**Issue by Flah** [tanersener/mobile-ffmpeg#425]
**Description**
Not able to execute FFmpeg task like example

**Expected behavior**
Download provided file as mp4

**Current behavior**
The command works fine in the shell but in Android Studi I am getting the error
that it is only a Read-only file system

**Logs**
`2020-05-19 00:06:05.132 7903-7903/com.example.myapplication I/mobile-ffmpeg: ffmpeg version v4.3-dev-2955 Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (5900059 based on r365631c) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290) (based on LLVM 9.0.8svn)
      configuration: --cross-prefix=i686-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-x86/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=i686 --cpu=i686 --cc=i686-linux-android24-clang --cxx=i686-linux-android24-clang++ --target-os=android --disable-neon --disable-asm --disable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videot  libavutil      56. 42.102 / 56. 42.102
      libavcodec     58. 78.102 / 58. 78.102
      libavformat    58. 42.100 / 58. 42.100
      libavdevice    58.  9.103 / 58.  9.103
      libavfilter     7. 77.101 /  7. 77.101
      libswscale      5.  6.101 /  5.  6.101
      libswresample   3.  6.100 /  3.  6.100
    [hls @ 0xe8660800] Skip ('#EXT-X-VERSION:3')
    [tls @ 0xdcfd8180] Error in the pull function.
    [tls @ 0xdcfd8180] The specified session has been invalidated for some reason.
    [hls @ 0xe8660800] Opening 'https://p28d1c9b884-6b67-4bc4-8b38-7fe101682ea8.hdfilme.ws/hls/b74ec1eb98c4b214199fb328d53ed255/b74ec1eb98c4b214199fb328d53ed255-842.png?msKey=S9' for reading
    [hls @ 0xe8660800] Opening 'https://p28d1c9b884-6b67-4bc4-8b38-7fe101682ea8.hdfilme.ws/hls/b74ec1eb98c4b214199fb328d53ed255/b74ec1eb98c4b214199fb328d53ed255-843.png?msKey=S9' for reading
    Input #0, hls, from 'https://load.hdfilme.ws/hls/b74ec1eb98c4b214199fb328d53ed255/b74ec1eb98c4b214199fb328d53ed255.m3u8':
      Duration: N/A, start: 5896.747789, bitrate: N/A
      Program 0 
        Metadata:
          variant_bitrate : 0
        Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x808 [SAR 1:1 DAR 240:101], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
        Metadata:
          variant_bitrate : 0
        Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
        Metadata:
          variant_bitrate : 0
    output.mp4: Read-only file system`

**Environment**
 - Platform: Android
 - Architecture: Nexus 5x x86 Emulator
 - Version com.arthenica:mobile-ffmpeg-full:4.3.2
 - Android Studio version 3.6.3

**Other**
Command which is creating the problem:
`FFmpeg.execute("-referer https://hdfilme.cx -i https://load.hdfilme.ws/hls/b74ec1eb98c4b214199fb328d53ed255/b74ec1eb98c4b214199fb328d53ed255.m3u8 output.mp4");`

**Comment by tanersener** [comment]
Please give full path for your output file!

**Comment by Flah** [comment]
That helped, thanks! I am new to android, so please be understanding.
I putted the output file into the Downloads directory, getting the path to it as follows:
`Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutPath();`
