### ISSUE TITLE
Get execution information and status

### ISSUE THREAD

**Issue by Flah** [tanersener/mobile-ffmpeg#427]
**Description**
First of all thanks for the great Library! I finally got it up and running.
How can we get the progress or any information of the ffmpeg execute command?
I am new to android and ffmpeg trying to find a way to show a percentage or anything similar
while loading a file through the execute command.
Didn´t know how or where to ask. Hope it´s ok in here.

**Comment by tanersener** [comment]
You can calculate the percentage by enabling a statistics callback. Take a look at Android test-app to see how it is used.

```
Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        Log.d(Config.TAG, String.format("frame: %d, time: %d", newStatistics.getVideoFrameNumber(), newStatistics.getTime()));
    }
});
```

**Comment by Flah** [comment]
Thanks for the fast response. I am not able to spot the example for this in your repo.
Can your share the link to it please.

**Comment by tanersener** [comment]
`android/test-app`

**Comment by karimdjemai** [comment]
The mentioned code is the following: 

`protected void updateProgressDialog() {
		if (statistics == null) {
			return;
		}

		int timeInMilliseconds = this.statistics.getTime();
		if (timeInMilliseconds > 0) {
			int totalVideoDuration = 9000;

			String completePercentage = new BigDecimal(timeInMilliseconds).multiply(new BigDecimal(100)).divide(new BigDecimal(totalVideoDuration), 0, BigDecimal.ROUND_HALF_UP).toString();

			TextView textView = progressDialog.findViewById(R.id.progressDialogText);
			if (textView != null) {
				textView.setText(String.format("Encoding video: %% %s", completePercentage));
			}
		}
	}`

How can you tell the total video duration? Why is it hard-coded? Is there any way to display the percentage

**Comment by vijayattatva** [comment]
UI Not updating in this function.

Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        Log.d(Config.TAG, String.format("frame: %d, time: %d", newStatistics.getVideoFrameNumber(), newStatistics.getTime()));
    }
});

**Comment by vjsingh96** [comment]
UI Not updating in this function.

```
Config.enableStatisticsCallback(new StatisticsCallback() {
    public void apply(Statistics newStatistics) {
        Log.d(Config.TAG, String.format("frame: %d, time: %d", newStatistics.getVideoFrameNumber(), newStatistics.getTime()));
    }
});
```

**Comment by tanersener** [comment]
@karimdjemai Total video duration depends on your command. It is not possible for `mobile-ffmpeg` to guess it, before actually running your command. In that example, I know what my command will do and what will be the total video duration. So, I defined video duration as a variable and used it to calculate the percentage.

@vjsingh96 `mobile-ffmpeg`s callbacks (both log and statistics) are invoked by `background` threads and background threads are not allowed to update the UI. This is a limitation coming from Android.

**Comment by vjsingh96** [comment]
@tanersener Thanks for the reply..
Is there any alternate way to achieve this? I just want to show the percentage on the progress bar.

**Comment by abkoradiya** [comment]
If I generate slide show from images? How can I track of progress?

**Comment by BilalAsif25** [comment]
Hi @karimdjemai , 
Did you find the solution about showing percentage in progress bar and finding out total time/duration?
