### ISSUE TITLE
Unrecognized option 'crf'

### ISSUE THREAD

**Issue by kcywek** [tanersener/mobile-ffmpeg#429]
**Description**
I'm trying to compress video using ffmpeg
 val commandCompress = arrayOf(   "-y", "-i", videoUri, "-vcodec", "libx264", "-crf", "20",         
 outputFilepath ) 
but got an error 
'Unrecognized option 'crf''

**Expected behavior**
video should be compressed

**Current behavior**
video is not compressed and got an error message

**Logs**
https://ghostbin.co/paste/ynaa6

**Environment**
 - Platform: Android
 - Architecture: arm-v7a
 - Version (if applicable) 4.3.1 LTS
 - Android Studio version (if applicable) 3.63

**Comment by tanersener** [comment]
According to the logs, you are using the `min` package. That package does not include `x264` and `crf` is an option specific to `x264`. I guess this is why you have this error. Please try again with one of the GPL licensed packages.

**Comment by kcywek** [comment]
Thanks for the quick response. You're right, changing package with GPL licensed packages do the job
