### ISSUE TITLE
How to support Android 4.x ?

### ISSUE THREAD

**Issue by suncj518** [tanersener/mobile-ffmpeg#43]
@tanersener May I know if the .so lib files can support Android 4.x ?  I found current version can only  support Android 5.0 and above .

Thanks.

**Comment by tanersener** [comment]
I don't think it is possible to use them for `Android 4.x`. Released binaries include settings which sets API=21 (5.0) as the min supported API level. If you want to support `Android 4.x` you need to build your own binaries with API=14 (4.0).

**Comment by suncj518** [comment]
Ok, got, thanks for reply.
