### ISSUE TITLE
Command's Template

### ISSUE THREAD

**Issue by lucazin** [tanersener/mobile-ffmpeg#431]
**Description**
Error in command template

**Expected behavior**
Encode; because in older version of ffmpeg working.

**Current behavior**
Give me command invalid y and no Options

   I/mobile-ffmpeg: ffmpeg version git-2020-01-25-fd11dd500 Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
      configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disa  libavutil      56. 38.100 / 56. 38.100
      libavcodec     58. 65.102 / 58. 65.102
      libavformat    58. 35.101 / 58. 35.101
      libavdevice    58.  9.103 / 58.  9.103
      libavfilter     7. 70.101 /  7. 70.101
      libswscale      5.  6.100 /  5.  6.100
      libswresample   3.  6.100 /  3.  6.100
    Unrecognized option 'me_method'.
    Error splitting the argument list: Option not found

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: API 28

**Other**
`public String[] CompressConfig_VideoApresentacao(File Source, File Destination) {
		String[] commandParams = new String[26];
		commandParams[0] = "-y";
		commandParams[1] = "-i";
		commandParams[2] = Source.getPath();
		commandParams[3] = "-s";
		commandParams[4] = "1280x720";
		commandParams[5] = "-r";
		commandParams[6] = "30";
		commandParams[7] = "-c:v";
		commandParams[8] = "libx264";
		commandParams[9] = "-preset";
		commandParams[10] = "ultrafast";
		commandParams[11] = "-c:a";
		commandParams[12] = "copy";
		commandParams[13] = "-me_method";
		commandParams[14] = "zero";
		commandParams[15] = "-tune";
		commandParams[16] = "fastdecode";
		commandParams[17] = "-tune";
		commandParams[18] = "zerolatency";
		commandParams[19] = "-strict";
		commandParams[20] = "-2";
		commandParams[21] = "-b:v";
		commandParams[22] = "1500k";
		commandParams[23] = "-pix_fmt";
		commandParams[24] = "yuv420p";
		commandParams[25] = Destination.getPath();
		
		return commandParams;
	}`

How can i use this command?
in ffmpeg library older work.. but in this library i have to do something.

**Comment by tanersener** [comment]
It is not possible to understand which `mobile-ffmpeg` package you're using right now. Also, whether that older `ffmpeg` implementation in which your command works is `mobile-ffmpeg` or not. Can you please give explain them?

Btw, did you see this `ffmpeg` ticket, [-me_method renamed to -motion-est](https://trac.ffmpeg.org/ticket/6771)? Maybe using `-motion-est` instead of `-me_method`can solve your problem.

**Comment by lucazin** [comment]
you can help me what command can i use to convert a video like with this command?

**Comment by tanersener** [comment]
Did you read my previous comment?

**Comment by lucazin** [comment]
I read..
Sorry my friend for not explain right, and my bad english.

1-  The version is : com.arthenica:mobile-ffmpeg-full:4.3.2.LTS

2 - The older implemetation of ffmpeg with this command, i use the LIB:  om.writingminds:FFmpegAndroid:0.3.2   (arm)

3 - this is original command that works before
`public String[] CompressConfig_VideoApresentacao(File Source, File Destination) {
		String[] commandParams = new String[26];
		commandParams[0] = "-y";
		commandParams[1] = "-i";
		commandParams[2] = Source.getPath();
		commandParams[3] = "-s";
		commandParams[4] = "1280x720";
		commandParams[5] = "-r";
		commandParams[6] = "30";
		commandParams[7] = "-c:v";
		commandParams[8] = "libx264";
		commandParams[9] = "-preset";
		commandParams[10] = "ultrafast";
		commandParams[11] = "-c:a";
		commandParams[12] = "copy";
		commandParams[13] = "-me_method";
		commandParams[14] = "zero";
		commandParams[15] = "-tune";
		commandParams[16] = "fastdecode";
		commandParams[17] = "-tune";
		commandParams[18] = "zerolatency";
		commandParams[19] = "-strict";
		commandParams[20] = "-2";
		commandParams[21] = "-b:v";
		commandParams[22] = "1500k";
		commandParams[23] = "-pix_fmt";
		commandParams[24] = "yuv420p";
		commandParams[25] = Destination.getPath();
		
		return commandParams;
	}`

4 - Im trying to move for this lib because my targetsdk is 29 now and ffmpeg not work with android 10, and i have to say thank you so much for create because will help a lot of developers.  

5 - I will test with this command   -motion-est instead of -me_method 

6 - The structure of command is ok for the mobileffmpg?

**Comment by lucazin** [comment]
This is the command:

-y -i /storage/emulated/0/Movies/VideoApresentacao.mp4 -s 1280x720 -r 30 -c:v libx264 -preset ultrafast -c:a copy -motion-est zero -tune fastdecode -tune zerolatency -strict -2 -b:v 1500k -pix_fmt yuv420p /storage/emulated/0/OnePlace/Videos/OnePlace_Video_Apresentacao_TempFile.mp4

What i'm doing wrong?

**Comment by tanersener** [comment]
You need to use one of the `GPL` licensed packages to use `libx264`.

**Comment by lucazin** [comment]
Its working @tanersener !

But my apk increase almost 20mb  ...normal size is 50mb go to 74mb 

any idea to reduce this size? 

im using full gpl in gradle.
