### ISSUE TITLE
libmobileffmpeg-abidetect.so not found

### ISSUE THREAD

**Issue by TooLazyy** [tanersener/mobile-ffmpeg#433]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/pro.getsalesapp.android-D0FG5r-dYT1-lAlNI9ZLJA==/base.apk"],nativeLibraryDirectories=[/data/app/pro.getsalesapp.android-D0FG5r-dYT1-lAlNI9ZLJA==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmobileffmpeg-abidetect.so"

Related issue was poster last year https://github.com/tanersener/mobile-ffmpeg/issues/176

Device - Xiaomi Mi 8
Android - Q (10)
Version used - 4.2.2.LTS

P.S. Jut checked - calling Config.enableStatisticsCallback or Config.resetStatistics leads to crash even on Pixel emulator

**Comment by tanersener** [comment]
Similar issues were reported before. All of them were resolved by rebuilding the application, cleaning the cache, etc. I'll recommend trying similar things.

`libmobileffmpeg-abidetect.so` is included in all `.aar` archives published by `mobile-ffmpeg`. If you're not manually excluding it in your `gradle` files, then it should copied to your `apk` as well. You can check it yourself by using `Build -> Analyze APK` menu of Android Studio.

**Comment by TooLazyy** [comment]
Yeah. Seems like a AS bug or smth else.
