### ISSUE TITLE
StreamInformation get video width

### ISSUE THREAD

**Issue by ZedZeal** [tanersener/mobile-ffmpeg#435]
**Description**
I would like to get the width and height using ffprobe. By reading the docs it seems that the only getWidth() method belongs to the class StreamInformation, and the only way I found to have a StreamInformation object in Swift is by doing `let comm = MobileFFprobe.getMediaInformation(url.relativeString).getStreams()[0].getWidth()`, however it does not work. 

**Expected behavior**
To receive the width info of the video.

**Current behavior**
It does not work.

**Logs**
I will not include the logs, as I think that the issue is just a misunderstanding of the class StreamInformation from my part.

**Environment**
 - Platform: IOS
 - Source branch master
 - Xcode version 11.4.1
 - Cocoapods version 1.9.1

**Comment by tanersener** [comment]
Would you mind explaining `it does not work`? What happens when you call that method? Does it return something? 

When you're working with `MobileFFprobe` and something is not working as expected, please check the output returned by `getRawInformation` method of `MediaInformation` class. It shows the output of `ffprobe` and can help you to identify underlying issues.

**Comment by ZedZeal** [comment]
Ok, I solved it. The problem was with type casting in Swift, as the method getStreams()[0] was not able to auto identify the object as StreamInformation. I am now able to retrieve width and height of the video by doing this:
```
let comm = MobileFFprobe.getMediaInformation(url.relativeString)
    let comm2 = comm?.getStreams()[1] as! StreamInformation
    print("COMM:")
    print(comm2.getHeight() ?? 1280)
    print(comm2.getWidth() ?? 720)
```
I would like to ask you a brief final question: from what I see the getStreams method returns 2 stream object, where the first is the audio and the second is the video. Do you know if this is always the case, does the video stream always comes after the audio one in the array, no matter the video file format?

**Comment by tanersener** [comment]
Unfortunately, no I don't know. I can't say that video stream always comes after the audio.

**Comment by ZedZeal** [comment]
Ok, thank you very much anyway for your time. I will close the issue.
