### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by huyubao** [tanersener/mobile-ffmpeg#436]
**Description**
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
Checking zlib
./configure: line 13045: syntax error near unexpected token `Z,zlib,'
./configure: line 13045: `        PKG_CHECK_MODULES(Z,zlib,'

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. Android]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by huyubao** [comment]
[build.log](https://github.com/tanersener/mobile-ffmpeg/files/4700589/build.log)

**Comment by tanersener** [comment]
That error is not the only error in your logs. There are other errors printed about build tools. Do you have all `Android` prerequisites installed? If they are then try to validate that they're working as expected and try to fix this error. This shouldn't be failing.

```
./configure: line 4710: PKG_PROG_PKG_CONFIG: command not found
```

**Comment by huyubao** [comment]
I've used the brew install pkg-config command
