### ISSUE TITLE
How to play RTSP video feed on iOS ??

### ISSUE THREAD

**Issue by PrashantGaikwad-iOS** [tanersener/mobile-ffmpeg#437]
**Description**
So, currently, I'm using the MobileVLCKit library to display the RTSP video feed but this library is very huge(1.65GB) and consuming a lot of memory and also using ffmpeg library to live stream the same RTSP video feed on youtube.

**Expected behavior**
How can we use this library to display the RTSP video feed on an iOS device?

**Current behavior**
We can't find any command in this library to do the same.

**Environment**
 - Platform: IOS 11
 - Xcode version 11.4
 - Cocoapods version - 4.3.2

**Other**
We are also using FFmpeg to run other command in parallel with the VLC player and it is not allowing FFmpeg command to execute. We are getting the following errors - 
Loaded mobile-ffmpeg-full-x86_64-4.3.2-20200415
ERROR: Connection to tcp://a.rtmp.youtube.com:1935 failed: Operation timed out
ERROR: Cannot open connection tcp://a.rtmp.youtube.com:1935
ERROR: rtmp://a.rtmp.youtube.com/live2/5r99-a18f-0ews-qqsr-bt7m: Operation timed out

**Comment by tanersener** [comment]
Unfortunately, `mobile-ffmpeg` does not include a component to play media files. Implementing a player based on `ffplay` is on the roadmap but I don't have a release date for that feature yet.

Having both `MobileVLCKit` and `mobile-ffmpeg` in the same application means that you have two `ffmpeg` implementations inside your app. This is not an ideal case and can cause some problems. You can receive unexpected errors. A `MobileVLCKit`/`mobile-ffmpeg` feature which is working when the library is used alone may stop working when you add the second library. You can find the technical details of this behaviour in this wiki page: [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application). 

There are also a few older issues created about using `MobileVLCKit` and `mobile-ffmpeg` together. Please take a look at them and try to apply solutions given inside them.
