### ISSUE TITLE
add "libfdk_aac" support

### ISSUE THREAD

**Issue by helgo1506** [tanersener/mobile-ffmpeg#439]
Hi,
i wanted to ask, if you can add support for "libfdk_aac".
I tested it myself already and it works with ndk and on android. dont know about ios.
I like this lib more then the buildin aac, cause it got better quality (ffmpeg even say this themself)

I hope you look into it. Thx for the ports.

**Comment by tanersener** [comment]
`libfdk_aac` is listed as one the libraries whose license is not compatible with `ffmpeg`. Adding support for it will create some problems about the license. So, I can't add support for it.

**Comment by helgo1506** [comment]
Okay. though something like this. thx anyway. great work. will use your projekt in one of my private tool.
