### ISSUE TITLE
Can't find mobile-ffmpeg-full 3.0 in CocoaPods

### ISSUE THREAD

**Issue by qoakzmxncb** [tanersener/mobile-ffmpeg#44]
**Description**
When the version 3.0 will release in CocoaPods?

**Comment by qoakzmxncb** [comment]
I had already clean the cache, but it dosn't work.
I use pod search, and can't find the new version.

![wx20181116-105122](https://user-images.githubusercontent.com/1749729/48594918-a3a59b00-e98d-11e8-82c8-4eb2d7c22aa6.png)

**Comment by tanersener** [comment]
Hi @qoakzmxncb, your pod repo is not up to date, you can't see versions `2.2` and `3.0`. Did you try updating your repo with `pod repo update --verbose`.

```
-> mobile-ffmpeg-full (3.0)
   Mobile FFmpeg Full Dynamic Framework
   pod 'mobile-ffmpeg-full', '~> 3.0'
   - Homepage: https://github.com/tanersener/mobile-ffmpeg
   - Source:  
   https://github.com/tanersener/mobile-ffmpeg/releases/download/v3.0/mobile-ffmpeg-full-3.0-ios-framework.zip
   - Versions: 3.0, 2.2, 2.1.1, 2.1, 2.0, 1.2, 1.1 [master repo]
```

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you still need help.
