### ISSUE TITLE
Io from memory

### ISSUE THREAD

**Issue by Hosseinyzr** [tanersener/mobile-ffmpeg#442]
Hi, thanks for your lib.
is it possible to set input/output to read or write from/to memory?
for example read a byte[] as an input or write in to stream object.
specially in android java

**Comment by isabsent** [comment]
I am interesting in this feature too. As I suppose `pipe` manipulation is for this purpose. Can you explain it in details?

**Comment by Hosseinyzr** [comment]
I don't know much details, but currently there is java repo for ffmpeg that can use stream as an input and output.
https://github.com/kokorin/Jaffree

as I saw the code, it uses socket and tcp port to write data into it and use it as io.

that lib is not for android but maybe the code can get us an idea.
It would be a very much favor if you take some time to see whether this is possible or not...

**Comment by isabsent** [comment]
@Hosseinyzr  Thanks for the link.

I hope the author *mobile-ffmpeg* will give us a code sample how to use his `pipe` equipment to transcode in Java `OutputStream`...

**Comment by tanersener** [comment]
See [Pipe Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Pipe-Support).

**Comment by Hosseinyzr** [comment]
Thanks, I saw that and test that and it worked.
but I think it is not the case!

As I noticed , you use address of storage like this:
/data/user/0/com.example.ffmpegtest/cache/mf_pipe_1

so isn't still it on disk?
I want to set io from memory for example byte[] or any other things.
I think writing to disk has overhead..
am I correct or I misunderstood?

**Comment by isabsent** [comment]
> I want to set io from memory for example `byte[]` or any other things.
I will take a lot of bytes and result in OOM for video. It would be better to send it in `OutputStream`

**Comment by Hosseinyzr** [comment]
> > I want to set io from memory for example `byte[]` or any other things.
> 
> I will take a lot of bytes and result in OOM for video. It would be better to send it in `OutputStream`.

yes but it depend on process. I just need some images and it wont make oom. any way outputstream ot byte[] or other things doesn't matters. I just need to be in memory and not dis.

**Comment by isabsent** [comment]
> I just need to be in memory and not disk.

#metoo

**Comment by alexcohn** [comment]
**pipe** is not a replacement for in-memory API. Not only it means unnecessary multiple memory copies, but also **pipe** is not seekable, and thus cripples many formats. There exists an example of [jni-protocol](https://github.com/appunite/AndroidFFmpeg/blob/master/library-jni/jni/jni-protocol.c), but it is not compatible with the contemporary version of **ffmpeg**.

**Comment by alexcohn** [comment]
On the face of it, you can try to employ the [`data` protocol](https://en.wikipedia.org/wiki/Data_URI_scheme).

**Comment by tanersener** [comment]
As explained in the [Pipe Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Pipe-Support) wiki page, you can use `Config.registerNewFFmpegPipe` method to create a pipe, open that pipe and write your data inside. `MobileFFmpeg` uses named pipes, they have a path like a file but they don't reside on disk. You can ask google about "the difference between named pipe and regular file" if you want to learn the details.

`pipe` protocol has some limitations and can't be used on all cases. However, they are the only available option you can use on `MobileFFmpeg` if you don't want to work with files.

[Jafree](https://github.com/kokorin/Jaffree) uses `stdin/stdout/stderr` to read and write streams. `stdin/stdout/stderr` are special file descriptors provided by the OS. Writing something to stdin is not very different than writing something to a named pipe. Both of them them do not reside on disk and are special types controlled by the OS.

By the way, I agree that `pipe` is a limited solution but I don't agree that it creates any kind of memory copies. If there had been an in-memory API out there it would be doing almost the same things that `pipe` protocol does right now.

**Comment by Hosseinyzr** [comment]
Thanks,I will close the issue and reopen it if needs.

**Comment by isabsent** [comment]
Can you give us a code samples to convert 
1. file from disk to pipe 
2. from pipe to another pipe?

**Comment by alexcohn** [comment]
@isabsent I believe that the [wiki](https://github.com/tanersener/mobile-ffmpeg/wiki/Pipe-Support#android) has the sample you need. Another sample which you can use a guideline for your app, is in the official test-app: https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/src/main/java/com/arthenica/mobileffmpeg/test/PipeTabFragment.java#L129

**Comment by isabsent** [comment]
@alexcohn The wiki sample is suitable for the situation where a pipe is an input and a file as an output as I understand. Is your second sample opposite to the first one?

**Comment by alexcohn** [comment]
@isabsent why would you use memory buffer for output of ffmpeg? Either save it to a temporary file, or stream it to destination using the appropriate ffmpeg streaming protocol.

**Comment by isabsent** [comment]
@alexcohn I have to get a video stream from android device camera, convert it to `.mp4` video, encrypt it and only after this procedure I can save encrypted compressed video to file. I can't keep unencrypted video on the file system.

**Comment by alexcohn** [comment]
@isabsent encryption is an interesting use case. And `.mp4` is a especially tricky because it cannot work as a stream. **ffmpeg** supports encryption, see e.g. https://stackoverflow.com/a/32735371/192373 or https://stackoverflow.com/a/44949160/192373. These are supported with **mobile-ffmpeg**. Does this answer your problem?

**Comment by isabsent** [comment]
Thanks a lot for links! I never knew `ffmpeg` supports encryption natively! I will try to figure out how to use it in my project.
