### ISSUE TITLE
setNativeEnvironmentVariable() does not call (*env)->ReleaseStringUTFChars()

### ISSUE THREAD

**Issue by alexcohn** [tanersener/mobile-ffmpeg#443]
**Description**
In [**setNativeEnvironmentVariable()**](https://github.com/tanersener/mobile-ffmpeg/blob/development/android/app/src/main/cpp/mobileffmpeg.c#L818) native implementation, Strings are converted to C from Java, but not released

**Expected behavior**
Every call to **GetStringUTFChars()** must be finalized with a corresponding call to **ReleaseStringUTFChars()**.

**Current behavior**
There seems to be no noticeable effect right now, but future hardening of the JVM or NDK may cause a problem here. Or, calling this method thousands and thousands of times could cause some visible memory leak.

**Environment**
 - Platform: Android
 - Architecture: any
 - Source branch: development, master, …

**Comment by tanersener** [comment]
Thanks, fixed in `development` branch.

**Comment by alexcohn** [comment]
I wouldn't call it *enhancement*. It's just a bug.

**Comment by tanersener** [comment]
I had initially marked this as `bug`. However, after giving a second thought to its impact, I decided to mark it as `enhancement`. As you've said, it has no noticeable effect.

**Comment by tanersener** [comment]
Released in `v4.4`.
