### ISSUE TITLE
openh264 armv7

### ISSUE THREAD

**Issue by Davarg** [tanersener/mobile-ffmpeg#444]
**Description**
Hi. I'm trying to archive application with embed ffmpeg framework. I've compiled frameworks with this command `./ios.sh --lts --enable-openh264`. Before using build script I've setted my build tools with this command `sudo xcode-select -s ~/Documents/Xcode_7.app`. But I have error `Undefined symbols for architecture armv7`

**Expected behavior**
Project successfully compiled and archived

**Current behavior**
Project archiving fails with error `Undefined symbols for architecture armv7`

**Logs**
<details>
  <summary>Errors</summary>
  Undefined symbols for architecture armv7:
  "_GeneralBilinearAccurateDownsampler_neon", referenced from:
      _GeneralBilinearAccurateDownsamplerWrap_neon in openh264(downsamplefuncs.o)

  "_VAACalcSad_neon", referenced from:
      WelsVP::CVAACalculation::InitVaaFuncs(WelsVP::TagVaaFuncs&, int) in openh264(vaacalculation.o)

  "_DyadicBilinearQuarterDownsampler_neon", referenced from:
      WelsVP::CDownsampling::InitDownsampleFuncs(WelsVP::SDownsampleFuncs&, int) in openh264(downsample.o)

  "_DyadicBilinearDownsamplerWidthx32_neon", referenced from:
      WelsVP::CDownsampling::InitDownsampleFuncs(WelsVP::SDownsampleFuncs&, int) in openh264(downsample.o)

  "_WelsIChromaPredV_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsIChromaPredPlane_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsIChromaPredH_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsIChromaPredDc_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredH_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredHD_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredVR_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredDDR_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredVL_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI4x4LumaPredDDL_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsI16x16LumaPredDc_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsSampleSatd8x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSatd8x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_VAACalcSadSsd_neon", referenced from:
      WelsVP::CVAACalculation::InitVaaFuncs(WelsVP::TagVaaFuncs&, int) in openh264(vaacalculation.o)

  "_VAACalcSadBgd_neon", referenced from:
      WelsVP::CVAACalculation::InitVaaFuncs(WelsVP::TagVaaFuncs&, int) in openh264(vaacalculation.o)

  "_WelsSampleSatd4x4_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSatd16x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSadFour8x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_DyadicBilinearDownsampler_neon", referenced from:
      WelsVP::CDownsampling::InitDownsampleFuncs(WelsVP::SDownsampleFuncs&, int) in openh264(downsample.o)

  "_WelsSampleSadFour4x4_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSadFour16x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSadFour16x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSad8x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSad4x4_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSampleSad16x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

      WelsVP::CComplexityAnalysisScreen::CComplexityAnalysisScreen(int) in openh264(ComplexityAnalysis.o)

  "_SampleVariance16x16_neon", referenced from:
      WelsVP::CAdaptiveQuantization::CAdaptiveQuantization(int) in openh264(AdaptiveQuantization.o)

  "_IdctResAddPred_neon", referenced from:
      void WelsDec::(anonymous namespace)::IdctFourResAddPred_<&(IdctResAddPred_neon)>(unsigned char*, int, short*, signed char const*) in openh264(decoder.o)

      _InitPredFunc in openh264(decoder.o)

  "_WelsIntra4x4Combined3Satd_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsQuantFour4x4Max_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_DyadicBilinearOneThirdDownsampler_neon", referenced from:
      WelsVP::CDownsampling::InitDownsampleFuncs(WelsVP::SDownsampleFuncs&, int) in openh264(downsample.o)

  "_SumOf8x8BlockOfFrame_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_WelsQuant4x4_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsQuant4x4Dc_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsDecoderI16x16LumaPredDc_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsHadamardT4Dc_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsDctT4_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsIDctT4Rec_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_WelsDequantIHadamard4x4_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_WelsIntra16x16Combined3Sad_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsIDctFourT4Rec_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_WelsDequantFour4x4_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_WelsDequant4x4_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_SumOf8x8SingleBlock_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_VAACalcSadSsdBgd_neon", referenced from:
      WelsVP::CVAACalculation::InitVaaFuncs(WelsVP::TagVaaFuncs&, int) in openh264(vaacalculation.o)

  "_SumOf16x16SingleBlock_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_WelsHadamardQuant2x2SkipKernel_neon", referenced from:
      _WelsHadamardQuant2x2Skip_neon in openh264(encode_mb_aux.o)

  "_WelsSampleSadFour8x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsSetMemZero_neon", referenced from:
      WelsEnc::InitFunctionPointers(WelsEnc::TagWelsEncCtx*, WelsEnc::TagWelsSvcCodingParam*, unsigned int) in openh264(encoder.o)

  "_WelsDecoderI16x16LumaPredV_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsDecoderI4x4LumaPredDDL_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_InitializeHashforFeature_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_WelsDecoderI4x4LumaPredH_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsDecoderIChromaPredDc_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsBlockZero8x8_neon", referenced from:
      WelsDec::WelsBlockFuncInit(WelsDec::TagBlockFunc*, int) in openh264(decode_slice.o)

  "_WelsDecoderI4x4LumaPredV_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_SumOf16x16BlockOfFrame_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_WelsDecoderIChromaPredPlane_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsDecoderIChromaPredH_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsSampleSatd16x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsDecoderI4x4LumaPredVR_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsDctFourT4_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsDecoderI4x4LumaPredDDR_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsDecoderI4x4LumaPredVL_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsBlockZero16x16_neon", referenced from:
      WelsDec::WelsBlockFuncInit(WelsDec::TagBlockFunc*, int) in openh264(decode_slice.o)

  "_WelsProcessingSampleSad8x8_neon", referenced from:
      WelsVP::CSceneChangeDetection<WelsVP::CSceneChangeDetectorVideo>::CSceneChangeDetection(EMethods, int) in openh264(SceneChangeDetection.o)

      WelsVP::CSceneChangeDetection<WelsVP::CSceneChangeDetectorScreen>::CSceneChangeDetection(EMethods, int) in openh264(SceneChangeDetection.o)

  "_VAACalcSadVar_neon", referenced from:
      WelsVP::CVAACalculation::InitVaaFuncs(WelsVP::TagVaaFuncs&, int) in openh264(vaacalculation.o)

  "_WelsIntra8x8Combined3Satd_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsDecoderI4x4LumaPredHU_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsQuantFour4x4_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsDecoderI4x4LumaPredHD_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsIntra16x16Combined3Satd_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsDecoderIChromaPredV_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsI4x4LumaPredV_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsIntra8x8Combined3Sad_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsGetNoneZeroCount_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsDecoderI16x16LumaPredPlane_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

  "_WelsHadamardQuant2x2_neon", referenced from:
      WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(encode_mb_aux.o)

  "_WelsI4x4LumaPredHU_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsSampleSad8x16_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_WelsIDctRecI16x16Dc_neon", referenced from:
      WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(decode_mb_aux.o)

  "_WelsSampleSad16x8_neon", referenced from:
      WelsEnc::WelsInitSampleSadFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(sample.o)

  "_FillQpelLocationByFeatureValue_neon", referenced from:
      WelsEnc::WelsInitMeFunc(WelsEnc::TagWelsFuncPointerList*, unsigned int, bool) in openh264(svc_motion_estimate.o)

  "_WelsI16x16LumaPredPlane_neon", referenced from:
      WelsEnc::WelsInitIntraPredFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int) in openh264(get_intra_predictor.o)

  "_WelsDecoderI16x16LumaPredH_neon", referenced from:
      _InitPredFunc in openh264(decoder.o)

ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</details>

**Environment**
 - Platform: iOS (10)
 - Architecture: armv7
 - Xcode version: 11.5 (11E608c)

**Other**
If I start building project for iOS > 10 everything is Ok. Flag for linker '-ObjC' is breaks everything

**Comment by tanersener** [comment]
`build.log` file can explain what is wrong with your build. Can you share it?

**Comment by Davarg** [comment]
@tanersener Thank you for response but easiest solution was just remove support of iOS 10
