### ISSUE TITLE
JNI_OnLoad should never detach its thread

### ISSUE THREAD

**Issue by alexcohn** [tanersener/mobile-ffmpeg#446]
**Description**
In `JNI_OnLoad()` there are three error cases [1](https://github.com/tanersener/mobile-ffmpeg/blob/7d9747789be58d343ff555d6e0fdf576a1503c36/android/app/src/main/cpp/mobileffmpeg.c#L610), [2](https://github.com/tanersener/mobile-ffmpeg/blob/7d9747789be58d343ff555d6e0fdf576a1503c36/android/app/src/main/cpp/mobileffmpeg.c#L617), [3](https://github.com/tanersener/mobile-ffmpeg/blob/7d9747789be58d343ff555d6e0fdf576a1503c36/android/app/src/main/cpp/mobileffmpeg.c#L624) that call `DetachCurrentThread()` (when some really nasty error happens).

**Expected behavior**
Only threads that are created from C may be detached.

**Current behavior**
The thread was created by JVM, so it should not be detached in JNI.

**Environment**
 - Platform: Android
 - Architecture: any
 - Version: v1.2
 - Source branch: master, and others

**Comment by tanersener** [comment]
Thanks, fixed in `development`.

**Comment by tanersener** [comment]
Released in `v4.4`.
