### ISSUE TITLE
Can I get debugable android so files with symbols within?

### ISSUE THREAD

**Issue by foobra** [tanersener/mobile-ffmpeg#447]
**Description**
The output android so didn't contain any debug symbol even I compile with -d

**Expected behavior**
Generate symbol so

**Screenshots**

**Environment**
 - Platform: Android
 - Architecture: x86
 - Version (if applicable) 4.2.1
 - Source branch (if applicable) 4.2.1
 - Android Studio version (if applicable) 4.0
 - Android NDK version (if applicable) r21

**Comment by tanersener** [comment]
Fixed in `development` branch.

**Comment by tanersener** [comment]
Released in `v4.4`.
