### ISSUE TITLE
Download required *.so files on runtime based on architecture

### ISSUE THREAD

**Issue by ChandraNakka** [tanersener/mobile-ffmpeg#449]
Dear @tanersener and developers,

I'm using this FFmpeg library on my APK project to convert video to audio and other media processing purposes.

But, using this library highly increases output APK file size. When I see list of files in **ARR** file it contains heavy **.so** files. So, these **.so** files increases my output APK file size.

So, is this possible to download and use required **.so** files on runtime based on mobile architecture. Instead of packing all .so files for all architectures.

**NOTE:** Due to some Google Play Store policies I can't upload my APK file to their store. Users need to download and install my APK file from internet.

So, even if I build different APK files for each architecture. Common user will confuse which architecture his mobile support and which APK file he needs to download.

So, please provide solution for my issue. I'm ready to pay for this contract.

Thank you :)

**Comment by alexcohn** [comment]
Vast majority of active Android devices can run **ameabi-v7a** code. The outliers are some extinct tablets (production of Atom devices was discontinued some 4 years ago), Chromebooks, and emulators. Do you care about these?

Note that most of the confusion about multiple ABI packaging is about the Google requirement to post 64-bit versions of apps in Play Store. If you are not on Play Store, you don't really need a 64-bit version of your app.

On the other hand, the number of 32-bit active devices is deteriorating at high speed. I don't have up-to-date statistics at hand, but I believe that supplying only **arm64** version of your app you won't loose much audience.
