### ISSUE TITLE
When will the new version of ffmpeg add delogo filtering?

### ISSUE THREAD

**Issue by shuszj** [tanersener/mobile-ffmpeg#450]
There is no delogo filtering service in the current ffmpeg version. I hope the author can add it in the next version. Thank you!

**Comment by tanersener** [comment]
See [GPL Licensed Filters](https://github.com/tanersener/mobile-ffmpeg/wiki/GPL-Licensed-Filters).

**Comment by shuszj** [comment]
How to reference GPL in Android?

**Comment by shuszj** [comment]
> See [GPL Licensed Filters](https://github.com/tanersener/mobile-ffmpeg/wiki/GPL-Licensed-Filters).

How to reference GPL in Android?

**Comment by shuszj** [comment]
> See [GPL Licensed Filters](https://github.com/tanersener/mobile-ffmpeg/wiki/GPL-Licensed-Filters).

Is Android compiled and directly referenced?

**Comment by shuszj** [comment]
Thank you very much！

**Comment by solankiranvir** [comment]
Hello Sir
I can't understand how to install GPL License for support delogo filtering.
Can you please give me exact solution for Android, which gradle i will import?

**Comment by tanersener** [comment]
You need to install one of the `mobile-ffmpeg` packages ending with `-gpl`. They are licensed under `GPL`.

**Comment by solankiranvir** [comment]
Thank You It's working now.
