### ISSUE TITLE
Build FFmpeg and FFprobe alongside with shared native libraries

### ISSUE THREAD

**Issue by nlgtuankiet** [tanersener/mobile-ffmpeg#457]
**Description**

Before converting a media user would want to see the details for their file (container, codec, and other information) => I need FFprobe executable, FFmpeg would do that too but not enough details. 

Convert a video require a lot of RAM so typically you would want to offload it to another process => I need FFmpeg executable to execute via `Runtime.getRuntime().exec()`. Also, the app has to support parallel execution, viewing process and cancellation, that why `Runtime.getRuntime().exec()` is a must.

For now, each executable take about 12mb, I believe that because they are built as a standalone executable file. Does having both executable files that share common .so file possible? If yes how can I do that because for now, I have no clue where to start. If not would you recommend any other solution?

Thanks!

**Expected behavior**
What you expected to happen.
12Mb for all FFmpeg FFprobe and shared libraries

**Current behavior**
12Mb for each FFmpeg FFprobe executable

**Environment**
 - Platform: Android
 - Architecture: All

**Comment by tanersener** [comment]
Did you try to use `MobileFFmpeg` in your application? You don't need to have `executables` to do the things you've said.

**Comment by nlgtuankiet** [comment]
@tanersener In my case, I need to use Runtime.getRuntime().exec() with executable file unfortunately

**Comment by tanersener** [comment]
`MobileFFmpeg` does not create `executables` for `FFmpeg` and `FFprobe` by default. It is possible to edit the scripts and generate them. [Building ffmpeg executable on Android](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) wiki page explains which files should be updated. However, steps explained there don't work on all devices. So, I can't guarantee that it will work for you.

**Comment by nlgtuankiet** [comment]
I tried to edit the script today, It creates several .so files and 2 executable ffmpeg and ffprobe as expected. Then I rename ffmpeg to libffmpeg.so to trick the android gradle plugin so that it will include the executable libffmpeg.so into the apk the extract it when the apk got installed. As the result, I can locate and execute libffmpeg.so, but it got error
```CANNOT LINK EXECUTABLE "libffmpeg.so" : library "libavdevice.so" not found```
Any ideas on how to solve this?

**Comment by tanersener** [comment]
No.

**Comment by nlgtuankiet** [comment]
Having 2 executable is kind of okay, the trade-off is your APK size will increase for about ~12mb, I will stick with that until we find out a better solution for this :(

**Comment by alexcohn** [comment]
When you build an executable that needs libavdevice.so and others, there is very little duplication, so the increase of size is inevitable. On the other hand, you can split by the ABI, and have smaller APKs for arm64, x86, etc.

**Comment by nlgtuankiet** [comment]
@alexcohn but 
When I build the executables with *.so, the executables show `CANNOT LINK EXECUTABLE "libffmpeg.so" : library "libavdevice.so" not found` when execute. 
Build 2 executable alone (with no .so files) then the size is double.
I use Android App Bundle so it split by the ABI by default

**Comment by nlgtuankiet** [comment]
Current working (double the size)
```
Output:
FFmpeg 12mb
ffprobe 12mb
```

Best base scenario (which current yell `CANNOT LINK EXECUTABLE`)
```
Output:
ffmpeg 100Kb
ffprobe 200kb
libav.so 6mb
libxx.so 1mb
...
```

**Comment by alexcohn** [comment]
You miss the environment parameter when you exec **ffmpeg**, e.g. like this:

    Runtime.getRuntime().exec(new String[]{"./libffmpeg.so", "--version"}, new String[]{"LD_LIBRARY_PATH=."}, getApplicationInfo().nativeLibraryDir);

**Comment by nlgtuankiet** [comment]
@alexcohn thank you very much, I will try that tomorrow

**Comment by nlgtuankiet** [comment]
@alexcohn l
thank man. it works like a charm

**Comment by alexcohn** [comment]
@tanersener it may be nice to document this use case in the [Wiki](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android)

**Comment by tanersener** [comment]
@alexcohn I think the case documented in the wiki is different than the case discussed here. Wiki page describes how to generate `ffmpeg` executable. In this thread, we have a case where both `ffmpeg` executable and other shared libraries are generated.

**Comment by alexcohn** [comment]
Right, the Wiki page speaks about statically-linked executables. It may be worth adding the case of shared-lib-linked executables, too. And the [story](https://github.com/android/ndk/issues/1300) of obligatory renaming and avoiding `android:extractNativeLibs=false`

**Comment by tanersener** [comment]
I don't know what that story is. Can I skip that part? 
I created this project to save people from those tricks and workarounds.
Ironically, I'm asked to write down a wiki about them.

**Comment by alexcohn** [comment]
Sorry, I didn't mean to offend you.

**Comment by tanersener** [comment]
@alexcohn No worries. I know you didn't. I'm just trying to say that I don't want to document a workaround which is beyond the scope of the project. I also don't know the details of it. 

Updated the wiki. When google decides to document those workarounds we may put a link about them in the wiki.

**Comment by alexcohn** [comment]
@tanersener thank you for being awesome!
