### ISSUE TITLE
Smart Exception do not importing

### ISSUE THREAD

**Issue by d1hamid** [tanersener/mobile-ffmpeg#458]
Hi.
I'm used this line in my gradle to test the "Test-App" in my Android Studio :

`implementation 'com.arthenica:mobile-ffmpeg-full:4.3.2'`

All things is OK except this importing having some truble's for the Exceptions lines:

import com.arthenica.smartexception.java.Exceptions;

This line of importable link that located in MainActivity, do not importing.
I need your help.
Thank you for reading my issue

**Comment by tanersener** [comment]
As you can see from [this line](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/build.gradle#L56) test application depends on `smart-exception-java` package. Do you have that dependency in your `build.gradle`?

**Comment by d1hamid** [comment]
ohhh yes. thank you for your attention. thnak you for your solution. its solved
