### ISSUE TITLE
Unable to  build 'vdpau/vdpau.h' file 

### ISSUE THREAD

**Issue by ingviso** [tanersener/mobile-ffmpeg#46]
**Description**
I'm building in Xcode10 for ios, going to use this for react-native project, have gone through the setup process and all seems to be up to date. 

**Expected behavior**
Being able to build.

**Current behavior**
Unable to  build 'vdpau/vdpau.h' file not found comes up.

**Screenshots**
<img width="1566" alt="screenshot 2018-12-04 22 22 27" src="https://user-images.githubusercontent.com/8041943/49477090-b6382500-f813-11e8-9c8a-b275be6f66a1.png">

**Environment**
 - Platform:IOS
 - Architecture: arm64
 - Source branch: master
 - Xcode version: 10

Am I missing some package that I need to install?

**Comment by tanersener** [comment]
No, it is not about a missing package. It looks like something is wrong in `Xcode` settings. 

According to the screenshot, you are trying to import `universal binary` packages. There is a [Using IOS Universal Binaries](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-IOS-Universal-Binaries) guide which lists all necessary steps to import `universal binary` packages into `Xcode`. Did you applied item `#4` and `#5` of this guide in your project?

By the way, I have `react-native` version of this library named [react-native-ffmpeg](https://github.com/tanersener/react-native-ffmpeg). It is not perfect but I think it has the solutions for some of your possible problems. You may want check it out. It loads libraries from `CocoaPods`.

**Comment by ingviso** [comment]
The issue came because I was using the legacy build system in Xcode so problem solved.
The reason I wanted to use this library is that I'm doing some media processing in C++ and I wanted to call ffmpeg from there, so my thought was to use your great library and bridge between C++/object C and C++/java.
