### ISSUE TITLE
Live transcoding from H265 to H264 on Mobile

### ISSUE THREAD

**Issue by itziksha** [tanersener/mobile-ffmpeg#460]
Hi, 
Our application works with cameras which provide H265 (HEVC) video encoding, but not all browsers / players, supports this encoding, so we were looking for solution.

One solution, was to make the transcoding from H265 to H264 on the cloud, 
but we would like to know if there is a solution to make the transcoding on the mobile itself (Android / iOS) and not on the server.

The video is live, so it’s required to be live transcoding, and not playback only after full conversion of the video....

**Does this library supports it such transcoding?
If not, can you point me to other solutions?**

(BTW, Our app is hybrid, using Ionic, so we can make the transcoding on the native side, and pass it to the app browser. If it's not possible, we can maybe play it on a native player)

Thanks!

**Comment by tanersener** [comment]
It is possible to capture the camera input, transcode it and stream it to another destination. However, capturing audio is not possible  on Android as far as I remember.

**Comment by itziks00** [comment]
> It is possible to capture the camera input, transcode it and stream it to another destination. However, capturing audio is not possible on Android as far as I remember.

@tanersener , Thank you for your answer.
I'm not sure I understand.
My mobile client will receive the video in h265 encoding, so I have to transcode it to h264 locally and stream to my browser, or to a native media player. Is it what you meant? 
Is it possible to make transcoding of the encoding types I mentioned, using this mobile-ffmpeg lib?
Thanks.

**Comment by tanersener** [comment]
Sorry, my bad. I thought you were capturing the camera as input. 

Yeah, you can do that with `MobileFFmpeg`. But you may need to use one of the GPL licensed packages if you want to encode `h264`.
