### ISSUE TITLE
Using ffmpeg with Cisco's prebuilt openh264 - is it possible?

### ISSUE THREAD

**Issue by JesperLR** [tanersener/mobile-ffmpeg#461]
**Description**
I am currently building mobile-ffmpeg with this build config:
./android.sh -l --enable-libopenh264 --disable-arm-v7a-neon --disable-arm64-v8a --disable-x86 --disable-x86-64

But I wish to use a prebuilt binary of openh264 from Cisco (see https://github.com/cisco/openh264/releases) in order to avoid having to pay MPEG LA license fees (see http://www.openh264.org/faq.html for more info).

Is there a way of enabling openh264 library support for the mobile-ffmpeg build, but instead of building/packaging it, then linking it to a openh264 binary that can then be provided at runtime?

**Expected behavior**
Being able to use a prebuilt openh264 binary.

**Current behavior**
Only able to build mobile-ffmpeg with the openh264 being built into the packaged aar.

**Environment**
 - Platform: Android/IOS
 - Architecture: [arm-v7a
 - Version: v4.3.1.LTS

**Comment by tanersener** [comment]
I think this question is about capabilities of Android/iOS. Can you download an `.so` or `.a` library to your mobile application and load it inside your application?

**Comment by JesperLR** [comment]
Yes - I have not tried it myself yet, but it sounds very possible judging from e.g. https://blog.hike.in/reduce-the-size-of-your-app-by-moving-so-files-to-over-the-air-b51ca9dfdaf2 which uses Facebook's library (https://github.com/facebook/SoLoader) to load an externally stored .so file at runtime.

I guess my question is how I might go about building mobile-ffmpeg so that it has openh264 enabled for ffmpeg, but without packaging it into the mobile-ffmpeg.aar

I have later found this project https://github.com/fourtalk/ffmpeg-android-kotlin that indicates that it is indeed possible to have ffmpeg and openh264 separate in a project and still let ffmpeg use the openh264 .so. But I would prefer to use mobile-ffmpeg as a packaging if possible :)

**Comment by tanersener** [comment]
Hmm, 2 quick questions then.

1. Did you read `Patent Mini-FAQ` section in https://ffmpeg.org/legal.html? `ffmpeg`s position in terms of MPEG LA is not too much different than `openh264`. Do you plan to download it too?

2. iOS?

**Comment by JesperLR** [comment]
Sure :)
1. Yes, I do not think there should be any issues when building ffmpeg without --enable-gpl and when only using openh264 by downloading the binary from Cisco and using that for H.264.

2. Luckily not needed for my project :)

**Comment by tanersener** [comment]
I don't think you understand why you're doing these things. License and MPEG LA are different things. Using or not using GPL doesn't change anything in terms of MPEG LA. Anyway, it's your responsibility. If you're happy with what you're doing, then I don't have anything to add.

I must also to say that the thing you do not think will be an issue for you is an issue for the library. So, I can't ignore it. There will be some changes in the library because of this too.

Regarding your original question. The feature you ask needs changing how ffmpeg and external libraries are packaged for Android. It's not simple as you think. Also, implementing that means abandoning the current approach. So, I need strong arguments to make that change. Currently, I disagree with you about your reasons/arguments. They're not valid for the library.

**Comment by JesperLR** [comment]
I hope that I do understand why I'm trying to do this ;)
So as I understand it, ffmpeg is covered by LGPL, which is usable in commercial contexts as well (with conditions of course, but reasonable ones to a company), unless otherwise determined by enabling gpl / packaging other libraries that require the use of GPL - but I don't have any need for those I think. 
And H.264 has the implication that you need to pay license fees to MPEG LA, unless you use the openh264 prebuilt binary from Cisco and follow their requirements, which among other things is that the prebuilt binary must be downloaded at runtime.

Hope this explained the use case better - otherwise please correct me if I've misunderstood something in that regard.

I think this could also be usable for others who wish to comply with the licensing, but without paying for it. Or others who wish to have a smaller apk and download external .so library files as needed on runtime.

**Comment by tanersener** [comment]
MPEG LA covers both encoders and decoders. And `ffmpeg` has a builtin `H264` decoder as you know. You don't need to have `x264` or `openh264` to use it. That's why I believe `openh264` is only a part of the problem.

**Comment by JesperLR** [comment]
Oh.. I see, so actually I would need to purely use openh264 then and skip ffmpeg altogether, or find a way to not include the H264 decoder when building ffmpeg and rely on openh264 for decoding.
Any idea if it's possible to exclude the H.264 decoder from ffmpeg?

**Comment by tanersener** [comment]
I haven't tried it before but it should possible. All `ffmpeg` components can be enabled/disabled.

By the way, I have to add that builtin `H264` decoder is one of the components that I know is bound to MPEG LA. However, there can be others as well. `MPEG4` decoder can be bound to MPEG LA too. Even`ffmpeg` developers themselves can't or don't answer that question. So, I just want to remind you that.

**Comment by JesperLR** [comment]
Ok, thank you for the input, much appreciated!
I will keep an eye out for other decoders that might be license related too, and see if I can make it work or if it's perhaps possible to use openh264 on it's own :)

**Comment by silvershort** [comment]
@JesperLR 
Did you succeed in adding the openh264 binary separately and using it in mobile-ffmpeg?

**Comment by JesperLR** [comment]
I didn't get a chance to try unfortunately.
