### ISSUE TITLE
Why should I use LTS instead of "overrideLibrary" tag in Manifest?

### ISSUE THREAD

**Issue by isabsent** [tanersener/mobile-ffmpeg#464]
`implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.3.2'` along with `minSdkVersion 23` is impossible. I know the problem with 

    Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-min-gpl:4.3.2] C:\Users\isabs\.gradle\caches\transforms-2\files-2.1\0fb42e5a1813c7b0b9dd6ab429831415\jetified-mobile-ffmpeg-min-gpl-4.3.2\AndroidManifest.xml as the library might be using APIs not available in 23
	Suggestion: use a compatible library with a minSdk of at most 23,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)
can be solved by using `'com.arthenica:mobile-ffmpeg-min-gpl:4.3.1.LTS'` version of your library. But I would like to solve it overriding your `Manifest` on merge by means of 

    tools:overrideLibrary="com.arthenica.mobileffmpeg"
tag in the `Manifest` along with  `Build.VERSION.SDK_INT > Build.VERSION_CODES.M` condition in a code. However this does not help. I can't compile my project (error message is the same) and can't understand why, because I definitely solved such problem with other libraries in other projects.

**Comment by isabsent** [comment]
Please, regard!

**Comment by tanersener** [comment]
`non-LTS` versions can not be run under API Level 24. There are native symbols that this library depends on. This is why `min-sdk` is 24 for those versions. It is not there for fun.
