### ISSUE TITLE
whats the minSdk version for this library?

### ISSUE THREAD

**Issue by SoniKarsh** [tanersener/mobile-ffmpeg#465]
**Description**
I have read whole read me and it shows that it supports sdk 16+. But it is not letting me run by giving me error that this library requires 24+.

**Expected behavior**
Want it to run for 21+

**Current behavior**
it doesnt let me run for 21+ and keep asking me to change min sdk to 24.

**Environment**
 - Platform: Android

** LOGS **
 - Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.arthenica:mobile-ffmpeg-full:4.3.2] 5888d33cf80d410d9e94841609a6b402/jetified-mobile-ffmpeg-full-4.3.2/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.mobileffmpeg" to force usage (may lead to runtime failures)

**Comment by tanersener** [comment]
See [LTS Releases](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases) and [Versions](https://github.com/tanersener/mobile-ffmpeg#3-versions).

**Comment by SoniKarsh** [comment]
> See [LTS Releases](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases) and [Versions](https://github.com/tanersener/mobile-ffmpeg#3-versions).

Thanks it worked.
