### ISSUE TITLE
Generating mp4 video from ffmpeg command but generated mp4 could not be played in exo player.

### ISSUE THREAD

**Issue by SoniKarsh** [tanersener/mobile-ffmpeg#467]
**Description**
I am trying to conver array of bitmaps to video of mp4 and i have tried that using below ffmpeg command which is 

val cmd2 = arrayOf(
            "-y",
            "-r",
            "2",
            "-f",
            "image2",
            "-i",
            filesDir.toString() + File.separator + "%d.jpg",
            newFilePath
        )

But in some device it is able to generate video but video could not be played by exo player.

**Expected behavior**
I want to generate mp4 video and then want to play it in Exo player.

**Current behavior**
In some device it is generating video but then cant be played by exo player.

**Logs**
When Video is gettting generated and not working in Exo player.
![carbon](https://user-images.githubusercontent.com/22278154/85196680-84a18480-b2f9-11ea-8d33-b69f98f26c54.png)

***Environment
Platform - Android

**Comment by tanersener** [comment]
> But in some device it is able to generate video but video could not be played by exo player.

Can you give more details about this? Do you receive this error on all devices or specific devices? Also, did you try to pull the file to your computer and play it there?

We know that some Android devices do not support specific MPEG profiles and resolutions. This can be the reason of your issue.

**Comment by SoniKarsh** [comment]
yes i have tried playing this by dragging it out of location and it played using VLC but couldnt play in Exo player. I dont know whats the issue. same command i have tried using https://github.com/WritingMinds/ffmpeg-android this library and it worked but this one doesnt work on all devices and it also dont support target SDK 29 or above, and also its not that active.so, i have tried this one and it worked on almost all the devices but just it didnt play in exo player but when used https://github.com/WritingMinds/ffmpeg-android this api it also played the video in exo player,

**Comment by tanersener** [comment]
Can you provide console outputs for both executions? Or`ffprobe` output for those two files, the one created with `WritingMinds` library and the other one created with `MobileFFmpeg` ?

**Comment by SoniKarsh** [comment]
Console Output of 'com.arthenica:mobile-ffmpeg-full:4.3.1.LTS' is already given above and
ffmpegprobe is as shown below.
-> 
![carbon(1)](https://user-images.githubusercontent.com/22278154/85205196-63f81f80-b337-11ea-86e4-ca5a77682840.png)

Console Output of 'https://github.com/writingminds/ffmpeg-android' 
Log of the device in which this one is not working or video is not getting generated
-> 
![carbon(6)](https://user-images.githubusercontent.com/22278154/85205394-cdc4f900-b338-11ea-8b4a-3c321e677932.png)
-> Log of the device in which this one is working or video is getting generated and played in exo player
![carbon(7)](https://user-images.githubusercontent.com/22278154/85205754-efbf7b00-b33a-11ea-9b54-abebed260900.png)

I have provided all logs and let me know if you need any other thing.

**Comment by tanersener** [comment]
This line shows codec information of the video generated by `MobileFFmpeg`.

<img width="601" alt="Screenshot 2020-06-20 at 17 11 58" src="https://user-images.githubusercontent.com/10158439/85206418-f25da880-b319-11ea-9567-540f535c316e.png">

This line shows codec information of the video generated by `WritingMinds` library.

<img width="612" alt="Screenshot 2020-06-20 at 17 13 58" src="https://user-images.githubusercontent.com/10158439/85206449-1de09300-b31a-11ea-9936-52d00e95c57f.png">

You can see that `MobileFFmpeg` generates an `mpeg4` file. But `WritingMinds` generate a `h264` file using `x264` encoder. 

As I've told you in my first post, some Android devices do not support specific MPEG profiles and resolutions. The following part from your screenshot shows proves my point. Your device does not support `1080x2244x2` for `mpeg4` files.

![Screenshot 2020-06-20 at 17 13 13](https://user-images.githubusercontent.com/10158439/85206507-83348400-b31a-11ea-815b-5bd4d660f3ad.png)

**Comment by SoniKarsh** [comment]
Ohkay, so is there any way using which i can generate h264 format using this library.com.arthenica:mobile-ffmpeg-full:4.3.1.LTS?

**Comment by tanersener** [comment]
You need to install one of the `GPL` licensed packages to use `libx264`. Then update your command and add `-c:v libx264` before your output file path.

**Comment by SoniKarsh** [comment]
Ohkay, so i need to install externally means along with this ffmpeg mobile. right?

Thanks for your quick responses.

**Comment by tanersener** [comment]
There are 8 different `mobile-ffmpeg` packages. Your logs show that you're using the `full` package. `GPL` packages are packages that end with `-gpl`. You can see them and external libraries included inside them under [2. Using](https://github.com/tanersener/mobile-ffmpeg#2-using). To install a package use instructions given in [2.1 Android](https://github.com/tanersener/mobile-ffmpeg#21-android).

**Comment by SoniKarsh** [comment]
I have done already what you said and these are things that i got

When i have used this library with min-gpl then it worked but in some device i got the error like

[libx264 @ 0x72620cce00] height not divisible by 2 (1080x2157)

E/mobile-ffmpeg: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

and i also wanted to ask is using gpl version and if i make this app and launch it then do i have to pay or something?

**Comment by tanersener** [comment]
I believe you see `height not divisible by 2` error. Please search for it on google. There are a lot of pages that can help you to understand why you receive it and how you can overcome that error.

In terms of licensing, refer to [Using MobileFFmpeg in Commercial Applications](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Commercial-Applications).

In terms of software patents, please read [Patent Mini-FAQ](https://www.ffmpeg.org/legal.html).

**Comment by maypic112** [comment]
@SoniKarsh Have you resolve the issue? I m facing same issue 

@tanersener Is there method to check device support MPEG profiles and resolutions?

**Comment by SoniKarsh** [comment]
> @SoniKarsh Have you resolve the issue? I m facing same issue
> 
> @tanersener Is there method to check device support MPEG profiles and resolutions?

I have resolved that issue by using implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.3.1.LTS'

**Comment by alexcohn** [comment]
@maypic112 Yes you can check the supported profiles and resolutions, see e.g. https://github.com/google/ExoPlayer/issues/6233#issuecomment-517343490. The bigger question is which you want to achieve: produce a video that can play on the same device, or a video that can be shared with other devices? In the latter case, `mediaCodecInfo.capabilities.getVideoCapabilities()` will not help; you must decide what range of devices and players you want to be supported.
