### ISSUE TITLE
si_destination_compare ffmpeg error when streaming RTSP to VLC as well as streaming the same to Youtube Live on iOS 13.5.1

### ISSUE THREAD

**Issue by jaydeepw** [tanersener/mobile-ffmpeg#468]
**Description**
On iOS, if I use a RTSP stream from a IP camera and pipe it to VLCPlayer from [MobileVLCKit](https://github.com/videolan/vlckit), it works seamlessly. However, at the same time, on press of a button in the UI, the RTSP stream is transcoded using following command and then supplied to authenticated RTMP url of Youtube live, then the VLCPlayer suddenly freezes.

Besides, if I try above steps with a RTSP stream of a [Bunny movie](rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it streams simultaneously for both, VLCPLayer and Youtube live at the same time.

```
MobileFFmpeg.execute("-i \"\(self.rtspIPCameraURL!)\" -re -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -f h263 -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv \"\(self.rtmpURL!)\"")
```

**Expected behavior**
Both streams, the one in VLCPlayer as well as the one being streaming online to Youtube live should continue playing until the end of the stream. Like it does in case of the Bunny movie url.

**Current behavior**
When streaming to youtube starts, the display of the stream in the VLCPlayer freezes

**Error in XCode console**
Loaded mobile-ffmpeg-full-arm64-4.3.2-20200415
[si_destination_compare] send failed: Invalid argument
[si_destination_compare] send failed: Undefined error: 0

**Environment**
 - Platform: - iOS - 13.5.1
 - Xcode version - 11.5
 - Cocoapods version - 1.9.0
- MobileVLCKit - 3.3.13
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64]

**Comment by tanersener** [comment]
You have multiple `ffmpeg` implementations in your application. See [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application).
