### ISSUE TITLE
Video roate

### ISSUE THREAD

**Issue by gururajKp** [tanersener/mobile-ffmpeg#470]
Hi I am using your library for my project working fine. 

**Expected behavior**
Roate video 0 degree,90 degree,180 and 270 degree.

**Current behavior**
Once I rotate video first time using the command "-y", "-i", inputpath, "-metadata:s:v:0", "rotate=" + rotation, "-codec", "copy", output, it is working fine. But when i rotate the already rotated video then its not working correctly. If I give angle 90, it is rotating 270. for 0 180 it is rotating 90.

**Environment**
 Android

**Comment by tanersener** [comment]
Would you mind sharing the version information?

**Comment by gururajKp** [comment]
> Would you mind sharing the version information?
This one
com.arthenica:mobile-ffmpeg-min-gpl:4.2.2.LTS

**Comment by tanersener** [comment]
Your command updates the metadata information of the file. Updating metadata means writing metadata keys & values inside the file but the video stream is not changed at all.

When you're writing rotate information again you're overriding previous rotate values. So, it doesn't matter whether it was previously rotated or not. The final rotate value is always the value you entered in your second command.

So, nothing is wrong there. You need to give the final rotate metadata value you want to have in your second command to achieve what you want to do. Or you can use rotate filter to do that.

After running the first command with rotate=90, this is what you have in your file.

```
    Metadata:
      rotate          : 270
    Side data:
      displaymatrix: rotation of 90.00 degrees
```

This is what you have after using rotate=270 on the new file.

```
    Metadata:
      rotate          : 90
    Side data:
      displaymatrix: rotation of -90.00 degrees
```

**Comment by gururajKp** [comment]
> You need to give the final rotate metadata value you want to have in your second command to achieve what you want to do

I din't get this one "You need to give the final rotate metadata value you want to have in your second command to achieve what you want to do" as i am using single command line and how to change that rotate metadata ?

**Comment by tanersener** [comment]
Your first command updates the rotate key and sets it to 90.
If you want to rotate it 90 degrees more, then you need to use 90 + 90 = 180 in your command. Because as I've explained in my previous post, your command is overriding existing metadata keys.
