### ISSUE TITLE
mobile ffmpeg fails to recognize enable='between(t,start_time,end_time)' in drawtext

### ISSUE THREAD

**Issue by digitGrove89** [tanersener/mobile-ffmpeg#473]
`-i /sdcard/input.mp4 -i /sdcard/img_1.png -filter_complex [0][1]overlay=135:104:enable='between(t,0,5)' -pix_fmt yuv420p -c:a copy -c:v mpeg4 /sdcard/output.mp4`

I'm getting a error message Missing ')' or too many args in 'between(t' ... could you help me with this issue..
i made sure no extra spaces or double quotes are used.. but still getting this error message below..

**Logs**
 [overlay @ 0x7cd9257400] [Eval @ 0x7fffea06e0] Missing ')' or too many args in 'between(t'
    [overlay @ 0x7cd9257400] Error when evaluating the expression 'between(t' for enable
    [AVFilterGraph @ 0x7cd92a7c00] Error initializing filter 'overlay'[AVFilterGraph @ 0x7cd92a7c00]  with args '135:104:enable=between(t'[AVFilterGraph @ 0x7cd92a7c00] 
    Error initializing complex filters.
    Invalid argument

**Comment by tanersener** [comment]
Did you try wrapping your filter complex body with double quotes?

**Comment by digitGrove89** [comment]
Thanks a lot.. wrapping it around double quotes worked..
