### ISSUE TITLE
ffmpeg for ARM based Mac

### ISSUE THREAD

**Issue by jack445** [tanersener/mobile-ffmpeg#474]
Apple has announced to bring its own ARM chip for Mac. Are there any plans to create a version compatible with the upcoming ARM based Macs ? I see that the support has been added till Mac-Catalyst.

**Comment by tanersener** [comment]
This project doesn't target supporting non-mobile platforms. So, there has to be some reasons for that. Right now, I don't see any benefits of adding that support.
