### ISSUE TITLE
Using Multiple FFmpeg Implementations In The Same iOS Application

### ISSUE THREAD

**Issue by Geremp** [tanersener/mobile-ffmpeg#475]
**Description**
Hello,

I am using an SDK to stream video in Webrtc.
These SDK use VP8/VP9 encoder.
I guess ffmpeg too…

Because, if i stream without link your framework (pod install), it is working.
If i link your framework, i cannot stream, the image is black and i get this error on the debug log : LibVpxFM: Creating and configuring VPX encoder.

I learn this page : https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application

But in can't find a way, because for my Webrtc SDK, the lib is link on the project tab General : Framework, libraries and Embed content.
So i cannot see them in the file POD as you can mention.
So i don't know how i can link your lib before them

**Expected behavior**
Use LiveSwitch SDK VP8 encoder to stream

**Current behavior**
error  : LibVpxFM: Creating and configuring VPX encoder.

**Screenshots**
![Capture d’écran 2020-06-25 à 19 45 45](https://user-images.githubusercontent.com/6321146/85771793-8c5b9180-b71c-11ea-8b17-5cb56e8b8f6a.png)
![Capture d’écran 2020-06-25 à 19 46 05](https://user-images.githubusercontent.com/6321146/85771810-8f568200-b71c-11ea-81d2-e6b252e58585.png)

**Logs**
[LiveSwitch][18354][10745335232] DEBUG   [FM][-] 2020-06-25T17:37:23.451Z LibVpxFM: Creating and configuring VPX encoder.

**Environment**
 - Platform: iOS 13
 - Architecture: No idea -> iphone 8
 - Version : pod 'mobile-ffmpeg-full', '~> 4.3.2'
 - Source branch : pod 'mobile-ffmpeg-full', '~> 4.3.2'
 - Xcode version : 11.4.1
 - Cocoapods version : 1.9.3

**Comment by tanersener** [comment]
I explained the situation about multiple `ffmpeg` implementations in that wiki page. Solution given there is an example about how the issue can be resolved for a library (`MobileVLCKit`) which is installed using `cocoapods`. 

For other cases, like your case, where the second library is not installed using `cocoapods`, approach is the same. The linking order has to be changed. However, I haven't tried it before and I don't know whether it is possible or not. So, I recommend googling about it.

You've said that your library is a VP8/VP9 encoder. Maybe you have two `libvpx` implementations in your app and this is the actual problem. Try using other `mobile-ffmpeg` packages which do not include `libvpx` and see if the error persists.
