### ISSUE TITLE
My building is not finding any libraries.

### ISSUE THREAD

**Issue by vncsms** [tanersener/mobile-ffmpeg#478]
**Description**
When i execute `./android.sh` is not finding any libraries and the built just dont finish.:

```

Building mobile-ffmpeg library for Android

Architectures: arm-v7a-neon, arm64-v8a, x86, x86-64
Libraries: none

Building arm-v7a-neon platform on API level 24


ffmpeg:

```

**Environment**
 - Version: v4.3.2
 - Android NDK version: 21.3

**Comment by tanersener** [comment]
This is the default behaviour. If you want to enable a library you need to add `--enable-<library name>` flag. 

If your build does not complete then check `build.log` file. It collects all details about your build. If something is wrong it will be listed there.
