### ISSUE TITLE
Is there anything to update if releasing with app bundle(.aab)?

### ISSUE THREAD

**Issue by chitrang200889** [tanersener/mobile-ffmpeg#479]
**Description**
We're using implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.1.LTS' version of the library. And planning to release the Android app as an app bundle in .aab format instead of uploading multiple APKs.

 ```
   bundle {
        density {
            enableSplit false
        }
        language {
            enableSplit false
        }
        abi {
            enableSplit true
        }
    }
```
I've been researching a lot about the app bundle and came across this [SO question](https://stackoverflow.com/questions/51092745/android-app-bundle-apk-doesnt-include-required-native-library).
There are different types of architectures [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]. 

1) So do I need to exclude certain kinds of architectures for Google Play Store release with the app bundle?

2) Also, it there a way to check which FFmpeg architecture is installed at runtime?

**Comment by alexcohn** [comment]
The bundle support will handle the architectures for you. 

[`AbiDetect.getAbi()`](https://tanersener.github.io/mobile-ffmpeg/android/javadoc/com/arthenica/mobileffmpeg/AbiDetect.html#getAbi--) will tell you which ABI is running.
