### ISSUE TITLE
[Android] Build fails for NDK r18b

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#48]
Building `mobile-ffmpeg` sources for `Android` platform fails on `NDK r18b`. The following error log should be analyzed.

```
CC	libavdevice/fbdev_dec.o
libavdevice/avdevice.c:88:26: warning: 'av_oformat_next' is deprecated [-Wdeprecated-declarations]
            if (!(prev = av_oformat_next(prev)))
                         ^
./libavformat/avformat.h:2087:1: note: 'av_oformat_next' has been explicitly marked deprecated here
attribute_deprecated
^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
libavdevice/avdevice.c:92:26: warning: 'av_iformat_next' is deprecated [-Wdeprecated-declarations]
            if (!(prev = av_iformat_next(prev)))
                         ^
./libavformat/avformat.h:2079:1: note: 'av_iformat_next' has been explicitly marked deprecated here
attribute_deprecated
^
./libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
CC	libavdevice/fbdev_enc.o
CC	libavdevice/lavfi.o
CC	libavdevice/reverse.o
2 warnings generated.
CC	libavdevice/timefilter.o
CC	libavdevice/utils.o
CC	libavdevice/v4l2-common.o
CC	libavdevice/v4l2.o
CC	libavdevice/v4l2enc.o
libavdevice/v4l2.c:135:9: error: assigning to 'int (*)(int, unsigned long, ...)' from incompatible type '<overloaded function type>'
        SET_WRAPPERS();
        ^~~~~~~~~~~~~~
libavdevice/v4l2.c:121:17: note: expanded from macro 'SET_WRAPPERS'
    s->ioctl_f  = prefix ## ioctl;      \
                ^           ~~~~~
/Users/taner/Library/Android/sdk/ndk-bundle/toolchains/mobile-ffmpeg-arm/sysroot/usr/include/bits/ioctl.h:56:5: note: candidate function has type mismatch at 2nd parameter (expected 'unsigned long' but has 'unsigned int')
int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
    ^
/Users/taner/Library/Android/sdk/ndk-bundle/toolchains/mobile-ffmpeg-arm/sysroot/usr/include/bits/ioctl.h:36:5: note: candidate function has type mismatch at 2nd parameter (expected 'unsigned long' but has 'int')
int ioctl(int __fd, int __request, ...);
    ^
CC	libavfilter/aeval.o
1 error generated.
CC	libavfilter/af_acontrast.o
make: *** [libavdevice/v4l2.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tanersener** [comment]
There exists two solutions to fix this error:

1. Disabling compilation of `libavdevice/v4l2.c` by appending the following flag to `./configure`
`--disable-indev=v4l2`

2. Adding `-DBIONIC_IOCTL_NO_SIGNEDNESS_OVERLOAD` to CFLAGS

As reported in #49, `video4linux2` does not work as expected so it will better to disable it on `dev-v3.x` by applying solution 1.

**Comment by sudovijay** [comment]
still seems to be failing for me. just ffmpeg, though external libs seems to be building perfectly fine.

**Comment by tanersener** [comment]
> still seems to be failing for me. just ffmpeg, though external libs seems to be building perfectly fine.

This fix is only applied on [dev-v3.x](https://github.com/tanersener/mobile-ffmpeg/tree/dev-v3.x) branch. Which branch do you use?

**Comment by sudovijay** [comment]
i know, did tried by changing codes manually on master branch locally, now downloading dev branch.

**Comment by sudovijay** [comment]
sadly, it fails too. even with --debug  can't produce much info. it basically fails in ./configure part.

**Comment by tanersener** [comment]
Is there an error printed in `build.log`?

**Comment by sudovijay** [comment]
okay did tried on Ubuntu system it builds fine. 👍  but on mac it has issues. lemme go through build logs

**Comment by sudovijay** [comment]
this is what im getting, did tried reinstalling gcc `arm-linux-androideabi-gcc is unable to create an executable file.`

**Comment by tanersener** [comment]
> this is what im getting, did tried reinstalling gcc `arm-linux-androideabi-gcc is unable to create an executable file.`

No, it is not the real error. Can you share `src/ffmpeg/ffbuild/config.log` log file, you can use [Ghostbin](https://ghostbin.com) if it is too big.

**Comment by sudovijay** [comment]
So after lots of tries it finally works the issues seems to be with `Android NDK` installed with `Brew`, I actually removed that one and added the one with Android Studio. And about that error it has
`llvm/prebuilt/darwin-x86_64/bin/clang: No such file or directory`

**Comment by tanersener** [comment]
I never knew there was an `Android NDK` in `Brew`. So, `android.sh` is working fine now, right?

**Comment by sudovijay** [comment]
Yes there's one used to be in `Core` now moved to `Cask` :) Anyway it seems to be working fine, the only issue i'm having is size, still trying to get it down. whats with `libiconv`? while im trying to build `Libraries: lame, x264`, it gets auto added.

**Comment by tanersener** [comment]
`lame` depends `libiconv` this is why is it auto added. You can check [External Libraries](https://github.com/tanersener/mobile-ffmpeg/wiki/External-Libraries) wiki page where all dependencies are listed.

**Comment by tanersener** [comment]
Building of `libvorbis` fails too since `gcc` is removed on `NDK r18b`. `libvorbis` build script should be updated to use `clang`.
