### ISSUE TITLE
How to use coreimage filter using mobile-ffmpeg?

### ISSUE THREAD

**Issue by sunil-zalavadiya** [tanersener/mobile-ffmpeg#480]
**Description**
I want to use coreimage filter of Ffmpeg mentioned here: https://ffmpeg.org/ffmpeg-filters.html#coreimage-1

I have tried following example given in the link:

`coreimage=filter=CIBoxBlur@default`

But its giving error like,

`No such filter: \'coreimage\'\nError initializing complex filters.\nInvalid argument\n`

Can you please let me know how to use coreimage filter using mobile-ffmpeg library?

**Comment by tanersener** [comment]
This case needs further analysis. According to `ffmpeg` documentation `CoreImage` is only supported on macOS. Because it depends on `OpenGL`. However, `mobile-ffmpeg` explicitly enables `CoreImage` while configuring `ffmpeg` and `ffmpeg` does not complain.

**Comment by tanersener** [comment]
Thanks for reporting this. Unfortunately, `CoreImage` is not supported on `iOS`. Apparently `CoreImage` video filter depends on `AppKit` and `AppKit` is not available on `iOS`/`tvOS`. That's the reason behind it.

I'm not sure why `ffmpeg` does not warn us about it during the build. Anyway, we need to update the documentation about it. Also both `ios.sh` and `tvos.sh` have to be updated.

**Comment by tanersener** [comment]
Fixed in the `development` branch.

**Comment by tanersener** [comment]
Released in `v4.4`.
