### ISSUE TITLE
Is there a VideoPlayer project based on mobile-ffmpeg?

### ISSUE THREAD

**Issue by YunlongYang** [tanersener/mobile-ffmpeg#481]
In my project, i use mobile-ffmpeg to create video,and i want to play it bythe video player based on mobile-ffmpeg (like https://github.com/appunite/AndroidFFmpeg),
but i can not find it anywhere, and i don't know how to make it. 
Thanks for attention.

**Comment by tanersener** [comment]
I'm working on an SDL based player. I plan to publish it as a `mobile-ffmpeg` package but I don't have a release date yet. It's still in `alpha` stage.

**Comment by YunlongYang** [comment]
@tanersener I found the sdl branch code, you have move out the code of create video , will you mind keep the code of create video ?

**Comment by tanersener** [comment]
Sorry, I don't follow. What's the question?

**Comment by Roen-Ro** [comment]
> There are not any video players implemented on top of `mobile-ffmpeg`, as far as I know.
> 
> I'm working on an SDL based one. I plan to publish it as a `mobile-ffmpeg` package but I don't have a release date yet. It's still in `alpha` stage.

great! looking forward to it
