### ISSUE TITLE
FFMpeg class not found when integrating AAR android library in another app

### ISSUE THREAD

**Issue by marcosvbras** [tanersener/mobile-ffmpeg#482]
**Description**
First of all, I have searched for every Android related issue in this repository and I didn't find anything even close to my problem.
My Mobile FFMpeg implementation is being done in an Android Library and distributed through an AAR with no artifact service (manually via gradle). I noticed a runtime bug:

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arthenica.mobileffmpeg.FFmpeg" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/net.someapp-b8ihOG8aQ5WoY-L3gRHD_g==/base.apk"],nativeLibraryDirectories=[/data/app/net.someapp-b8ihOG8aQ5WoY-L3gRHD_g==/lib/arm, /data/app/net.someapp-b8ihOG8aQ5WoY-L3gRHD_g==/base.apk!/lib/armeabi-v7a, /system/lib]]
```

Both the android library gradle and the application gradle have the same Splits settings:

```
splits {
      abi {
            enable true
            reset()
            universalApk false
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }

```

And proguard does not seem to be a problem:

```
-keep class com.arthenica.mobileffmpeg.Config {
    native <methods>;
    void log(int, byte[]);
    void statistics(int, float, float, long , int, double, double);
}

-keep class com.arthenica.mobileffmpeg.AbiDetect {
    native <methods>;
}

-keep class com.arthenica.mobileffmpeg.FFmpeg { *; }
```

However, when I duplicate the Mobile FFMpeg dependency to the main application (since it is already in the android library gradle), the app can finally find the FFMpeg class that was not being found before.

What can I do to solve this integration problem? I suspect that the FFMpeg is not being packed properly inside my aar file, or, the FFMpeg dependencies are not being created for each ABI. Is there any other thing to set considering that my android library is not in the same project as my main app?

**Expected behavior**
The main app being able to find the FFMpeg class

**Environment**
 - Platform: Android
 - Architecture: arm-v7a, arm64-v8a, x86, x86_64
 - Version: min-gpl:4.3.1.LTS
 - Android Studio version: 4.0
- Android Gradle Plugin: 4.0

**Comment by tanersener** [comment]
I believe that this issue is more about how resolve transitive dependencies for .aar files. I saw a few `stackoverflow` posts which recommend using `transitive = true` on older `gradle` versions. Did you try applying them?

**Comment by marcosvbras** [comment]
@tanersener Yes, in my application my android library is set as transitive:

```
implementation(name: 'myLibrary', ext: 'aar') {
        transitive = true
}
```

The Mobile FFmpeg is set as api but it does not work as 'implementation' as well:
`api 'com.arthenica:mobile-ffmpeg-min-gpl:4.3.1.LTS'`

**Comment by tanersener** [comment]
I haven't done something similar before. I really have no idea.

**Comment by alexcohn** [comment]
To have a consumer of your library, `myLibrary`, to also receive the classes and native libraries of **mobile-ffmpeg**, consider creating a Maven repository with a [**pom** file](https://maven.apache.org/pom.html) that lists the dependencies of your module. [Here](https://stackoverflow.com/a/58647791/192373) you can find an example of how to publish to Maven.

Alternatively, you can create *a fat AAR*. This was [discouraged](https://stackoverflow.com/a/20715155/192373) by a leading developer of Android, but still you can try [fataar gradle plugin](https://github.com/Mobbeel/fataar-gradle-plugin) or one of its many competitors.
