### ISSUE TITLE
choose cpu architectures so files

### ISSUE THREAD

**Issue by Hosseinyzr** [tanersener/mobile-ffmpeg#483]
Hi,
is there any way to remove shared libraries for some cpu architectures?
for example I just wanna arm v7 and x86 ... to reduce the apk file size...
how can we do this?

**Comment by alexcohn** [comment]
If you are speaking about Android, you can restrict the ABIs for **release**: 

```
android.buildTypes {
        release {
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }
        debug {
        }
    }
```
Or  you can even create separate APKs for **armv7** and **x86**:

    android.splits {
        abi {
            enable true
            reset()
            include "x86", "armeabi-v7a"
            universalApk false
        }
    }

Note that you need 64-bit libraries to publish your APK on Google Play Store.
