### ISSUE TITLE
mobile-ffmpeg threading model

### ISSUE THREAD

**Issue by bsutton** [tanersener/mobile-ffmpeg#484]
I'm trying to understand how threading works with mobile-ffmpeg.

My understanding is that in flutter the plugin thread is attached to the main gui isolate in flutter.
This implies that if a plugin thread takes a long time to process an action that the main gui isloate locks up until the plugin returns.

As such I'm concerned that if I run a long running mobile-ffmpeg codec conversion process that it will cause jank in the flutter ui.

I see from the java doc that it explicitly states that it does a 'synchronous' execution of ffmpeg.

```
 /**
     * <p>Synchronously executes FFmpeg command provided. Command is split into arguments using
     * provided delimiter character.
     */
    public static int execute(final String command, final String delimiter) {
```

Looking at the base ffmpeg library it looks like they do spool up multiple threads (although I'm uncertain if they do this on mobile) however I would guess that is simply going to speed up the entire conversion but still leave the main thread locked whilst the process runs to completion.

So the short question is; is there a way to run ffmpeg without stopping the main flutter ui thread?

**Comment by tanersener** [comment]
The API of the latest published `mobile-ffmpeg` release is synchronous. It does not define any async methods. `ffmpeg` commands are executed by the same thread that calls the `execute()` method. If a UI thread calls the `execute()` method then app will freeze until execution completes. It is developer's responsibility to decide which thread will call the `execute()` method. I provided some utility classes for asynchronous execution on Android and used them on the test applications.

`flutter_ffmpeg` provides an async API. Both platforms use other threads/thread pools to call the `execute()` method. This means that you can call `flutter_ffmpeg` s `execute()` method using a UI thread but internally plugin uses another thread to call `MobileFFmpeg` s `execute()` method. Therefore main ui thread is not affected from long running executions.

**Comment by bsutton** [comment]
OK that makes sense. 
I've found the AsyncTask logic now.
Thanks.
