### ISSUE TITLE
mobileffmpeg/MobileFFprobe.h file not found

### ISSUE THREAD

**Issue by rabelhmd** [tanersener/mobile-ffmpeg#486]
**Description**
I've installed this library using **pod 'mobile-ffmpeg-full-gpl', '~> 4.2.1'** . So far it's working fine.

**Expected behavior**
I want to import mobileffmpeg/MobileFFprobe.h file.

**Screenshots**
<img width="1274" alt="Screenshot 2020-07-03 at 10 32 54 PM" src="https://user-images.githubusercontent.com/15835743/86486514-47b7a200-bd7d-11ea-9695-5901dcb144df.png">

**Current behavior**
I'm facing problems while importing mobileffmpeg/MobileFFprobe.h header file. The error is as follows mobileffmpeg/MobileFFprobe.h file not found.

**Environment**
 - Platform: [IOS]
 - Xcode version [Version 11.1]
 - 'mobile-ffmpeg-full-gpl', '~> 4.2.1'

**Comment by tanersener** [comment]
You need to use a newer version if you want to use it, `FFprobe` support was added in `v4.3.1`.

**Comment by rabelhmd** [comment]
> You need to use a newer version if you want to use it, `ffprobe` support was added in `v4.3.1`.

Thanks. It's working now.
I tried 4.3.2 and could not able to install that particular version then. 
`ffprobe` library is being imported using `v4.3.1`.  💯
