### ISSUE TITLE
[Android] Accessing camera

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#49]
`video4Linux2` support was added in `v3.0` but `v4l2` fails to detect Android cameras. So a new solution, possibly [android_camera](https://www.ffmpeg.org/ffmpeg-devices.html#android_005fcamera) device is needed for `Android`.

**Comment by tanersener** [comment]
Camera support won't be added in short and middle term. Both `video4linux2` and `android_camera` input devices does not provide a complete solution to access capture devices.

**Comment by EitanGoldfrad** [comment]
Hi @tanersener ,

What will you recommend doing currently for camera capture with this library?

Thanks,

**Comment by tanersener** [comment]
Hi @EitanGoldfrad,

Status of `camera support` is explained in [this](https://github.com/tanersener/mobile-ffmpeg/wiki/Camera-Support) wiki page. You can capture camera on `IOS` with `avfoundation` device; but on `Android` it is not possible to access camera devices, so you can't do it right now.

Current plan is to add `android_camera` device support for `Android` on upcoming releases. Still I don't like it, since it won't work on all `Android` devices.

**Comment by tanersener** [comment]
No, as far as I know.

**Comment by EitanGoldfrad** [comment]
Thanks 👍 i'll let you know if I find a way
