### ISSUE TITLE
ffmpeg "No such file or directory" error when white space in input path

### ISSUE THREAD

**Issue by mrj976** [tanersener/mobile-ffmpeg#491]
I have "No such file or directory" error when my file path have white space.
my file path: /storage/emulated/0/My Test/20200627_130932_413.mp4

ffmpeg error:
`E/mobile-ffmpeg: /storage/emulated/0/My: No such file or directory`

Please help me
Thanks

**Comment by tanersener** [comment]
How do you access files with space character on your computer?

**Comment by alexcohn** [comment]
Try to put the name inside double or single quotes, e.g.

`'/storage/emulated/0/My Test/20200627_130932_413.mp4'`

Note that there may be `Permission denied` error for files under `'/storage/emulated/0/`.

**Comment by mrj976** [comment]
> How do you access files with space character on your computer?

I use this in android

**Comment by mrj976** [comment]
> Try to put the name inside double or single quotes, e.g.
> 
> `'/storage/emulated/0/My Test/20200627_130932_413.mp4'`
> 
> Note that there may be `Permission denied` error for files under `/storage/emulated/0/`.

Video file select from user in gallery and video path change with user

**Comment by mrj976** [comment]
Please help me

**Comment by tanersener** [comment]
> I use this in android

I can see you're using android. I'm trying to tell you that accessing a file containing space character(s) on Android is similar to accessing a file containing space character(s) on your computer. You need put single or double quotes around the file path. Did you try doing that?

**Comment by mrj976** [comment]
No. Please explain with an example. Thanks

**Comment by mrj976** [comment]
> > I use this in android
> 
> I can see you're using android. I'm trying to tell you that accessing a file containing space character(s) on Android is similar to accessing a file containing space character(s) on your computer. You need put single or double quotes around the file path. Did you try doing that?

No. Please explain with an example. Thanks

**Comment by tanersener** [comment]
Alex already gave you an example. Did you see it?

Instead of
`/storage/emulated/0/My Test/20200627_130932_413.mp4`
use 
`'/storage/emulated/0/My Test/20200627_130932_413.mp4'`
or
`"/storage/emulated/0/My Test/20200627_130932_413.mp4"`

**Comment by mrj976** [comment]
> Alex already gave you an example. Did you see it?
> 
> Instead of
> `/storage/emulated/0/My Test/20200627_130932_413.mp4`
> use
> `'/storage/emulated/0/My Test/20200627_130932_413.mp4'`
> or
> `"/storage/emulated/0/My Test/20200627_130932_413.mp4"`

Thanks
