### ISSUE TITLE
Missing format_long_name in ffprobe

### ISSUE THREAD

**Issue by nlgtuankiet** [tanersener/mobile-ffmpeg#498]
**Description**
Missing long name in ffprobe format.
If you print the json format in ffprobe desktop, it will give you the `format_long_name`, but this is missing in mobile-ffmpeg build.
Command:
```
ffprobe -hide_banner -print_format json -show_format -show_streams a.mp4
```
```
{
    "streams": [
     // bla bla
    ],
    "format": {
        "filename": "a.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "2.822000",
        "size": "4751113",
        "bit_rate": "13468782",
        "probe_score": 100,
        "tags": {
            "major_brand": "mp42",
            "minor_version": "0",
            "compatible_brands": "isommp42",
            "creation_time": "2020-07-24T10:18:46.000000Z",
            "com.android.version": "8.1.0"
        }
    }
}

```
 

**Expected behavior**
`format` object has `format_long_name` field

**Current behavior**
the `format_long_name` field is missing

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: Android
 - Architecture: all 
 - Version: latest
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by alexcohn** [comment]
Counterintuitively, you can enable long format names and some other features by specifying `**--speed**` for the build script (`android.sh`, `ios.sh`, or `tvos.sh`). This will turn off the default optimization for size, and turn on the optimization for speed. I cannot say how significant the effect on binary sizes (or speed) will be, but if you need this info, it's just there for you.

**Comment by nlgtuankiet** [comment]
thank man, I will check that out!
