### ISSUE TITLE
How to add gif/image on video and text together?

### ISSUE THREAD

**Issue by rocky8roy** [tanersener/mobile-ffmpeg#505]
**Description**
i am trying to add gif and text on video using ffmpeg somewhat similar to tiktok.

**Expected behavior**
want it to be like tiktok ie on top right gif and text and after sometime left bottom same gif and text on the video.

**Current behavior**
i am able to achieve gif on the video but how to add both text and gif 

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. Android/IOS] android 
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64] NA
 - Version (if applicable) [e.g. v1.2] ffmpeg full 4.3.1LTS
 - Source branch (if applicable) [e.g. master, dev-v2.x] master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1] NA
 - Cocoapods version (if applicable) [e.g. 1.2.1] NA
 - Android Studio version (if applicable) [e.g. 3.1] 4
 - Android NDK version (if applicable) [e.g. 16b, 17c] NA

**Other**
I want similar to tiktok video watermark thing 
Kindly provide for both:
1) gif and text on video:  for sometime on right top and after that for sometime on bottom left
2) png and text on video: for sometime on right top and after that for sometime on bottom left

**Comment by dummy-amit** [comment]
Looks for answers on Stackoverflow, this is not a mobile-ffmpeg library issue.
