### ISSUE TITLE
Mobile-ffmpeg-audio is 4.4, but Libamr_WB still doesn't work

### ISSUE THREAD

**Issue by zhangruiyu** [tanersener/mobile-ffmpeg#507]
Mobile-ffmpeg-audio is 4.4, but Libamr_WB still doesn't work
![image](https://user-images.githubusercontent.com/10591822/88999156-4cdd2200-d326-11ea-919a-a01bf87a22dd.png)
![image](https://user-images.githubusercontent.com/10591822/88999159-4ea6e580-d326-11ea-80d2-e33a8d8e18f4.png)

**Comment by tanersener** [comment]
You're using the wrong library. Test applications include a working example of `amr-wb` encoding. Can you please take a look at [this](https://github.com/tanersener/mobile-ffmpeg/blob/master/ios/test-app/pods-with-tooltips/MobileFFmpegTest/AudioViewController.m#L318) line? It is from `pods-with-tooltips` test application?
