### ISSUE TITLE
OnLoad thread failed to GetStaticMethodID

### ISSUE THREAD

**Issue by anupdey99** [tanersener/mobile-ffmpeg#508]
I am getting this error when app crashed.

JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static method "Lcom/arthenica/mobileffmpeg/Config;.log(JI[B)V"

Proguard rules
-keep class com.arthenica.mobileffmpeg.Config {
    native <methods>;
    void log(int, byte[]);
    void statistics(int, float, float, long , int, double, double);
}

-keep class com.arthenica.mobileffmpeg.AbiDetect {
    native <methods>;
}

Android Studio 4.0.1
Gradle gradle-6.1.1-all gradle:4.0.1
minSdkVersion 21
targetSdkVersion 29

implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS'

**Comment by anupdey99** [comment]
Issue fixed. Proguard rules was the problem
New rules

-keep class com.arthenica.mobileffmpeg.Config {
     native <methods>;
     void log(long, int, byte[]);
     void statistics(long, int, float, float, long , int, double, double);
 }

 -keep class com.arthenica.mobileffmpeg.AbiDetect {
     native <methods>;
 }

Please update the Wiki page.

**Comment by tanersener** [comment]
Thanks for reporting this issue. We may need to patch Android packages because of that.

**Comment by tanersener** [comment]
Fixed in the `development` branch. `v4.4` and `v4.4.LTS` packages are patched and re-published too.
