### ISSUE TITLE
Other language in ffmpeg drawtext not supported

### ISSUE THREAD

**Issue by mrj976** [tanersener/mobile-ffmpeg#510]
In ffmpeg drawtext not supported to use persian or farsi language.
Like this:
String text = "دعوای گربه و طوطی";

 String s = "-i " + input_video.getAbsolutePath() +  " -vf drawtext=text='" + text + "':fontfile=" + file_font1.getAbsolutePath() + ":fontcolor=white:fontsize=38:x=(w-text_w)/2:y=h-th-70 -c:a copy -movflags +faststart  -preset ultrafast " + output_video.getAbsolutePath();

Please help me
Thanks

**Comment by tanersener** [comment]
As far as I know `harbuzz` is needed for that. I tried to compile it but unfortunately I couldn't fix the build errors. There is a circular dependency between `harfbuzz` and `freetype`/`fontconfig` which is very hard to eliminate.  [This gist](https://gist.github.com/tanersener/c9237feb387319a9eb18cd8a5b51e0b0) includes the latest version of the build script I used.

**Comment by mrj976** [comment]
I found the  answer.
Use this code:

`String s = "-i " + input_caption.getAbsolutePath() +  " -vf drawtext=text_shaping=1:text='" + text + "':fontfile=" + file_font1.getAbsolutePath() + ":fontcolor=white:fontsize=38:x=(w-text_w)/2:y=h-th-70 -c:a copy -movflags +faststart  -preset ultrafast " + output_video.getAbsolutePath();`
