### ISSUE TITLE
Question: If i do executeAsync on Android, how would i go about getting the command output?

### ISSUE THREAD

**Issue by emongev** [tanersener/mobile-ffmpeg#513]
I had created async tasks using the old .utils.AsyncExecuteTask and those had the return code and the command output, however on the newer version theres only executionId and the return code, but my old code was tied to getting the command output. How would I go about on getting the command output from the last executeAsync task?

**Comment by tanersener** [comment]
`AsyncExecuteTask` utility class used on older versions was using `FFmpeg.getLastCommandOutput()` to get the output before calling the `ExecuteCallback`. See [this line](https://github.com/tanersener/mobile-ffmpeg/blob/v4.3/android/app/src/main/java/com/arthenica/mobileffmpeg/util/AsyncExecuteTask.java#L42). You can do the same and call `FFmpeg.getLastCommandOutput()` yourself to get the output.

If you are executing multiple commands at the same time using the `LogCallback` is a better approach. It will give you the execution id as well. So you can understand which log line belongs to which execution.

**Comment by emongev** [comment]
Oh my bad i was doing the wrong thing, i was actually executing a command on the Java side of things which had no output. I can mention that i did use Config.getLastCommandOutput() instead, dunno if theres a difference :)
