### ISSUE TITLE
mac build android error

### ISSUE THREAD

**Issue by chongbo2013** [tanersener/mobile-ffmpeg#514]
![image](https://user-images.githubusercontent.com/3191545/89270988-afa82380-d66e-11ea-8b58-bf88224628a3.png)
pls help me

**Comment by tanersener** [comment]
See https://github.com/tanersener/mobile-ffmpeg/wiki/Building and https://github.com/tanersener/mobile-ffmpeg/wiki/Logs sections.

**Comment by chongbo2013** [comment]
INFO: Using Android NDK v21.3.6528147 provided at /Users/mx/Library/Android/sdk/ndk/21.3.6528147

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 15时55分06秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 15时55分06秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features directory not found

INFO: Flags detected for cpu-features: already installed=1, rebuild=, dependency rebuilt=

----------------------------------------------------------------

INFO: Building cpu-features with the following environment variables

TERM_PROGRAM=Apple_Terminal
rvm_bin_path=/Users/mx/.rvm/bin
MOBILE_FFMPEG_TMPDIR=/Users/mx/ffmpeg/mobile-ffmpeg/.tmp
ANDROID_HOME=/Users/mx/Library/Android/sdk
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/8v/ghyrc71s4hsgc8gsxst09hz00000gn/T/
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=65E351E3-07A5-4432-BFC9-E9BE437CD44B
USER=mx
ANDROID_NDK_ROOT=/Users/mx/Library/Android/sdk/ndk/21.3.6528147
rvm_path=/Users/mx/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nUaiqAFFhS/Listeners
PUB_HOSTED_URL=https://pub.flutter-io.cn
rvm_prefix=/Users/mx
PATH=/Users/mx/development/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mx/.rvm/bin
ORIGINAL_API=24
PWD=/Users/mx/ffmpeg/mobile-ffmpeg
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
LANG=zh_CN.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
rvm_version=1.29.9 (latest)
TOOLCHAIN=darwin-x86_64
HOME=/Users/mx
SHLVL=2
TOOLCHAIN_ARCH=arm
API=24
LOGNAME=mx
ARCH=arm-v7a
BASEDIR=/Users/mx/ffmpeg/mobile-ffmpeg
_=/usr/bin/env
----------------------------------------------------------------

INFO: System information

INFO: Darwin mxdeMacBook-Pro-3.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

----------------------------------------------------------------


DEBUG: Downloading library source: cpu-features

DEBUG: Checking if cpu-features is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/cpu-features

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/src/cpu-features directory not found

Cloning into '/Users/mx/ffmpeg/mobile-ffmpeg/src/cpu-features'...
Note: switching to '60aa741cab3a7754d1652886a273b3e98604fc82'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

DEBUG: cpu-features library downloaded

-- Check for working C compiler: /Users/mx/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/mx/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mx/ffmpeg/mobile-ffmpeg/android/build/cpu-features/arm
Scanning dependencies of target unix_based_hardware_detection
[  8%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[ 16%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/unix_features_aggregator.c.o
[ 16%] Built target unix_based_hardware_detection
Scanning dependencies of target utils
[ 25%] Building C object CMakeFiles/utils.dir/src/filesystem.c.o
[ 33%] Building C object CMakeFiles/utils.dir/src/stack_line_reader.c.o
[ 41%] Building C object CMakeFiles/utils.dir/src/string_view.c.o
[ 41%] Built target utils
Scanning dependencies of target cpu_features
[ 50%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o
[ 58%] Linking C static library libcpu_features.a
[ 58%] Built target cpu_features
Scanning dependencies of target list_cpu_features
[ 66%] Building C object CMakeFiles/list_cpu_features.dir/src/utils/list_cpu_features.c.o
[ 75%] Linking C executable list_cpu_features
[ 75%] Built target list_cpu_features
Scanning dependencies of target ndk_compat
[ 83%] Building C object ndk_compat/CMakeFiles/ndk_compat.dir/cpu-features.c.o
[ 91%] Building C object ndk_compat/CMakeFiles/ndk_compat.dir/__/src/cpuinfo_arm.c.o
[100%] Linking C static library libndk_compat.a
[100%] Built target ndk_compat
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/libcpu_features.a
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/include/cpu_features/cpu_features_macros.h
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/include/cpu_features/cpu_features_cache_info.h
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/include/cpu_features/cpuinfo_arm.h
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/bin/list_cpu_features
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeatures/CpuFeaturesTargets.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeatures/CpuFeaturesTargets-release.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeatures/CpuFeaturesConfig.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeatures/CpuFeaturesConfigVersion.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/libndk_compat.a
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/include/ndk_compat/cpu-features.h
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeaturesNdkCompat/CpuFeaturesNdkCompatTargets.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeaturesNdkCompat/CpuFeaturesNdkCompatTargets-release.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeaturesNdkCompat/CpuFeaturesNdkCompatConfig.cmake
-- Installing: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features/lib/cmake/CpuFeaturesNdkCompat/CpuFeaturesNdkCompatConfigVersion.cmake

INFO: Using Android NDK v21.3.6528147 provided at /Users/mx/Library/Android/sdk/ndk/21.3.6528147

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 15时55分53秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 15时55分53秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=


INFO: Using Android NDK v21.3.6528147 provided at /Users/mx/Library/Android/sdk/ndk/21.3.6528147

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时06分50秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时06分50秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=


INFO: Using Android NDK v21.3.6528147 provided at /Users/mx/Library/Android/sdk/ndk/21.3.6528147

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时10分47秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时10分47秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg directory not found

Cloning into '/Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg'...
fatal: unable to access 'https://github.com/tanersener/FFmpeg/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

DEBUG: Failed to clone https://github.com/tanersener/FFmpeg

INFO: Downloading library ffmpeg failed. Can not get library from https://github.com/tanersener/FFmpeg


INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时16分12秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时16分12秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg directory not found

Cloning into '/Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg'...

[KUpdating files:  46% (3444/7339)

[KUpdating files:  47% (3450/7339)

[KUpdating files:  48% (3523/7339)

[KUpdating files:  49% (3597/7339)

[KUpdating files:  50% (3670/7339)

[KUpdating files:  51% (3743/7339)

[KUpdating files:  52% (3817/7339)

[KUpdating files:  53% (3890/7339)

[KUpdating files:  54% (3964/7339)

[KUpdating files:  55% (4037/7339)

[KUpdating files:  56% (4110/7339)

[KUpdating files:  57% (4184/7339)

[KUpdating files:  58% (4257/7339)

[KUpdating files:  59% (4331/7339)

[KUpdating files:  60% (4404/7339)

[KUpdating files:  61% (4477/7339)

[KUpdating files:  62% (4551/7339)

[KUpdating files:  63% (4624/7339)

[KUpdating files:  64% (4697/7339)

[KUpdating files:  65% (4771/7339)

[KUpdating files:  66% (4844/7339)

[KUpdating files:  67% (4918/7339)

[KUpdating files:  68% (4991/7339)

[KUpdating files:  69% (5064/7339)

[KUpdating files:  70% (5138/7339)

[KUpdating files:  71% (5211/7339)

[KUpdating files:  72% (5285/7339)

[KUpdating files:  73% (5358/7339)

[KUpdating files:  74% (5431/7339)

[KUpdating files:  75% (5505/7339)

[KUpdating files:  76% (5578/7339)

[KUpdating files:  77% (5652/7339)

[KUpdating files:  78% (5725/7339)

[KUpdating files:  79% (5798/7339)

[KUpdating files:  80% (5872/7339)

[KUpdating files:  81% (5945/7339)

[KUpdating files:  82% (6018/7339)

[KUpdating files:  83% (6092/7339)

[KUpdating files:  84% (6165/7339)

[KUpdating files:  85% (6239/7339)

[KUpdating files:  86% (6312/7339)

[KUpdating files:  87% (6385/7339)

[KUpdating files:  88% (6459/7339)

[KUpdating files:  89% (6532/7339)

[KUpdating files:  90% (6606/7339)

[KUpdating files:  91% (6679/7339)

[KUpdating files:  92% (6752/7339)

[KUpdating files:  93% (6826/7339)

[KUpdating files:  94% (6899/7339)

[KUpdating files:  95% (6973/7339)

[KUpdating files:  96% (7046/7339)

[KUpdating files:  97% (7119/7339)

[KUpdating files:  98% (7193/7339)

[KUpdating files:  99% (7266/7339)

[KUpdating files: 100% (7339/7339)

[KUpdating files: 100% (7339/7339), done.
From https://github.com/tanersener/FFmpeg
 * branch            d222da435e63a2665b85c0305ad2cf8a07b1af6d -> FETCH_HEAD
Note: switching to 'd222da435e63a2665b85c0305ad2cf8a07b1af6d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d222da4 set user friendly version v4.4-dev-416
DEBUG: ffmpeg library downloaded

INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi24-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时17分08秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时17分08秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: ffmpeg library already downloaded

INFO: ffmpeg already downloaded. Source folder found at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi24-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时17分14秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时17分14秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: ffmpeg library already downloaded

INFO: ffmpeg already downloaded. Source folder found at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi24-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: -l --full --enable-x264

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 LTS library for Android: 2020年 8月 4日 星期二 16时21分07秒 CST

(*) Invalid configuration detected. GPL library x264 enabled without --enable-gpl flag.


INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时21分23秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时21分23秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: ffmpeg library already downloaded

INFO: ffmpeg already downloaded. Source folder found at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi24-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: --full

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时21分49秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时21分49秒 CST

INFO: Enabled library fontconfig

INFO: Enabled library freetype

INFO: Enabled library fribidi

INFO: Enabled library gmp

INFO: Enabled library gnutls

INFO: Enabled library lame

INFO: Enabled library libass

INFO: Enabled library libiconv

INFO: Enabled library libtheora

INFO: Enabled library libvorbis

INFO: Enabled library libvpx

INFO: Enabled library libwebp

INFO: Enabled library libxml2

INFO: Enabled library opencore-amr

INFO: Enabled library shine

INFO: Enabled library speex

INFO: Enabled library wavpack

INFO: Enabled library kvazaar

INFO: Enabled library libilbc

INFO: Enabled library opus

INFO: Enabled library snappy

INFO: Enabled library soxr

INFO: Enabled library libaom

INFO: Enabled library chromaprint

INFO: Enabled library twolame

INFO: Enabled library sdl

INFO: Enabled library tesseract

INFO: Enabled library openh264

INFO: Enabled library vo-amrwbenc

INFO: Enabled library giflib

INFO: Enabled library jpeg

INFO: Enabled library libogg

INFO: Enabled library libpng

INFO: Enabled library libuuid

INFO: Enabled library nettle

INFO: Enabled library tiff

INFO: Enabled library expat

INFO: Enabled library libsndfile

INFO: Enabled library leptonica

INFO: Enabled library cpu-features

INFO: Skipping fontconfig, run=0, completed=

INFO: Skipping freetype, run=0, completed=

DEBUG: Checking if fribidi is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/fribidi

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/fribidi directory not found

INFO: Flags detected for fribidi: already installed=1, rebuild=, dependency rebuilt=

----------------------------------------------------------------

INFO: Building fribidi with the following environment variables

TERM_PROGRAM=Apple_Terminal
rvm_bin_path=/Users/mx/.rvm/bin
MOBILE_FFMPEG_TMPDIR=/Users/mx/ffmpeg/mobile-ffmpeg/.tmp
ANDROID_HOME=/Users/mx/Library/Android/sdk
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/8v/ghyrc71s4hsgc8gsxst09hz00000gn/T/
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=65E351E3-07A5-4432-BFC9-E9BE437CD44B
USER=mx
ANDROID_NDK_ROOT=/Users/mx/ffmpeg/android-ndk-r17c
rvm_path=/Users/mx/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nUaiqAFFhS/Listeners
PUB_HOSTED_URL=https://pub.flutter-io.cn
rvm_prefix=/Users/mx
PATH=/Users/mx/development/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mx/.rvm/bin
ORIGINAL_API=24
PWD=/Users/mx/ffmpeg/mobile-ffmpeg
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
LANG=zh_CN.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
rvm_version=1.29.9 (latest)
TOOLCHAIN=darwin-x86_64
HOME=/Users/mx
SHLVL=2
TOOLCHAIN_ARCH=arm
API=24
LOGNAME=mx
ARCH=arm-v7a
BASEDIR=/Users/mx/ffmpeg/mobile-ffmpeg
_=/usr/bin/env
----------------------------------------------------------------

INFO: System information

INFO: Darwin mxdeMacBook-Pro-3.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

----------------------------------------------------------------

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for arm-linux-androideabi-gcc... armv7a-linux-androideabi24-clang
checking whether the C compiler works... no
configure: error: in `/Users/mx/ffmpeg/mobile-ffmpeg/src/fribidi':
configure: error: C compiler cannot create executables
See `config.log' for more details

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: -full


INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: --full

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时23分10秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时23分10秒 CST

INFO: Enabled library fontconfig

INFO: Enabled library freetype

INFO: Enabled library fribidi

INFO: Enabled library gmp

INFO: Enabled library gnutls

INFO: Enabled library lame

INFO: Enabled library libass

INFO: Enabled library libiconv

INFO: Enabled library libtheora

INFO: Enabled library libvorbis

INFO: Enabled library libvpx

INFO: Enabled library libwebp

INFO: Enabled library libxml2

INFO: Enabled library opencore-amr

INFO: Enabled library shine

INFO: Enabled library speex

INFO: Enabled library wavpack

INFO: Enabled library kvazaar

INFO: Enabled library libilbc

INFO: Enabled library opus

INFO: Enabled library snappy

INFO: Enabled library soxr

INFO: Enabled library libaom

INFO: Enabled library chromaprint

INFO: Enabled library twolame

INFO: Enabled library sdl

INFO: Enabled library tesseract

INFO: Enabled library openh264

INFO: Enabled library vo-amrwbenc

INFO: Enabled library giflib

INFO: Enabled library jpeg

INFO: Enabled library libogg

INFO: Enabled library libpng

INFO: Enabled library libuuid

INFO: Enabled library nettle

INFO: Enabled library tiff

INFO: Enabled library expat

INFO: Enabled library libsndfile

INFO: Enabled library leptonica

INFO: Enabled library cpu-features

INFO: Skipping fontconfig, run=0, completed=

INFO: Skipping freetype, run=0, completed=

DEBUG: Checking if fribidi is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/fribidi

DEBUG: /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/fribidi directory not found

INFO: Flags detected for fribidi: already installed=1, rebuild=, dependency rebuilt=

----------------------------------------------------------------

INFO: Building fribidi with the following environment variables

TERM_PROGRAM=Apple_Terminal
rvm_bin_path=/Users/mx/.rvm/bin
MOBILE_FFMPEG_TMPDIR=/Users/mx/ffmpeg/mobile-ffmpeg/.tmp
ANDROID_HOME=/Users/mx/Library/Android/sdk
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/8v/ghyrc71s4hsgc8gsxst09hz00000gn/T/
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=65E351E3-07A5-4432-BFC9-E9BE437CD44B
USER=mx
ANDROID_NDK_ROOT=/Users/mx/ffmpeg/android-ndk-r17c
rvm_path=/Users/mx/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nUaiqAFFhS/Listeners
PUB_HOSTED_URL=https://pub.flutter-io.cn
rvm_prefix=/Users/mx
PATH=/Users/mx/development/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mx/.rvm/bin
ORIGINAL_API=24
PWD=/Users/mx/ffmpeg/mobile-ffmpeg
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
LANG=zh_CN.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
rvm_version=1.29.9 (latest)
TOOLCHAIN=darwin-x86_64
HOME=/Users/mx
SHLVL=2
TOOLCHAIN_ARCH=arm
API=24
LOGNAME=mx
ARCH=arm-v7a
BASEDIR=/Users/mx/ffmpeg/mobile-ffmpeg
_=/usr/bin/env
----------------------------------------------------------------

INFO: System information

INFO: Darwin mxdeMacBook-Pro-3.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

----------------------------------------------------------------

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for arm-linux-androideabi-gcc... armv7a-linux-androideabi24-clang
checking whether the C compiler works... no
configure: error: in `/Users/mx/ffmpeg/mobile-ffmpeg/src/fribidi':
configure: error: C compiler cannot create executables
See `config.log' for more details

INFO: Using Android NDK v17.2.4988734 provided at /Users/mx/ffmpeg/android-ndk-r17c

INFO: Build options: 

INFO: Building mobile-ffmpeg v4.3.2-26-g725aef963 library for Android: 2020年 8月 4日 星期二 16时24分01秒 CST

INFO: Starting new build for arm-v7a on API level 24 at 2020年 8月 4日 星期二 16时24分01秒 CST

INFO: Enabled library cpu-features

DEBUG: Checking if cpu-features is already built and installed at /Users/mx/ffmpeg/mobile-ffmpeg/prebuilt/android-arm/cpu-features

INFO: cpu-features library is already built and installed

INFO: Flags detected for cpu-features: already installed=0, rebuild=, dependency rebuilt=

INFO: Enabling library cpu-features

DEBUG: Downloading library source: ffmpeg

DEBUG: Checking if ffmpeg is already downloaded at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: ffmpeg library already downloaded

INFO: ffmpeg already downloaded. Source folder found at /Users/mx/ffmpeg/mobile-ffmpeg/src/ffmpeg

INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi24-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by chongbo2013** [comment]
Do you have any requirements for the ndk sdk version? thank u

**Comment by tanersener** [comment]
Everything is written in the README and wiki pages. Why don't you try to find the answers there?

**Comment by chongbo2013** [comment]
thank u is ok.
