### ISSUE TITLE
Hardware encoder

### ISSUE THREAD

**Issue by jim-king-2000** [tanersener/mobile-ffmpeg#515]
There is only a hardware decoder - "h264_mediacodec" in the library. Is it possible to add a hardware encoder?

**Comment by tanersener** [comment]
This is the list that `ffmpeg` supports, [HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro). I don't see any other hardware encoders that can enabled.

**Comment by jim-king-2000** [comment]
1. Can we use "HWAccelIntro" on Android?
1. According to the search result, MediaCodec can be used as an encoder for Android hardware acceleration. Will mobile-ffmpeg enable it as an encoder?

**Comment by tanersener** [comment]
If someone implements it I'll be happy to include it in this project. But, personally I have no plans for this in the near future.

**Comment by jim-king-2000** [comment]
OK. Thanks.

**Comment by mafanwei** [comment]
It is OK?
https://github.com/ElegantWang/ffmpeg_mediacodec_encoder

**Comment by tanersener** [comment]
@mafanwei I don't know, is it? I can't see whether that implementation is stable or not. It doesn't have a documentation.

**Comment by mafanwei** [comment]
I tried it and this works on my phone, but I don't know if he works on all Android devices.

The idea of his code is as follows:
1.Receive AVFrame and convert it to MediaCodec processable frame data
2.Provide data to the MediaCodec
3.Receive the result of MediaCodec processing and convert it to AVPacket

Compile:
1.merge it in your code.
2.complie:
```
./android.sh --disable-arm-v7a --disable-arm64-v8a --disable-x86 --disable-x86-64 --enable-gpl --full --enable-android-media-codec

```

TestCode:
```
-c:v h264_mediacodec -i http://112.50.243.8/PLTV/88888888/224/3221225827/1.m3u8 -max_muxing_queue_size 8888 -c:v hevc_mediacodec_enc -c:a copy -b 2m -f mpegts udp://192.168.10.107:12345
```

**Comment by tanersener** [comment]
I found the same instructions here https://blog.csdn.net/wychmiss/article/details/107147747. The page says that this implementation is created for learning purposes and it uses hardcoded parameters to make it work on the test device used. It doesn't seem like an implementation that we can rely on.

**Comment by tanersener** [comment]
By the way, this discussion on `ffmpeg` mailing list (http://lists.ffmpeg.org/pipermail/ffmpeg-devel/2020-March/259374.html) shows that some ffmpeg developers are already working on MediaCodec encoder.
