### ISSUE TITLE
 Building ffmpeg keeps failing on latest master branch

### ISSUE THREAD

**Issue by dummy-amit** [tanersener/mobile-ffmpeg#516]
**Description**
Building ffmpeg keeps failing on latest master branch

**Expected behavior**
Expected to get android.aar and ffmpeg binaries

**Current behavior**
Build is failing with this log
`INFO: Cleaning workspace for ffmpeg
sed: can't read /home/amit/work/mobile-ffmpeg/src/ffmpeg/libavutil/log.c: No such file or directory
/home/amit/work/mobile-ffmpeg/build/android-ffmpeg.sh: line 360: ./configure: No such file or directory
`

**Logs**
https://ghostbin.co/paste/2kk6h

**Environment**
 - Platform: Android
 - Architecture: All
 - Version (if applicable) 4.4LTS
 - Source branch (if applicable) master
 - Android NDK version (if applicable) 21.3.6528147

**Other**
Build works fine if I go couple commits back i.e. 8bc316508345d0285f95baec5fc4b9d860fa1b40
But fails on latest commit on master

**Comment by tanersener** [comment]
I can't reach `ghostbin.co` and see your logs. But as far as I know, some linux distributions which use curl and gnutls based `git` clients can't clone the `master`. They fail with the following error.

```
Cloning into 'mobile-ffmpeg-master'...
remote: Enumerating objects: 30317, done.
remote: Counting objects: 100% (30317/30317), done.
remote: Compressing objects: 100% (23151/23151), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

The meaning of this message is: repository is too big and some git clients don't work well with big repos. So, I'm not sure if we can fix this easily. Tried various git configuration settings but couldn't find a working one.

As a workaround, you can:
 - Download the source code (as a zip or tar.gz file) from [release v4.4](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.4)
- Download `master.git.tar.gz` from [release v4.4](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.4)
- Unpack the `source` and `master.git.tar.gz` into the same folder. `master.git.tar.gz` includes the `git` folder of the repository
- After that you can run top level build scripts

**Comment by tanersener** [comment]
This is one of the issues we're facing because `MobileFFmpeg` repository became too big. We don't have an easy solution for this. I suggest switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit) if you get this error.
