### ISSUE TITLE
It's consuming CPU even when there's no active task.

### ISSUE THREAD

**Issue by 402m** [tanersener/mobile-ffmpeg#520]
**Description**
Right after I use `Config.setLogLevel`, my app keeps a ~ 10% CPU usage even though I haven't start any command.

**Expected behavior**
There should be ~ 0% CPU usage when idle. 

**Current behavior**
The CPU stays ~10% on my Nexus 6P & Pixel 4 devices.

**Logs**
```
08-10 18:18:49.652 26071 26162 I mobile-ffmpeg: Loading mobile-ffmpeg.
08-10 18:18:49.813 26071 26162 I mobile-ffmpeg: Loaded mobile-ffmpeg-min-gpl-arm64-v8a-4.3.2-20200415.
08-10 18:18:49.815 26071 26211 D mobile-ffmpeg: Callback thread started.
```

**Environment**
 - Platform: Android
 - Architecture: arm64-v8a
 - Version: 4.3.2
 - Android Studio version: IDEA 2020.1.1

**Comment by tanersener** [comment]
Thanks for reporting this issue. Something was not right about `monitorWait` function on `Android`. Fixed it on the `development` branch. It is around % 1 after the fix.

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit). This bug is fixed there.
