### ISSUE TITLE
Unknown encoder 'libx265' - Android Test App

### ISSUE THREAD

**Issue by deepattwoiq** [tanersener/mobile-ffmpeg#523]
### **Description**
I tried running test android app on my nokia 3.1 Android 10 Device. My goal is to compress Video with HEVC H,265.

**Expected behavior**
It should encode video to provided options

**Current behavior**
But it only works for mpeg4 not for x264 or x265. It says Encode failed. Please check logs for detail.

**Logs**
attaching debuglog from android studio
https://ghostbin.co/paste/s2f3d 

**Environment**
 - Platform: Android
 - Architecture: CPU ARM Cortex-A53
 - Android Studio version: 4.0.1

**Comment by tanersener** [comment]
Try to install one of the `GPL` licensed `mobile-ffmpeg` packages.

**Comment by deepattwoiq** [comment]
Thank you very much for prompt reply.

Could you please tell me which are  GPL licensed packages? 
And what will be the procedure to add them into my project. Or any document reference where I can get that information.

Thanks in advance.

**Comment by tanersener** [comment]
Please read the README. [2.1 Packages](https://github.com/tanersener/mobile-ffmpeg#21-packages) sections lists all the packages and [2.2 Android](https://github.com/tanersener/mobile-ffmpeg#22-android) section explains how a package can be installed.

**Comment by deepattwoiq** [comment]
Yes Its done.
Now it sounds naive question but I am glad I asked.
Thanks a lot.

For future reference It requires Minimum SDK Version 24 - Android-7

**Comment by tanersener** [comment]
You have two options there. See [4. LTS Releases](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases)

**Comment by ideepdave** [comment]
That seems the exact thing I wanted. Thanks @tanersener 
Now Only thing I wish for is to reduce apk size !!

**Comment by deepattwoiq** [comment]
That seems the exact thing I wanted. Thanks @tanersener
Now Only thing I wish for is to reduce apk size !!
