### ISSUE TITLE
How should I add files from raw or assets to ffmpeg command?

### ISSUE THREAD

**Issue by raghavtilak** [tanersener/mobile-ffmpeg#533]
I am trying to add gif overlay on video, but don't know how should I add the path of the gif which is stored either in raw or asset folder to the ffmpeg command.
I tried `file:///android_asset/indi.gif` in command but its isn't working.

**Comment by msabo1** [comment]
Take a look at rawResourceToFile method in this file https://github.com/tanersener/mobile-ffmpeg/blob/master/android/test-app/src/main/java/com/arthenica/mobileffmpeg/util/ResourcesUtil.java . You should implement something like that and than you can concatenate file.toString() to your ffmpeg command.
