### ISSUE TITLE
How can I insert a keyframe?

### ISSUE THREAD

**Issue by guoyi427** [tanersener/mobile-ffmpeg#538]
I can't insert keyframe in video when I use "-c:v libx264 -x264opts keyint=30"
and it log:
ERROR: Unable to find a suitable output format for 'keyint=30'
ERROR: keyint=30: Invalid argument

**Comment by alexcohn** [comment]
You are missing quotes: 

    "-c:v libx264 -x264opts \"keyint=30\""
