### ISSUE TITLE
[ANDROID] Need help for android app slideshow transitions

### ISSUE THREAD

**Issue by bilalilyas90** [tanersener/mobile-ffmpeg#54]
Hi
I now see your android version and thank you for this.
I need help regarding slideshow app in android and want to create mp4 files using images and transitions as you created in scripts . Please can you provide a working example of same previous scripts for android app?
Thank you in advance

**Comment by tanersener** [comment]
Test applications included in this project implement `Fade In` transition under `VIDEO` tab. You can browse the source code under `android/test-app` folder in implement other transitions as well.
