### ISSUE TITLE
WSL 2.0 Ubuntu build for Android fails with: checking whether the C compiler works... no

### ISSUE THREAD

**Issue by s7aycool** [tanersener/mobile-ffmpeg#540]
**Description**
I tried to build mobile-ffmeg with next command
`./android.sh --enable-lame --enable-libtheora --enable-libvorbis --enable-x264 --enable-libvpx --enable-opus --enable-gpl --disable-arm-v7a-neon`

**Expected behavior**
Expected .so libs as output

**Current behavior**
Build fails with next logs:

**Logs**
https://ghostbin.co/paste/ck69x

**Environment**
 - Platform: [Android]
 - Architecture: [arm-v7a, arm64-v8a, x86, x86_64]
 - Source branch (if applicable) [master]
 - Android NDK version (if applicable) [17c]

**Other**
Also I donwloaded SDK 21 through Android Studio-> Sdk Manager, but your script says that it uses SDK 24:

```
Architectures: arm-v7a, arm64-v8a, x86-64
Libraries: cpu-features, lame, libiconv, libtheora, libvorbis, libvpx, x264, opus

Building arm-v7a platform on API level 24

libiconv: failed
```
Why?

**Comment by alexcohn** [comment]
I am afraid NDK r.17c is not supported with `master`.

**Comment by s7aycool** [comment]
@alexcohn my bad. I thought I have seen somewhere in wiki's that r17 is recommended. Okay, actually I need ffmpeg for API 21+, it's v4.2 LTS release. I should build ffmpeg from that commit?

**Comment by s7aycool** [comment]
Also, I have a question about libtheora. It's not building separately on my side. It can't find sys/timeb.h when built with SDK 21. How did you solved it?

**Comment by alexcohn** [comment]
I would strongly suggest the latest release ([4.4](https://github.com/tanersener/mobile-ffmpeg/tree/v4.4)). If you need API 21+ support, use `--lts` build option for **android.sh**. It gives you 16+ at no significant cost.

I don't remember specific problems with libtheora; I hope you will see it all compile if you use `--lts` build.

**Comment by s7aycool** [comment]
@alexcohn 
But I want arm64-v8a, x86-64, and I know that min API for them in x64 is SDK 21. How it works in case of --lts?

**Comment by s7aycool** [comment]
What a beautiful thing to watch. So minimalistic. So pristine. Enjoying every line, actually
![image](https://user-images.githubusercontent.com/59872947/91914223-3973fc80-ecc0-11ea-9db9-8f0d75aca5b4.png)

**Comment by s7aycool** [comment]
@alexcohn I have one more question. Some of the built libs and not in the required formet, e.g. On my side there are some-lib.so used(in-app), and in mobile-ffmpeg some-lib. A

**Comment by alexcohn** [comment]
Which Android.mk uses static libs? Not mobile-ffmpeg, as far as I know.

**Comment by s7aycool** [comment]
@alexcohn yes, it's my app's internal make file, not mobile-ffmpeg's. Sorry For confusion. I already have ffmpeg manually built in my proj. Its very old and buildable only on sdk 16, so I can't buikd x64. I am trying to swap my old ffmpeg with your fresh ffmpeg, but my jni is built with some of ffmpeg libs that are static, but in mobile-ffmpeg I see this libs are shared. And question: can I control what the output in mobile-ffmpeg will be, shared or static?

**Comment by alexcohn** [comment]
I would suggest that you simply use shared ffmpeg libs in your project. The libraries built for **mobile-ffmpeg** should not cause any problem, but keep your eye on the extras that you need or don't.

It isn't hard to tweak the **mobile-ffmpeg** script to produce static libraries, but it may be more painful to work with them.

**Comment by s7aycool** [comment]
Sorry for offtopping again, but I still would like to try to change format of the procuced output of mobile-ffmpeg.

So, I need next libs in exactly that format:

```
libtheora.a
libtheoradec.a
libtheoraenc.a
libavcodec.a
libavdevice.a
libavfilter.a
libavformat.a
libavutil.a
libpostproc.a
libswresample.a
libswscale.a
libvpx.a
libmp3lame.so
libopus.so
libogg.so
libvorbisenc.so
libvorbisfile.so
libvorbis.so
libx264.so
```

But, mobile-ffmpeg produces next ones formats:

```
libtheora.a
libtheoradec.a
libtheoraenc.a
libavcodec.so
libavdevice.so
libavfilter.so
libavformat.so
libavutil.so
libpostproc.so (need to add --enable-postproc)
libswresample.so
libswscale.so
libvpx.a
libmp3lame.a
libopus.a
libogg.a
libvorbisenc.a
libvorbisfile.a
libvorbis.a
libx264.a
```

I tried to tweak my own app to adapt to your output, but it hasn't worked out.
So, I decided to tweak mobile-ffmpeg scripts to produce different output formats, so, I have modified next scripts:

cd mobile-ffmpeg
git diff:
<script src="https://gist.github.com/s7aycool/2387e4245e1f33b29ac53958e31cdf67.js"></script>

And as output I had exact formats I needed. But, there is a problem:

Ndk says that some of .a libs and some of .so are broken. It says that libavcodec.a is not an ELF format, furthermore I can't read lib with `readelf -h libavcodec.a`:

<script src="https://gist.github.com/s7aycool/29889542b2e49609b81b4f76f031aa0d.js"></script>

Question: how can I get needed output from mobile-ffmpeg, and keep files working?

**Comment by s7aycool** [comment]
@alexcohn okay, solved by building ffmpeg in .a, and other libs in .so. It's working now. Thanks for answers!

**Comment by s7aycool** [comment]
Also, my build fails with ndk 21r with usage of --lts. Without --lts it builds ok, but min Api 24 is not what I need:

command used:
`./android.sh --enable-lame --enable-libtheora --enable-libvorbis --enable-x264 --enable-libvpx --enable-opus --enable-gpl --disable-arm-v7a-neon --lts
`
diff from your scripts: (not much diff actually, just some of libs with --enable-shared, and --enable-postproc in ffmpeg)
`diff --git a/android/app/build.gradle b/android/app/build.gradle
index bed536cc5..d96b90774 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -5,10 +5,10 @@ android {
     ndkVersion "21.3.6528147"
 
     defaultConfig {
-        minSdkVersion 24
+        minSdkVersion 16
         targetSdkVersion 29
-        versionCode 240440
-        versionName "4.4"
+        versionCode 160440
+        versionName "4.4.LTS"
         project.archivesBaseName = "mobile-ffmpeg"
         consumerProguardFiles 'proguard-rules.pro'
     }
diff --git a/build/android-ffmpeg.sh b/build/android-ffmpeg.sh
index f1d23c82b..243e467a5 100755
--- a/build/android-ffmpeg.sh
+++ b/build/android-ffmpeg.sh
@@ -374,7 +374,7 @@ ${SED_INLINE} 's/static int av_log_level/__thread int av_log_level/g' ${BASEDIR}
     --enable-jni \
     --enable-optimizations \
     --enable-swscale \
-    --enable-shared \
+    --enable-static \
     --enable-v4l2-m2m \
     --disable-outdev=fbdev \
     --disable-indev=fbdev \
@@ -384,13 +384,13 @@ ${SED_INLINE} 's/static int av_log_level/__thread int av_log_level/g' ${BASEDIR}
     ${DEBUG_OPTIONS} \
     --disable-neon-clobber-test \
     --disable-programs \
-    --disable-postproc \
+    --enable-postproc \
     --disable-doc \
     --disable-htmlpages \
     --disable-manpages \
     --disable-podpages \
     --disable-txtpages \
-    --disable-static \
+    --disable-shared \
     --disable-sndio \
     --disable-schannel \
     --disable-securetransport \
diff --git a/build/android-lame.sh b/build/android-lame.sh
index 7116c29e9..9fca517ec 100755
--- a/build/android-lame.sh
+++ b/build/android-lame.sh
@@ -48,8 +48,8 @@ fi
     --with-pic \
     --with-sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot \
     --with-libiconv-prefix=${BASEDIR}/prebuilt/android-$(get_target_build)/libiconv \
-    --enable-static \
-    --disable-shared \
+    --disable-static \
+    --enable-shared \
     --disable-fast-install \
     --disable-maintainer-mode \
     --disable-frontend \
diff --git a/build/android-libogg.sh b/build/android-libogg.sh
index b01ef21be..72e26d11c 100755
--- a/build/android-libogg.sh
+++ b/build/android-libogg.sh
@@ -46,8 +46,8 @@ fi
     --prefix=${BASEDIR}/prebuilt/android-$(get_target_build)/${LIB_NAME} \
     --with-pic \
     --with-sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot \
-    --enable-static \
-    --disable-shared \
+    --disable-static \
+    --enable-shared \
     --disable-fast-install \
     --host=${BUILD_HOST} || exit 1
 
diff --git a/build/android-libvorbis.sh b/build/android-libvorbis.sh
index e143d6aed..64f408235 100755
--- a/build/android-libvorbis.sh
+++ b/build/android-libvorbis.sh
@@ -49,8 +49,8 @@ PKG_CONFIG= ./configure \
     --with-sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot \
     --with-ogg-includes=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/include \
     --with-ogg-libraries=${BASEDIR}/prebuilt/android-$(get_target_build)/libogg/lib \
-    --enable-static \
-    --disable-shared \
+    --disable-static \
+    --enable-shared \
     --disable-fast-install \
     --disable-docs \
     --disable-examples \
diff --git a/build/android-opus.sh b/build/android-opus.sh
index e73cf6c86..ac7fe48eb 100755
--- a/build/android-opus.sh
+++ b/build/android-opus.sh
@@ -46,12 +46,12 @@ fi
     --prefix=${BASEDIR}/prebuilt/android-$(get_target_build)/${LIB_NAME} \
     --with-pic \
     --with-sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot \
-    --enable-static \
+    --disable-static \
     --enable-rtcd \
     --enable-asm \
     --enable-check-asm \
     --enable-custom-modes \
-    --disable-shared \
+    --enable-shared \
     --disable-fast-install \
     --disable-maintainer-mode \
     --disable-doc \
diff --git a/build/android-x264.sh b/build/android-x264.sh
index 19d71a269..d1b099a1e 100755
--- a/build/android-x264.sh
+++ b/build/android-x264.sh
@@ -68,7 +68,7 @@ esac
     --prefix=${BASEDIR}/prebuilt/android-$(get_target_build)/${LIB_NAME} \
     --enable-pic \
     --sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot \
-    --enable-static \
+    --enable-shared \
     --disable-cli \
     ${ASM_FLAGS} \
     --host=${BUILD_HOST} || exit 1
`

Error: 
`ffmpeg: failed`

Error from build.log:
'INFO: Cleaning workspace for ffmpeg
armv7a-linux-androideabi16-clang is unable to create an executable file.
C compiler test failed'
