### ISSUE TITLE
Steps to add or enable external packages in iOS swift for x265

### ISSUE THREAD

**Issue by Pg1308** [tanersener/mobile-ffmpeg#541]
Hi,

I am working with FFmpeg for iOS swift and added in my project with pod 'mobile-ffmpeg-full', '~> 4.4'.
Whenever I try to compress and convert video using following command it fails with rc=1.

MobileFFmpeg.executeAsync("-i old.mp4 -c:v libx265 -crf 28 -c:a aac -b:a 128k -tag:v hvc1 new.mp4", withCallback:self)

I have searched to add or enable external package 'min-gpl'  for x265 to config in iOS but unable to find steps or anything to read and complete.

Please look into this issue and it would be really helpful if you can add it in your readme or mention here.

Thanks in advance.

**Comment by bhavesh4349** [comment]
Is Apple rejecting gpl license app?
