### ISSUE TITLE
Make the .so file size smaller (around ~2MB)? (Or, how to compile my custom version)

### ISSUE THREAD

**Issue by fzyzcjy** [tanersener/mobile-ffmpeg#543]
**Description**
Thanks for the wonderful lib! I only need to use the audio encoding (say, combine two .amr files). However, even if I use the "min" variant of mobile-ffmpeg, it takes 12.5MB (6.5MB after compression) which is quite huge. Actually, [it is said that](https://stackoverflow.com/questions/9913032/how-can-i-extract-audio-from-video-with-ffmpeg) an audio-only ffmpeg only takes about 2MB of size. Thus, I wonder how to compile a version that is small enough?

**Expected behavior**
See above.

**Current behavior**
See above.

**Screenshots**
N/A

**Logs**
N/A

**Environment**
 - Platform: [e.g. Android/IOS] android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64] v8a
 - Version (if applicable) [e.g. v1.2] latest
 - Source branch (if applicable) [e.g. master, dev-v2.x] master
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1] latest
 - Cocoapods version (if applicable) [e.g. 1.2.1] latest
 - Android Studio version (if applicable) [e.g. 3.1]latest
 - Android NDK version (if applicable) [e.g. 16b, 17c]latest

**Other**
N/A

**Comment by tanersener** [comment]
See [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size) wiki page.

**Comment by fzyzcjy** [comment]
Thank you very much!

**Comment by fzyzcjy** [comment]
@tanersener Hi sorry for bothering. I did not succeed in compiling it. So I wonder, if only enable audio, will it really be 2MB, or will it still be big? Thanks very much!

**Comment by tanersener** [comment]
It depends on which `ffmpeg` components are enabled in that `audio only` configuration. I don't know what it is, so hard to say what the final size will be. But it will be smaller, that's for sure.

**Comment by fzyzcjy** [comment]
@tanersener Ah thanks!
