### ISSUE TITLE
How to exclude FFprobe?

### ISSUE THREAD

**Issue by uzaysan** [tanersener/mobile-ffmpeg#544]
**Description**
I want to exclude ffprobe from library.

**Expected behavior**
I want to exclude FFprobe from library. I don't need FFprobe. So it's just increasing apk size and taking unnneccessary space.

**Current behavior**
FFprobe included by default.

I was using bravobit ffmpeg library. For that library we can exclude ffprobe by using this in app.gradle file:
```
aaptOptions {
        ignoreAssetsPattern "!*ffprobe"
    }
```

How can we do same in this library? Thank you very much.

**Comment by alexcohn** [comment]
In **mobile-ffmpeg**, extra size of FFprobe is minimal. See [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size) wiki page.

**Comment by uzaysan** [comment]
hey @alexcohn Sorry for the late reply. And thank you for your answer.
I only use ffmpeg for compressing video. This is my one and only command:

`FFmpeg.execute("-y -i "+ path +" -vcodec libx265 -vf scale="+resol+":-2 -crf 28 -movflags +faststart -acodec copy "+ context.getCacheDir()+File.separator+"compressedvideo.mp4");`

I really dont know about fmpeg and NDK in android development. Can you help me with this?

I'm using verison  `implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.4.LTS'`

**Comment by alexcohn** [comment]
@uzaysan help you with what, exactly?

**Comment by uzaysan** [comment]
@alexcohn nevermind. I switched to epmedia.
