### ISSUE TITLE
android drawtext with padding to overcome wrapping text issue

### ISSUE THREAD

**Issue by pratikbutani** [tanersener/mobile-ffmpeg#545]
**Description**
I am running the following command to write text on video. Its writing text on video successfully but If I use 2-3 lines, it's wrapping out the video.

String command = "-i '" + videoPath + "' -vf \"drawtext=fontsize=20:fontcolor=White:fontfile=" + fontFile.getAbsolutePath() + ":text='" + myTwoThreeLines + "':x=(w-text_w)/2:y=(h-10-text_h)\" -b:v 5M -codec:a copy '" + mDestinationPath +"'";

**Expected behavior**
I want to give some padding left and right side so the text does not wrap and display properly with some space both sides. It must become in the next line If text is bigger then the video's width.

**Current behavior**
It's wrapping out the text outsides the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/3306366/92995554-45628880-f522-11ea-8b48-54c2b5a787b9.png)

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch : master
 - Android Studio version :  4.0.1

**Comment by shaheercs** [comment]
can you please tell me how did you take font file in android?

**Comment by pratikbutani** [comment]
> can you please tell me how did you take the font file in android?

You need to save the font file into a folder before loading and give the absolute path of that file.
