### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by fachel** [tanersener/mobile-ffmpeg#549]
**Description**
when i execute any command (except  "-version") then an error appears "Permission denied", example the command "-i /storage/emulated/0/Android/data/ru.mirea.testaudio/files/Music/audio1.wav -i /storage/emulated/0/Android/data/ru.mirea.testaudio/files/Music/audio2.wav -filter_complex concat=a=1:v=0 -c:a libmp3lame -q:a 4 /storage/emulated/0/Android/data/ru.mirea.testaudio/files/Music/audio4.wav"

**Logs**
https://ghostbin.co/paste/bdp33

**Environment**
 -Android 10
 - Samsung Galaxy s10e
 - Android Studio version 4.0
 - targetSdkVersion and compileSdkVersion 28 (thought it would help change the version from 29 to 28 but it did not help)

**Comment by alexcohn** [comment]
Correct. You must provide full path to the files; don't expect the command to look in your app directory.

**Comment by fachel** [comment]
> Correct. You must provide full path to the files; don't expect the command to look in your app directory.
I have abbreviated the command in the description. Naturally, I indicate the full path, this can be seen from the link in Logs

**Comment by binhbk230** [comment]
I have same issue on Android 10, any guys resolve it, pls help me

**Comment by fachel** [comment]
@binhbk230 I've resolved this problem. You need to request permission :

```@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull
            int[] grantResults) {
        if (requestCode == REQUEST_CODE_PERMISSION) {
            isWork = grantResults.length > 0
                    && grantResults[0] == PackageManager.PERMISSION_GRANTED;
        }
    }

and add  android:requestLegacyExternalStorage="true" in manifest under <application like
<application
    android:requestLegacyExternalStorage="true"
    android:allowBackup="true"

**Comment by alexcohn** [comment]
Good, except `requestLegacyExternalStorage` is not a *permission* strictly speaking. The issue can be closed now, or there is something unclear that still bothers you?

**Comment by fachel** [comment]
The issue can be close
