### ISSUE TITLE
iOS and tvOS XCFramwork

### ISSUE THREAD

**Issue by milos1290** [tanersener/mobile-ffmpeg#552]
**Description**
Add support for single iOS and tvOS XCFramework with all slices

**Expected behavior**
Ability to build single XCFramework that contains both iOS(arm64, x86_64, catalyst) and tvOS(arm64, x86_64) slices

**Current behavior**
Separate libraries for iOS and tvOS

**Comment by tanersener** [comment]
I don't want to update existing scripts. They're already quite complex. Why don't you use a separate script to combine existing `iOS` `tvOS` bundles together?
