### ISSUE TITLE
x86_64 architecture issue

### ISSUE THREAD

**Issue by dancixx** [tanersener/mobile-ffmpeg#557]
Hi guys,

after updating Xcode, i got this issue: 
```
in /Users/tamaskoller/Desktop/connec-fitness-rn/ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec(aacencdsp.o), building for iOS Simulator, but linking in object file built for free standing, file '/Users/tamaskoller/Desktop/connec-fitness-rn/ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec' for architecture x86_64
```

Do you have any idea what can i do? The app doesnt work only in simulator, i can build on physical iphone via xcode, and can upload to testflight?

Thx,
Daniel

**Comment by gaojuanjuan** [comment]
> Hi guys,
> 
> after updating Xcode, i got this issue:
> 
> ```
> in /Users/tamaskoller/Desktop/connec-fitness-rn/ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec(aacencdsp.o), building for iOS Simulator, but linking in object file built for free standing, file '/Users/tamaskoller/Desktop/connec-fitness-rn/ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec' for architecture x86_64
> ```
> 
> Do you have any idea what can i do? The app doesnt work only in simulator, i can build on physical iphone via xcode, and can upload to testflight?
> 
> Thx,
> Daniel

I also encountered the same problem
