### ISSUE TITLE
Could not find tag for codec amr_nb in stream #1, codec not currently supported in container

### ISSUE THREAD

**Issue by shiv71** [tanersener/mobile-ffmpeg#560]
I am getting this issue in android emulatror api level 28,29,30

E/mobile-ffmpeg: [mp4 @ 0xe61aa710] Could not find tag for codec amr_nb in stream #1, codec not currently supported in container
 E/mobile-ffmpeg: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

**Comment by AdityaAnand1** [comment]
Were you able to find a solution for this? This seemed to be have worked well with bravobit library..

**Comment by Krutika-chotara** [comment]
Did you found any solution? I am also facing same issue in emulator with api level 30.

**Comment by xeroxoid** [comment]
The problem seems to be that MP4 containers do not support the amr_nb codec.

To fix this we just re-encoded the audio of the file using the `-acodec aac` flag instead of `-acodec copy`. Mind you the flag can also be written as the aliased versions `-c:a aac` and `-c:a copy`
