### ISSUE TITLE
MobileFFmpeg v1.2 No such module 'mobileffmpeg'

### ISSUE THREAD

**Issue by longkeng** [tanersener/mobile-ffmpeg#564]
**Description**
Hi. Thanks for making a more comprehensible version of FFmpeg for iOS. 
Cause of the conflict between the version of FFmpeg 4.x and 3.x version, I can't use the latest version FFmpegMobile.
So, I tried to use version 1.2 for iOS project with swift language.
https://github.com/tanersener/mobile-ffmpeg/releases/tag/v1.2
But after installing the version by Cocoapod, the bellow of error is displaying.

`No such module 'mobileffmpeg'`

**Expected behavior**
Use version 1.2 for ios swift project

**Current behavior**
Now, the error is displaying. Can't use that version.

**Screenshots**
<img width="821" alt="Screen Shot 2020-10-04 at 6 20 39 PM" src="https://user-images.githubusercontent.com/2831186/95014030-61170580-066e-11eb-9ab0-223b9f1ae51b.png">

**Environment**
 - Platform: IOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) v1.2
 - Xcode version (if applicable) 11.6
 - Cocoapods version (if applicable) 1.9.3

**Comment by tanersener** [comment]
You're asking help for a version which is more than 2 years old. Hard to say if it possible it on Swift.

**Comment by longkeng** [comment]
Thank you for your reply.
It seem not support Swift. 
I will close this issue.

**Comment by longkeng** [comment]
I reopen issue to ask you is there version FFmpeg-mobile using FFmpeg 3.x supporting Swift?

**Comment by tanersener** [comment]
Sorry, I don't know. `FFmpeg 3.x` releases are too old to remember the details about them. 

If you want to use `FFmpeg 3.x` I suggest checking out the source code of `mobile-ffmpeg`, replacing `ffmpeg` source code used under `src/ffmpeg` folder with a version you want to use and building the library yourself. You may receive minor errors but you won't have anything major.
