### ISSUE TITLE
Library not supporting Android SDK versions below 24 (Android 7.0)

### ISSUE THREAD

**Issue by ankurgecr** [tanersener/mobile-ffmpeg#567]
As per the ReadMe this libary is supposed to work with all the Android versions above 16+.

<img width="754" alt="Screenshot 2020-10-06 at 4 32 08 PM" src="https://user-images.githubusercontent.com/9653850/95178359-ed9e0100-07f1-11eb-9c72-20ba87d1532b.png">

But when I try to compile my source with `minSdkVersion 23` It's showing this error:

<img width="1029" alt="Screenshot 2020-10-06 at 4 33 41 PM" src="https://user-images.githubusercontent.com/9653850/95178431-00b0d100-07f2-11eb-96c8-a94ed29b1fab.png">

it seems like the ```minSDKVersion``` declared in the lib source code is 24.

If you can support min from `23`, it will add additional 7% of global Android devices.

**Comment by tanersener** [comment]
See [4. LTS Releases](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases).

**Comment by ankurgecr** [comment]
Since the min SDK version already mentioned [here](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases), I guess no further update required on this. 
Thanks.
