### ISSUE TITLE
Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by kishorejethava** [tanersener/mobile-ffmpeg#57]
I need x264 encoder to fast video processing and It's showing in logs 

> Unknown encoder 'libx264'

**Comment by tanersener** [comment]
Which package do you use? You need to use one of the `gpl` packages, as explained [here](https://github.com/tanersener/mobile-ffmpeg#2-using), for `x264` support.

If you need `h264` support only for `IOS` then you can use `h264_videotoolbox` codec which uses `Apple VideoToolbox` framework for encoding and you don't have to use a `gpl` package.
