### ISSUE TITLE
configure: error: C compiler cannot create executable when build mobile-ffmpeg(4.3.2) for ios 

### ISSUE THREAD

**Issue by wujun** [tanersener/mobile-ffmpeg#574]
**Description**
I choose mobile-ffmpeg version: 4.3.2 because I want to build arm64e mobile-ffmpeg on my macbook pro. The Android side is good. 

**Expected behavior**
What you expected to happen.

**Current behavior**

Building mobile-ffmpeg debug static library for iOS

Architectures: arm64, arm64e
Libraries: x264, x265, libvidstab

Building arm64 platform

x264: already built
x265: already built
libvidstab: already built

ffmpeg: skipped

mobile-ffmpeg: failed

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.
1. build.log
  the last few lines in build.log(edited in vim):
55255 checking for a BSD-compatible install... /usr/bin/install -c
55256 checking whether build environment is sane... yes
55257 checking for aarch64-ios-darwin-strip... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip
55258 checking for a thread-safe mkdir -p... ./install-sh -c -d
55259 checking for gawk... no
55260 checking for mawk... no
55261 checking for nawk... no
55262 checking for awk... awk
55263 checking whether make sets $(MAKE)... yes
55264 checking whether make supports nested variables... yes
55265 checking whether to enable maintainer-specific portions of Makefiles... no
55266 checking build system type... x86_64-apple-darwin19.6.0
55267 checking host system type... aarch64-ios-darwin
55268 checking whether make supports the include directive... yes (GNU style)
55269 checking for aarch64-ios-darwin-gcc... clang
55270 checking whether the C compiler works... no
55271 configure: error: in `/Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios':
55272 configure: error: C compiler cannot create executables
55273 See `config.log' for more details

2.config.log
[config.log](https://github.com/tanersener/mobile-ffmpeg/files/5382025/config.log)

3.vscode launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (hardcoded script name)",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/ios.sh",
            "args": [
                "-d", 
                "--enable-gpl", 
                "--disable-i386",
                "--disable-x86-64",
                "--disable-x86-64-mac-catalyst",
                "--enable-libvidstab",
                "--enable-x264",
                "--enable-x265",
            ]
        },
    ]
}
**Environment**
 - Platform: iOS
 - Architecture: [arm64, arm64e]
 - Version (if applicable) [4.3.2]
 - Source branch (if applicable) [4.3.2]
 - Xcode version (if applicable) [11.7]
 - Cocoapods version (if applicable) [1.9.2]
 - Android Studio version (if applicable) [v4.0]
 - Android NDK version (if applicable) [21.3.xxxx]
- Clang version 10.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
- gcc version 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Other**

**Comment by wujun** [comment]
sorry, I forget provide more information about my Macos: Catalina 10.15.6

**Comment by tanersener** [comment]
Why don't you use one of the latest versions, like `4.4`? `4.3.2` was not tested with `Catalina 10.15.6`.

Your output shows a few things.

1. `ffmpeg` is skipped. I don't know why but it shouldn't be.

2. Are you using a `launch.json` to start the build? If yes, have you tried using a normal `bash`/`zsh` terminal? They don't work in the same way. You may experience unexpected errors with it.

3... Some of the prerequisites are not found. Don't know whether they're installed or not but config.log fails to find them.
```
ACLOCAL='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/missing aclocal-1.16'
AUTOCONF='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/missing autoconf'
AUTOHEADER='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/missing autoheader'
AUTOMAKE='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/missing automake-1.16'
MAKEINFO='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/missing makeinfo'
install_sh='${SHELL} /Users/wujun/Workspace/mobile-ffmpeg-4.3.2/ios/install-sh'
```

**Comment by wujun** [comment]
@tanersener Thanks a lot for your quick response.😄
skipping ffmpeg is for save time to build at each time, I only want to care about mobile-ffmpeg.
I just tested on my laptop which currently is used as my dev environment. Which platform is preferred to build mobile-ffmpeg from source, Windows, Linux, or Macos and specific version of mobile-ffmpeg? Could you consider to write a docker file to regulate building environment as well?  Anyway, thank you for your great job.

**Comment by wujun** [comment]
In addition, I would check your concern for prerequisites and give feeback as soon as possile.
