### ISSUE TITLE
Compilation sped is too slow

### ISSUE THREAD

**Issue by karthiknew01** [tanersener/mobile-ffmpeg#577]
**Description**
I using the following command `-i  1caf527f-30a9-4cab-9ca1-2a98b52a6d6a/Movie/Q78730.mp4 -i video1.mp4 -i CleanLogo_720-hb.mp4 -i looped.m4a -i ba255f8b-a5ad-431a-9285-362366b3ffe7.png 
-filter_complex 
"[0:v]scale=1280x720,setdar=16/9,setsar=1/1[v0];[1:v]scale=1280x720,setdar=16/9,setsar=1/1[v1];[2:v]scale=1280x720,setdar=16/9,setsar=1/1[v2];[3:v]scale=1280x720,setdar=16/9,setsar=1/1[v3];[v0][0:a][v1][1:a][v2][2:a][v3][3:a]concat=n=4:v=1:a=1[outv1][outa1],[5:v]scale=160:-1[outv2],[outv1][outv2]overlay=main_w-overlay_w-20:main_h-overlay_h-70[outv];[4:a]volume=enable='between(t,11.96,21.991)+between(t,20.991,29.951)':volume=0.4,afade=t=out:st=26.951:d=3[outa2];[outa1][outa2]amix=inputs=2[outa]" -map [outv] -map [outa] -g 2 -preset ultrafast video2.mp4 -y` to merge multiple videos and add overlays

**Expected behavior**
I used this command with [WritingMinds](https://github.com/WritingMinds/ffmpeg-android-java) library. It used to work with speed of 1x to 1.5x.

**Current behavior**
After migration to this library, compilation speed is very slow. I'm getting a speed of 0.0005x. 

**Logs**
frame=120000 fps=564 q=19.0 size=  114944kB time=00:00:00.11 bitrate=7847697.1kbits/s dup=119996 drop=0 speed=0.000564x  

**Environment**
 - Platform: Android 10
 - Source branch mobile-ffmpeg-full-gpl:4.4.LTS
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Android Studio version - 4.1

**Comment by AllwinJohnson** [comment]
I'm also facing this issue. I migrated from Bravobit. Below command, I used to merge two videos and a image
inputFile1 - .mp4, approximately 5mb 
inputFile2 - .mp4 698kb
inputFile3 - .png 1.54kb
```
"-y", "-i", inputFile1, "-i", inputFile2, "-i",  inputFile3,
			  "-filter_complex", "[0:v]scale=" + res + ",setsar=1[v0];" + "[1:v]scale=" + res + ",setsar=1[v1];" +
			  "[v0][0:a][v1][1:a]concat=n=2:v=1:a=1[v];" +
			  "[v][2]overlay=x=0:y=(main_h-overlay_h)/2:enable='lte(t," + duration + ")'",
			  "-ab", "48000",
			  "-ac", "2", "-ar", "22050", "-s", "" + res, "-vcodec", "libx264", "-crf", "27", "-preset",
			  "ultrafast", outputPath
```
I'm getting a speed of 
`I/mobile-ffmpeg: frame=33333 fps=1273 q=21.0 size=    2304kB time=00:00:00.20 bitrate=89889.6kbits/s dup=33331 drop=0 speed=0.00802x   `
to 
`I/mobile-ffmpeg: frame=3000000 fps=1318 q=21.0 size=  234752kB time=00:00:03.18 bitrate=604339.7kbits/s dup=2999909 drop=0 speed=0.0014x   ` 
In log i'm getting `W/mobile-ffmpeg: More than 1000 frames duplicated` as processing the command  the frame count increases by `100000`, `1000000`
after the process is completed I'm getting an **output of file size 598mb** and also the video can't play. 

**Environment**
Platform : Android 10, arm-64v8a
mobile-ffmpeg-full-gpl:4.4.LTS

full log -> https://pastebin.com/5hvgxsbC

**Comment by tanersener** [comment]
When we are talking about a performance difference between two different libraries, there are a lot of variables that come into play. And the right way to understand the root cause is to:

1. Run the same command
2. Using the same input files
3. On the same device
4. Compare the `ffmpeg` console outputs

I don't see that kind of information in this ticket. So, I'm marking it with `missing-issue-template` label. Please provide console outputs of each library if you want this to be investigated.
