### ISSUE TITLE
iOS app builds and runs fine, but doesn't validate on submit to Apple

### ISSUE THREAD

**Issue by amayers** [tanersener/mobile-ffmpeg#581]
**Description**
I integrated FFmpeg using the `XCFramework` builds manually, following the Wiki's instructions. The app can build and run just fine. I'm able to use FFmpeg successfully. But when I go to submit the iOS app to the App Store, it fails to submit with validation errors. 

**Expected behavior**
That FFmpeg would pass Apple's validation and allow uploading to the App Store. 

**Current behavior**
Runs locally fine. Fails validation when submitted to the App Store.

**Screenshots**
<img width="713" alt="Screen Shot 2020-10-22 at 3 08 00 PM" src="https://user-images.githubusercontent.com/868103/96918517-69e24680-1478-11eb-9de2-22293d091ce5.png">
<img width="813" alt="Screen Shot 2020-10-22 at 3 13 41 PM" src="https://user-images.githubusercontent.com/868103/96919046-30f6a180-1479-11eb-8a8f-75d6c7821a7d.png">
<img width="751" alt="Screen Shot 2020-10-22 at 3 14 45 PM" src="https://user-images.githubusercontent.com/868103/96919196-6e5b2f00-1479-11eb-991f-58a81cfd3f44.png">

**Logs**
```
Prepared archive for uploading
Upload failed
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libswscale.framework/libswscale' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libavdevice.framework/libavdevice' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libavcodec.framework/libavcodec' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libswresample.framework/libswresample' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libavformat.framework/libavformat' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libavutil.framework/libavutil' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
	error: App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Revl.app/Frameworks/libavfilter.framework/libavfilter' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
```

**Environment**
 - Platform: iOS
 - Architecture: arm64
 - Version (if applicable) 4.4
 - Source branch (if applicable) https://github.com/tanersener/mobile-ffmpeg/releases/download/v4.4/mobile-ffmpeg-min-4.4-ios-xcframework.zip
 - Xcode version (if applicable) 12.1 (12A7403)

**Comment by tanersener** [comment]
Some of the wiki steps are misinterpreted in your integration. You shouldn't be embedding and signing xcframeworks coming from `mobile-ffmpeg`. Additionally, zip file you're referring to does not include files with `.framework` extension. They all end with `.xcframework`.

See my video below. You should be doing something wrong.

![2](https://user-images.githubusercontent.com/10158439/96924058-06710c80-14aa-11eb-9724-9a3076a5bb1c.gif)

**Comment by amayers** [comment]
@tanersener thank you SO MUCH. It was the `Embed & Sign` instead of the correct setting of `Do Not Embed`. It uploads just fine now. Might be good to point this out in the wiki.

**Comment by tanersener** [comment]
Sure, updated the wiki. Thank you for your contribution :+1:
