### ISSUE TITLE
Android - Crash on device (arm) when Config.ignoreSignal is called (mandatory for Unity usage)

### ISSUE THREAD

**Issue by fernando-closs-clansoft** [tanersener/mobile-ffmpeg#584]
**Description**
Android - Crash on device - AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmobileffmpeg_abidetect.so" 

Seems to be related to com.arthenica.mobileffmpeg.Config.ignoreSignal(Signal.SIGXCPU)

**Expected behavior**
No error

**Current behavior**
app crashes when com.arthenica.mobileffmpeg.Config.ignoreSignal(Signal.SIGXCPU); is called
---
E/Unity: AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmobileffmpeg_abidetect.so"...
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmobileffmpeg_abidetect.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:131)
        at com.clansoft.tacticalpad.TacticalPadAndroidActivity.startFFmpegVideo(TacticalPadAndroidActivity.java:1171) 

Line 1171 of my java is com.arthenica.mobileffmpeg.Config.ignoreSignal(Signal.SIGXCPU);

**Screenshots**
No screenshot

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Android 5.1.1 - Works normally on Android 9
 - Arm7
 - mobile-ffmpeg 4.4
 - From release aar (on github)

**Other**
After a little search, it looks like __register_atfork is available from API >= 24 (the aar minSDK is correctly set to 24, only the documentation here on github says 16)

**Comment by alexcohn** [comment]
You need one of the LTS builds to run **mobile-ffmpeg** on Android 5 (or whatever version with API level from 16 upto 23).

**Comment by fernando-closs-clansoft** [comment]
> You need one of the LTS builds to run **mobile-ffmpeg** on Android 5 (or whatever version with API level from 16 upto 23).

Ok. Thanks. I will try that as soon as I can and check the ignoreSignal on  LTS for <= API 23. Thanks.
