### ISSUE TITLE
Getting the same output in command line

### ISSUE THREAD

**Issue by Extazx2** [tanersener/mobile-ffmpeg#585]
**Description**
In my app, I use `getMediaInformation()` to get (among other things) the gps coordinates of a video. On some devices, I can't find the gps coordinates, and instead of having to download the video on my working devices and using the method on the phone, I would like to get the same information from my ubuntu's command line.
But when I try to use the arguments used in FFProbe.java (e.g `"-v", "error", "-hide_banner", "-print_format", "json", "-show_format", "-show_streams", "-i"`) in command line, I don't get the same output.

How could I get the same results, if possible ?

**Expected behavior**
I expect to get something like this : 
[output.txt](https://github.com/tanersener/mobile-ffmpeg/files/5445490/output.txt)
Where we can clearly see the gps coordinates

**Current behavior**
I get something like this :
[output_other.txt](https://github.com/tanersener/mobile-ffmpeg/files/5445516/output_other.txt)
Where we cannot see the GPS coordinates

**Other**
As you can see in the first output file, I use flutter_ffmpeg which is using the mobile_ffmpeg methods. That's why I'm posting here

**Comment by tanersener** [comment]
You don't have to use `getMediaInformation()` method if you're not happy with its output. Just run the command that produces `output.txt` on `flutter_ffmpeg` and you will get back the same result. There is no magic there.

And if GPS coordinates are not there, then please provide us the outputs. Because `output.txt` and `output_other.txt` you've shared in your post are executed on different files. `VID_20201027_120400.mp4` output does not include any GPS coordinates. I see that. But did you try to copy that file to `ubuntu` and check whether it really has GPS information inside?

**Comment by Extazx2** [comment]
I'm totally happy with the result of `getMediaInformation()` !

It produces the output.txt file and I want to get the same amount of information when doing the commands in command line (which produces output_other.txt).

By the way, that's the same file in both outputs.
My file_picker is extracting it with another name (which ends with .jpg, known issue)

I might have worded my request badly, but I wanted to know if there are other arguments running in the getMediaInformation() method other than the ones I've included in my first post : 
`"-v", "error", "-hide_banner", "-print_format", "json", "-show_format", "-show_streams", "-i"`

(Or maybe I've mistaken the getMediaInformation() used by the flutter package with another one ?)

**Comment by tanersener** [comment]
Let's start again.

- What is the mobile-ffmpeg version you're using? 
- Also can you please provide flutter_ffmpeg version as well?
- Where is `output.txt` coming from? `getMediaInformation()`?

**Comment by Extazx2** [comment]
On my App i'm using Flutter_ffmpeg v0.2.10
I'm not using mobile_ffmpeg "as is" only through flutter_ffmpeg.

Output.txt are the mobile_ffmpeg logs from this piece of code :
```dart
 String coordinates = await _flutterFFprobe.getMediaInformation(filePath).then((info) {
      String coordinatesIdentifier;
      if (Platform.isIOS) {
        coordinatesIdentifier = "com.apple.quicktime.location.ISO6709";
      } else {
        coordinatesIdentifier = "location";
      }
      return info['metadata'] != null ? info['metadata'][coordinatesIdentifier] : null;
    });
    if (coordinates != null) {
      return _getLongAndLat(coordinates);
    }
    return null;
  }
```

On my computer i'm using Ffmpeg v3.4.8

**Comment by tanersener** [comment]
You're using the older version of the plugin. Please use the latest version of `flutter_ffmpeg`. It has a new and more flexible `getMediaInformation` implementation.

**Comment by Extazx2** [comment]
The version of the plugin I'm using is not the problem here...

What I would like to know is : what are the ffmpeg commands to use to replicate mobile-ffmpeg `getMediaInformation()` ?

**Comment by tanersener** [comment]
You're using `flutter_ffmpeg v0.2.10`. It depends on `mobile-ffmpeg v4.3.1`. You can see the version [here](https://github.com/tanersener/flutter-ffmpeg/blob/v0.2.10/android/build.gradle#L48). `getMediaInformation` implementation on `mobile-ffmpeg v4.3.1` uses [this command](https://github.com/tanersener/mobile-ffmpeg/blob/v4.3.1/android/app/src/main/java/com/arthenica/mobileffmpeg/FFprobe.java#L86).

**Comment by Extazx2** [comment]
Ok, so I thought well but it does not output the information I want in command line...

Thanks anyway
