### ISSUE TITLE
fftools_ffmpeg.h file not found for xCode project

### ISSUE THREAD

**Issue by aldov500** [tanersener/mobile-ffmpeg#586]
**Description**
I get Lexical or Preprocessor error with the file not being found. The MobileFFmpeg.m file cant found the fftools_ffmpeg.h file

**Expected behavior**
Project succesfully build

**Current behavior**
Build failed with 1 error

**Screenshots**
![Captura](https://user-images.githubusercontent.com/25472620/97635640-49c50100-19fd-11eb-99b1-252cc5e99784.PNG)

**Environment**
 - Platform: [IOS]
 - Architecture: [armv7, armv7s, arm64]
 - Xcode version : 12
 - Cocoapods version: pod 'mobile-ffmpeg-full', '~> 4.4

**Comment by aldov500** [comment]
Create a new project in Xcode, add cocoapods and installa the library. Still got an error

**Comment by tanersener** [comment]
See #132
