### ISSUE TITLE
Need Custom Build for My Project

### ISSUE THREAD

**Issue by basaktamal** [tanersener/mobile-ffmpeg#588]
I need personal help to build the ffmpeg for my own android project. I shall pay for it. Please help me....

**Comment by tanersener** [comment]
There are different sponsorship options available under the `Sponsor` button. They give you priority support for your Github issues or e-mail support for your issues. Have you considered using one of them?

**Comment by basaktamal** [comment]
First of all thanks for your quick reply.
Let me tell you that I need your personal help to build FFMPEG for my
running project. My email address is tamal@littleapps.in
Hope you will do that...

Waiting for your reply..
