### ISSUE TITLE
Execute -filter_complex

### ISSUE THREAD

**Issue by vanhung1710** [tanersener/mobile-ffmpeg#591]
I can not execute this command:
`ffmpeg -i input1.mp4 -i input2.webm -i input3.mov 
-filter_complex "[0:v:0][0:a:0][1:v:0][1:a:0][2:v:0][2:a:0]concat=n=3:v=1:a=1[outv][outa]" 
-map "[outv]" -map "[outa]" output.mkv`

**Comment by thuan09878** [comment]
Me too. Does anyone has a solution for this?

**Comment by iamkdblue** [comment]
Try this
`-i input1.mp4 -i input2.webm -i input3.mov -filter_complex '[0:v:0][0:a:0][1:v:0][1:a:0][2:v:0][2:a:0]concat=n=3:v=1:a=1[outv][outa]' -map[outv] -map[outa] output.mkv`
