### ISSUE TITLE
android FFmpeg.executeAsync command execution failed rc=3001

### ISSUE THREAD

**Issue by arabsiphone** [tanersener/mobile-ffmpeg#592]
// I have a strange problem. I am using this wonderful library and thank you for that, but there is an error for which I have not found a solution, knowing that the output and files are correct and the operation is excellent

commands = new String[]{"-i",orignalPath,"-map","0","-segment_time",""+duration,"-g",""+duration,
                "-sc_threshold","0","-force_key_frames","expr:gte(t,n_forced*"+duration+")","-f","segment","-reset_timestamps","1",dest.getAbsolutePath()};

        long executionId = FFmpeg.executeAsync(commands, new ExecuteCallback() {

            @Override
            public void apply(final long executionId, final int returnCode) {
                if (executionId == RETURN_CODE_SUCCESS) {
                    Log.i(Config.TAG, "Async command execution completed successfully.");
                } else if (executionId == RETURN_CODE_CANCEL) {
                    Log.i(Config.TAG, "Async command execution cancelled by user.");
                } else {
                    Log.i(Config.TAG, String.format("Async command execution failed with rc=%d.", executionId));
                    Config.printLastCommandOutput(Log.INFO);
                }
            }
        });

/Log 

2020-11-03 19:02:42.055 23347-23837/com.golden.goldencut I/mobile-ffmpeg: video:11779kB audio:194kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
2020-11-03 19:02:42.055 23347-23837/com.golden.goldencut I/mobile-ffmpeg: unknown
2020-11-03 19:02:42.084 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] frame I:139   Avg QP:22.11  size: 47298
2020-11-03 19:02:42.084 23347-23347/com.golden.goldencut I/mobile-ffmpeg: Async command execution failed with rc=٣٠٠١.
2020-11-03 19:02:42.084 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] frame P:416   Avg QP:25.86  size: 11704
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] frame B:834   Avg QP:27.31  size:   741
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] consecutive B-frames: 19.9%  0.0%  0.0% 80.1%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] mb I  I16..4: 21.7% 71.7%  6.6%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] mb P  I16..4:  6.3% 12.7%  0.1%  P16..4: 25.9%  4.6%  1.4%  0.0%  0.0%    skip:48.8%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.7%  0.1%  0.0%  direct: 0.3%  skip:91.8%  L0:41.9% L1:57.4% BI: 0.7%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] 8x8 transform intra:69.6% inter:89.3%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] coded y,uvDC,uvAC intra: 28.4% 36.5% 6.1% inter: 2.4% 4.1% 0.0%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] i16 v,h,dc,p: 35% 36%  9% 20%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 20% 32%  3%  3%  3%  3%  3%  4%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 25% 12%  7%  9%  7%  8%  5%  5%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] i8c dc,h,v,p: 66% 18% 12%  3%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] Weighted P-Frames: Y:20.4% UV:1.9%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] ref P L0: 76.7%  9.9%  9.9%  3.0%  0.4%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] ref B L0: 94.9%  4.3%  0.9%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] ref B L1: 97.4%  2.6%
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] kb/s:8336.05
2020-11-03 19:02:42.085 23347-23837/com.golden.goldencut I/mobile-ffmpeg: [aac @ 0x72a5bea300] Qavg: 1189.927
2020-11-03 19:02:42.086 23347-23347/com.golden.goldencut I/mobile-ffmpeg: ffmpeg version v4.4-dev-416 Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
      configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --extra-libs='-L/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libx264 --enable-gpl --enable-libxvid --enable-gpl --enable-libx265 --enable-gpl --enable-libvidstab --enable-gpl --disable-sdl2 --enable-zlib --enable-mediacodec
      libavutil      56. 55.100 / 56. 55.100
      libavcodec     58. 96.100 / 58. 96.100
      libavformat    58. 48.100 / 58. 48.100
      libavdevice    58. 11.101 / 58. 11.101
      libavfilter     7. 87.100 /  7. 87.100
      libswscale      5.  8.100 /  5.  8.100
      libswresample   3.  8.100 /  3.  8.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/٢٠٢٠٠٩٢٥_٢٢٢٦٣٢.mp4':
      Metadata:
        major_brand     : mp42
        minor_version   : 0
        compatible_brands: isommp42
        creation_time   : 2020-09-25T19:26:45.000000Z
        com.android.version: 9
        com.android.capture.fps: 30.000000
      Duration: 00:00:11.58, start: 0.000000, bitrate: 14525 kb/s
        Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 14267 kb/s, SAR 1:1 DAR 16:9, 29.72 fps, 120 tbr, 90k tbn, 180k tbc (default)
        Metadata:
          rotate          : 90
          creation_time   : 2020-09-25T19:26:45.000000Z
          handler_name    : VideoHandle
        Side data:
          displaymatrix: rotation of -90.00 degrees
        Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
        Metadata:
          creation_time   : 2020-09-25T19:26:45.000000Z
          handler_name    : SoundHandle
    Stream mapping:
      Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
      Stream #0:1 -> #0:1 (aac (native) -> aac (native))
    Press [q] to stop, [?] for help
    [graph 0 input from stream 0:0 @ 0x72bd0d9e40] sws_param option is deprecated and ignored
    [libx264 @ 0x72a5be9400] using SAR=1/1
    [libx264 @ 0x72a5be9400] using cpu capabilities: ARMv8 NEON
    [libx264 @ 0x72a5be9400] profile High, level 5.1, 4:2:0, 8-bit
2020-11-03 19:02:42.087 23347-23347/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] 264 - core 160 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=10 keyint_min=1 scenecut=0 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
    [segment @ 0x72bd18a200] Opening '/storage/emulated/0/Android/data/com.golden.goldencut/files/GoldenCutTrim/٢٠٢٠١١٠٣١٨٠١٤١GoldenCut_000.mp4' for writing
    Output #0, segment, to '/storage/emulated/0/Android/data/com.golden.goldencut/files/GoldenCutTrim/٢٠٢٠١١٠٣١٨٠١٤١GoldenCut_%03d.mp4':
      Metadata:
        major_brand     : mp42
        minor_version   : 0
        compatible_brands: isommp42
        com.android.capture.fps: 30.000000
        com.android.version: 9
        encoder         : Lavf58.48.100
        Stream #0:0(eng): Video: h264 (libx264), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], q=-1--1, 120 fps, 15360 tbn, 120 tbc (default)
        Metadata:
          encoder         : Lavc58.96.100 libx264
          creation_time   : 2020-09-25T19:26:45.000000Z
          handler_name    : VideoHandle
        Side data:
          cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
          displaymatrix: rotation of -0.00 degrees
        Stream #0:1(eng): Audio: aac, 48000 Hz, stereo, fltp, 128 kb/s (default)
        Metadata:
          creation_time   : 2020-09-25T19:26:45.000000Z
          handler_name    : SoundHandle
          encoder         : Lavc58.96.100 aac
    frame=   31 fps=0.0 q=33.0 size=N/A time=00:00:01.00 bitrate=N/A dup=24 drop=0 speed=1.69x    
    frame=   47 fps= 40 q=33.0 size=N/A time=00:00:01.00 bitrate=N/A dup=36 drop=0 speed=0.857x    
    frame=   59 fps= 33 q=33.0 size=N/A time=00:00:01.00 bitrate=N/A dup=45 drop=0 speed=0.553x    
    frame=   77 fps= 31 q=33.0 size=N/A time=00:00:01.00 bitrate=N/A dup=58 drop=0 speed=0.409x    
    frame=   93 fps= 31 q=33.0 size=N/A time=00:00:01.00 bitrate=N/A dup=70 drop=0 speed=0.336x    
    frame=  109 fps= 30 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=82 drop=0 speed=0.545x    
    frame=  125 fps= 29 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=94 drop=0 speed=0.473x    
    frame=  141 fps= 29 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=106 drop=0 speed=0.406x    
    frame=  157 fps= 28 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=118 drop=0 speed=0.356x    
    frame=  181 fps= 28 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=137 drop=0 speed=0.307x    
    frame=  197 fps= 27 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=149 drop=0 speed=0.279x    
    frame=  213 fps= 27 q=33.0 size=N/A time=00:00:02.00 bitrate=N/A dup=161 drop=0 speed=0.255x    
    frame=  225 fps= 26 q=33.0 size=N/A time=00:00:02.02 bitrate=N/A dup=170 drop=0 speed=0.234x    
    frame=  241 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=182 drop=0 speed=0.326x    
    frame=  257 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=194 drop=0 speed=0.305x    
    frame=  269 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=203 drop=0 speed=0.288x    
    frame=  285 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=215 drop=0 speed=0.272x    
    frame=  301 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=227 drop=0 speed=0.255x    
    frame=  317 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=239 drop=0 speed=0.242x    
    frame=  337 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=255 drop=0 speed=0.23x    
    frame=  349 fps= 26 q=33.0 size=N/A time=00:00:03.00 bitrate=N/A dup=264 drop=0 speed=0.22x    
    frame=  365 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=276 drop=0 speed=0.28x    
2020-11-03 19:02:42.087 23347-23347/com.golden.goldencut I/mobile-ffmpeg: frame=  381 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=288 drop=0 speed=0.267x    
    frame=  397 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=300 drop=0 speed=0.255x    
    frame=  417 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=315 drop=0 speed=0.243x    
    frame=  433 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=327 drop=0 speed=0.234x    
    frame=  445 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=336 drop=0 speed=0.228x    
    frame=  461 fps= 25 q=33.0 size=N/A time=00:00:04.01 bitrate=N/A dup=348 drop=0 speed=0.219x    
    frame=  473 fps= 25 q=33.0 size=N/A time=00:00:04.03 bitrate=N/A dup=357 drop=0 speed=0.213x    
    frame=  493 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=372 drop=0 speed=0.258x    
    frame=  509 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=384 drop=0 speed=0.249x    
    frame=  525 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=396 drop=0 speed=0.243x    
    frame=  541 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=408 drop=0 speed=0.235x    
    frame=  557 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=420 drop=0 speed=0.229x    
    frame=  573 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=432 drop=0 speed=0.223x    
    frame=  585 fps= 25 q=33.0 size=N/A time=00:00:05.01 bitrate=N/A dup=441 drop=0 speed=0.217x    
    frame=  597 fps= 25 q=33.0 size=N/A time=00:00:05.03 bitrate=N/A dup=450 drop=0 speed=0.211x    
    frame=  617 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=465 drop=0 speed=0.243x    
    frame=  629 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=474 drop=0 speed=0.238x    
    frame=  641 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=483 drop=0 speed=0.233x    
    frame=  657 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=495 drop=0 speed=0.227x    
    frame=  669 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=504 drop=0 speed=0.222x    
    frame=  681 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=513 drop=0 speed=0.217x    
    frame=  693 fps= 25 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=522 drop=0 speed=0.213x    
    frame=  705 fps= 24 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=531 drop=0 speed=0.209x    
    frame=  717 fps= 24 q=33.0 size=N/A time=00:00:06.01 bitrate=N/A dup=540 drop=0 speed=0.204x    
    frame=  729 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=549 drop=0 speed=0.232x    
    frame=  741 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=558 drop=0 speed=0.227x    
    frame=  753 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=567 drop=0 speed=0.223x    
    frame=  765 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=576 drop=0 speed=0.219x    
    frame=  777 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=585 drop=0 speed=0.215x    
    frame=  789 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=594 drop=0 speed=0.21x    
    frame=  801 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=603 drop=0 speed=0.206x    
    frame=  817 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=615 drop=0 speed=0.203x    
    frame=  825 fps= 24 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=621 drop=0 speed= 0.2x    
    frame=  837 fps= 23 q=33.0 size=N/A time=00:00:07.01 bitrate=N/A dup=630 drop=0 speed=0.197x    
    frame=  849 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=639 drop=0 speed=0.221x    
    frame=  861 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=648 drop=0 speed=0.217x    
    frame=  874 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=658 drop=0 speed=0.214x    
    frame=  886 fps= 23 q=30.0 size=N/A time=00:00:08.02 bitrate=N/A dup=667 drop=0 speed=0.211x    
    frame=  898 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=676 drop=0 speed=0.208x    
    frame=  909 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=684 drop=0 speed=0.205x    
    frame=  925 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=696 drop=0 speed=0.202x    
2020-11-03 19:02:42.087 23347-23347/com.golden.goldencut I/mobile-ffmpeg: frame=  937 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=705 drop=0 speed=0.199x    
    frame=  949 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=714 drop=0 speed=0.196x    
    frame=  957 fps= 23 q=33.0 size=N/A time=00:00:08.02 bitrate=N/A dup=720 drop=0 speed=0.194x    
    frame=  969 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=729 drop=0 speed=0.215x    
    frame=  981 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=739 drop=0 speed=0.212x    
    frame=  997 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=751 drop=0 speed=0.209x    
    frame= 1013 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=763 drop=0 speed=0.206x    
    frame= 1029 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=775 drop=0 speed=0.203x    
    frame= 1041 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=784 drop=0 speed= 0.2x    
    frame= 1057 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=796 drop=0 speed=0.198x    
    frame= 1069 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=805 drop=0 speed=0.195x    
    frame= 1085 fps= 23 q=33.0 size=N/A time=00:00:09.02 bitrate=N/A dup=817 drop=0 speed=0.192x    
    frame= 1097 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=826 drop=0 speed=0.211x    
    frame= 1109 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=835 drop=0 speed=0.209x    
    frame= 1121 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=844 drop=0 speed=0.207x    
    frame= 1133 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=853 drop=0 speed=0.205x    
    frame= 1149 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=865 drop=0 speed=0.202x    
    frame= 1161 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=874 drop=0 speed=0.199x    
    frame= 1177 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=886 drop=0 speed=0.197x    
    frame= 1189 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=895 drop=0 speed=0.195x    
    frame= 1209 fps= 23 q=33.0 size=N/A time=00:00:10.02 bitrate=N/A dup=910 drop=0 speed=0.192x    
    frame= 1221 fps= 23 q=33.0 size=N/A time=00:00:11.39 bitrate=N/A dup=919 drop=0 speed=0.216x    
    [segment @ 0x72bd18a200] Opening '/storage/emulated/0/Android/data/com.golden.goldencut/files/GoldenCutTrim/٢٠٢٠١١٠٣١٨٠١٤١GoldenCut_001.mp4' for writing
    frame= 1237 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=931 drop=0 speed=0.215x    
    frame= 1249 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=940 drop=0 speed=0.213x    
    frame= 1265 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=952 drop=0 speed=0.21x    
    frame= 1281 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=964 drop=0 speed=0.207x    
    frame= 1297 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=976 drop=0 speed=0.205x    
    frame= 1313 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=988 drop=0 speed=0.203x    
    frame= 1325 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=997 drop=0 speed=0.201x    
    More than 1000 frames duplicated
    frame= 1337 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=1006 drop=0 speed=0.199x    
    frame= 1357 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=1021 drop=0 speed=0.197x    
    frame= 1373 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=1033 drop=0 speed=0.195x    
    frame= 1389 fps= 23 q=33.0 size=N/A time=00:00:11.43 bitrate=N/A dup=1045 drop=0 speed=0.193x    
    frame= 1389 fps= 23 q=-1.0 Lsize=N/A time=00:00:11.55 bitrate=N/A dup=1045 drop=0 speed=0.192x    
    video:11779kB audio:194kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    [libx264 @ 0x72a5be9400] frame I:139   Avg QP:22.11  size: 47298
    [libx264 @ 0x72a5be9400] frame P:416   Avg QP:25.86  size: 11704
    [libx264 @ 0x72a5be9400] frame B:834   Avg QP:27.31  size:   741
    [libx264 @ 0x72a5be9400] consecutive B-frames: 19.9%  0.0%  0.0% 80.1%
    [libx264 @ 0x72a5be9400] mb I  I16..4: 21.7% 71.7%  6.6%
2020-11-03 19:02:42.087 23347-23347/com.golden.goldencut I/mobile-ffmpeg: [libx264 @ 0x72a5be9400] mb P  I16..4:  6.3% 12.7%  0.1%  P16..4: 25.9%  4.6%  1.4%  0.0%  0.0%    skip:48.8%
    [libx264 @ 0x72a5be9400] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  7.7%  0.1%  0.0%  direct: 0.3%  skip:91.8%  L0:41.9% L1:57.4% BI: 0.7%
    [libx264 @ 0x72a5be9400] 8x8 transform intra:69.6% inter:89.3%
    [libx264 @ 0x72a5be9400] coded y,uvDC,uvAC intra: 28.4% 36.5% 6.1% inter: 2.4% 4.1% 0.0%
    [libx264 @ 0x72a5be9400] i16 v,h,dc,p: 35% 36%  9% 20%
    [libx264 @ 0x72a5be9400] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 20% 32%  3%  3%  3%  3%  3%  4%
    [libx264 @ 0x72a5be9400] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 25% 12%  7%  9%  7%  8%  5%  5%
    [libx264 @ 0x72a5be9400] i8c dc,h,v,p: 66% 18% 12%  3%
    [libx264 @ 0x72a5be9400] Weighted P-Frames: Y:20.4% UV:1.9%
    [libx264 @ 0x72a5be9400] ref P L0: 76.7%  9.9%  9.9%  3.0%  0.4%
    [libx264 @ 0x72a5be9400] ref B L0: 94.9%  4.3%  0.9%
    [libx264 @ 0x72a5be9400] ref B L1: 97.4%  2.6%
    [libx264 @ 0x72a5be9400] kb/s:8336.05
    [aac @ 0x72a5bea300] Qavg: 1189.927

**Comment by tanersener** [comment]
Can you use `returnCode` to check the execution result? You are using `executionId` right now.

**Comment by Cutta** [comment]
I made the same mistake today and I lost my 2 hours with it. After that I realized "rc" is not defined so I changed it with "executionId".  This misunderstanding occurs from a documentation typo. 
Here: https://tanersener.github.io/mobile-ffmpeg/ ->
_3. Execute asynchronous FFmpeg commands._
"rc" should be "returnCode" in the documentation.

**Comment by tanersener** [comment]
Yeah, I noticed that too. Will update the example documentation.

**Comment by arabsiphone** [comment]
thanks :)
