### ISSUE TITLE
How to consume response from FFprobe

### ISSUE THREAD

**Issue by leephela** [tanersener/mobile-ffmpeg#594]
Hello,
How to synchronously get and consume the response from the `FFprobe?`
The example only shows about the status of the FFprobe query.
Also, the `Config.enabledLog` method has no method to reset the log or disable it again later, which is not a very convenient way to go with it at the very first place.

Also, an example on how to use the command for `getMediaInformationFromCommand` will be really helpful as it always return null for any input command passed down.

Thank you

**Comment by tanersener** [comment]
How to synchronously get and consume the response from the FFprobe?
The example only shows about the status of the FFprobe query.
Also, the Config.enabledLog method has no method to reset the log or disable it again later, which is not a very convenient way to go with it at the very first place.

Also, an example on how to use the command for getMediaInformationFromCommand will be really helpful as it always return null for any input command passed down.

**Comment by tanersener** [comment]
> How to synchronously get and consume the response from the FFprobe?
The example only shows about the status of the FFprobe query.

The default behaviour of `FFprobe` is to print an output. This is what it does on other platforms and this is also what it does as part of `MobileFFmpeg`. The output generated by `FFprobe` changes depending on options used. So, there does not exist a standard way to read `FFprobe` output. If you choose to get the output as xml, it will be in xml format, if you choose csv it will be in csv format. You can see all available output formats in [ffprobe documentation](https://ffmpeg.org/ffprobe.html). As you know, you can get `FFprobe` output using `Config.getLastCommandOutput()` method.

`getMediaInformation` is a helper method which uses a generic `FFprobe` command to get information for the given media file in json format. It uses `MediaInformationParser` class to parse the `FFprobe` output and builds a `MediaInformation` object which includes all fields printed.

> Also, the Config.enabledLog method has no method to reset the log or disable it again later, which is not a very convenient way to go with it at the very first place.

I don't understand what you mean by reset. You can disable a log callback by setting the log callback to null or disable log redirection feature completely by running `Config.disableRedirection()`. And, it is possible to enable them again using corresponding functions.

> Also, an example on how to use the command for getMediaInformationFromCommand will be really helpful as it always return null for any input command passed down.

`getMediaInformation` uses `getMediaInformationFromCommandArguments` internally. Why don't you have a look at the implementation inside [FFprobe](https://github.com/tanersener/mobile-ffmpeg/blob/master/android/app/src/main/java/com/arthenica/mobileffmpeg/FFprobe.java#L85) implementation?

**Comment by leephela** [comment]
Thank you for keeping this project up to date. This `ffmpeg` is one of the best android library out there on the web.

`getLastCommandOutput` is the one I was missing at. And, will `disableRedirection` completely disables the `statisticsCallback` as well, or they operate independently ?

**Comment by tanersener** [comment]
`disableRedirection` will disable both callbacks. If you need `statisticsCallback` functionality I'll suggest setting log callback to `null`.
