### ISSUE TITLE
Optimized implementation of ffmpeg x265 for mobile chips

### ISSUE THREAD

**Issue by aytunch** [tanersener/mobile-ffmpeg#595]
I know that this Library is not the direct recipient of this issue but I could not find a better place to bring this subject in.  So I apologize beforehand if this is not appropriate. 

I am trying to encode videos on iOS and Android clients and then upload them. So Encode times are very critical for my use case. x265 had nearly %50 advantage in terms of file size. This comes with a disadvantage in encode times. Usually it is 5-10 times slower than x264 encoding. I understand that this is not totally because of the x265's algorithm but because the encoders can not use the cpu's in a fully optimized way.

I came across with this article: [How Fast is H.265/HEVC Software Encoding on ARM CPUs (iPhone/Android) With FFmpeg?](https://quanticdev.com/articles/h265-encoding-on-arm-cpus/) and the related video comparing the encode time differences of an Intel and Arm processor: [video of the article](https://www.youtube.com/watch?v=UZCKD-zcrfU)

The author states that the specific Intel processor is 2.5times faster than the specific arm processor. However in the case of ffmpeg, the encode time difference is 10 times. [He states that this unbalance is caused by the unoptimized implementation of ffmpeg on arm chips.](https://forum.doom9.org/showthread.php?p=1817880#post1817880)

[This article shows the adoption rate for mobile phones with hardware support of x265.](https://www.scientiamobile.com/growing-support-of-hevc-or-h-265-video-on-mobile-devices/)

[Lastly I found out that neon code instead of c makes a huge difference in encoding/decoding performances](https://medium.com/@ewoutterhoeven/how-arms-neon-enables-efficient-av1-decoding-on-mobile-5fcb3a4f6e7f). Is there any plans on supporting a neon implementation of ffmpeg?

I would be glad if someone can inform us more about this subject.

**Comment by tanersener** [comment]
`mobile-ffmpeg` supports 3 Android (`arm-v7a`, `arm-v7a-neon`, `arm64-v8a`) and 4 iOS (`armv7`, `armv7s`, `arm64`, `arm64e`) ARM architectures. All of them except Android's `arm-v7a` uses neon optimisations. So, there is nothing that can be improved about neon optimisations on `ffmpeg`.

Regarding `x265` cpu optimisations, [ASM Support](https://github.com/tanersener/mobile-ffmpeg/wiki/ASM-Support) wiki page lists which libraries are built with cpu optimisations enabled and which are not. You can also see what kind of issues we face when we enable them. Unfortunately, cpu optimisations for `x265` on ARM architectures are mostly disabled. This comes from `x265` and needs to be improved by them.

**Comment by aytunch** [comment]
Thank you very much for the explanation and pointing me towards the right direction. I will further investigate the issue in x265 specific areas.
