### ISSUE TITLE
Xamarin - Exiting normally, received signal 24: but the process is not finished

### ISSUE THREAD

**Issue by SteezCram** [tanersener/mobile-ffmpeg#598]
Hello,

**Description**
I'm writing an encoder application for Android using Xamarin. I need all the things to export your project to Xamarin since you give the .aar file.

So after that, I export all the commands using the DependencyService to expose all your functions. But when I use `FFmpeg.Execute("my command string")` the video is processed but randomly the processing stop and I have this: `Exiting normally, received signal 24.` and the code execution of the app is completely blocked.
This can happen for the same video at 10000 frames, 1000 frames, or 0 frames.

**Expected behavior**
That the video is processed entirely since there is no reason that the process block.

**Current behavior**
The video processing is blocked with this code: `Exiting normally, received signal 24`. Moreover, the code execution of the app is completely blocked (the method `FFmpeg.Execute("my command string")` never stop).
No error is throw if the processing block.

**Logs**
https://ghostbin.co/paste/9r3hht2

**Environment**
 - Platform: Android
 - Architecture: x86_64
 - Version: Android 10 with Google API (not Google Play)
 - Source branch: version 4.4 FULL LTS
 - Microsoft Visual Studio version: 2019 Community
 - Android NDK version: 28
 - Xamrin Essentials version: 1.5.3.2
 - Xamarin Forms version: 4.8.0.1269

**Comment by SteezCram** [comment]
I have updated my post, sorry I don't see the issue template.

**Comment by tanersener** [comment]
Can you try running this method on startup?

```
Config.ignoreSignal(Signal.SIGXCPU);
```

See [my post](https://github.com/tanersener/mobile-ffmpeg/issues/258#issuecomment-645664260) on Unity thread. Unity also uses Mono under the hood. We managed to fix similar errors by running `ignoreSignal` method on application startup.

**Comment by SteezCram** [comment]
Thanks, it works now!

I don't see your post on the Unity thread, but I look at the wiki, maybe you should put the solution here since I think many people never read the closed issue.
Moreover, I learn something about Mono, I never heard of that before.

Also I have another question, can I post here or not?

**Comment by tanersener** [comment]
Sure, go for it.

**Comment by SteezCram** [comment]
I solve it myself, so I don't have any questions now, thanks for all!
