### ISSUE TITLE
Command execution failed with rc =1

### ISSUE THREAD

**Issue by Dta-KO** [tanersener/mobile-ffmpeg#603]
this is my debug capture. 
![image](https://user-images.githubusercontent.com/55838130/99670217-c7cb7380-2aa2-11eb-85b1-5c5b52ecfc0a.png)

**Comment by sgnm-enespecenek** [comment]
@tanersener FFmeg calıştırdığımda returnCode 1 olarak dönüyor

**Comment by tanersener** [comment]
Return code alone doesn't tell anything. Have a look at console output. It will tell you what's wrong here.

**Comment by sgnm-enespecenek** [comment]
Thank you
