### ISSUE TITLE
FFprobe.getMediaInformation return null , Any alternate solution is available for get media information?

### ISSUE THREAD

**Issue by AxitaKathiriya** [tanersener/mobile-ffmpeg#604]
**Description**
FFprobe.getMediaInformation() return null and Android App crash when i try to get media duration. Any alternate solution is available for getting media information?

**Expected behavior**
I want to get media Information. Each and every time i want to get information of any media file instead of null.

**Current behavior**
Sometime FFprobe.getMediaInformation() return null and Android App crashes.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/54742470/99874884-3fb7ac00-2c11-11eb-8a8d-22421ca88b9d.PNG)

**Logs**
I/mobile-ffmpeg: Loading mobile-ffmpeg.
I/mobile-ffmpeg: Loaded mobile-ffmpeg-full-arm-v7a-neon-4.4-lts-20200803.
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.arthenica.mobileffmpeg.MediaInformation.getDuration()' on a null object reference

**Environment**
 - Platform: Android
 - Architecture: arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64
- Device Os : 4, 5, 6, 7, 8, 9, 10
 - Android Studio version : 3.5, 4.1

**Comment by AxitaKathiriya** [comment]
Please check i have updated issue according to your issue-template format.

**Comment by AxitaKathiriya** [comment]
Please check @tanersener.. I have updated issue according to your issue-template format.

**Comment by AxitaKathiriya** [comment]
Please check @tanersener.. I have updated issue according to your issue-template format. And please give me alternate solution. Thanks

**Comment by tanersener** [comment]
I need to be able to test your case in order to help you. But the information in your post is still not enough to make a comment or test it.
- Your post doesn't include anything about your input file. Is that a local file or a remote file with https schema?
- What is the API Level of your device?
- Those log lines are not helping at all. Is that all you have under `logcat`? If that's all, try to increase log severity using `Config.setLogLevel()`. We need more detailed logs to understand what's going on there.

**Comment by snti** [comment]
Hello @tanersener maybe my issue is related to AxitaKathiriya problem.

I just starting using this library, first of all, I tried to get info about a video using FFprobe.getMediaInformation method, but it returns null.

I tried with Uri and file.path

```
videoUri = content://[my app package].fileprovider/files/VID_2020_12_03_00_10_41_083.mp4
videoFile.getAbsolutePath() = /files/VID_2020_12_03_00_10_41_083.mp4

MediaInformation info = FFprobe.getMediaInformation(videoUri);
MediaInformation info2 = FFprobe.getMediaInformation(videoFile.getAbsolutePath());

info1 and info2 are null
```

AS 4.1.1
compileSdkVersion 29
Pixel 3aXL with android 11.
The video was taken with Camera2 Api

Thanks!

**Comment by tanersener** [comment]
@snti You don't need me to understand what is happening there. Logs tell you what the problem is: `Protocol not found`. `content:` is not a valid protocol. See https://ffmpeg.org/ffmpeg-protocols.html

**Comment by AxitaKathiriya** [comment]
Hello @tanersener i am using following command.

**Comment by AxitaKathiriya** [comment]
Hello @tanersener i am using following command.
Command :- -i videoPath -hide_banner

**Comment by AxitaKathiriya** [comment]
Hello @tanersener i am using below command. 
Command :- -i videopath -hide_banner

When i getting info using this command then command is fail with return code 1. 

Can you please tell me what is the meaning of return_code 1 ??

**Comment by iamkathy27** [comment]
Hi @tanersener, is there any update regarding this issue? I also encountered the same with @AxitaKathiriya. Is there also a way to parse the media information from Config.enableLogCallback in Json format? Thank you very much!

**Comment by tanersener** [comment]
If you have the full output you can use `MediaInformationParser.from()` method for parsing.

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
