### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by silvershort** [tanersener/mobile-ffmpeg#610]
**Description**
Thank you for providing a great library.

I need scoped storage
because support to android11

**Expected behavior**
https://github.com/tanersener/mobile-ffmpeg/pull/440
The PR should be released.

**Current behavior**
Android 11 has already been applied to the Pixel Phone.
Samsung phones are also in beta testing...

Can I get an approximate next release date?

**Screenshots**

**Logs**

**Environment**

**Other**

**Comment by tanersener** [comment]
Jan 2020 is the current plan.

**Comment by silvershort** [comment]
Thank you for answer.

**Comment by PaulWoitaschek** [comment]
Really looking forward to this. I'm relying on the published library for fdroid builds and need the SAF functionality.
