### ISSUE TITLE
Why the armeabi-v7a folder has a few more so files than the v8a folder after compilation, how can I filter it out?

### ISSUE THREAD

**Issue by androidGhost** [tanersener/mobile-ffmpeg#611]
Why the armeabi-v7a folder has a few more so files than the v8a folder after compilation, how can I filter it out?

**Comment by tanersener** [comment]
See [Android-NEON-Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Android-NEON-Support) wiki page.
