### ISSUE TITLE
How can I draw text with system fonts in iOS ?

### ISSUE THREAD

**Issue by VictorJi** [tanersener/mobile-ffmpeg#612]
**Description**
I wanna use drawtext to add subtitles to a video in iOS.
Can I use system fonts? Or I have to add a font file like .ttc to project resource?

**Environment**
 - Platform: IOS

**Comment by tanersener** [comment]
I only know that you can use `drawtext` without specifying a font name on `iOS`. I'm not sure whether you can use a system font name or not. You need to test it.

The following utility methods are available on `iOS` for registering fonts. They may help you with this.

`MobileFFmpegConfig.setFontDirectory`
`MobileFFmpegConfig.setFontconfigConfigurationPath`

**Comment by VictorJi** [comment]
I have tried use `drawtext` without specifying a font name.

```
NSString *command = [NSString stringWithFormat:@"-i %@ -vf \"drawtext=text='12121223123':x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2\" %@", videoPath, toPath];
int result = [MobileFFmpeg execute:command];
```
but get error 

Fontconfig error: Cannot load default config file
2020-12-03 10:22:41.742700+0800 XXXXXX[6305:1084245] ERROR: Cannot find a valid font for the family Sans
2020-12-03 10:22:41.743375+0800 XXXXXX[6305:1084245] ERROR: Error initializing filter 'drawtext'
2020-12-03 10:22:41.743672+0800 XXXXXX[6305:1084245] ERROR:  with args 'text=12121223123:x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2'
2020-12-03 10:22:41.743917+0800 XXXXXX[6305:1084245] ERROR:
2020-12-03 10:22:41.744102+0800 XXXXXX[6305:1084245] ERROR: Error reinitializing filters!

Do you have any suggestion? Thanks!

**Comment by tanersener** [comment]
It seems like it doesn't work without specifying a font. Have you tried setting one of the system fonts as font name?

**Comment by VictorJi** [comment]
Today I have tried several fonts.
 
Font Heiti 'STHeitiSC-Medium'
```
NSString *command = [NSString stringWithFormat:@"-i %@ -vf \"drawtext=font='STHeitiSC-Medium':text='12121223123':x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2\" %@", videoPath, toPath];
```
Heiti family 'Heiti TC'
```
NSString *command = [NSString stringWithFormat:@"-i %@ -vf \"drawtext=font='Heiti TC':text='12121223123':x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2\" %@", videoPath, toPath];
```
Font family 'PingFang SC'
```
NSString *command = [NSString stringWithFormat:@"-i %@ -vf \"drawtext=font='PingFang SC':text='12121223123':x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2\" %@", videoPath, toPath];
```
Font 'Helvetica'
```
NSString *command = [NSString stringWithFormat:@"-i %@ -vf \"drawtext=font='Helvetica':text='12121223123':x=10:y=30:fontsize=24:fontcolor=yellow:shadowy=2\" %@", videoPath, toPath];
```
But sadly none of them works.

**Comment by monurcevik** [comment]
Any updates? I'm having this issue as well. @VictorJi

**Comment by tanersener** [comment]
As far as I know `/System/Library/Fonts` and `/System/Library/Fonts/Cache` folders include the system fonts on `iOS`.

If you register `/System/Library/Fonts` as font directory then you will be able to use them in `FFmpeg` commands.
