### ISSUE TITLE
Get Statistics by Execution ID

### ISSUE THREAD

**Issue by JChappel** [tanersener/mobile-ffmpeg#618]
**Description**
Right now it appears the only way to get statistics is as they come in on the delegate callback. Is there a way to ad hoc a statistics call while passing an execution ID to get particular stats for that execution?

**Expected behavior**
Would like to get statistics by execution ID.

**Current behavior**
New Feature Request

**Screenshots**

**Logs**

**Environment**

**Other**

**Comment by tanersener** [comment]
No, there is not. Currently they're generated during the execution and we pass them in StatisticsDelegate/StatisticsCallback calls.

**Comment by JChappel** [comment]
Could this be a feature that is implemented in the future?

**Comment by tanersener** [comment]
Getting statistics requires saving statistics. And if library saves statistics its needs to define a mechanism to delete them too. You can not keep them in memory forever. That's the difficult part. Any suggestions about when to delete them or how to decide about deleting them?

**Comment by JChappel** [comment]
My thought was using MobileFFmpegConfig.getLastReceivedStatistics() call, but being able to pass an active Execution ID. But after the command is completed you could then delete the statistic.

In my project, I'm recording an RTSP stream to a local file, so I would like to be able to periodically check the statistics of the command. Once the command has been stoped I would no longer need access to the statistics and it could then be deleted. Right now I monitor the statisticsCalclback and watch for my Execution ID.

Not sure if that answers your question.

**Comment by tanersener** [comment]
Saving the last received statistics and deleting it when execution completes is possible. I'll mark this issue as enhancement.
