### ISSUE TITLE
Run static ffmpeg ends with cannot locate symbol "__sfp_handle_exceptions"

### ISSUE THREAD

**Issue by TRtomasz** [tanersener/mobile-ffmpeg#620]
**Description**
Run static ffmepg on android

**Expected behavior**
run it and read output

**Current behavior**
ends with an error
`CANNOT LINK EXECUTABLE "./ffmpeg": cannot locate symbol "__sfp_handle_exceptions"`
`readelf -Ws libc++_shared.so | grep __sfp_handle_exceptions`
returns no match

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: Android 11
 - Architecture: arm64
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by alexcohn** [comment]
How did you build your **ffmpeg**? Does it need **libc++_shared.so** at all?
