### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sanketkoladiya** [tanersener/mobile-ffmpeg#622]
I am getting UnsatisfiedLinkError on android 9 & 10  on release mode from the play store.Below is the crash I got 

**Dependencies**
implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS'

**Logs**

**java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/packagename-m1OXGa1yNNBlrEZSonabCg==/lib/arm64/libmobileffmpeg.so": 0**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:19)

**java.lang.UnsatisfiedLinkError:** 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1016)
  at java.lang.System.loadLibrary (System.java:1669)
  at com.arthenica.mobileffmpeg.Config.<clinit> (Config.java:133)
  at com.arthenica.mobileffmpeg.Config.nativeFFprobeExecute (Config.java)
  at com.arthenica.mobileffmpeg.FFprobe.execute (FFprobe.java:55)
  at com.arthenica.mobileffmpeg.FFprobe.getMediaInformationFromCommandArguments (FFprobe.java:123)
  at com.arthenica.mobileffmpeg.FFprobe.getMediaInformation (FFprobe.java:86)

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a,, arm64-v8a]
 - Android Studio version **4.1.1**
 - Android NDK version **22.0.7026061**

**Gradle Config**
android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'
    defaultConfig {
        applicationId "$ApplicatioId"
        minSdkVersion 16
        targetSdkVersion 29
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
        }
    }

   bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }
}

Any help will be appreciated, I am stuck between update the app on the play store.

**Comment by sanketkoladiya** [comment]
can anyone help me out with this error? this error is recently faced after I updated my app on playstore

**Comment by tanersener** [comment]
Stack trace included in your post is very generic. And, most of the time, a stack trace alone is not enough to understand what is wrong there. This is why we have #132. I suggest filling issue template fields when you create a issue.

Additionally, I suggest searching for similar issues before creating a new one.

**Comment by sanketkoladiya** [comment]
@tanersener  can you please check now, I really need help as I am stuck for the last 1 week on this issue, the last change I made was just updating the android studio version and NDK version

**Comment by iamkdblue** [comment]
@sanketkoladiya  are you using the Dynamic Feature module in your app?

**Comment by Olegasv** [comment]
@sanketkoladiya, I Think that problem with proguard rules. Try to disable (shrinkResources and  minifyEnabled) in your gradle. 
If it solved the problem, add this line in your proguard rules: 
-keep class com.arthenica.mobileffmpeg.** { *; }
