### ISSUE TITLE
Where to download Android prebuilt executable file?

### ISSUE THREAD

**Issue by yyan7223** [tanersener/mobile-ffmpeg#623]
**Description**
Hello! I want to download the prebuilt executable files for Android because I don't have linux machine to build it by myself...
I try to find it in page [https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.3.1](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.3.1) but failed..
Can anyone help build ffmpeg 4.3.1 executable file for Android?

Appreciate.

**Comment by tanersener** [comment]
This project doesn't provide prebuilt executables. Only libraries (shared or static libraries) are distributed.

**Comment by KnIfER** [comment]
I need executables too. 

You can get them via Termux. but termux doesn't support android4.4
