### ISSUE TITLE
Is using this library at risk when posting on Google Play?

### ISSUE THREAD

**Issue by vucong** [tanersener/mobile-ffmpeg#631]
I'm sorry if this question bothers you.
I am new to application development, I love this your library and want to use it. I don't know when using and putting it on google play is there any risk related to suspend, remove or reject are not ?

**Comment by tanersener** [comment]
I don't know what you're asking. If you have concerns about the license or the patents please have a look at these two wiki pages: [Patents](https://github.com/tanersener/mobile-ffmpeg/wiki/Patents), [License](https://github.com/tanersener/mobile-ffmpeg/wiki/License ).
