### ISSUE TITLE
Add support for arm64 iOS Simulator on Mac with Apple Silicon chip

### ISSUE THREAD

**Issue by salpieiev** [tanersener/mobile-ffmpeg#632]
**Description**
It's impossible to use Mobile FFMpeg framework on iOS Simulator on Mac with Apple Silicon chip. Resulting framework contains arm64 binary for iphoneos platform, but it doesn't fit for iphonesimulator platform.

**Expected behavior**
ios.sh script is able to build XCFramework with iphonesimulator arm64 architecture

**Current behavior**
XCode complains that Mobile FFMpeg framework is built for different platform (iPhoneOS), but attempt is made to use it on iPhone Simulator platform

**Screenshot**
<img width="392" alt="Screenshot 2020-12-27 at 22 29 48" src="https://user-images.githubusercontent.com/1250605/103179301-45995080-4893-11eb-9917-d2e4e04321e3.png">

**Environment**
 - Platform: Mac with Apple Silicon
 - Architecture: arm64
 - Source branch: master
 - Xcode version: 12.3

**Comment by IshchenkoAndriy** [comment]
Any updates?

I have the same problem.

**Comment by confucious** [comment]
Root issue: https://github.com/tanersener/mobile-ffmpeg/issues/597
