### ISSUE TITLE
build mobile-ffmpeg: failed

### ISSUE THREAD

**Issue by vevev** [tanersener/mobile-ffmpeg#637]
**Description**
build mobile-ffmpeg: failed

**Current behavior**
build mobile-ffmpeg: failed

**Logs**
INFO: Completed build for x86-64 on API level 21 at Wed 30 Dec 2020 08:08:46 PM +07

[armeabi-v7a] Compile arm    : mobileffmpeg <= mobileffmpeg.c
[armeabi-v7a] Compile arm    : mobileffmpeg <= mobileffprobe.c
[armeabi-v7a] Compile arm    : mobileffmpeg <= android_lts_support.c
[armeabi-v7a] Compile arm    : mobileffmpeg <= mobileffmpeg_exception.c
[armeabi-v7a] Compile arm    : mobileffmpeg <= fftools_cmdutils.c
jni/../app/src/main/cpp/fftools_cmdutils.c:361:79: error: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
        *(int64_t *)dst = parse_number_or_die(opt, arg, OPT_INT64, INT64_MIN, INT64_MAX);
                          ~~~~~~~~~~~~~~~~~~~                                 ^~~~~~~~~
/home/nqv/Android/Sdk/ndk/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:188:27: note: expanded from macro 'INT64_MAX'
#define INT64_MAX        (INT64_C(9223372036854775807))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nqv/Android/Sdk/ndk/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:147:27: note: expanded from macro 'INT64_C'
#  define INT64_C(c)      c ## LL
                          ^~~~~~~
<scratch space>:128:1: note: expanded from here
9223372036854775807LL
^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/home/**/Android/Sdk/ndk/android-ndk-r22/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/mobileffmpeg/fftools_cmdutils.o] Error 1

**Environment**
 - Platform: Android
 - Architecture: x86_64
 - Source branch (if applicable) master
 - Android Studio version (if applicable) 4.1.1
 - Android NDK version (if applicable) r22

**Comment by programmerLifeJourney** [comment]
If you don't need x86_64 arch try run script with "--disable-x86-64".
Give me same error on Linux Ubuntu 18, NDK- r21d, SDK 23

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit). This issue is fixed there.
