### ISSUE TITLE
Is use this library in android Free app require any attribute or licences link in app  for posting on Google Play?

### ISSUE THREAD

**Issue by Naresh95375** [tanersener/mobile-ffmpeg#645]
hey sir,
Please explain the required step for licenses in use this library in my android free app
in my app just simple command use for trim video

i use this implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.4.LTS'  in my android app

**Comment by tanersener** [comment]
See [Patents](https://github.com/tanersener/mobile-ffmpeg/wiki/Patents) and [License](https://github.com/tanersener/mobile-ffmpeg/wiki/License) wiki pages.
