### ISSUE TITLE
Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by rabelhmd** [tanersener/mobile-ffmpeg#647]
**Description**
libx264 encoder not build in **'mobile-ffmpeg-full', '~> 4.4'** iOS. So, how can I able to use the libx264 encoder?

**Expected behavior**
Previously I installed mobile-ffmpeg-full 4.3.1 where I could use the libx264 but once I upgrade the mobile-ffmpeg-full 4.4 the libx264 encoder not found error is occurring. 

**Current behavior**
Command:
**-y -hide_banner -i IMG_3266.MOV -vf scale=540:960 -f mov -acodec aac -crf 24 -vcodec libx264 -profile:v high -pix_fmt yuv420p -color_range 2 output.mov**

**Logs**
(https://pastebin.ubuntu.com/p/VrpjVkpMN4/)

**Environment**
 - Platform: iOS
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version **'mobile-ffmpeg-full', '~> 4.4'**

**Comment by rishabhshukla7** [comment]
use this 
implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.4'
I will surely help You.

**Comment by rabelhmd** [comment]
@rishabhshukla7 required platform is iOS not Android.

**Comment by tanersener** [comment]
@rabelhmd Have you read the README? You're using the `full` package and `full` package does not include `x264`. Only `GPL` licensed packages has `x264`. You need to use one of them as @rishabhshukla7 pointed out.

**Comment by rajgupta93** [comment]
> use this
> implementation 'com.arthenica:mobile-ffmpeg-min-gpl:4.4'
> I will surely help You.

can you help me my source code don't work in android 10
