### ISSUE TITLE
support for ffmpeg-gl-transition

### ISSUE THREAD

**Issue by bhavesh-hirpara** [tanersener/mobile-ffmpeg#65]
Can you compile using this?
https://github.com/transitive-bullshit/ffmpeg-gl-transition

**Comment by tanersener** [comment]
It is not possible to build some of the dependencies. For example `glfw` does not have an Android port and it is not possible build it from source for Android.

Moreover, this filter mainly targets desktop operating systems. Creating a mobile fork i.e. `mobile-ffmpeg-gl-transition` and depending on system libraries is a better approach. `Android` already has `EGL` and `OpenGL` support. So `gl-transition` filter can use them without compiling. But for IOS, there is not an easy solution. `Metal` framework should be used for OpenGL and this means filter needs to be rewritten completely which I don't want to do.

So it is not an easy task for me right now. Maybe you should ask the author of `ffmpeg-gl-transition` to do that?
