### ISSUE TITLE
TOOLCHAIN test is missing from build/android-x265.sh

### ISSUE THREAD

**Issue by juha-h** [tanersener/mobile-ffmpeg#651]
**Description**
TOOCHAIN test is missing from build/android-x265.sh

**Expected behavior**
If not defined, I would expect an error message like
```
if [[ -z ${TOOLCHAIN} ]]; then
    echo -e "(*)  TOOLCHAIN not defined\n"
    exit 1
fi
```

**Current behavior**
```
The CMAKE_C_COMPILER:

    /opt/Android/ndk/21.1.6352462//toolchains/llvm/prebuilt//bin/aarch64-linux-android24-clang

  is not a full path to an existing compiler tool.
```

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform: [e.g. Android/IOS]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version (if applicable) [e.g. v1.2]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Xcode version (if applicable) [e.g. 7.3.1, 9.0.1]
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) [e.g. 3.1]
 - Android NDK version (if applicable) [e.g. 16b, 17c]

**Other**

**Comment by tanersener** [comment]
Why should we do that? `TOOLCHAIN` is defined in `android.sh`, at [this line](https://github.com/tanersener/mobile-ffmpeg/blob/master/android.sh#L805). And it is not the only environment variable used by build scripts under the `build` folder. If I start checking all of them it will be a very long list.

**Comment by juha-h** [comment]
Fine, I was building only x265 and therefore met the issue.
