### ISSUE TITLE
Downloading GPL library x265 failed

### ISSUE THREAD

**Issue by juha-h** [tanersener/mobile-ffmpeg#653]
I cloned mobile-ffmpeg tag V4.4.LTS.  It tries to download non-existing x265 library file from bitbucket:
```
DEBUG: x265 library package not found. Downloading from https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 

INFO: Failed to download https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz to /usr/src/libbaresip-android/mobile-ffmpeg/.tmp/x265_3.4.tar.gz, rc=22. DEBUG: Build will continue.

INFO: Downloading GPL library x265 failed. Can not get library package from https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz
```
Master version downloads x265 from github and it succeeds.

LTS downloads should be reliable.  How about changing the site from bitbucket to github?

**Comment by tanersener** [comment]
I'm not updating the release tags unless there is a critical bug inside. This is a minor issue. And `master` already has the fix. Please use the `master`, it is identical to `v4.4` and `v4.4.LTS`.

**Comment by juha-h** [comment]
OK, will use master then.  Just thought to use something that is stable, since I'm going to include your project inside mine (baresip-studio) and there the builds are done automatically by F-Droid.

One possibility might be to introduce a stable branch (not tag) that can be updated when bugs are discovered.

**Comment by tanersener** [comment]
> One possibility might be to introduce a stable branch (not tag) that can be updated when bugs are discovered.

We're using `master` for that.
