### ISSUE TITLE
Creating Android archive under prebuilt/android-aar: failed

### ISSUE THREAD

**Issue by Random017** [tanersener/mobile-ffmpeg#658]
**Description**
I use the virtual machine, centos7, to compile the project but it happened 
`Creating Android archive under prebuilt/android-aar: failed`

**Expected behavior**
Creating Android archive under prebuilt/android-aar: ok

**Current behavior**
What happened.

**Screenshots**

**Logs**

```
Building mobile-ffmpeg LTS library for Android

Architectures: arm-v7a, arm-v7a-neon, arm64-v8a
Libraries: android-zlib, android-media-codec, cpu-features, x264, x265

Building arm-v7a platform on API level 16

x264: ok
x265: ok
cpu-features: ok

ffmpeg: ok

Building arm-v7a-neon platform on API level 16

x264: ok
x265: ok
cpu-features: ok

ffmpeg: ok

Building arm64-v8a platform on API level 21

x264: ok
x265: ok
cpu-features: ok

ffmpeg: ok

mobile-ffmpeg: ok


Creating Android archive under prebuilt/android-aar: failed
```

**Environment**
 - Platform: [VM Centos7 Android]
 - Architecture: [arm-v7a, arm-v7a-neon,  arm64]
 - Version (if applicable) [e.g. v4.4]
 - Source branch (if applicable) [master]
 - Android NDK version (if applicable) [ndk/21.0.6113669]

**Other**

According to the problems and solutions in issues, I have configured `ANDROID_HOME` and `ANDROID_NDK_ROOT`
but it still failed

**Comment by tanersener** [comment]
Have you looked at `build.log` file? 

I also see that you use an older NDK version. Master was built using the latest NDK LTS version `21.3.6528147`. I suggest using that version to build the `master`.
