### ISSUE TITLE
Unable to create appbundel using this library in other module 

### ISSUE THREAD

**Issue by iukust3** [tanersener/mobile-ffmpeg#659]
**Description**
Hi i have a dynomic feature module which is using this library the name of  his is "android10" when i want to create appbundel its show below error :
"All modules with native libraries must support the same set of ABIs, but module 'base' supports '[ARMEABI_V7A]' and module 'android10' supports '[X86, ARMEABI_V7A, X86_64, ARM64_V8A]'."
How i can solve this problem

**Comment by iukust3** [comment]
@monkeywithacupcake  @alexcohn @Javernaut @hannesa2

**Comment by hannesa2** [comment]
An easy step is to add in your `android10`

```
android {
    defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
}
```
to make it work, but I would at least add `arm64-v8a` to your `base` to have 64 bit as well. Playstore forces it too.

When you show your code, it's probably easier to help
