### ISSUE TITLE
[IOS] Long linking time

### ISSUE THREAD

**Issue by skrew** [tanersener/mobile-ffmpeg#66]
**Description**
Linking is - very - long (almost 15-20 secs) on a MBP 2018 with 32gb ram / core i9

**Expected behavior**
Linking must take a few seconds

**Environment**
 - Platform: iOS
 - Architecture: [x86_64, arm64]
 - Version 4.2
 - Source branch master
 - Xcode version 10.1

I'm using self build ffmpeg / libass (...) libs, linking take a few seconds.
But with almost the same ffmpeg config and your libs, linking take a very long time... Too many to works with (full linking is made every time you edit the code)

This is the configure line i used:

```./ios.sh --speed --enable-gpl --disable-armv7 --disable-armv7s --disable-arm64e --disable-i386 --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-coreimage --enable-ios-videotoolbox --enable-gnutls --enable-libass``` 

Any idea ?

**Comment by skrew** [comment]
Maybe adding a switch so, while dev, we use optimised linking time and for release the optimised size ? With a tool like fastlane it's easy to do something like that.

BTW thanks, i will try the 3.x

**Comment by tanersener** [comment]
According to `App Store File Sizes` table inside `App Store Connect`, there is no size difference between using `link-time-optimizations` or not. So I republished `v4.2` binaries without link-time optimizations. Can you clean your `pod cache` and try again?

**Comment by tanersener** [comment]
This issue is fixed in [v4.2](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.2) and [v4.2.LTS](https://github.com/tanersener/mobile-ffmpeg/releases/tag/v4.2.LTS) releases. Please create a new issue if you still have errors.
