### ISSUE TITLE
libx264 for option vcodec not found even using 'full-gpl'

### ISSUE THREAD

**Issue by Duna** [tanersener/mobile-ffmpeg#665]
**Description**
I have downloaded the sample application with package id: com.arthenica.mobileffmpeg.test and I modified the gradle file accordingly to the Readme to have libx264 vcodec included: implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.4' or implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.4.LTS'

**Expected behavior**
When I execute the command -version the codec libx264 should be present in the lib
Command used: `-i /storage/emulated/0/DCIM/Camera/20210125_193031.mp4 -vcodec libx264 -c:a copy /storage/emulated/0/DCIM/Camera/file.mp4`

**Current behavior**
libx264 is missing

**Screenshots**
[file](https://photos.app.goo.gl/WzpbwdVRA9xGSrQA9)

**Logs**
Parsing a group of options: output url /data/user/0/com.arthenica.mobileffmpeg.test/files/video.mp4.
Applying option map (set input stream mapping) with argument [video].
Applying option c:v (codec name) with argument libx264.
Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 30.
Successfully parsed a group of options.
Opening an output file: /data/user/0/com.arthenica.mobileffmpeg.test/files/video.mp4.
**Unknown encoder 'libx264'**

**Environment**
 - Platform: Android 11
 - Architecture: Samsung Galaxy S20+
 - Version (if applicable) [e.g. v1.2]
 - Source branch: main (master)
 - Android Studio version: 4.1.2

**Other**

**Comment by Duna** [comment]
`-i /storage/emulated/0/DCIM/Camera/20210125_193031.mp4 -vcodec libx264 -c:a copy /storage/emulated/0/DCIM/Camera/file.mp4` - command used

**Comment by tanersener** [comment]
Your screenshot and your logs don't match. If you're running the test app, I suggest testing `x264` encoding from the `video` tab. It will tell you whether `x264` is there or not.

**Comment by Duna** [comment]
Is there a mapping from linux based ffmpeg command line and this library?

**Comment by tanersener** [comment]
This project uses the same source code as the linux `ffmpeg`. It's not the issue here.

Moreover, I tested your command and didn't get an error. I don't know how you set your command, it might be an issue about it.

**Comment by Duna** [comment]
I just paste it in the sample project in the first fragment

**Comment by Duna** [comment]
here it is a [screenshot](https://photos.app.goo.gl/8cW5N46cxNCQDC6Z7)

**Comment by tanersener** [comment]
Do you paste the command into the text box on the fragment when your emulator is running?

**Comment by Duna** [comment]
Nevermind, I succeeded d

**Comment by lexluthors** [comment]
> Nevermind, I succeeded :)

I also encountered the same problem, how did you solve it?
