### ISSUE TITLE
How to preview stream video?

### ISSUE THREAD

**Issue by haitrvn** [tanersener/mobile-ffmpeg#67]
Your FFmpeg build so amazing!
I try to play video stream with this command (windows version), look like this:
Windows:
$ffplay rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
Android / Java: 
???

on your tutorial just talk about ffmpeg command only,like this:
Windows
$ffmpeg -i file1.mp4 -c:v mpeg4 file2.mp4
Android / Java:
 FFmpeg.execute("-i file1.mp4 -c:v mpeg4 file2.mp4");

So how do i use "ffplay" command and how do i get execution output to preview?

**Comment by tanersener** [comment]
Unfortunately, `ffmpeg` binaries, including `ffplay`, are not included in `mobile-ffmpeg` right now and it is not possible to stream audio/video.

**Comment by tanersener** [comment]
I use [VideoView](https://developer.android.com/reference/android/widget/VideoView) and [MediaController](https://developer.android.com/reference/android/widget/MediaController) to play videos in my Android test application. It is possible to stream videos with them too. I guess you don't want to use them, right?

**Comment by haitrvn** [comment]
yeah! because i'm looking for some build like VLC player - play video -  live video(rtsp/rtmp/hls...)

**Comment by calicratis19** [comment]
If we build ffmpeg with enable-ffplay then will it be possible to use ffplay with this proejct? Thanks very much for your contribution.

**Comment by tanersener** [comment]
Unfortunately no, you can't build `ffplay`.

**Comment by calicratis19** [comment]
Can you please explain why? At least a hint so that I can check myself for a solution. Will really appreciate that.

**Comment by tanersener** [comment]
Build scripts fail when you enable `ffplay`. I'm not sure about the reason so I can't explain why. You can try and see it yourself.
