### ISSUE TITLE
Error with -abort_on empty_output_stream

### ISSUE THREAD

**Issue by buntupana** [tanersener/mobile-ffmpeg#671]
**Description**
Experiencing a failed encoding when I use `-abort_on empty_output_stream` but everything is fine when I use `-abort_on empty_output`

**Expected behavior**
Execute the command as it should

**Current behavior**
The execution will throw result with code 1 with this command:
`-y -i example.mp4  -filter_complex "[0:v] pad=iw:'if(gt(iw, ih), iw, ih)':(ow-iw)/2:(oh-ih)/2, crop=iw:iw, scale=-1:480, setsar=1 [clip0]; [0:a] anull [audio0]; [clip0][audio0] concat=n=1:v=1:a=1 [v][a]" -map '[v]' -map '[a]' -c:a aac -c:v h264 -crf 18 -r 30 -preset veryfast -loglevel warning -abort_on empty_output_stream out.mp4`

**Logs**
```
 [ @ 0x7aebbdc180] [Eval @ 0x7aebbdbaf0] Undefined constant or missing '(' in 'empty_output_stream'
 [ @ 0x7aebbdc180] Unable to parse option value "empty_output_stream"
 Failed to set value 'empty_output_stream' for option 'abort_on': Invalid argument
 Error parsing global options: Invalid argument
```

**Environment**
 - Platform: Android
 - Version (if applicable) 4.4.LTS
 - Android Studio version (if applicable) 4.1.2
 - Android NDK version (if applicable) 22.0

**Comment by tanersener** [comment]
This issue happens because our [fftools_ffmpeg_opt.c](https://github.com/tanersener/mobile-ffmpeg/blob/v4.4.LTS/android/app/src/main/cpp/fftools_ffmpeg_opt.c#L225-L226) is a bit outdated. `empty_output_stream` is not one of the options we have there right now. We must update this file from `ffmpeg` upstream.

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit). This issue is fixed there.
