### ISSUE TITLE
Cant Create Video with Image

### ISSUE THREAD

**Issue by Jigneshpf** [tanersener/mobile-ffmpeg#679]
**Description**
Hello, I want to replace green color with image in video template. But i cant get proper output video.
I used below command for it 
I already upload a video template and i want to add image for specific area.
If anyone have an idea then please share with me.

("-i&"  + Activity_Progress.this.y + "&-i&" + Activity_Progress.file_path + "&-filter_complex&[0:v]scale=480x800,setdar=3:5,colorkey=0x00d900:0.4:0.3[ckout];[1:v]scale=" + 480 + "x" + 800 + ",setdar=3:5[bg];[bg][ckout]overlay[out]&-map&[out]&" + Activity_Progress.outputPath).split("&");

**Environment**
 - Platform: [Android]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64
 - Android Studio version [ 4.1.1]
 - Android NDK version [22.0.7026061]

https://user-images.githubusercontent.com/42066282/108025778-24600f80-704d-11eb-95cb-e2fc2589746b.mp4

**Comment by subhantariq33** [comment]
I have same issue my FFMPEG command is:
[-y, -r, 1/2, -i, slide_%05d.jpg, -vcodec, libx264, -r, 2, -pix_fmt, yuv420p, -preset, ultrafast, /video_25_02_2021_17_53_17.mp4]
