### ISSUE TITLE
reduce size of apk

### ISSUE THREAD

**Issue by m-moradi** [tanersener/mobile-ffmpeg#685]
hello
I use this library just for  save hls stream video and sound to android storage no more.
I add **com.arthenica:mobile-ffmpeg-min:4.4.LTS** to gradle 
but when I get release version of my application size of that is **41 MB** most of this size is for FFMPGE
how can I reduce size of apk?

**Comment by PaulWoitaschek** [comment]
Make use of [App Bundles](https://developer.android.com/platform/technology/app-bundle)
