### ISSUE TITLE
Android: How to pipe videochunks (from MediaRecorder)

### ISSUE THREAD

**Issue by athlyzer-janos** [tanersener/mobile-ffmpeg#689]
**Description**
I get videochunks h264 encoded (Browser delivers them from MediaRecorder.ondataavailable via websockets to my local server on an android phone).
Thy are sent as ByteBuffer.

I read the wiki about pipe (Runtime.getRuntime().exec(new String[]{"sh", "-c", "cat <image path> > " + pipe1});

How can i pipe these chunks (ByteBuffer) to the ffmpeg process?

**Expected behavior**
On windows and mac (electron) this appoach worked like a charm

**Current behavior**
invalid data

**Screenshots**

**Logs**

**Environment**
 - Platform: [e.g. Android/IOS]

**Other**
`String pipe = Config.registerNewFFmpegPipe(this.getActivity());
String ffmpegCommand = "-i " + pipe  + " -c:v copy -c:a aac -strict -2 -ar 44100 -b:a 64k -y -use_wallclock_as_timestamps 1 -async 1 -bufsize 1000 -max_muxing_queue_size 9999 " + this.outputPath + outputFilename + ".m3u8";
FFmpeg.execute(ffmpegCommand)

  public void onMessage(WebSocket conn, ByteBuffer videoChunk) {
          Runtime.getRuntime().exec(new String[]{"sh", "-c",  ???? > " + pipe});
}`

**Comment by athlyzer-janos** [comment]
by the way: thank you so much for mobile-ffmpeg, it's amazing

**Comment by tanersener** [comment]
`pipe` is a path. You need to open it as a file and write your video chunks into it.
