### ISSUE TITLE
Android 10: Permission denied

### ISSUE THREAD

**Issue by jansvanda** [tanersener/mobile-ffmpeg#697]
**Description**
When running a command 

`-i /storage/emulated/0/DCIM/Camera/VID_20210311_160728.mp4 -i /sdcard/DCIM/mockup.png -filter_complex...`

on a real device or emulator, the logcat says 
`E/mobile-ffmpeg: /storage/emulated/0/DCIM/Camera/VID_20210311_160728.mp4: Permission denied`

i inserted even those two permissions in manifest
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

I included this lib offline inside the lib folder and added
```
    App: implementation(name:'mobile-ffmpeg-full-4.4', ext:'aar')
    
    Project:         flatDir { dirs 'libs' }

```

**Expected behavior**
Run without Error

**Current behavior**
Permission denied error

**Screenshots**
![image](https://user-images.githubusercontent.com/23197316/111157215-eba54e80-8596-11eb-835f-f0dd572735d5.png)

**Environment**
 - Platform: Android 10-11

Thanks in advanced for any help

**Comment by AsynctaskCoffee** [comment]
android:requestLegacyExternalStorage="true" (in manifest) have you tried this ?

**Comment by jansvanda** [comment]
> android:requestLegacyExternalStorage="true" (in manifest) have you tried this ?

Yeah tried several times, Thought that would definitely clear it, but no .....

**Comment by AsynctaskCoffee** [comment]
You ve declared these permissions inside manifest which is ok but you should also declare runtime permissions (+6.0) inside your java or kotlin code, have you declared them too?

**Comment by jansvanda** [comment]
Oh yeah that was it!!! Thanks a ton!
  ```
 private fun requestPermission() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            requestPermissions(
                arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
                REQUEST_WRITE_PERMISSION
            )
        } else {
            Log.i(Config.TAG, "Shit permissions.")

        }
    }
```

**Comment by AsynctaskCoffee** [comment]
You re welcome 👍🏻

**Comment by 67defalt** [comment]
Hello,
Unfortunately none of these solutions are working for me.
What I did so far :
* Add permissions to manifest
* Add android:requestLegacyExternalStorage="true to manifest
* Add runtime permission (no permission asked because I granted them)

The file I'm trying to read is a file named 'in.mp3' located in /storage/emulated/0/Download

What should I do please ?
Thanks.

**Comment by jansvanda** [comment]
> Hello,
> Unfortunately none of these solutions are working for me.
> What I did so far :
> 
> * Add permissions to manifest
> * Add android:requestLegacyExternalStorage="true to manifest
> * Add runtime permission (no permission asked because I granted them)
> 
> The file I'm trying to input is a file named 'in.mp3' located in /storage/emulated/0/Download
> 
> I still get « permission denied »
> 
> What should I do please ?
> Thanks.

How do you reference the file? What is the file path you pass?
