### ISSUE TITLE
Overlay enable not working in ios FFMPEG 4.4 (tried all versions)

### ISSUE THREAD

**Issue by divyeshdobariya** [tanersener/mobile-ffmpeg#698]
I tried so many times . Android run same code is working fine but in ios that is not working perfectly..

Here is some code that i want to make the video

"-i \(img0) -i \(img1) -i \(img2) -i \(img3) -i \(bgPath) -i \(first) -filter_complex \"[4]split=2[color][alpha];[color]crop=iw/2:ih:0:0[color]; [alpha]crop=iw/2:ih:iw/2:0[alpha]; [color][alpha]alphamerge[ovrly]; [0]scale=540:960[0_scalled]; [1]scale=540:960[1_scalled]; [2]scale=540:960[2_scalled]; [3]scale=540:960[3_scalled]; [5][0_scalled]overlay=enable=\'between=(t,0,3.4)'[v1]; [v1][1_scalled]overlay=enable=\'between=(t,3.4,6.8)'[v2]; [v2][2_scalled]overlay=enable=\'between=(t,6.8,10.7)'[v3]; [v3][3_scalled]overlay=enable=\'between=(t,10.7,15)'[v4]; [v4][ovrly]overlay=0:0[final_video]\" -map [final_video] -map 4:a -t 15 \(outputPath)"

I tried this code , it gives only first image output in video .

Second , third & fourth image not showing in the video , even i add time on overlay function . please help me

Thanks

**Comment by divyeshdobariya** [comment]
Any update ???

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
