### ISSUE TITLE
How to APK size Decreased My App is Video to Mp3 Converter and Ringtone Maker (Mp3 Trim)

### ISSUE THREAD

**Issue by sureapps** [tanersener/mobile-ffmpeg#699]
I have add dependency

dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-audio:4.4-LTS'
}

Output APK or AAB file size is 40MB but when I find on playstore related my application then size is 5 MB to Max 7 MB So how to remove unnecessary library or module in my application.

**Comment by rajgupta93** [comment]
hey my is not working in android 10 can you help me?

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
