### ISSUE TITLE
Does this allow access to raw video?

### ISSUE THREAD

**Issue by connormeaton** [tanersener/mobile-ffmpeg#703]
I have a general question. I am wondering what kind of access this library provides to the android video camera. If I run:

```"FFmpeg.execute(-f android_camera -i 0:0 -c:v libx264 -r 30 -crf 0 -pixel_format yuv420p -t 00:00:02 output.mp4")```

Then which of the following is happening:

a.) The command calls raw video to be recorded and encodes raw, uncompressed video according to the specifications in the above command.

-- OR --

b.) The command calls video to be recorded which is automatically encoded based on some low-level design on the device that I can't change, and then the `execute()` function further encodes the video according to the specifications.

Essentially, I am trying to improve the video quality compared to out-of-the-box android video recording by setting CRF to 0. If this setting is applied to raw video, then that solves my problem, but if it is applied to already compressed video, then it does not solve my problem. 

Thanks!

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
