### ISSUE TITLE
Unrecognized option 'x265-params'

### ISSUE THREAD

**Issue by chesschi** [tanersener/mobile-ffmpeg#711]
I have downloaded the mobile-ffmpeg-full-gpl-4.4.aar file and imported it to the Android Studio. When I run the `FFmpeg.execute` with "-x265-params" as one of the parameters in the command, it shows the following error. May I know if mobile-ffmpeg supports x265-params? Many thanks!

`Unrecognized option 'x265-params'`

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
