### ISSUE TITLE
Get executionId

### ISSUE THREAD

**Issue by VivekThummar52** [tanersener/mobile-ffmpeg#714]
Hey there, i'm using this lib from around one and a half year and all was working fine until today because now i want to execute multiple command simultaneously and also wants to cancel/stop some of them on button click but i can't find the way to do that because as of my research we need `executionId` to do that and i can't find method `FFmpeg.executeAsync(.....)`(according to `README` file).

I'm using ffmpeg version `ffmpeg-full-gpl:4.2.2.LTS'` for my requirenment and i want to cancel specific ongoing ffmpeg execution and it's my requirement. Please try to help me as soon as possible..Thank you!!!

**Comment by tanersener** [comment]
Asynchronous API methods and `executionId` was introduced in `v4.4`. You can't use them with earlier versions.

**Comment by VivekThummar52** [comment]
Ok, Thanks for reply and i just changed my old version to new `v4.4.LTS` and if i got any problem in my old ffmpeg operations i will ask for your help, Thank you very much!!!
