### ISSUE TITLE
[Android] Android 11 compatibility

### ISSUE THREAD

**Issue by jseisson** [tanersener/mobile-ffmpeg#716]
I merged an image with a video all seems good except for Android 11.

The only output i have is : mobile-ffmpeg: /storage/emulated/0/Movies/video_to_share.mp4: File exists

When i check if the file exist before FFmpeg.executeAsync, the file.exist() return false. The uri of my file is provided by the Media API. Because i want to share the video after the merging.

Here is my command : 

-y -i /storage/emulated/0/Android/data/com.package.app/files/Movies/original_video.mp4 -i /storage/emulated/0/Android/data/com.package.app/files/Pictures/filigrane.png -filter_complex "[1:v] scale=1080:1920 [ol], [0:v] [ol] overlay" -vcodec libx264 -crf 27 -preset ultrafast -strict -2 /storage/emulated/0/Movies/video_to_share.mp4

Is it possible to be any issue with the new restriction and scoped storage for Android 11 ?

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
