### ISSUE TITLE
[Linux: ARM64 ] Support for statically linked executable w/Android (camera/mediacodec) 

### ISSUE THREAD

**Issue by gWOLF3** [tanersener/mobile-ffmpeg#73]
**Description**

I am trying to compile a statically linked executable file for ARM64 architecture. Rather than defaulting to using the standard (Android NDK) runtime libraries — libc++_shared.so, I would like to instead tell the linked to expect libc++.so as the runtime library. 

**Environment**
 - Platform: Linux 
 - Architecture: arm64-v8a
 - Version: latest
 - Source branch: master
 - Xcode version: Xcode 10.1
 - Android NDK Pkg.Revision = 18.0.5002713

**Details**

For both configurations (see below) I run the following command to build ffmpeg: 

```
./android.sh --debug --enable-gpl --disable-arm-v7a --disable-arm-v7a-neon --disable-x86 --disable-x86-64 --enable-android-media-codec --enable-x264 --reconf-LIBRARY
```

I have edit the build/android-ffmpeg.sh configure script a bit: 

./configure \.... 

1) 
```
removed: disable-programs \ (so that it would generate an executable
added: enable-static \ (to allow for static linking)
added: enable-indev=android_camera \ (for android camera device support) 
```

Build static executable successfully: 

`ffmpeg: ELF 64-bit LSB pie executable ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped`

However, after adb push to /system/bin, I can run directly from adb shell but results in following linage error:

CMD:
 ```ffmpeg -version```

RESULT:
``` 
CANNOT LINK EXECUTABLE "ffmpeg": library "libc++_shared.so" not found
```
 
It seems to not be able to find the c++ runtime libraries to link to. 

In the /system/lib64 directory, I can see the cpp runtime for ARM64 — libc++.so
However, it seems to be looking for libc++_shared.so. 

I have also attempted to just take the NDK's libc++_shared.so (located in $ANDROID_NDK_HOME/toolchains/mobile-ffmpeg-api-28-aarch64/aarch64-linux-android/lib/libc++_shared.so) and push that to /system/bin of device (which is, by default, in the PATH). This did not fix the issue and it was still unable to locate the file. 

**Attempt to Fix**

To resolve this, Instead of specifying the target-os=android, I tried specifying the target-os=linux — this, in hopes of letting the linker know that at runtime. 

```
removed: disable-programs \ (so that it would generate an executable
removed: enabled-shared \ (do not want building of shared libraries
added: disable-shared \ ""
added: enable-static \ (to allow for static linking)
added: enable-indev=android_camera \ (for android camera device support) 
added: target-os=linux \ (to let the linker know -- i thought -- to use system/lib64/ runtime libs instead)
```

if we set configuration options to "disable-shared" and "enable-static", 
I get the following, which I suspect is incorrect: 

```
At least one library type must be built.
Specify --enable-static to build the static libraries or --enable-shared to
build the shared libraries as well. To only build the shared libraries specify
--disable-static in addition to --enable-shared. 
```

Setting '--target-os=linux' without disabling-shared results in: 
```
aarch64-linux-android-gcc is unable to create an executable file.
C compiler test failed.
```

**Comment by tanersener** [comment]
Hi @gWOLF3,

Can you try using `APP_STL := c++_static` in `android/jni/Application.mk` file?

**Comment by gWOLF3** [comment]
Update: WIP

1) In the build_application_mk() function inside of android.sh, we set APP_STL := c++_static. 

This should tell our app to use a static runtime as documented in NDK: 
https://developer.android.com/ndk/guides/cpp-support#runtimes

2) We also tried replacing the libc++_shared references in the build/android-common.sh file with libc++_static. 

3) '--target-os=android' should be correct

**Comment by gWOLF3** [comment]
New error but making progress: 

@ghostbin
https://ghostbin.com/paste/ern3u

**Comment by gWOLF3** [comment]
After removing `--debug` option, the compilation completes successfully, however, after pushing to device over adb bridge, and running the executable, I get the following error: 

```CANNOT LINK EXECUTABLE "ffmpeg": cannot locate symbol "glob" referenced by "/system/bin/ffmpeg"...```

Running `file ffmpeg` yields the following: 

```ELF shared object, 64-bit LSB arm64, dynamic (/system/bin/linker64), for Android 28, built by NDK r18 (5002713), stripped```

**Comment by tanersener** [comment]
I tested the same steps with NDK r18 and r19. Both binaries worked successfully. Below you can see the `-devices` output. 

Unfortunately I don't have an `arm64` device, so an `x86` simulator was used for tests. Can you repeat your tests on a Simulator with a lower API level like 26.

```
/data/local/tmp # ./ffmpeg -devices                                                                                                                                               
ffmpeg version v4.2-dev-480 Copyright (c) 2000-2018 the FFmpeg developers
  built with Android (4751641 based on r328903) clang version 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) (based on LLVM 7.0.2svn)
  configuration: --cross-prefix=i686-linux-android- --sysroot=/Users/taner/Library/Android/sdk/android-ndk-r18b/toolchains/mobile-ffmpeg-api-28-i686/sysroot --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/android-x86/ffmpeg --pkg-config=/usr/local/bin/pkg-config --enable-version3 --arch=i686 --cpu=i686 --target-os=android --disable-neon --disable-asm --disable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-static --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --enable-debug --disable-neon-clobber-test --disable-ffprobe --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-shared --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-sdl2 --disable-zlib --enable-mediacodec
  libavutil      56. 25.100 / 56. 25.100
  libavcodec     58. 42.104 / 58. 42.104
  libavformat    58. 25.100 / 58. 25.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 D  android_camera   
 D  lavfi   
```

**Comment by gWOLF3** [comment]
**STATIC ELF EXEC ARM64 API LEVEL 28 WORKING. W/MEDIA CODEC & ANDROID_CAMERA SUPPORT** 

However, problem compiling for API level 27: 

The issue I was experiencing was occurring because I was not compiling for the correct API version I was running on device. My device was running Lineage OS which is still using API level 27. I retested on another device running Pie (API level 28) and it worked as expected. 

While doing this however, when I tried recompiling for API level 27 — the build resulted in the following error: 

```
cp: /usr/local/share/android-ndk/toolchains/mobile-ffmpeg-api-27-aarch64/aarch64-linux-android/lib/libc++_shared.so: No such file or directory

INFO: Starting new build for arm64-v8a on API level 27 at Tue Jan 29 20:08:33 EST 2019


INFO: Building cpu-features for for arm64-v8a

/Users/glenn.wolfe/mobile-ffmpeg/build/android-common.sh: line 1025: aarch64-linux-android-clang: command not found
aarch64-linux-android-ar: /usr/local/share/android-ndk/sources/android/cpufeatures/cpu-features.o: No such file or directory
/Users/glenn.wolfe/mobile-ffmpeg/build/android-common.sh: line 1027: aarch64-linux-android-clang: command not found
INFO: Enabling library android-media-codec
aarch64-linux-android-clang is unable to create an executable file.
C compiler test failed.
```

**Comment by tanersener** [comment]
> cp: /usr/local/share/android-ndk/toolchains/mobile-ffmpeg-api-27-aarch64/aarch64-linux-android/lib/libc++_shared.so: No such file or directory
> 
> /Users/glenn.wolfe/mobile-ffmpeg/build/android-common.sh: line 1025: aarch64-linux-android-clang

These logs show that some files are missing in your toolchains.

1. Can your delete all existing `mobile-ffmpeg` toolchains by running `rm -rf /usr/local/share/android-ndk/toolchains/mobile-ffmpeg-*`? They will be created on your next try.

2. If the error persists then you need to update/reinstall your NDK installation. It looks like there is an outdated or missing component that prevents NDK to use API level 27.

**Comment by gWOLF3** [comment]
Got it — thank you Taner. 

Closing this issue because initial question has been resolved and answered.

**Comment by ramsundark5** [comment]
@gWOLF3 did you get it working. If so, can you please share the script changes to create the static build?

**Comment by tanersener** [comment]
@ramsundark5 There is a [building ffmpeg executable on Android](https://github.com/tanersener/mobile-ffmpeg/wiki/Building-ffmpeg-executable-on-Android) wiki page which lists necessary steps to build static libraries and executables.

**Comment by ramsundark5** [comment]
@tanersener thanks for the quick response. Will give it a try.

**Comment by gWOLF3** [comment]
Yes, I got it working. Remember to specify `--enable-static` and `--disable-shared`, as Taner notes, as well as specify the API version you are targeting.

Lmk if you have trouble.
