### ISSUE TITLE
Asynchronous Execution

### ISSUE THREAD

**Issue by adisiji** [tanersener/mobile-ffmpeg#79]
**Description**
I'm trying to execute the ffmpeg command with RxJava so it doesnt block the UI thread.
Here is my code : 
```
Single.just(FFmpeg.execute(command))
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Consumer<Integer>() {
                            @Override
                            public void accept(final Integer integer) throws Exception {
                                deviceImages[pos].setFilePath(output);
                                isLoading.setValue(false);
                            }
                        }, new Consumer<Throwable>() {
                            @Override
                            public void accept(Throwable throwable) throws Exception {
                                Log.e("FFMPEG", "failed ", throwable);
                                isLoading.setValue(false);
                            }
                        })
```

**Expected behavior**
Run the command in background / io thread.

**Current behavior**
It's blocking the UI thread.

**Logs**
https://ghostbin.com/paste/aaa2c

**Environment**
 - Platform: Android
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, armv7s, arm64, i386, x86_64]
 - Version: v4.2-dev-480
 - Android Studio version: 3.3
 - Android NDK version: r19

**Comment by tanersener** [comment]
Android and IOS APIs both are designed to be blocking the calling thread. I want to keep both APIs identical and adding asynchronous logic will complicate things.

You can run `FFmpeg.execute` inside an `AsyncTask` if this is a concern for you.

**Comment by adisiji** [comment]
Finally I can handle it with [```Completable```](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html) and it doesn't block the UI thread.

Thanks.
