### ISSUE TITLE
Update to libvpx v1.8.0

### ISSUE THREAD

**Issue by EwoutH** [tanersener/mobile-ffmpeg#80]
[libvpx v1.8.0](https://chromium.googlesource.com/webm/libvpx/+/v1.8.0) was tagged yesterday ([GitHub](https://github.com/webmproject/libvpx/releases/tag/v1.8.0)), it would be nice if libvpx-go could be updated to this version.

**Comment by tanersener** [comment]
Thanks, [development](https://github.com/tanersener/mobile-ffmpeg/tree/development) branch is updated to `v1.8.0`. It will be merged to `master` after the next main release.
