### ISSUE TITLE
Support for Haivision Open SRT (Secure Reliable Transport) protocol

### ISSUE THREAD

**Issue by moster67** [tanersener/mobile-ffmpeg#81]
This is really not an issue but more of a question or request for implementation.

The title says it all, I guess i.e. Support for Haivision Open SRT (Secure Reliable Transport) protocol. 
This protocol is being more and more used. It is open source and you can read about it here:
[https://github.com/Haivision/srt](url)

It is included in the official distribution of FFmpeg since version 4.0 (I think). 
[https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/libsrt.c](url)

For instance, I could use the following command:
`ffmpeg -re -i big_buck_bunny_1080p_stereo.avi -c copy -f mpegts srt://127.0.0.1:4242`
(of course adapted for Android command line)
which I then would listen for on a server or using VLC.

Maybe it is enough to enable  `--enable-libsrt`  in the configuration line?

I will try myself in the following days hoping there is no need to write any JNI/wrapping code which I unfortunately do not master.

**Comment by tanersener** [comment]
Thanks for creating this issue. 

I remember I tried to add support for this library but it failed somewhere; so it wasn't added in the end. I can't say exactly where it failed; if you can make it work, I'll be happy to accept your PR.

**Comment by moster67** [comment]
Thanks.  I don't have much experience with building libs and setting up configurations etc, especially merging other libs. However, I will try....

**Comment by tanersener** [comment]
Unfortunately it is not possible to support `srt` library right now. 

`srt` depends on `openssl` and I don't want to support `openssl` because its license is a little bit complicated and incompatible with `GPL`/`LGPL`.

`openssl` plans to use `apache 2.0` license in new releases. When this transition completes, we can reconsider supporting `srt`.
