### ISSUE TITLE
[Android] Can not use h264_mediacodec decoder

### ISSUE THREAD

**Issue by tanersener** [tanersener/mobile-ffmpeg#83]
When `h264_mediacodec` is used to decode an input, as used in `-c:v h264_mediacodec -i <input path> ...`, request fails with `No Java virtual machine has been registered` error.

```
D/mobile-ffmpeg-test: No Java virtual machine has been registered
D/mobile-ffmpeg-test: [h264_mediacodec @ 0x96994700] 
D/mobile-ffmpeg-test: Failed to create media format
```

**Comment by tanersener** [comment]
Fixed in [development](https://github.com/tanersener/mobile-ffmpeg/tree/development), issue will be closed when development is merged to master.

**Comment by gWOLF3** [comment]
👍 Thanks Taner
