### ISSUE TITLE
download all libraries as tarball like gpl libraries

### ISSUE THREAD

**Issue by davsinghm** [tanersener/mobile-ffmpeg#84]
shouldn't the libraries be downloaded as tarball instead of distributing in the repo, as gpl libraries are?
it will make it easier to maintain, and also allow other people to update it easily.
another advantage is it allows one to find the version of library being used easily.
and ideally, any changes to library should be send as a patch to them if it's directly related to android.

here is some work: https://github.com/dsmudhar/mobile-ffmpeg/commit/c909a44a8949fba5f1439fc66e48449d780f869b
i can send pull request, but some of the libraries (which i don't need) requires additional configuration, as ./configure isn't there, and --reconfig-LIBRARY doesn't work directly.
did you also modify the external libraries to make this step work?

**Comment by tanersener** [comment]
The idea behind the current approach is not to depend on any download links or source repositories as much as possible. In this way, anyone who downloads the master or a tag, even years later, will be able to build the library. Moreover, I regularly test the build process and guarantee that the build will succeed. I won't be able to do if I depend on another project source. I saw many projects which depend on not-existing download URLs or uses git submodules of non-existing projects/commits. I don't want this project to be one of them and this is my way of solving it. You are right, it is not perfect, it has some drawbacks, but I want to keep it that way.

**Comment by dsmudhar** [comment]
well, the git tarballs are hosted for years, because they are just git tags, which means will be generated (assuming they cache it) on demand based on version tags* (which are git commits refs).
even some repos, they host it as far as 2005: https://download.videolan.org/pub/videolan/x264/snapshots/.
so as long as they delete the repo (which is very unlikely), it won't be going to be changed.

i understand your point. but one thing that you could do is, include option like $ android.sh --download-fresh-tarballs, off by default.
and also include current release of tarballs in this repo which will be extracted when enabled, which you already do with gpl libraries

*example: https://github.com/libass/libass/archive/0.14.0.tar.gz is a release tag.

**Comment by dsmudhar** [comment]
another thing worth mentioning is, the more frequent reason the ndk project build system would break, is not because of changes in external libraries* (like ffmpeg, x264), it's changes in ndk itself, as you might have seen recently with r19 (llvm build system, system stl etc.)

so in the future, the ndk will be changed more often than the tarball links.

*most of which have stable external/public apis. like libmp3lame haven't been updated for over a year now. (oct 2017)

**Comment by tanersener** [comment]
> well, the git tarballs are hosted for years, because they are just git tags, which means will be generated (assuming they don't cache it) on demand based on version tags* (which are git commits refs).
> even some repos, they host it as far as 2005: https://download.videolan.org/pub/videolan/x264/snapshots/.
> so as long as they delete the repo (which is very unlikely), it won't be going to be changed.

I'd like to see all external libraries updated regularly like `x264`. Unfortunately the current situation is very different from that. Some projects are not updated for years, some of them still use `CVS`. Some of them doesn't even publish their source code repositories. Main download server of some of the libraries is often down. One I remember is always down. After seeing all these, I need strong reasons to change my approach.

> i understand your point. but one thing that you could do is, include option like $ android.sh --download-fresh-tarballs, off by default.
> and also include current release of tarballs in this repo which will be extracted when enabled, which you already do with gpl libraries
> 
> *example: https://github.com/libass/libass/archive/0.14.0.tar.gz is a release tag.

How will that work? I need to add a few details about some of the libraries here. `tesseract v4.0` is released months ago but it has compilation errors which I still couldn't fix, so I still depend on `v3.05.02`. `gnutls v3.6.x` has its own compilation errors, some regarding thread-local usage, some regarding ASM, so I still use `v3.5.19` from not not updated `v3.5.x` line. `libwebp v1.0.2` is released exactly one month ago but it has compilation errors on Android NEON architectures, so I still use the old one. I'm trying to say that supporting the new version of an external library is not easy.

> so in the future, the ndk will be changed more often than the tarball links.

Probably but what can we do about it? I can't prevent Google from making changes to the NDK build system. I can only keep my own repository stable.

**Comment by alexcohn** [comment]
I fully understand that there can be no easy split-strategy-fit-all in the case of so many dependencies, each with their own release strategy, version control and deployment technologies.

Still, I would humbly (but strongly) suggest, based on years of personal experience with projects large and small, open and closed source, to use git submodule whenever possible. There is no incentive to follow this path for all dependencies, but for the ones that are hosted on GitHub, both the overhead and the risks are minimal.

I understand your major concern that the library repo may be updated in an incompatible way. Luckily, on GitHub there is no way to retroactively change a remove a ref. Note that submodule, unlike tarball, uses any git hash on the sub-repo, it must not necessarily be a 'release', 'tag', or whatever.

For further protection, you can point a submodule not to the original repo, but to your personal fork of that repo. Creating a fork on GitHub takes very little time, and from this moment you don't depend on the good will of the repo maintainer even if they choose to remove it, or switch to a different host.

The main advantage of the submodule approach is that it allows to follow any changes made to a dependency in its own context, and (altruistic mode begins) even allows to propose improvements to these libraries with less manual labor.

The drawback of submodule approach as compared to the current keep-copy-of-all-dependencies is that the total size of initial clone will grow. On the other hand, some smart git techniques may help people who only want the minimal set of dependencies, not to download the rest of them at all.

**Comment by tanersener** [comment]
@alexcohn Thanks for explaining the details of git submodules. I'm trying to visualise how can I work with them. I haven't felt the need to use them before. This looks like a major change for the library and I'm not sure if I can deal with complexity it brings.

**Comment by alexcohn** [comment]
May I suggest to try it on one example of cpu_features? The simple steps will be as follows:

1. _You_ create a fork of https://github.com/google/cpu_features.git
2. I change the [PR](https://github.com/tanersener/mobile-ffmpeg/pull/375) to pick the submodule from your fork.
3. You accept the PR.
4. Live with this for a while to see if this brings unwanted complexity to you.

**Comment by tanersener** [comment]
Okay, created a fork of `cpu_features`. I'll just use it to test `submodules`. Later we can switch back to the original `repo`. Can you update your `PR`. So, I can start reviewing it.
