### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by chaocharleswang** [tanersener/mobile-ffmpeg#85]
Undefined symbols for architecture armv7:
  "_RETURN_CODE_SUCCESS", referenced from:
      function signature specialization <Arg[1] = Value Promoted from Box, Arg[2] = Value Promoted from Box> of closure #1 ([Swift.AnyHashable : Any]?) -> () in closure #1 () -> () in BoTubes.URLParserManager.parseUrl(videoId: Swift.String, completion: ([Swift.UInt : Foundation.URL], Swift.String?) -> ()) -> () in URLParserManager.o
  "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
      objc-class-ref in URLParserManager.o
      objc-class-ref in PlayerViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chaocharleswang** [comment]
I tried to build the framework by myself. However, I got the following error:

./ios.sh
Building mobile-ffmpeg static library for IOS

Architectures: armv7, armv7s, arm64, arm64e, i386, x86-64
Libraries: none

Building armv7 platform


ffmpeg: failed

**Comment by tanersener** [comment]
> Undefined symbols for architecture armv7:

Main releases like `4.2` doesn't include `armv7` architecture, can you try with `4.2.LTS`. Details of this difference is explained in [LTS releases](https://github.com/tanersener/mobile-ffmpeg#4-lts-releases) section.

> I tried to build the framework by myself. However, I got the following error:

The latest `Xcode` releases doesn't support 32 bit architectures, you need to disable them when building the library.
```
./ios.sh --disable-armv7 --disable-armv7s --disable-i386
```

**Comment by chaocharleswang** [comment]
Can you use 4.2.LTS with Podfile?

**Comment by tanersener** [comment]
> Can I use 4.2.LTS with Podfile?

Yes, you can?
```
pod 'mobile-ffmpeg-full', '4.2.LTS'
```
