### ISSUE TITLE
Chromaprint

### ISSUE THREAD

**Issue by rodgarcialima** [tanersener/mobile-ffmpeg#86]
This is not an issue at all.

Can I use the external chromaprint to generate an audio fingerprint?

Sorry and thank you,

Rod

**Comment by tanersener** [comment]
You can use [Chromaprint muxer](https://ffmpeg.org/ffmpeg-formats.html#chromaprint-1) enabled in `ffmpeg` but the latest `v4.2` binaries doesn't include it. You need to use `v3.1`, `audio`, `full`  and `full-gpl` packages of this version has `chromaprint` enabled.
