### ISSUE TITLE
E/mobile-ffmpeg: "/storage/emulated/0/DCIM/Camera/...mp4": No such file or directory

### ISSUE THREAD

**Issue by kachurovskiy** [tanersener/mobile-ffmpeg#89]
**Description**
FFmpeg can't seem to access an existing file:

int code = FFmpeg.execute(String.format(" -i \"%s\" -vcodec libx264 -preset slow -acodec aac \"%s\"", path, outputPath));
if (code != 0) snack("Failed with code " + code); // Prints "Failed with code 1"

https://gist.github.com/kachurovskiy/8fc1b342da776c392057a7332d2f7e82

**Current behavior**
E/mobile-ffmpeg: "/storage/emulated/0/DCIM/Camera/VID_20190224_180822.mp4": No such file or directory

**Environment**
 - Platform: Android
 - Android Studio version: 3.3.1

Thank you for your time looking into this.

**Comment by tanersener** [comment]
Unfortunately, I'm unable to run your `MainActivity` without your layout. 

I made a few tests with Android `test-app` using existing files and all were successful. You can try it yourself. `test-app` is under the `android/test-app` folder.

If your error had been `Permission denied`, I'd say that something is wrong with your app permissions. But it is `No such file or directory`; so I recommend checking the folder and file with `adb shell`.

**Comment by kachurovskiy** [comment]
Taner, thank you. The problem was in the quotes - once I removed them, it started failing in some other place :) Switched to `int code = FFmpeg.execute(new String[]{"-y", "-i", path, "-preset", "slow", "-acodec", "aac", outputPath});`
