### ISSUE TITLE
[Android] Custom build with minimal size

### ISSUE THREAD

**Issue by sanekyy** [tanersener/mobile-ffmpeg#90]
Hello!
The first thing I want to say is: thanks for the awesome project.

I'm developing a project ( it's connected with video edition ) with usage pf ffmpeg.
I built custom ffmpeg binary half a year ago and spent a lot of time to find how to do it.

Now I need to add some functionality to ffmpeg and when searching how to make it, i found your library. I'm very happy to find it and want to use it in my project.

I have some requirements for functionanity of ffmpeg for my project.

I need to execute 2 commands:
1) extract from .gif or .mp4 frame at given time and save it to png. 
Example command
 `ffmpeg -ss 00:23:00 -i video.mp4 -frames:v 1 out1.png`
2) with input movie (gif or video) + image ( png with alpha ): trim movie + crop movie + scale movie + overlay image on movie ( result video is mp4 without sound )
Example command
```
 ffmpeg -i in.mp4 -i in.png -ss 00:00:05.096 -strict -2 -to 00:00:07.035
   -filter_complex "[0]crop=1440:864:232:96[mv1],
   [mv1]scale=-1:288[mv2],
   [mv2][1:v]overlay=0:0" out.mp4
```

Now I successfully execute this commands in my project using my own binary build of ffmpeg.

But I faced with an error on mp4 videos with major_brand : iso6 and compatible_brands: mp42iso6avc1isom ( I tried to find differences between others mp4 videos which work good with my build ) and found out, that I don't enabled dash demuxer and libxml2.

While i was trying to add this and rebuild ffmpeg ( still can't do it ) I found your l project and was very happy.
I studied this project ( wiki + issues + sample project ) and saw how much work you've done and want to use your project to build ffmpeg.

When I tried to make custom build of ffmpeg I want to have minimal size of binary file.
and as result I tried to reach my goal with disabling everything what I can in configure ( --disable-everything for example ) and enable just what I need to successful command executing.

This is my ffmpeg configuration:

```
./configure \
\
--arch=${ARCH} \
--cpu=${CPU} \
--cross-prefix=${CROSS_PREFIX_PATH} \
--enable-cross-compile \
--sysroot=${SYSROOT_PATH} \
--target-os=linux \
\
--cc=${CC} \
\
--extra-cflags="-fPIE -fPIC ${ADDI_CFLAGS} -I${PREFIX_X264}/include -I/usr/local/opt/libxml2/include" \
--extra-ldflags="-pie ${ADDI_LDFLAGS} -L${PREFIX_X264}/lib -L/usr/local/opt/libxml2/lib"  \
\
--prefix=../build \
\
--enable-gpl \
--enable-nonfree \
--enable-version3 \
\
--disable-doc \
--disable-htmlpages \
--disable-manpages \
--disable-podpages \
--disable-txtpages \
\
--enable-ffmpeg \
--disable-ffprobe \
\
--enable-small \
\
--disable-everything \
--enable-libx264 \
\
--enable-encoder=libx264,aac,png \
\
--enable-decoder=h264,aac,png,gif \
\
--enable-muxer=mp4,image2 \
\
--enable-demuxer=rtp,image2,gif \
\
--enable-filter=crop,scale,overlay,transpose \
\
--enable-protocol=file \
```

With this configuration I achived size of binary file 4.1Mb and 1.8Mb in result APK ( probably it is the size after compression ).

For support iso6, dash I added dash to --enable-demuxer and added --enable-libxml2 but can't build it and want to use your project.

Now I want to ask: can I use your project and achieve the same goals?

I just want to be able to execute the two commands described above and have the minimum size of ffmpeg files to reduce the size of the final apk application.

At the moment I'm studing how I can customize your scripts and use result of executing android.sh aar. It's my first time working with it.

I tried to build sample aar just for x86 and compare size with my own custom binary build.
Using `./android.sh --enable-gpl --lts --enable-x264 --disable-arm-v7a --disable-arm-v7a-neon --disable-arm64-v8a --disable-x86-64` I got 7Mb in result aar file. And hope that it can be smaller. 

And now I'm trying to build sample aar just for x86 and compare size.
Using ./android.sh --enable-gpl --lts --enable-x264 --disable-arm-v7a --disable-arm-v7a-neon --disable-arm64-v8a --disable-x86-64 I got 9Mb in result file. And hope that it can be smaller.

Thanks in advance for the answer and help.

**Environment**
 - Platform: Android
 - Source branch: development
 - Android NDK version: 19.1.53..... ( from SDK manager )

**Comment by tanersener** [comment]
Hi, compilation of each library is performed by the scripts under the `build` folder. There are two sets of scripts; one set for Android starting with `android-` prefix and one set for IOS starting with `ios-` prefix.

In your case, you need to modify `android-ffmpeg.sh` file. It includes a configure line similar to the one you've been using. Build flags (CFLAGS, CXXFLAGS, LDFLAGS) and enabled external libraries are controlled by the top-level `android.sh`, but all other options can be modified to decrease binary size.

**Comment by sanekyy** [comment]
I tried to build binary ffmpeg.
Used:

```
./configure \
    --cross-prefix="${TARGET_HOST}-" \
    --sysroot="${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot" \
    --prefix="${BASEDIR}/prebuilt/android-$(get_target_build)/${LIB_NAME}" \
    --pkg-config="${HOST_PKG_CONFIG_PATH}" \
    --enable-version3 \
    --arch="${TARGET_ARCH}" \
    --cpu="${TARGET_CPU}" \
    --cc="${CC}" \
    --cxx="${CXX}" \
    --target-os=android \
    ${ASM_FLAGS} \
--enable-cross-compile \
\
--enable-gpl \
--enable-nonfree \
--enable-version3 \
\
--disable-doc \
--disable-htmlpages \
--disable-manpages \
--disable-podpages \
--disable-txtpages \
\
--enable-ffmpeg \
--disable-ffprobe \
\
--enable-small \
\
--disable-everything \
--enable-libx264 \
\
--enable-libxml2 \
\
--enable-encoder=libx264,aac,png \
\
--enable-decoder=h264,aac,png,gif \
\
--enable-muxer=mp4,image2 \
\
--enable-demuxer=rtp,image2,gif,dash \
\
--enable-filter=crop,scale,overlay,transpose \
\
--enable-protocol=file \
1>>${BASEDIR}/build.log 2>&1
```

I just replaced with my configuration bottom part after ASM_FLAGS.

But when I executed result I got error:

CANNOT LINK EXECUTABLE ".../ffmpeg": library "libc++_shared.so" not found

What could I miss?

**Comment by sanekyy** [comment]
Also think about using a non-binary format and using your wrapper to work with ffmpeg.
But at the same time use my custom build of ffmpeg.
Do I understand correctly, then in this case there is some minimum size? For example size of libc++_shared.so, as I understood?

**Comment by tanersener** [comment]
Can you please try with this block and use `./android.sh --enable-x264 --enable-libxml2 --enable-gpl` to enable `x264` and `xml2`.

```
    ${ASM_FLAGS} \
    ${SIZE_OPTIONS} \
    ${DEBUG_OPTIONS} \
    ${CONFIGURE_POSTFIX} \
--enable-cross-compile \
--enable-gpl \
--enable-nonfree \
--enable-version3 \
--disable-doc \
--disable-htmlpages \
--disable-manpages \
--disable-podpages \
--disable-txtpages \
--enable-ffmpeg \
--disable-ffprobe \
--enable-small \
--disable-everything \
--enable-encoder=libx264,aac,png \
--enable-decoder=h264,aac,png,gif \
--enable-muxer=mp4,image2 \
--enable-demuxer=rtp,image2,gif,dash \
--enable-filter=crop,scale,overlay,transpose \
--enable-protocol=file \
1>>${BASEDIR}/build.log 2>&1
```

Additionally, `master` has some issues with newer Android 19.1 SDK. Can you try building on development branch?

> Also think about using a non-binary format and using your wrapper to work with ffmpeg.
> But at the same time use my custom build of ffmpeg.
> Do I understand correctly, then in this case there is some minimum size? For example size of libc++_shared.so, as I understood?

When non-binary format is used, `libc++_shared` is required and its size will effect the total apk size. But I'm not sure if it will be possible to use `ffmpeg` executable without including static or dynamic `libc++_shared`. I didn't test it before.

**Comment by sanekyy** [comment]
> Can you please try with this block and use ./android.sh --enable-x264 --enable-libxml2 --enable-gpl to enable x264 and xml2.

I tried. Unsuccessfully.

> Additionally, master has some issues with newer Android 19.1 SDK. Can you try building on development branch?

Already on development branch.

> When non-binary format is used, libc++_shared is required and its size will effect the total apk size. But I'm not sure if it will be possible to use ffmpeg executable without including static or dynamic libc++_shared. I didn't test it before.

I understood you. Probably it's possible to include static libc++_shared `libc++_shared`, because my old custom build works without dynamic  `libc++_shared`.

For now I see two options.
1) Build binary with static `libc++_shared`. Possibly it is also necessary to build x264 and libxml2 with static `libc++_shared`?

2) Build non binary ffmpeg. Is this possible to reduce size of `libc++_shared.so`?  As I understood it even contains what is not used

**Comment by tanersener** [comment]
> I understood you. Probably it's possible to include static libc++_shared libc++_shared, because my old custom build works without dynamic libc++_shared.

I need to repeat some of the tests to see if I can remove `libc++_shared` requirement. C++ runtime libraries included in NDK have changed over time, contents of these libraries have also changed.

> 2. Build non binary ffmpeg. Is this possible to reduce size of libc++_shared.so? As I understood it even contains what is not used

Unfortunately no, it is built by Android. `android.sh` copies ` libc++_shared` from `${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${TOOLCHAIN}/sysroot/usr/lib/$(get_target_host)/` path during compilation.

**Comment by tanersener** [comment]
Hi @sanekyy, I made some changes on the `development` branch. `c++_shared` is no longer required by `ffmpeg` and not included in `mobile-ffmpeg` packages if you don't enable `tesseract`. Unfortunately, `tesseract` still needs it, so if you enable `tesseract` it will be included in `.aar` archives.

**Comment by sanekyy** [comment]
Hi, thx.
I found out that in final APK build `c++_shared` have less size that original:
APK analizer
![image](https://user-images.githubusercontent.com/18647037/53914163-0f5f6100-406e-11e9-97cc-4a9fb9d2b26e.png)
 Apparently during assembly, Gradle himself cuts out all unnecessary from `c++_shared`

Thx for your help.
I'll use your wrapper for my project to split the architecture very soon.
If I have any questions, I will open a new issue.

**Comment by tanersener** [comment]
> Thx for your help.
> I'll use your wrapper for my project to split the APK by architecture out of the box very soon.
> If I have any questions, I will open a new issue.

OK mate
