### ISSUE TITLE
 Cocoapods中找不到mobile-ffmpeg-full 4.2

### ISSUE THREAD

**Issue by matangfeng** [tanersener/mobile-ffmpeg#93]
期望可以通过CocoaPods下载  4.2

**Comment by tanersener** [comment]
你可以在运行之后再试一次吗？

`pod update`

**Comment by matangfeng** [comment]
> 你可以在运行之后再试一次吗？
> 
> ```
> pod update
> pod cache clean mobile-ffmpeg-full
> ```

#### 通过这个命令 我安装成功  mobile-ffmpeg-full 🙏
