### ISSUE TITLE
Question: possible to write single images into stdin pipe

### ISSUE THREAD

**Issue by woidl** [tanersener/mobile-ffmpeg#96]
**Description**
Is it possible to write single images into stdin pipe of ffmpeg process

**Expected behavior**
Trying to exec:
"-f image2pipe -vcodec mjpeg -framerate 10 -i - -vcodec h264 -f mpegts udp://192.168.0.103:23000"

Goal is to capture single images (using a thread/timer) from some Android/iOS canvas and write them into ffmpeg using the "-i -" (pipe-in) option.
Problem is, that I do not know how to write to the stdin of your ffmpeg process. Seems there is no way to get the process-streams?

Many thnx for any help!

**Comment by tanersener** [comment]
[Pipe Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Pipe-Support) wiki page includes details about pipes.

**Comment by woidl** [comment]
Hi tanersener,
thats cool - didn't see this. I will try in a minute!

Thank you very much!!

**Comment by woidl** [comment]
Unfortunately building the dev-branch didn't work (installed all the ndk and build stuff), android.sh just verboses: failed. When do you release 4.2.1?

**Comment by tanersener** [comment]
> Unfortunately building the dev-branch didn't work (installed all the ndk and build stuff), android.sh just verboses: failed. 

[Logs](https://github.com/tanersener/mobile-ffmpeg/wiki/Logs) wiki page can help you on identifying build errors.

> When do you release 4.2.1?

1st week of April

**Comment by woidl** [comment]
Hi tanersener, managed to build your dev branch ;-)
Your pipe seems to work, but I try to write single image frames (in a thread) to file-system, and using the cat command i call your shell-exec command for each image-file every 100 ms; ffmpeg shows no errors, but i get some too-many-files after error around 250 images.

**Comment by tanersener** [comment]
There are different scenarios that can cause this error. 

`closeFFmpegPipe` method on `Config` class (`MobileFFmpegConfig` on IOS) closes previously created pipes. Can you call this method when you're done with a pipe and check if this change makes any difference?

**Comment by woidl** [comment]
Hi, think problem was I didn't destroy the shell processes, now i do the following:
for (i = 0; i < maxImageFrames; i++) {
                       if (proc != null)
                            proc.destroy();

                        File file_in = new File(path, "/img/" + String.format("img%03d.jpg", i));
                        proc = rt.exec(new String[]{"sh", "-c", "cat "+file_in.getAbsolutePath()+" > " + pipeImg});
}

so the issue with too-many-files error is closed. I try to pipe all my images into your pipe.
The for-loop above is enclosed in it's own thread, so meanwhile i can start the ffmepg command:
"-vcodec mjpeg -i " + pipeImg + " -r 10 -vcodec mpeg4 -f mpegts udp://client-ip:23000";

...and I get following logcat (looks good, no errors so far, but i do NOT receive any video-stream with ffplay):

---------------------------------------------------
[mjpeg @ 0xcf90b400] EOI missing, emulating
    Input #0, jpeg_pipe, from '/data/user/0/com.example.videostream/cache/mf_pipe_1':
      Duration: N/A, bitrate: N/A
        Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
    Stream mapping:
      Stream #0:0 -> #0:0 (mjpeg (native) -> mpeg4 (native))
    Press [q] to stop, [?] for help
    [swscaler @ 0xcf962000] deprecated pixel format used, make sure you did set range correctly
    Output #0, mpegts, to 'udp://192.168.0.103:23000':
      Metadata:
        encoder         : Lavf58.26.100
        Stream #0:0: Video: mpeg4, yuv420p, 320x240 [SAR 1:1 DAR 4:3], q=2-31, 200 kb/s, 10 fps, 90k tbn, 10 tbc
        Metadata:
          encoder         : Lavc58.46.100 mpeg4
        Side data:
          cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
    frame=    1 fps=0.0 q=1.6 Lsize=       2kB time=00:00:00.00 bitrate=1230545.5kbits/s speed=0.000231x    
    video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 83.913040%
---------------------------------------------------

Do you know whats wrong here? For any help I'm very grateful!

**Comment by tanersener** [comment]
> frame= 1 fps=0.0 q=1.6 Lsize= 2kB time=00:00:00.00 bitrate=1230545.5kbits/s speed=0.000231x
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 83.913040%

Is this the only log printed? This log says only 1 frame is read from the pipe.

It looks like you're streaming the output. I think it would be easier if you write the output to a file first. When you see that file is created correctly, then you can stream it instead of writing to a file.

**Comment by woidl** [comment]
Hi,
as I wrote before, in

File file_in = new File(path, "/img/" + String.format("img%03d.jpg", i));
proc = rt.exec(new String[]{"sh", "-c", "cat "+file_in.getAbsolutePath()+" > " + pipeImg});

...already writes the image-files. All images are completely presented in the /img folder before. 
Tested some conversion of images to byte[] before, all ok.
Also tested similar ffmpeg call on linux PC before, it's working. Also your ffmpeg working an Android when I use some video instead of single images.

Maybe problem is that I use for every img a new runtime-exec? I do not know how to this correctly.
My goal is to grab a bitmap from Canvas around every 100ms and put this into your pipe...
Dp you know how this can be done?

**Comment by tanersener** [comment]
> Hi,
> as I wrote before, in
> 
> File file_in = new File(path, "/img/" + String.format("img%03d.jpg", i));
> proc = rt.exec(new String[]{"sh", "-c", "cat "+file_in.getAbsolutePath()+" > " + pipeImg});
> 
> ...already writes the image-files. All images are completely presented in the /img folder before.

I mean writing the output to the file, not the input.
>
> Tested some conversion of images to byte[] before, all ok.
> Also tested similar ffmpeg call on linux PC before, it's working. Also your ffmpeg working an Android when I use some video instead of single images.
> 
> Maybe problem is that I use for every img a new runtime-exec? I do not know how to this correctly.
> My goal is to grab a bitmap from Canvas around every 100ms and put this into your pipe...
> Dp you know how this can be done?

It's a complicated task. I'm not sure if it is really possible, I haven't done something similar. If you have a command working on desktop ffmpeg but not working on `mobile-ffmpeg` I can help you understand why it fails. But other than that I have no idea.

**Comment by woidl** [comment]
Hi, i use something like:
cat ./img/*.jpg | ffmpeg -i - r 10 -vcodec h264 -f mpegts udp://127.0.0.1:23000 

Sure here I put ALL images using cat *.jpg into pipe at once. But since I wanna do this frame-by-frame in future I thought it could work with multiple 
cat img000.jpg > pipe
cat img001.jpg > pipe
...

**Comment by tanersener** [comment]
Does it work when you use only one `cat img000.jpg > pipe` ?

**Comment by woidl** [comment]
Hi Tanersener, in your code it works. But as we have seen ffmpeg seems to take only the first.
Question: Could you provide the Process - object of your executed ffmpeg command somwhere in your Config-Class? Maybe then it is possible to fetch the Process-InputStream, where I could put the image-data...

**Comment by woidl** [comment]
Hi, thnx for your help and hint with EOF - and sounds great that it worked for you in iOS!

I already thought writing image-bytes directly into pipe - but this was my main problem: I do not know how to open the correct pipe for the main process (using java.io ?)...

**Comment by tanersener** [comment]
> Hi, thnx for your help and hint with EOF - and sounds great that it worked for you in iOS!
> 
> I already thought writing image-bytes directly into pipe - but this was my main problem: I do not know how to open the correct pipe for the main process (using java.io ?)...

You need to create only one pipe and write all image data to it. There are some examples about reading and writing files in [this](https://developer.android.com/training/data-storage/files#java) link.

**Comment by woidl** [comment]
Hi, thnx for the hint.
"You need to create only one pipe" is my problem: HOW?
For example, openFileOutput creates an output-stream but think this stream goes directly to the file-system off the App. But we need a pipe which directly 'feeds' ffmpeg -i -

**Comment by tanersener** [comment]
[Pipe-Support](https://github.com/tanersener/mobile-ffmpeg/wiki/Pipe-Support#1--create-a-new-pipe) wiki page already shows how to create a pipe. Test application of `development` branch already includes a tab based on that document. You've said that you tried them both but you're ignoring them. You are trying to feed ` ffmpeg -i -`, which is actually reading input from `stdin`. Unfortunately it reading input from `stdin` is not supported, I can't help you about that.

**Comment by woidl** [comment]
Hi, thnx for your help - think I'll go on experimenting with your pipe-support, if I have solution I'll send you.

**Comment by tanersener** [comment]
okay

**Comment by woidl** [comment]
Hi Tanersener, managed to get it to work:

I think you meant the follwoing (what I didn't check at the beginning):
String pipeImg = Config.registerNewFFmpegPipe(mainActivity);
FileOutputStream fos = new FileOutputStream(pipeImg);

Lateron, inside some thread, now I can put bitmaps (fetched from Canvas) directly into the fos, inside an endless loop using sleep to wait for framerate:

bm.compress(Bitmap.CompressFormat.JPEG, 90, fos);

Only the problem now that ffmpeg takes around 400 images before starting the stream, here I experiment with some options for more frequent keyframe gen, after startup of stream, delay from Mobile to Client is around 3 seconds...

Thnx a lot for your help again!

**Comment by tanersener** [comment]
> Only the problem now that ffmpeg takes around 400 images before starting the stream, here I experiment with some options for more frequent keyframe gen, after startup of stream, delay from Mobile to Client is around 3 seconds...
> 

I'm not familiar with streaming options but [ffmpeg streaming guide](https://trac.ffmpeg.org/wiki/StreamingGuide) has a `Latency` section which includes tips about decreasing the latency. I think you may find answers to your issues there.

**Comment by woidl** [comment]
Hi, think I have tried the most stuff of the ffmpeg streaming guide. Not working so far.
I'll close this issue now, since my pipe-problem is solved. Thnx again, your lib is great work!
