### ISSUE TITLE
why i export ANDROID_NDK_ROOT success, but build ffmpeg failed.

### ISSUE THREAD

**Issue by krislyy** [tanersener/mobile-ffmpeg#97]
**Description**
when i build the project with command "./android.sh --disable-x86 --disable-x86-64 --disable-arm64-v8a --enable-android-media-codec --enable-x265 --enable-x265 --enable-libass --enable-gpl",  all libraries is built ok, but the ffmpeg failed.

i checked out the build.log, and found the problem 
```
/Users/krislyy/Library/Android/ndk/android-ndk-r14b/toolchains/mobile-ffmpeg-api-24-arm/sysroot/usr/include/sys/user.h:40:5: warning: '__i386__' is not defined, evaluates to 0 [-Wundef]
#if __i386__
    ^
libavformat/udp.c:290:28: error: member reference base type '__be32' (aka 'unsigned int') is not a structure or union
        mreqs.imr_multiaddr.s_addr = ((struct sockaddr_in *)addr)->sin_addr.s_addr;
        ~~~~~~~~~~~~~~~~~~~^~~~~~~
libavformat/udp.c:292:32: error: assigning to '__be32' (aka 'unsigned int') from incompatible type 'struct in_addr'
            mreqs.imr_interface= ((struct sockaddr_in *)local_addr)->sin_addr;
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavformat/udp.c:294:32: error: member reference base type '__be32' (aka 'unsigned int') is not a structure or union
            mreqs.imr_interface.s_addr= INADDR_ANY;
            ~~~~~~~~~~~~~~~~~~~^~~~~~~
libavformat/udp.c:295:29: error: member reference base type '__be32' (aka 'unsigned int') is not a structure or union
        mreqs.imr_sourceaddr.s_addr = ((struct sockaddr_in *)&sources[i])->sin_addr.s_addr;
```

however I export ANDROID_NDK_ROOT=/Users/krislyy/Library/Android/ndk/android-ndk-r18b
**Expected behavior**
build ffmpeg ok.

**Current behavior**
What happened.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.com) and insert the link here.

**Environment**
 - Platform: [Android]
 - Architecture: [arm-v7a, arm-v7a-neon]
 - Version (if applicable) [master]
 - Source branch (if applicable) [e.g. master, dev-v2.x]
 - Android Studio version (if applicable) [3.3]
 - Android NDK version (if applicable) [18b]

**Other**

**Comment by tanersener** [comment]
Your logs include `/Users/krislyy/Library/Android/ndk/android-ndk-r14b` path, which means `NDK r14b` is used for compilation. Can you check your environment variables and see which variable still has `NDK r14b` path? After fixing it, compilation will succeed.

**Comment by krislyy** [comment]
> Your logs include `/Users/krislyy/Library/Android/ndk/android-ndk-r14b` path, which means `NDK r14b` is used for compilation. Can you check your environment variables and see which variable still has `NDK r14b` path? After fixing it, compilation will succeed.

Thanks a lot. I finally moved android-ndk-r14b to android-ndk-r14bXXXX, and compiled again, everything goes well. I don't know why, but works.
