### ISSUE TITLE
How does porting ffmpeg into iOS work?

### ISSUE THREAD

**Issue by Saren-Arterius** [tanersener/mobile-ffmpeg#98]
I have no experience in iOS development but I am very interested in benchmarking various iOS devices, just like I used your app in the latest iPad Pro and found that the A12X is 30% slower than a 8550u in VP8 test and similar performance in VP9 test.

I would like to port other benchmarking CLI programs into iOS and test the CPU performances, for example mprime and blender. Is it as simple as passing string array as arguments for main() and redirect the stderr/stdout to some text area, or some effort has to be put in to fix issues? What are the limitations and how did you make it work? Please help, thanks.

**Comment by tanersener** [comment]
The most time consuming issue of this project was IOS platform support. `ffmpeg` supports IOS but some of the external libraries enabled doesn't support or prioritize IOS. So I had to test different build flags to find a working configuration. Other than that, there were lots of `ffmpeg` specific issues but telling them won't help you much. Some of them are documented in [Wiki](https://github.com/tanersener/mobile-ffmpeg/wiki) section.

**Comment by Saren-Arterius** [comment]
Thank you. Does that mean if there is no build issue for the external libs and the program does not use CPU/OS specific code, the porting should be as simple as I described?

**Comment by tanersener** [comment]
You'll still have application specific issues, but yes, porting will be as simple as that. 

But I'm not sure if this is really what you want. In my case, I tried to enable ASM (CPU/OS specific code) for all libraries. ASM enabled applications generally have better performance than the others. If you disable them, your compilation will be less painful but you won't get maximum performance from your device hardware.
