### ISSUE TITLE
Is the tcp protocol, in addition to udp, supported for outgoing streaming?

### ISSUE THREAD

**Issue by moster67** [tanersener/mobile-ffmpeg#99]
Is the tcp protocol, in addition to udp, supported for outgoing streaming?
example:

> ffmpeg -re -i /storage/emulated/0/this.mp4 -vcodec copy -acodec copy -movflags faststart -f mpegts tcp://192.168.1.167:1234?listen

Thanks.

**Comment by tanersener** [comment]
Yes, it is supported. You can see available protocols by running `-protocols` command.
